polkadot-js/apps

packages/app-accounts/src/Creator.js
packages/app-extrinsics/src/Signer/Decoded.js
packages/app-extrinsics/src/Signer/Signer.css
packages/app-extrinsics/src/Signer/Unlock.js
packages/app-extrinsics/src/Signer/index.js
packages/app-extrinsics/src/index.js
packages/app-extrinsics/src/types.js
packages/ui-keyring/src/index.js
packages/ui-keyring/src/save/accountCreate.js
packages/ui-keyring/src/types.js

Closes https://github.com/polkadot-js/apps/issues/35

Allow unlock on locked accounts (extrinsics)

---

.travis.yml
package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/ui-app/package.json
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react/package.json
packages/ui-signer/package.json
yarn.lock

Prevents older versions as discussed/found in https://github.com/polkadot-js/apps/pull/78
Fixes https://github.com/polkadot-js/apps/issues/81
Closes https://github.com/polkadot-js/apps/pull/78
Closes https://github.com/polkadot-js/apps/pull/82

Add yarn & node to engines

---

packages/apps/src/SideBar/index.tsx
packages/ui-app/src/Button/types.d.ts
packages/ui-app/src/Input.tsx
packages/ui-app/src/Output.tsx
packages/ui-app/src/Password.tsx
packages/ui-app/src/Static.tsx
packages/ui-react-rx/src/types.d.ts
packages/ui-signer/src/Extrinsic.tsx

#114 Stricter typing for children props

---

package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-extrinsics/src/Selection.tsx
packages/ui-app/package.json
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react/package.json
packages/ui-signer/package.json
packages/ui-signer/src/sign.ts
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/141

Fix index change not updating for 0

---

package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/apps/src/SideBar/Item.tsx
packages/apps/src/SideBar/index.tsx
packages/ui-app/package.json
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react/package.json
packages/ui-signer/package.json
yarn.lock

Fixes the navbar not updating when the routes change. This was unintended due to the introduction of PureComponents, where unneeded renders are blocked. Changes are here (somewhat dwarfed by dependency updates) -
https://github.com/polkadot-js/apps/pull/150/files#diff-f9bc036c2d13373014f1a74a7e70b1c2R11
The correct solution is to make sure the router location is passed in -
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

Wrap SideBar items in withRouter

---

packages/app-example/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/ui-app/package.json
packages/ui-app/src/Params/Param/findComponent.ts
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react/package.json
packages/ui-signer/package.json
yarn.lock

- Allows for new empty param formatting as `null` (`api/api-rx`)
- Allows for parachain register/deregister (`common/type-extrinsics`)

Update deps, fix formatting, parachain priv methods

---

packages/apps/src/NodeInfo.tsx
packages/apps/src/index.tsx

Display UI version on sidebar

---

package.json
packages/app-vanitygen/package.json
packages/app-vanitygen/scripts/vanitygen.js
yarn.lock

Didn't survive the TS conversion - now running the same way the dev client does.

Fix yarn run vanitygen

---

Dockerfile
README.md
packages/apps/src/index.tsx

Add a multistage docker image with the UI.
It builds a docker image based on nginx and weight around 11 MB.
See https://hub.docker.com/r/chevdor/polkadot-ui/

Add Dockerfile

---

packages/app-staking/package.json
packages/app-staking/src/Account.tsx
packages/app-staking/src/StakeList.tsx
packages/app-staking/src/UnnominateButton.tsx
packages/app-staking/src/index.css
packages/app-staking/src/index.tsx
packages/ui-app/src/styles/components.css
packages/ui-app/src/styles/semantic.css
packages/ui-react-rx/src/with/storage.tsx
packages/ui-react-rx/src/with/types.d.ts

Closes https://github.com/polkadot-js/apps/issues/175

(un)Nominate functionality

---

packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/styles/components.css
packages/ui-app/src/util/toShortAddress.ts

Add AddressRow component

---

packages/app-accounts/src/index.css
packages/app-accounts/src/index.tsx
packages/app-addresses/src/index.css
packages/app-addresses/src/index.tsx
packages/app-example/src/index.css
packages/app-example/src/index.tsx
packages/app-explorer/src/index.css
packages/app-explorer/src/index.tsx
packages/app-extrinsics/src/index.css
packages/app-extrinsics/src/index.tsx
packages/app-rpc/src/index.css
packages/app-rpc/src/index.tsx
packages/app-staking/src/index.css
packages/app-staking/src/index.tsx
packages/app-storage/src/index.css
packages/app-storage/src/index.tsx
packages/app-toolbox/src/index.tsx
packages/app-vanitygen/src/index.css
packages/app-vanitygen/src/index.tsx
packages/ui-app/src/Navigation.tsx
packages/ui-app/src/Page.tsx
packages/ui-app/src/styles/components.css

Common component, remove duplicated styles

Introduce Page & Navigation components (consistency)

---

packages/app-example/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-rpc/src/Account.tsx
packages/app-rpc/src/Selection.tsx
packages/app-staking/package.json
packages/app-staking/src/Account.tsx
packages/ui-app/package.json
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react-rx/src/util/isTestChain.ts
packages/ui-react-rx/src/util/numberFormat.ts
packages/ui-react-rx/src/util/shouldUseLatestChain.ts
packages/ui-react/package.json
packages/ui-signer/package.json
packages/ui-signer/src/Modal.tsx
packages/ui-signer/src/Queue.tsx
yarn.lock

- Fixes new master & 0.2.4 branches broken to due non-existent entries now being returned as `null`
Additional related dependency PRs -
- https://github.com/polkadot-js/common/pull/188
- https://github.com/polkadot-js/common/pull/189
- https://github.com/polkadot-js/common/pull/190
- https://github.com/polkadot-js/api/pull/124

Detect nonce === null, set as new BN(0)

---

packages/app-democracy/package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-explorer/src/BlockHeader/Extrinsics.tsx
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-app/src/util/shouldDisplaySection.ts
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react-rx/src/Api/index.tsx
packages/ui-react-rx/src/ApiObservable/index.ts
packages/ui-react-rx/src/ApiObservable/types.d.ts
packages/ui-react-rx/src/types.d.ts
packages/ui-react/package.json
packages/ui-signer/package.json
packages/ui-signer/src/Modal.tsx
yarn.lock

Also added support for method checks, ie in this case `chain_getBlock` (which is useful in this https://github.com/polkadot-js/apps/issues/226)
Finally closes https://github.com/polkadot-js/apps/issues/222

Pull in new subscription API (tracking subs per method)

---

packages/app-democracy/package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-explorer/src/BlockByHash/BlockByHash.tsx
packages/app-explorer/src/BlockByHash/index.tsx
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-explorer/src/index.css
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/apps/src/SideBar/SideBar.css
packages/ui-app/package.json
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/CardSummary.tsx
packages/ui-react-rx/package.json
packages/ui-react-rx/src/ApiObservable/index.ts
packages/ui-react-rx/src/ApiObservable/types.d.ts
packages/ui-react/src/Elapsed.tsx
packages/ui-signer/package.json
yarn.lock

Display justifications for block click-through

---

packages/app-democracy/src/Summary.tsx
packages/app-democracy/src/index.css
packages/app-explorer/src/Main.tsx
packages/app-explorer/src/Summary.tsx
packages/app-explorer/src/SummarySession.tsx
packages/app-explorer/src/index.css
packages/app-staking/src/Summary.tsx
packages/app-staking/src/index.css
packages/ui-app/src/Balance.tsx
packages/ui-app/src/CardBar.tsx
packages/ui-app/src/CardSummary.tsx
packages/ui-app/src/styles/components.css

- start using the CardBar & CardSummary on staking
- Cleanup staking summaries
- display lateness as overall percentage

DRY Card display (CardBar component, consistency)

---

packages/ui-app/src/InputAddress/index.tsx
packages/ui-app/src/util/toAddress.ts
packages/ui-keyring/src/address/meta.ts
packages/ui-keyring/src/loadAll.ts

Closes https://github.com/polkadot-js/apps/issues/220

Store addresses via actual address (when PK pasted)

---

packages/app-staking/src/index.css
packages/ui-app/src/styles/partials/_variables.css
packages/ui-app/src/styles/semantic.css

- Fix https://github.com/polkadot-js/apps/issues/245
- Use of the following colors https://coolors.co/4e4e4e-d75ea1-ffffff-96bdc6-98aaae
- For buttons, progress bar, anchors, staking star

Use new colors

---

packages/app-accounts/src/Editor.tsx
packages/app-accounts/src/Forgetting.tsx
packages/app-extrinsics/src/Selection.tsx

First attempt at creating a confirmation modal to appear when a user clicks "Forget" to remove an account.

Marni wip 219 forget confirmation

---

packages/app-democracy/package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/app-storage/src/Selection.tsx
packages/apps/src/routing/storage.ts
packages/ui-app/package.json
packages/ui-app/src/InputStorage/SelectKey.tsx
packages/ui-app/src/InputStorage/SelectSection.tsx
packages/ui-app/src/Params/Param/findComponent.ts
packages/ui-app/src/Params/initValue.ts
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react/package.json
packages/ui-signer/package.json
yarn.lock

- Fix failing enumSet query, Closes https://github.com/polkadot-js/apps/issues/274
- Rename Storage -> State in UI
- Pull in latest api, includes additional storage keys
- Storage method changes always change params, Closes https://github.com/polkadot-js/apps/issues/286

Staking storage updates

---

packages/app-transfer/src/Transfer.tsx
packages/app-transfer/src/index.css

Closes https://github.com/polkadot-js/apps/issues/310
- Move to general UI styles for row definition, fixing broken flex
- Lose the ">>" (like the idea, but it should be icon really - don't clutter until some real UX guru can look at things)

Fix transfer copy, cleanup styles

---

packages/ui-react/src/IdentityIcon/Polkadot.tsx
packages/ui-react/src/IdentityIcon/Substrate.tsx
packages/ui-react/src/IdentityIcon/index.tsx

- Display Identicon based on UI_THEME
- Closes https://github.com/polkadot-js/apps/issues/307

Substrate theme with different Identicon

---

packages/app-accounts/src/Creator.tsx

https://github.com/polkadot-js/apps/issues/223

Added a warning popup at account creation for seed backup

---

package.json
packages/app-accounts/src/Editor.tsx
packages/app-accounts/src/Forgetting.tsx
packages/app-accounts/src/index.css
packages/app-accounts/src/index.tsx
packages/app-democracy/package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react/package.json
packages/ui-signer/package.json
yarn.lock

Deps bumping has made this look worse than it is, effectively accounts for two-thirds of the lines.

Cleanup app-accounts, align with addresses

---

packages/app-staking/src/StakeList/Nominating.tsx
packages/ui-app/src/InputError.tsx

fix #266 - helpful error message when input address is not in intentions list

---

packages/app-accounts/src/Creator.tsx

FIX#334 - button ordering

---

packages/app-staking/src/StakeList/Account.tsx
packages/app-staking/src/index.css

#276 
I'm not sure this is the right solution, I am still confused on how to create practice data to test. Feel free to send a gif of how to populate (while running polkadot node) with practice data!

trying to get mapping of nominators correct

---

.travis.yml
README.md
package.json

- Closes https://github.com/polkadot-js/apps/issues/368

[next] Bump yarn to 1.10.1 in engines, travis

---

packages/ui-signer/src/Status.tsx
packages/ui-signer/src/index.css

Closes https://github.com/polkadot-js/apps/issues/378

[next] Queue status icons

---

packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-explorer/src/BlockByHash/BlockByHash.tsx
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-app/src/Params/Param/findComponent.ts
packages/ui-app/src/Params/initValue.ts
packages/ui-app/src/Params/values.ts
packages/ui-react-rx/package.json
packages/ui-signer/src/Status.tsx
yarn.lock

- Compact field encoding support
- Add Compact rendering support
- Aura support

[next] Support latest substrate master

---

packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/StakeList/Account.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/Balance.tsx

- Make validator balances display in the list view again
- Slightly adjust top-right summary balance display
- Only display nominated balances when >0

[next] Cleanup staking list balance displays

---

packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/app-explorer/src/BlockHeader/index.tsx

- Cleanup block display to handle both large and small cases
Not happy here atm, but needs some through - there is way too much random numbers on-screen here

[next] Cleanup block display with cleaner formatting

---

packages/ui-keyring/src/index.ts

Closes https://github.com/polkadot-js/apps/issues/289

[next] Only filter dev accounts when in dev

---

package.json
packages/app-accounts/src/Creator.tsx
packages/app-accounts/src/bipWorker.ts
packages/app-accounts/src/worker-loader.d.ts
packages/apps/webpack.config.js
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/399

[next] Move BIP generation to worker (UI responsiveness)

---

packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/app-explorer/src/BlockHeader/index.tsx
packages/ui-app/src/styles/app.css

Some small styling and layout tweaks

[next] Cleanup explorer header display

---

packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/app-transfer/src/Fees.tsx
packages/app-transfer/src/index.css
packages/ui-app/package.json
packages/ui-identicon/package.json
packages/ui-react-rx/package.json
packages/ui-signer/src/Modal.tsx
packages/ui-signer/src/Queue.tsx
packages/ui-signer/src/Status.tsx
yarn.lock

- Closes #420
- Update API to expose observable error
- Pass error through to status
- Status displays actual error.message

[next] Catch & display observable status errors

---

packages/ui-app/src/styles/semantic.css
packages/ui-identicon/src/Empty.tsx
packages/ui-identicon/src/IdentityIcon.css
packages/ui-identicon/src/Polkadot.tsx
packages/ui-identicon/src/Substrate.tsx

[next] Adjust menu & IdentityIcon styling

---

packages/app-democracy/package.json
packages/app-democracy/src/Item.tsx
packages/app-explorer/package.json
packages/app-explorer/src/BlockByHash/BlockByHash.tsx
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-react-rx/package.json
yarn.lock

- Proposal documentation now shows
- First chain proposal (number id =0) does not fail (API update)

[next] Cleanup proposal & referendum display

---

packages/app-democracy/package.json
packages/app-democracy/src/Referendum.tsx
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-extrinsics/src/Params/Extrinsic.tsx
packages/app-extrinsics/src/Params/Proposal.tsx
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-app/src/Params/Param/KeyValue.tsx
packages/ui-app/src/Params/Param/KeyValueArray.tsx
packages/ui-app/src/Params/Param/findComponent.ts
packages/ui-app/src/Params/initValue.ts
packages/ui-app/src/Params/values.ts
packages/ui-react-rx/package.json
yarn.lock

The short version - submitting a proposal with setStorage(items) did not work -
- Proposal was not properly created,
- Values were not properly showing
- Votes were not working with true/false
The first 2 addressed via API update and cleanups along the way in the UI. The second via api-observable.

[next] Cleanup Referendums & voting process (with Vec<KV>)

---

packages/app-staking/src/Overview/CurrentList.tsx
packages/apps/src/SideBar/SideBar.css
packages/apps/src/index.css
packages/ui-app/src/styles/app.css
packages/ui-app/src/styles/semantic.css

- Adjust backgrounds to be slightly darker

[next] Cleanup styling

---

packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/435

[next] Bump deps, metadata parsing

---

packages/app-storage/src/Selection/Modules.tsx
packages/ui-app/src/InputExtrinsic/InputExtrinsic.css
packages/ui-app/src/Params/index.tsx

Merge master for #324 fixes (with small updates)

[next] Merge master, param change update

---

package.json
packages/app-accounts/src/Creator.tsx
packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-app/src/Dropdown.tsx
packages/ui-app/src/Params/Param/Account.tsx
packages/ui-app/src/Params/Param/Amount.tsx
packages/ui-app/src/Params/Param/Balance.tsx
packages/ui-app/src/Params/Param/BaseBytes.tsx
packages/ui-app/src/Params/Param/Bool.tsx
packages/ui-app/src/Params/Param/Code.tsx
packages/ui-app/src/Params/Param/String.tsx
packages/ui-app/src/Params/Param/Timestamp.tsx
packages/ui-app/src/Params/Param/Tuple.tsx
packages/ui-app/src/Params/Param/Vector.tsx
packages/ui-app/src/Params/Param/VoteThreshold.tsx
packages/ui-app/src/Params/Param/findComponent.ts
packages/ui-app/src/Params/Params.css
packages/ui-app/src/Params/index.tsx
packages/ui-app/src/Params/initValue.ts
packages/ui-app/src/styles/app.css
packages/ui-app/src/util/toAddress.ts
packages/ui-identicon/package.json
packages/ui-identicon/src/index.tsx
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
yarn.lock

- Allow Tuple Entry
- Allow Array entry
- Closes #72 & https://github.com/polkadot-js/apps/issues/180

[next] Support dynamic Tuple & Array inputs

---

packages/app-staking/src/Overview/CurrentList.tsx
packages/ui-keyring/src/index.ts
packages/ui-keyring/src/types.d.ts

- Added missing getAccount() method to ui-keyring package (from address and public key)
- Added getDisplayName() as method to `CurrentList`
- Fixes #303

[next] Display intention/validator name in staking list #303

---

packages/app-accounts/src/Creator.tsx
packages/ui-app/src/Modal.tsx
packages/ui-app/src/styles/semantic.css
packages/ui-keyring/src/index.ts

- Added the `<AddressSummary />` component (as suggested by @yjkimjunior)
- Added forced backup file download on save (instead of showing additional download button)
- Changed text from 'Warning' to 'Important notice'
- Fixes #394
TODO: Implement user feedback as notification pop-up in the style of https://github.com/polkadot-js/apps/pull/391 once #391 is merged

[next] Backup warning modal on account creation #394

---

packages/app-accounts/src/Creator.tsx
packages/app-accounts/src/bipWorker.ts
packages/app-addresses/src/Creator.tsx
packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/util/toAddress.ts
packages/ui-identicon/package.json
packages/ui-identicon/src/index.tsx
packages/ui-keyring/package.json
packages/ui-keyring/src/index.ts
packages/ui-react-rx/package.json
packages/ui-react-rx/src/Api/index.tsx
packages/ui-react-rx/src/with/observableBase.tsx
yarn.lock

[next] Explicit Identityicon prefix

---

packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-explorer/src/BlockByHash/Logs.tsx
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-app/src/Params/Param/Vector.tsx
packages/ui-react-rx/package.json
yarn.lock

Vector should not render add/remove in isDisabled mode

---

packages/app-explorer/src/BlockHeader/index.tsx

Make Block Hash "Hover to Copy"-able

---

packages/app-democracy/src/Referendum.tsx
packages/app-democracy/src/Summary.tsx
packages/ui-app/src/CardSummary.tsx

- Closes https://github.com/polkadot-js/apps/issues/453
- Closes https://github.com/polkadot-js/apps/issues/454

[next] Democracy countdown (launch & voting)

---

packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-react-rx/package.json
yarn.lock

[next] Bump API to handle StorageData -> Bytes with prefix

---

packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-react-rx/package.json
yarn.lock

[next] Bump api deps

---

packages/apps/src/Content/index.tsx
packages/ui-app/src/IdentityIcon.tsx
packages/ui-app/src/Status/index.tsx
packages/ui-identicon/src/index.tsx
packages/ui-identicon/src/types.ts
packages/ui-signer/src/index.tsx

[next] Make settings accessible from non-running node

---

packages/app-accounts/src/Backup.tsx
packages/app-accounts/src/ChangePass.tsx
packages/app-accounts/src/Creator.tsx
packages/app-accounts/src/Editor.tsx
packages/app-accounts/src/Restore.tsx
packages/app-addresses/src/Creator.tsx
packages/app-addresses/src/Editor.tsx
packages/app-explorer/src/Events.tsx
packages/apps/src/Content/Status.tsx
packages/apps/src/Content/index.tsx
packages/ui-app/src/Params/Param/Vector.tsx
packages/ui-app/src/Status/index.tsx
packages/ui-app/src/Status/types.ts

[next] Display received events (balalnces.Transfer atm)

---

packages/ui-app/src/InputAddress/index.tsx

Trying to get a handle and issue from @rphmeier (which I cannot quite reproduce atm - at the very least this will give more info)

Extra information on address decode errors

---

packages/app-explorer/src/BlockByHash/Logs.tsx
packages/app-explorer/src/index.css

[next] fix: Fixes #493. Contain logs digest item within div

---

packages/app-accounts/src/Backup.tsx
packages/app-accounts/src/ChangePass.tsx
packages/app-accounts/src/Creator.tsx
packages/app-accounts/src/Editor.tsx
packages/app-accounts/src/Restore.tsx
packages/app-addresses/src/Creator.tsx
packages/app-addresses/src/Editor.tsx
packages/apps/src/Content/index.tsx
packages/apps/src/Status.tsx
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/Balance.tsx
packages/ui-app/src/Button/Button.tsx
packages/ui-app/src/Button/Group.tsx
packages/ui-app/src/Button/index.tsx
packages/ui-app/src/IdentityIcon.tsx
packages/ui-app/src/InputFile.tsx
packages/ui-app/src/Params/Param/File.tsx
packages/ui-app/src/Params/Param/Vector.tsx
packages/ui-app/src/Status/index.tsx
packages/ui-app/src/Status/types.ts
packages/ui-app/src/styles/components.css

- Closes https://github.com/polkadot-js/apps/issues/485
- Snuck in a number of smaller code cleanups for sanity (mostly package imports)
- Lowercase for status messages (align everywhere)

Allow onCopy Status for IdentityIcon

---

packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-app/src/Params/initValue.ts
packages/ui-react-rx/package.json
yarn.lock

Solves and prevents lil sneak-attack issues such as #505

[next] Align number inputs to 0 defaults everywhere

---

packages/ui-app/src/Params/Param/Account.tsx

Fixes #508

---

packages/app-rpc/package.json
packages/app-settings/package.json
packages/app-staking/package.json
packages/app-toolbox/package.json
packages/app-transfer/package.json
packages/apps/package.json
packages/ui-app/package.json
packages/ui-app/src/Params/Param/Unknown.tsx
packages/ui-signer/package.json
yarn.lock

Unknown to allow hex/bytes input

---

packages/ui-app/src/Static.tsx
packages/ui-app/src/styles/components.css

Wrap and break static text

---

packages/ui-app/src/Params/Param/BaseBytes.tsx

Closes https://github.com/polkadot-js/apps/issues/552

Only set isAction when children passed

---

packages/app-extrinsics/src/Selection.tsx
packages/ui-app/src/Status/Queue.tsx
packages/ui-app/src/Status/types.ts
packages/ui-signer/src/Extrinsic.tsx
packages/ui-signer/src/Modal.tsx

Closes https://github.com/polkadot-js/apps/issues/558

Allow submission of unsigned (inherent)

---

packages/apps/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/565

WS_URL override takes precedence

---

packages/app-extrinsics/src/Params/Call.tsx
packages/app-extrinsics/src/Params/Extrinsic.tsx
packages/app-extrinsics/src/Params/Proposal.tsx
packages/app-extrinsics/src/Selection.tsx
packages/ui-react-rx/src/Api/index.tsx
packages/ui-react-rx/src/types.ts

Closes https://github.com/polkadot-js/apps/issues/575

Provide fallback for tx defaults (Extrinsic, Proposal)

---

packages/ui-app/package.json
packages/ui-react-rx/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/577

Update API, fixing isReady wait

---

packages/app-accounts/src/Backup.tsx
packages/app-accounts/src/ChangePass.tsx
packages/app-accounts/src/Creator.tsx
packages/app-accounts/src/Editor.tsx
packages/app-accounts/src/Restore.tsx
packages/app-addresses/src/Creator.tsx
packages/app-addresses/src/Editor.tsx
packages/apps/src/Status.tsx
packages/ui-app/src/IdentityIcon.tsx
packages/ui-app/src/Status/Queue.tsx
packages/ui-app/src/Status/index.tsx
packages/ui-app/src/Status/types.ts
packages/ui-app/src/styles/components.css
packages/ui-signer/src/Modal.tsx

- Display events per extrinsic as submitted, closes https://github.com/polkadot-js/apps/issues/580
- Display democracy events globally, closes https://github.com/polkadot-js/apps/issues/516

Display events created via extrinsic submission

---

packages/apps/src/SideBar/index.tsx

adding in Wiki link to sidebar

---

packages/app-democracy/src/Referendum.tsx
packages/app-democracy/src/Summary.tsx
packages/app-explorer/src/BlockByHash/BlockByHash.tsx
packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-explorer/src/Events.tsx
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-reactive/package.json
yarn.lock

- Display publicDelay (enactment block) for referendums, Closes https://github.com/polkadot-js/apps/issues/578
- Display block author, Closes https://github.com/polkadot-js/apps/issues/560
- Update API for cleaner EnumType's, https://github.com/polkadot-js/api/pull/579
- Fix proposal counts not displaying (wrong API endpoint)

Update summary info displays

---

packages/app-explorer/src/BlockByHash/BlockByHash.tsx
packages/app-explorer/src/BlockByHash/Events.tsx
packages/app-explorer/src/Events.tsx
packages/app-explorer/src/EventsRecent.tsx
packages/app-explorer/src/Main.tsx
packages/ui-api/src/with/call.tsx
packages/ui-api/src/with/types.ts

Closes https://github.com/polkadot-js/apps/issues/518

Display all events on expanded block view

---

packages/ui-api/src/types.ts
packages/ui-api/src/with/api.tsx
packages/ui-api/src/with/call.tsx

Closes https://github.com/polkadot-js/apps/issues/486

Update HOC props with typing (no any)

---

packages/app-nodeinfo/src/Peers.tsx
packages/app-nodeinfo/src/Summary.tsx
packages/app-nodeinfo/src/index.css
packages/app-nodeinfo/src/index.tsx
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-reactive/package.json
packages/ui-reactive/src/Elapsed.tsx
packages/ui-reactive/src/index.ts
yarn.lock

- Pulls in https://github.com/polkadot-js/api/pull/608
- Snuck refresh & best peer block (the first closes https://github.com/polkadot-js/apps/issues/628)

Bump API, Node info peer id displayed

---

packages/ui-app/src/AddressSummary.tsx

Lookup balance from accountId (AccountIndex mapping)

---

packages/app-settings/src/index.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/index.css

Display last-authored block per validator

---

packages/app-explorer/src/BlockByHash/Events.tsx
packages/app-explorer/src/BlockByHash/Extrinsics.tsx
packages/app-explorer/src/BlockByHash/Logs.tsx
packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-explorer/src/BlockHeaders.tsx
packages/app-explorer/src/Events.tsx
packages/app-explorer/src/index.css
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/InputAddress/index.tsx
packages/ui-app/src/styles/components.css
packages/ui-app/src/styles/form.css
packages/ui-app/src/styles/theme/polkadot.css
packages/ui-params/src/Params.css
packages/ui-signer/src/Transaction.tsx
packages/ui-signer/src/Unlock.tsx
packages/ui-signer/src/index.css

- Closes https://github.com/polkadot-js/apps/issues/645
- Hover should not hop all over the screen, adjust to highlight and not displace other content
- Signer should display from account with name & address

Hover & signer name updates

---

packages/app-settings/src/index.css
packages/app-settings/src/index.tsx

- Just make new and improved settings play well with the UI master
- Some minor tweaks, i18n, toggle back to preset selects first

Misc. small tweaks (settings)

---

packages/app-123code/src/TxButton.tsx
packages/app-democracy/src/Voting.tsx
packages/app-staking/src/index.tsx
packages/app-toolbox/src/index.tsx
packages/apps/src/routing/democracy.ts
packages/apps/src/routing/staking.ts
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-app/src/Status/Queue.tsx
packages/ui-reactive/package.json
packages/ui-signer/src/Modal.tsx
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/655 (issue https://github.com/polkadot-js/api/issues/654)

Bump API for hash-value signatures

---

packages/ui-api/src/Api.tsx
packages/ui-app/src/util/formatBalance.spec.ts
packages/ui-app/src/util/formatBalance.ts

Closes https://github.com/polkadot-js/apps/issues/676

Show balance units with denomination (inline-text)

---

packages/app-js/src/Output.tsx
packages/app-js/src/index.css
packages/app-js/src/snippets/extrinsics-examples.ts
packages/app-js/src/snippets/rpc-examples.ts
packages/app-js/src/snippets/storage-examples.ts

PR into sd-668 -
- Errors are 2 lines off, no idea why and how to make those non-anon.
- throwing an error inside the callbacks, yields uncaught
- On the positive side, things look better when logged now, including structs.... a start. (See the edited example as well)

Expand JS console logging

---

packages/ui-params/src/Param/Tuple.tsx
packages/ui-params/src/Param/Vector.tsx

- Closes https://github.com/polkadot-js/apps/issues/687

Cleanup Tuple state updates

---

packages/app-js/src/index.css

- Part of #692
- 12px font, 18px line-height
- adjust editor/output areas to fit screen bounds
- 60/40 initial split for editor/output

Adjust js Editor/Output sizing

---

packages/app-js/src/Editor.tsx
packages/app-js/src/index.tsx
packages/app-js/src/snippets/wrapping.ts
packages/ui-api/src/Api.tsx
packages/ui-api/src/types.ts

Inject keyring only on dev chains

---

packages/ui-app/src/InputBalance.tsx
packages/ui-app/src/InputNumber.tsx

Closes https://github.com/polkadot-js/apps/issues/725

Fix InputBalance with initial value

---

packages/app-explorer/src/NodeInfo/Peers.tsx
packages/ui-app/src/styles/media.css
packages/ui-params/src/Params.css

Closes https://github.com/polkadot-js/apps/issues/712

Warp ui--row inside Params

---

lerna.json
packages/app-123code/package.json
packages/app-accounts/package.json
packages/app-addresses/package.json
packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-js/package.json
packages/app-settings/package.json
packages/app-staking/package.json
packages/app-storage/package.json
packages/app-toolbox/package.json
packages/app-transfer/package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-params/package.json
packages/ui-reactive/package.json
packages/ui-signer/package.json

Delayed by one, should have gone in with #730

Bump apps version

---

packages/app-js/src/Editor.tsx
packages/app-js/src/index.tsx
yarn.lock

Fixes https://github.com/polkadot-js/apps/issues/733

Bugfix: deep clone imported snippets

---

packages/ui-app/src/InputNumber.tsx

... and again, validator setPreferences is being problematic. The actual sane approach is to strip the SI stuff from InputNumber and properly apply in InputBalance.

Fix InputBalance (with value prop, si calc)

---

packages/app-democracy/src/Summary.tsx
packages/ui-params/src/Param/findComponent.ts

- Adjust `ui-params` componentMap to be easier to adjust
- Additionally closes https://github.com/polkadot-js/apps/issues/743

Cleanup ComponentMap (easier to reason about)

---

packages/ui-api/package.json
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/733, Closes https://github.com/polkadot-js/apps/issues/750

Bump API, fix Option handling on storage

---

packages/app-js/package.json
packages/app-js/src/Playground.tsx
packages/app-js/src/index.tsx
packages/app-js/src/snappyjs.d.ts
yarn.lock

Resolves https://github.com/polkadot-js/apps/issues/752

Compress code with snappyjs

---

packages/app-accounts/src/Restore.tsx

- Closes https://github.com/polkadot-js/apps/issues/760
- Allows both old check and new check from https://github.com/polkadot-js/apps/pull/761

Check for both v0 & v1 files in restore

---

packages/ui-params/src/Param/findComponent.ts
packages/ui-params/src/initValue.ts

Closes https://github.com/polkadot-js/apps/issues/763

Check instanceof to determine param (numbers only)

---

CONTRIBUTING.md
README.md
package.json
packages/apps/webpack.config.js
yarn.lock

- Closes https://github.com/polkadot-js/apps/issues/766

Don't pass UI_MODE/UI_THEME via env

---

packages/ui-app/src/Status/Queue.tsx

Closes https://github.com/polkadot-js/apps/issues/779

Show system events (extrinsic success & failure)

---

package.json
packages/ui-api/package.json
yarn.lock

- Pulls in https://github.com/polkadot-js/api/pull/760
- Closes https://github.com/polkadot-js/apps/issues/790

Bump API (Header with number alias)

---

package.json
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/index.tsx
packages/apps/src/SideBar/Item.tsx
packages/apps/src/routing/staking.ts
packages/apps/src/types.ts
packages/ui-api/package.json
yarn.lock

- As an initial step, have staking available, but actions hidden (until bond call implemented)
- Part of https://github.com/polkadot-js/apps/issues/715
- Pulls in https://github.com/polkadot-js/api/pull/761

Hide staking actions (when on bond API)

---

package.json
packages/ui-api/package.json
yarn.lock

Pulls in API from https://github.com/polkadot-js/api/pull/765 (fixes https://github.com/polkadot-js/api/issues/764 on the apps layer)
cc @siman

Bump API (subId & result out of order fix)

---

packages/app-js/package.json
packages/app-js/src/Playground.tsx
packages/ui-app/package.json
packages/ui-app/src/Editor/codeflask.d.ts
packages/ui-app/src/Editor/index.tsx
packages/ui-app/src/index.tsx

To make it re-usable in `app-settings` to edit custom JSON

Move editor from app-js to ui-app component

---

packages/ui-app/src/Editor/index.tsx
packages/ui-app/src/Editor/style.css

There were two minor bugs regarding the error state in the editor component

Fix editor bugs after refactor

---

packages/apps/src/Content/index.tsx

Closes https://github.com/polkadot-js/apps/issues/809

Inject react router into content (work-around)

---

scripts/findPackages.js

Reported by @tomusdrw - don't try to stat the file, check for existence

lstatSync -> existsSync (for package.json)

---

packages/app-settings/src/General.tsx

Add active setting to SUI <Tab>

---

package.json
packages/ui-api/package.json
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/792
Thanks to @xlc

Metadata V2 support

---

packages/app-js/src/snippets/extrinsics-examples.ts
packages/app-js/src/snippets/storage-examples.ts
packages/app-js/src/snippets/transfer.ts

This is my attempt to solve https://github.com/polkadot-js/apps/issues/828 .

Updated addresses for sr25519

---

packages/app-staking/src/StakeList/Account.tsx
packages/app-staking/src/StakeList/Bonding.tsx
packages/app-staking/src/StakeList/Nominating.tsx
packages/app-staking/src/StakeList/Preferences.tsx
packages/app-staking/src/index.tsx
packages/ui-app/src/TxButton.tsx

Part of https://github.com/polkadot-js/apps/issues/715

Add bonding preferences

---

packages/app-staking/src/Account/Staking.tsx
packages/app-staking/src/Account/index.tsx
packages/ui-app/src/TxButton.tsx

Part of #715 
Staking buttons as available -
Staking panel -

Add ability to stake

---

packages/app-staking/src/Account/Nominating.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/StakeList.tsx

Part of #715
Nominee selection (only single atm, must be expanded) -
Buttons (needs TLC) -

Add nomination (basic, initially single account)

---

packages/app-staking/src/Account/Bonding.tsx
packages/app-staking/src/Account/Controller.tsx
packages/app-staking/src/Account/Nominating.tsx
packages/app-staking/src/Account/Staking.tsx
packages/app-staking/src/Account/index.tsx
packages/ui-app/src/TxButton.tsx

Add chill functionality

---

package.json
packages/app-staking/src/Account/index.tsx
yarn.lock

Display controller only if no bonding

---

package.json
packages/app-staking/src/Account/Bonding.tsx
packages/app-staking/src/Account/SessionKey.tsx
packages/app-staking/src/Account/index.tsx
packages/ui-api/package.json
yarn.lock

Be explicit in setting session keys, rework controlling

---

package.json
packages/app-staking/src/Account/Bonding.tsx
packages/app-staking/src/Account/Nominating.tsx
packages/app-staking/src/Account/Validating.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/StakeList.tsx
packages/app-staking/src/index.css
packages/app-staking/src/index.tsx
packages/app-staking/src/types.ts
packages/ui-api/package.json
packages/ui-api/src/with/call.tsx
yarn.lock

More informative staking page (buttons based on actions)

---

packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/index.tsx
packages/app-staking/src/index.tsx

Re-introduce nominators per validator

---

package.json
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/StakeList.tsx
packages/app-staking/src/index.css
packages/app-staking/src/index.tsx
packages/apps/src/routing/staking.ts
packages/ui-api/package.json
yarn.lock

- Closes #857 
- Closes https://github.com/polkadot-js/apps/issues/858
- Closes https://github.com/polkadot-js/apps/issues/863

Next up list (and API update for improved list support)

---

packages/app-staking/src/Account/Bonding.tsx

Don't allow controllers same as stash

---

packages/app-staking/src/Account/Bonding.tsx

The title says it all, I guess it was simply forgotten. 
- closes #887 
question: should I change my linter settings somehow to make sure my PR reflect what I really changed?

Add value field to destination dropdown for bonding settings

---

packages/ui-app/src/styles/media.css

Remove display: none

---

packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/index.css

Display controller on overview

---

packages/app-staking/src/Overview/Address.tsx

- Closes https://github.com/polkadot-js/apps/issues/916

Combine controller/session when the same

---

packages/app-staking/src/Account/Bond.tsx
packages/app-staking/src/Account/BondExtra.tsx
packages/app-staking/src/Account/index.tsx

- Top-up of bonded value
- Part of https://github.com/polkadot-js/apps/issues/859

Allow bonding of extra funds

---

packages/app-accounts/src/Creator.tsx
packages/app-addresses/src/Creator.tsx
packages/app-addresses/src/Editor.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/index.css
packages/app-staking/src/RecentlyOffline.tsx
packages/app-staking/src/index.css
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/Bonded.tsx
packages/ui-app/src/styles/components.css
packages/ui-reactive/src/Bonded.tsx

Closes #896 
Adds new reactive component to fetch address' controller and then its bonded value
(Accidentally included some work towards showing recentlyOffline in more places as well)

Add BondedRx component & display bonded value, refactor RecentlyOffline

---

packages/app-staking/src/Overview/Address.tsx

Filter nominators on the stash

---

package.json
packages/app-contracts/src/Call.tsx
packages/ui-api/package.json
yarn.lock

cc @RobbePop
... This time I actually clicked the damn button.

Pass actual address when calling contract

---

packages/app-contracts/src/Call.tsx

Swap from params to 0, keeps old

---

packages/app-explorer/src/BlockQuery/index.tsx
packages/app-explorer/src/index.tsx

Closes #942 
Automatically displays latest block when navigating to BlockQuery page without parameter

Auto-show latest block on BlockQuery

---

packages/apps/src/SideBar/index.tsx
packages/ui-app/src/styles/semantic.css
packages/ui-app/src/styles/theme.ts

Substrate tab theme adjustment

---

packages/app-staking/src/Account/Bond.tsx
packages/app-staking/src/Account/Nominating.tsx
packages/app-staking/src/Account/ValidateController.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/Overview/index.tsx
packages/app-staking/src/StakeList.tsx
packages/app-staking/src/index.tsx
packages/app-staking/src/types.ts
packages/ui-app/src/Labelled.tsx

Closes https://github.com/polkadot-js/apps/issues/962

Additional set controller checks

---

packages/ui-signer/src/Checks/index.tsx

Closes https://github.com/polkadot-js/apps/issues/947
Specifically the "this will drop the account" was not highlighted

Make warning visible on existential issues

---

packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/index.css
packages/ui-app/src/styles/app.css

- Closes https://github.com/polkadot-js/apps/issues/936
- Some additional padding, some moving up and everything seems to fit (for now)
- As a bonus when the user does have nominators, the block display works better when there is a session + controller involved

Hide Nominators(0)

---

packages/app-contracts/src/Code.tsx
packages/app-contracts/src/Instantiate.tsx
packages/app-contracts/src/index.tsx
packages/app-contracts/src/store.ts
packages/app-contracts/src/types.ts
packages/ui-api/src/Api.tsx
packages/ui-api/src/index.ts

Closes https://github.com/polkadot-js/apps/issues/979

Store the genesisHash along with code & contracts (load check)

---

packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/ui-app/src/Labelled.tsx
packages/ui-app/src/styles/app.css

- Just couldn't let this one go ... been making my OCD work in overdrive
- Closes #984

Align labels to the top

---

packages/app-contracts/src/Code.tsx
packages/app-contracts/src/Instantiate.tsx
packages/app-contracts/src/ValidateAddr.tsx
packages/app-contracts/src/ValidateCode.tsx
packages/ui-app/src/InfoForInput.tsx
packages/ui-app/src/Status/types.ts
packages/ui-app/src/index.tsx
packages/ui-signer/src/Modal.tsx

- Valid WASM magic number, Closes https://github.com/polkadot-js/apps/issues/981
- Valid address with codehash, Closes https://github.com/polkadot-js/apps/issues/980
- Valid codehash with code, Closes https://github.com/polkadot-js/apps/issues/978
- Additionally, adjust TxButton callbacks so txFailed is called with RPC errors and cancelling

Validate codehash (with wasm), address (with code) & wasm header

---

package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
yarn.lock

- Pulls in https://github.com/polkadot-js/ui/pull/115
- Closes #986 & #987 by @kwingram25

Bump ui & api

---

packages/app-123code/src/AccountSelector.tsx
packages/app-explorer/src/BlockHeaders.tsx
packages/app-extrinsics/src/Balance.tsx
packages/app-extrinsics/src/Selection.tsx
packages/app-staking/src/Account/Bond.tsx
packages/app-staking/src/Account/Nominating.tsx
packages/app-staking/src/Account/Validating.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Accounts.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/index.tsx
packages/app-staking/src/index.tsx
packages/app-staking/src/types.ts
packages/app-storage/src/Query.tsx
packages/app-toolbox/src/Rpc/Account.tsx
packages/ui-api/src/types.ts
packages/ui-api/src/with/call.tsx
packages/ui-api/src/with/types.ts
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/Balance.tsx
packages/ui-app/src/Bonded.tsx
packages/ui-reactive/src/AccountIndex.tsx
packages/ui-reactive/src/Balance.tsx
packages/ui-reactive/src/Bonded.tsx
packages/ui-reactive/src/Nonce.tsx

- Closes https://github.com/polkadot-js/apps/issues/997
- This one sprawled... a bit.

Fix staking buttons to immediately show

---

packages/app-staking/src/Account/index.tsx

Add a proper check to avoid page crash in staking>accounts

---

packages/app-democracy/src/Proposal.tsx
packages/app-democracy/src/Proposals.tsx
packages/app-explorer/src/BestHash.tsx
packages/app-explorer/src/BlockHeaders.tsx
packages/app-explorer/src/BlockQuery/index.tsx
packages/app-explorer/src/EventsRecent.tsx
packages/app-extrinsics/src/Balance.tsx
packages/app-staking/src/Account/UnnominateButton.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-transfer/src/Submit.tsx
packages/apps/src/Content/Status.tsx
packages/apps/src/SideBar/index.tsx
packages/ui-reactive/src/AccountIndex.tsx
packages/ui-reactive/src/Balance.tsx
packages/ui-reactive/src/BestFinalized.tsx
packages/ui-reactive/src/BestNumber.tsx
packages/ui-reactive/src/Chain.tsx
packages/ui-reactive/src/NodeName.tsx
packages/ui-reactive/src/NodeVersion.tsx
packages/ui-reactive/src/Nonce.tsx
packages/ui-reactive/src/TimeNow.tsx
packages/ui-signer/src/Checks/Proposal.tsx
packages/ui-signer/src/Checks/Transfer.tsx

Closes #1009 
Replace all instances of withCall with withCalls<Props>

Replace withCall -> withCalls

---

packages/ui-app/src/CardSummary.tsx

Closes https://github.com/polkadot-js/apps/issues/1008

Adjust summary labels min height

---

packages/app-staking/src/index.css
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/styles/components.css

Closes https://github.com/polkadot-js/apps/issues/1007

Adjust AddressMini layout

---

packages/app-js/src/snippets/storage-examples.ts

Fixes https://github.com/polkadot-js/apps/issues/1061

Fix examples

---

packages/ui-app/src/InputNumber.tsx

Closes #1049 
Keep InputNumber value constant across unit changes

Keep number input value on unit change

---

packages/app-democracy/src/Overview/VotingButtons.tsx

Closes https://github.com/polkadot-js/apps/issues/1083

Swap yay/nay to be correct

---

packages/ui-app/src/styles/components.css

Closes https://github.com/polkadot-js/apps/issues/1087
cc @kwingram25 - Would like your eyes on this one as well (i.e. am I being completely stupid here)

Adjust offline icon placement

---

packages/app-staking/src/Overview/Address.tsx

Hello,
this will fix the problem: 
Thanks!

Fixed my nominations filter (#1080)

---

packages/app-settings/src/index.css
packages/app-settings/src/index.tsx
packages/app-settings/src/md/basics.md

Should round out https://github.com/polkadot-js/apps/issues/1017

Markdown for the settings app

---

packages/ui-app/src/HelpOverlay.tsx

Closes https://github.com/polkadot-js/apps/issues/944

Simple slide in help overlay

---

packages/app-staking/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1073

Align staking capitalization with other apps

---

packages/app-contracts/src/Call.tsx
packages/app-contracts/src/Code.tsx
packages/ui-app/src/TxButton.tsx

- Closes https://github.com/polkadot-js/apps/issues/1037 & Closes https://github.com/polkadot-js/apps/pull/1093
- Adjust code deploy redirection (w & wo contracts)
- Allow contract call with 0 value
- Adjust TxButton to work with non-changing function-as-params (#1093)

Small contracts fixes & adjustments

---

packages/ui-app/src/Chart/Base.tsx
packages/ui-app/src/Chart/Doughnut.tsx
packages/ui-app/src/styles/components.css

Some movement in https://github.com/polkadot-js/apps/issues/674 (inspired by https://github.com/polkadot-js/apps/pull/1097)

Move Chart to styled-components

---

packages/app-accounts/src/Creator.tsx

Closes https://github.com/polkadot-js/apps/issues/1103
- trim seed before passing through (spaces are added anyway)
- catch errors and show validation errors

Handle key suri parsing errors

---

package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-app/src/InputAddress/index.tsx
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/988

Keyring case for recents

---

packages/apps/src/Apps.tsx
packages/apps/src/SideBar/Item.tsx
packages/apps/src/TopBar.tsx
packages/apps/src/overlays/Accounts.tsx
packages/apps/src/overlays/Connecting.tsx
packages/apps/src/styles.ts

Closes https://github.com/polkadot-js/apps/issues/1101

Create an overlay for no accounts

---

package.json
packages/ui-api/package.json
yarn.lock

Should fix https://github.com/polkadot-js/apps/issues/1121

Bump API (combineLatest & multi)

---

packages/app-extrinsics/src/Selection.tsx
packages/ui-app/src/TxButton.tsx

Rework inherent submission (allow inherent submission via extrinsics app)

---

packages/app-staking/src/Account/Bond.tsx
packages/app-staking/src/Account/ValidateController.tsx

Closes https://github.com/polkadot-js/apps/issues/1074

Turn bond controller selection into non-submit errors

---

packages/app-staking/src/Account/index.tsx
packages/ui-app/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1134
It handles value properly, but not quite defaultValue when Uint8Array is supplied. (Which is problematic, since AccountId is very valid as an input)

InputAddress should handle defaultValue of U8a

---

packages/app-js/src/Playground.tsx
packages/app-js/src/index.css

Addresses https://github.com/polkadot-js/apps/issues/1120

Move buttons above the editor

---

packages/app-toolbox/src/Verify.tsx

Closes https://github.com/polkadot-js/apps/issues/1126

Support sr25519 signatures (toolbox verify)

---

packages/app-settings/src/General.tsx
packages/app-toolbox/src/Hash.tsx
packages/app-toolbox/src/Rpc/Selection.tsx
packages/app-toolbox/src/Sign.tsx
packages/app-toolbox/src/Unlock.tsx

- Settings > General
- Toolbox (excluding verify, which was done in https://github.com/polkadot-js/apps/pull/1131)

Additional help messages

---

packages/app-explorer/src/BlockInfo/index.tsx
packages/app-explorer/src/Main.tsx
packages/app-explorer/src/Query.tsx
packages/app-explorer/src/index.tsx
packages/ui-app/src/FilterOverlay.tsx
packages/ui-app/src/Input.tsx
packages/ui-app/src/Tabs.tsx

Closes https://github.com/polkadot-js/apps/issues/1119
- Allow onEnter to submit
- Incorporate @Tbaut disabled suggestion
- Move Query back to explorer (it is only valid there)
- Adjust layout (internal button, let SUI do the heavy lifting)

Explorer query updates

---

packages/ui-reactive/src/Unlocking.tsx

closes https://github.com/polkadot-js/apps/issues/1135
I'd take any good advice on how to do this in a more elegant manner, I couldn't figure out how to do this nicely with a `reduce` instead of a `map`+ `for..of`
before / after

Group unlocking by era

---

packages/app-staking/src/Account/Bond.tsx
packages/app-staking/src/Account/Nominating.tsx
packages/app-staking/src/Account/SessionKey.tsx
packages/app-staking/src/Account/Unbond.tsx
packages/app-staking/src/Account/ValidateSession.tsx
packages/app-staking/src/Account/Validating.tsx
packages/app-staking/src/Account/index.tsx

Check sessionkey type before allowing it to be set

Only allow ed25519 session keys in modal

---

packages/app-democracy/src/index.tsx
packages/app-settings/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1140

Hide developer settings & democracy propose for light mode

---

packages/app-staking/src/Account/Bond.tsx

Remove console from Bond.tsx

---

package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
yarn.lock

Bump API, pulls in fixes for https://github.com/polkadot-js/api/issues/900 (also includes @Stefie 's https://github.com/polkadot-js/api/pull/904 that went in before, so this _may_ also be a fix for #1160)
Local master, EE & Alex:

Bump API, EventRecord update

---

package.json
packages/ui-api/package.json
yarn.lock

Bump API, node-template + EventRecord

---

package.json
packages/ui-api/package.json
packages/ui-app/src/InputExtrinsic/options/method.tsx
yarn.lock

... contains @Stefie's fixes, so _may_ fix https://github.com/polkadot-js/apps/issues/1160

Bump API, metadata, new multi & derive, Extinsic/Method

---

package.json
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-explorer/src/BlockHeaders.tsx
packages/app-explorer/src/BlockInfo/ByHash.tsx
packages/app-explorer/src/SummarySession.tsx
packages/app-staking/src/Account/Validating.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/Overview/index.tsx
packages/apps/src/Content/index.tsx
packages/ui-api/package.json
yarn.lock

Convert to new api.derive (multi-query) functions

---

packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/CopyButton.tsx
packages/ui-app/src/IdentityIcon.tsx
packages/ui-app/src/styles/components.css

Closes https://github.com/polkadot-js/apps/issues/1176

Re-add CopyButton on AddressSummary

---

packages/app-extrinsics/src/Balance.tsx
packages/app-staking/src/Account/index.tsx
packages/ui-reactive/src/Balance.tsx
packages/ui-reactive/src/Unlocking.tsx

- closes https://github.com/polkadot-js/apps/issues/1185
- reorder alphabetically on the fly

Convert balances.freeBalance to derive.balances.all

---

.gitignore
packages/app-explorer/src/index.css
packages/ui-app/src/styles/app.css

Trim details to the summary, expand shows all

---

packages/app-accounts/src/modals/Transfer.tsx

Reworked the fee calculations to one-shot promises - instead of subscriptions. This needs to be applied everywhere where there are calculations.
(It potentially just keeps on creating the original nested versions each time there are changes - do it explicitly when asked)

Transfer fees calc cleanups

---

packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/CopyButton.tsx
packages/ui-app/src/styles/app.css
packages/ui-app/src/styles/components.css

As per https://github.com/polkadot-js/apps/pull/1210#issuecomment-496028122

Tiny copy button (same as edit, full-row action)

---

package.json
packages/app-accounts/src/Account.tsx
packages/app-accounts/src/modals/Create.tsx
packages/app-address-book/src/Address.tsx
packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/apps/webpack.config.js
packages/ui-api/package.json
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/Balance.tsx
packages/ui-app/src/Bonded.tsx
packages/ui-app/src/Nonce.tsx
packages/ui-app/src/styles/components.css
yarn.lock

Convert the built-in AddressRow/AddressSummary label display to use labels

Bumps, minor style adjustments (labels)

---

packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/ui-app/src/CardSummary.tsx
packages/ui-app/src/styles/app.css

Could make it slightly cleaner (for some), maybe a (slight) change is as good as a holiday...

Some minor card styling changes

---

packages/app-accounts/src/Account.tsx
packages/app-accounts/src/modals/Transfer.tsx
packages/app-address-book/src/Address.tsx

Add "deposit" button to address (transfer to)

---

package.json
packages/ui-api/package.json
yarn.lock

Pulls in updated keyring with Bob's stash

Bump common & api

---

packages/ui-app/src/AddressInfo.tsx
packages/ui-app/src/AddressSummary.tsx

From watercooler -
Not sure what causes this...
Also closes https://github.com/polkadot-js/apps/issues/1235

Only render positive numbers

---

packages/app-accounts/src/Account.tsx
packages/app-address-book/src/Address.tsx
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-explorer/src/BlockInfo/ByHash.tsx
packages/app-explorer/src/BlockInfo/Extrinsics.tsx
packages/ui-api/src/Api.tsx
packages/ui-api/src/types.ts
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/LinkPolkascan.tsx
packages/ui-app/src/index.tsx
packages/ui-app/src/styles/components.css

Only per enabled chain, which is currently only Alexander.

External links from blocks/addresses/extrinsics to polkascan

---

package.json
packages/ui-api/package.json
packages/ui-app/src/CryptoType.tsx
packages/ui-signer/src/Modal.tsx
yarn.lock

- Pulls in https://github.com/polkadot-js/extension/pull/36
Needs some work.

SingleSource accounts & signer compat

---

package.json
packages/ui-api/package.json
packages/ui-app/src/AddressInfo.tsx
packages/ui-app/src/styles/semantic.css
packages/ui-signer/src/Transaction.tsx
yarn.lock

- Pull in https://github.com/polkadot-js/api/pull/963
- Reverts https://github.com/polkadot-js/apps/pull/1241 (due to above)
Problematic account displays and is able to transfer (without success, i.e. `CantPay` as opposed to crash). 
Should be logged: Fees should use the availableBalance in their calculations

Revert .gtn(-1), update api

---

packages/app-accounts/src/md/basic.md
packages/ui-app/src/AddressInfo.tsx

closes: https://github.com/polkadot-js/apps/issues/1250
closes: https://github.com/polkadot-js/apps/issues/1251

unlocking -> unbonding

---

packages/app-accounts/src/modals/Transfer.tsx
packages/ui-signer/src/Checks/Transfer.tsx
packages/ui-signer/src/Checks/index.tsx

closes https://github.com/polkadot-js/apps/issues/1246
Alexander, recipient too low
Substrate node, dropping account

Use balances.all when possible and show existential deposit

---

packages/app-staking/src/Overview/Address.tsx
packages/apps/src/Apps.tsx
packages/apps/webpack.config.js
packages/ui-app/src/AddressInfo.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/styles/components.css

A small part of https://github.com/polkadot-js/apps/issues/1232

Render AddressRow balances from AddressInfo

---

packages/app-accounts/src/Account.tsx
packages/app-address-book/src/Address.tsx
packages/app-council/src/Overview/Candidate.tsx
packages/app-council/src/Overview/Member.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/ui-app/src/AddressCard.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/index.tsx

Add AddressCard

---

packages/ui-app/src/AddressCard.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/CardGrid.tsx

Flex AddressRow on header & buttons

---

packages/app-js/src/ActionButtons.tsx
packages/app-js/src/Output.tsx
packages/app-js/src/Playground.tsx
packages/app-js/src/index.tsx

- Closes https://github.com/polkadot-js/apps/issues/1271
- Reverts TxComponent
- Small whitespace changes
- Output to PureComponent (consistency)

Fix snippet saving

---

package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
yarn.lock

Should have been part of https://github.com/polkadot-js/apps/pull/1273 (Trigger-happy merge)

Bump ui, api & common

---

packages/app-settings/src/General.tsx
packages/ui-app/src/Toggle.tsx
packages/ui-app/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1205

Use toggle for custom endpoint

---

packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/RecentlyOffline.tsx

- Last applicable part of https://github.com/polkadot-js/apps/issues/1232, closes https://github.com/polkadot-js/apps/issues/1232 (Any small issues after this can be logged, addressed - it needs playtime)
- Remove absolute from RecentlyOffline, add positioning to AddressRow/AddressMini
Mini and card -

Remove absolute from RecentlyOffline

---

package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
yarn.lock

cc @kwingram25 Also pulls in your keyring changes into master

Bump deps (incl. substrate master support via api)

---

packages/app-staking/src/Actions/Account/index.tsx
packages/ui-app/src/AddressCard.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/Row.tsx

Use AddressCard

---

packages/app-democracy/src/Overview/Item.tsx
packages/app-democracy/src/Overview/Referendum.tsx
packages/app-democracy/src/Overview/Seconding.tsx
packages/app-democracy/src/Overview/Voting.tsx
packages/app-staking/src/Overview/Address.tsx
packages/ui-app/src/index.tsx
packages/ui-app/src/styles/components.css

- Closes https://github.com/polkadot-js/apps/issues/1306
- Reworks static min-length to not overflow (https://github.com/polkadot-js/apps/pull/1309#issuecomment-503469033)

Seconding modal

---

packages/app-123code/src/AccountSelector.tsx
packages/app-123code/src/Summary.tsx
packages/app-accounts/src/Vanity/Match.tsx
packages/app-accounts/src/Vanity/index.tsx
packages/app-council/src/index.tsx
packages/app-dashboard/src/Entry.tsx
packages/app-dashboard/src/index.tsx
packages/app-explorer/src/index.tsx
packages/app-settings/src/Developer.tsx
packages/app-staking/src/Actions/Accounts.tsx
packages/app-sudo/src/SetKey.tsx
packages/app-toolbox/src/Rpc/Account.tsx

Where these things are simple, remove the `const Wrapper = styled.div'...styles...'` and move to the the end of the files.
- remove `Wrapper` element
- add className to element (div, section, main, etc...)
- add the styles to the end of the file
There are still some left, not major issue, some of these probably need to be split into multiple components, others need some extra classes. But the bulk of the simple-Wrapper-only ones are taken care of here. Just adding some more consistency to the codebase.

Small rework of styled (to bottom)

---

packages/ui-app/src/Extrinsic.tsx
packages/ui-app/src/Params/Extrinsic.tsx
packages/ui-params/src/Param/index.tsx
packages/ui-params/src/Params.css

Fix extrinsics app [object Object]

---

packages/ui-app/src/Chart/Doughnut.tsx
packages/ui-app/src/Chart/HorizBar.tsx

Closes https://github.com/polkadot-js/apps/issues/1318

Use getDerivedState for Chart (and kick the can...)

---

packages/app-accounts/src/modals/Transfer.tsx
packages/app-contracts/src/ABI.tsx
packages/app-staking/src/Actions/Account/index.tsx
packages/app-sudo/src/SetKey.tsx
packages/app-toolbox/src/Sign.tsx

Note: I have not tested these - at all. Not for lack of will, just ran out of time with the other PRs opened. These are not critical though, so can hang about.

Additional styled component adjustments

---

packages/app-contracts/src/Contracts/Add.tsx
packages/app-contracts/src/Deploy.tsx
packages/app-contracts/src/store.ts

cc @kwingram25 Would like your eyes on this.

Remove api imports (only on store, non-context)

---

packages/app-accounts/src/modals/Create.tsx
packages/ui-app/src/Input.tsx

- Don't display derivation path & type labels as monospace
- readonly seed when in dev seed mode

Create account cleanups

---

packages/app-democracy/src/Overview/Item.tsx
packages/app-democracy/src/Overview/Referendum.tsx
packages/ui-app/src/Chart/HorizBar.tsx

- closes https://github.com/polkadot-js/apps/issues/1352
- closes https://github.com/polkadot-js/apps/issues/1342

Fixes for democracy display

---

packages/app-staking/src/Actions/Account/SetSessionAccount.tsx

- forgot this one in an earlier PR

Remove stray log

---

packages/app-staking/src/Actions/Account/BondExtra.tsx
packages/ui-app/src/Labelled.tsx
packages/ui-app/src/styles/app.css

closes #1368 
this is how it looks, I find it quite hard to read:

Bonded and available as labelExtra in Staking > bond more funds

---

packages/app-accounts/src/vanitygen/cli.ts

Additionally, wait for crypto before using, i.e. allow sr25519

Fix passing numbers (e.g. 12345), to vanitygen cli

---

packages/app-accounts/src/Vanity/index.tsx
packages/app-accounts/src/vanitygen/cli.ts
packages/app-accounts/src/vanitygen/generate.ts
packages/app-accounts/src/vanitygen/types.d.ts

`$ yarn vanitygen --match 55 --mnemonic true`
`--match` is the string to match on
cc @Tbaut

Allow cli vanitygen mnemonic

---

packages/ui-app/src/Call.tsx
packages/ui-params/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1403
I introduced this one :(

Fix static params display

---

packages/app-accounts/src/Account.tsx
packages/app-accounts/src/Overview.tsx
packages/app-address-book/src/Address.tsx
packages/app-contracts/src/Codes/Upload.tsx
packages/app-contracts/src/Contracts/Call.tsx
packages/app-contracts/src/Deploy.tsx
packages/app-contracts/src/Params.tsx
packages/app-contracts/src/index.tsx
packages/app-democracy/src/Overview/Voting.tsx
packages/app-staking/src/Actions/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/index.tsx
packages/ui-app/src/LabelHelp.tsx
packages/ui-params/src/Param/Enum.tsx
packages/ui-params/src/Param/Vector.tsx
packages/ui-params/src/index.tsx

Casting to `unknown as State` loses info and checking, the `Pick` approach solves that

eslint cleanup (as unknown as State -> Pick<State, never>)

---

package.json
packages/app-contracts/package.json
packages/ui-api/package.json
yarn.lock

- closes https://github.com/polkadot-js/apps/issues/1378

Bump API, "nextKeyFor" for 2.x

---

package.json
packages/app-contracts/package.json
packages/app-explorer/src/BlockInfo/Extrinsics.tsx
packages/ui-api/package.json
yarn.lock

Add birth to mortality

---

packages/app-accounts/src/vanitygen/cli.ts

- this changes the default behaviour BTW

add --withCase to vanitygen cli

---

packages/app-js/src/snippets/consts-examples.ts
packages/app-js/src/snippets/index.ts
packages/app-js/src/snippets/storage-examples.ts

Quick one in between while compiling Substrate.
Closes https://github.com/polkadot-js/apps/issues/1418

Add const example to app-js

---

package.json
packages/app-123code/package.json
packages/app-accounts/package.json
packages/app-address-book/package.json
packages/app-contracts/package.json
packages/app-council/package.json
packages/app-dashboard/package.json
packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-js/package.json
packages/app-parachains/package.json
packages/app-settings/package.json
packages/app-staking/package.json
packages/app-storage/package.json
packages/app-sudo/package.json
packages/app-toolbox/package.json
packages/app-transfer/package.json
packages/app-treasury/package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-app/src/Call.tsx
packages/ui-app/src/InputFile.tsx
packages/ui-params/package.json
packages/ui-signer/package.json
packages/ui-signer/src/Modal.tsx
yarn.lock

Bump api (support &[u8])

---

packages/ui-app/src/InputNumber.tsx

Get mod length before convert to bignumber
In function bnToInputValue , 0.001 and 0.1 will convert to the same value.

Fixed InputNumber.tsx bnToInputValue convert bug

---

packages/ui-signer/src/Checks/Transfer.tsx
packages/ui-signer/src/Checks/index.tsx

lte -> lt
https://github.com/paritytech/substrate/blob/1fcd1286d87dc7acb8c2b0ee3ff6fe2199536ea0/srml/balances/src/lib.rs#L892

Make existentialDeposit check match with Substrate

---

packages/app-council/src/Motions/Motion.tsx
packages/app-council/src/Motions/Propose.tsx
packages/app-council/src/Motions/index.tsx
packages/app-treasury/src/Overview/Approve.tsx
packages/ui-app/src/Voting.tsx

Closes #1436 
(collective => council)

Use correct api section for app-council

---

packages/app-staking/src/Actions/Account/InputValidationSessionEd25519.tsx
packages/app-staking/src/Actions/Account/InputValidationSessionSr25519.tsx
packages/app-staking/src/Actions/Account/SetSessionAccount.tsx

- Closes https://github.com/polkadot-js/apps/issues/1449
- Does not solve https://github.com/polkadot-js/apps/issues/1408 (but at least it is set-able)

Session keys for 2.x

---

packages/ui-api/src/Api.tsx

The default decimals aligns with what we have on e.g. FF & Alex (so a sane default)

Change dev units to 'DEV', adjust decimals to 15 (when 0)

---

package.json
packages/app-contracts/package.json
packages/ui-api/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/1408
- Alice is default
- Bob has a key set
- Charlie doesn't (yet) have a key set
- Eve is just nominating, no key set

Bump API, fix sessions

---

packages/app-staking/src/Overview/Address.tsx
packages/ui-app/src/Row.tsx
packages/ui-app/src/styles/app.css

Hello :) 
Looking good in My Accounts and My Contacts:

Adjusted article padding and corrected Row's buttons position (1465)

---

package.json
packages/app-contracts/package.json
packages/apps/src/SideBar/NodeInfo.tsx
packages/apps/src/SideBar/SideBar.css
packages/apps/src/SideBar/index.tsx
packages/apps/src/SideBar/logos.ts
packages/ui-api/package.json
yarn.lock

Display logo based on node, prominent chain

---

packages/app-staking/src/Actions/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/react-components/src/AddressInfo.tsx
packages/react-components/src/CardGrid.tsx

- closes #1500 
- closes #1487

Render session hex

---

package.json
packages/app-contracts/package.json
packages/app-storage/src/Query.tsx
packages/react-api/package.json
packages/react-params/src/valueToText.tsx
yarn.lock

- Pull in API for fix of https://github.com/polkadot-js/api/issues/1310

Bump API, storage dup. fix

---

packages/react-components/src/CardGrid.tsx
packages/react-components/src/Collection.tsx

@jacogr fixes the missing button problem

Add buttons back

---

package.json
packages/app-contracts/package.json
packages/app-staking/src/Actions/Account/Validate.tsx
packages/react-api/package.json
packages/react-components/src/AddressInfo.tsx
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/1325 with updated `ValidatorPrefs`, adapt for 1.x & 2.x

Update for 2.x ValidatorPrefs

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
packages/react-components/src/Labelled.tsx
yarn.lock

cc @kwingram25 This whacks the label text-transform as well - so there _may_ be some where it is inconsistent now (hopefully not, but, well...)

Bump API, no default label lowerCase

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
packages/react-api/src/Api.tsx
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/1335

Use ss58Format from chain properties

---

packages/app-staking/src/Actions/Account/InputValidationController.tsx
packages/app-staking/src/Actions/Account/Validate.tsx
packages/app-staking/src/Actions/NewStake.tsx
packages/apps/src/SideBar/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1516

Only warn for controller === stash (Dev, Kusama)

---

packages/app-explorer/src/Forks.tsx
packages/app-explorer/src/index.tsx

AuraBabe fork display

---

packages/app-claims/src/index.tsx

Clarify instructions and show placeholder object

Claims placeholder

---

packages/app-staking/src/Actions/Account/SetControllerAccount.tsx
packages/app-staking/src/Actions/NewStake.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/index.tsx
packages/react-api/src/with/call.tsx

Closes https://github.com/polkadot-js/apps/issues/1524

Render validators based on stashId or address

---

package.json
packages/app-contracts/package.json
packages/app-explorer/src/BestHash.tsx
packages/app-explorer/src/BlockHeaders.tsx
packages/app-explorer/src/Forks.tsx
packages/app-js/src/snippets/rpc-examples.ts
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/index.tsx
packages/react-api/package.json
packages/react-components/src/styles/app.css
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/1338

Swap to subscribeNewHeads in API

---

packages/apps/src/SideBar/SideBar.css
packages/apps/src/SideBar/index.tsx

Display specVersion as part of chain details

---

package.json
packages/app-123code/src/SummaryBar.tsx
packages/app-accounts/src/modals/Create.tsx
packages/app-claims/src/.test-jaco.json
packages/app-claims/src/.test-keith.json
packages/app-contracts/package.json
packages/react-api/package.json
yarn.lock

Currently the derive path with a `///password` specifier doesn't work - since these are split and not actually part of the path. Use the validate suri functionality

Fix derive for ///password

---

packages/app-claims/src/index.tsx

Allows claiming to an account in address book

---

packages/react-params/src/Param/KeyValueArray.tsx

... KeyValue is now a Tuple in the api

Fix KeyValue[] input (eg. system.setStorage)

---

packages/app-explorer/src/BlockInfo/Extrinsics.tsx

Closes https://github.com/polkadot-js/apps/issues/1547

Fix index position

---

packages/app-democracy/src/Overview/Referendum.tsx
packages/app-toolbox/src/Rpc/Selection.tsx
packages/react-components/src/Toggle.tsx
packages/react-params/src/Param/Amount.tsx
packages/react-params/src/Param/Balance.tsx
packages/react-params/src/Param/Base.tsx
packages/react-params/src/Param/Bool.tsx
packages/react-params/src/Param/Bytes.tsx
packages/react-params/src/Param/Code.tsx
packages/react-params/src/Param/Enum.tsx
packages/react-params/src/Param/Hash.tsx
packages/react-params/src/Param/KeyValueArray.tsx
packages/react-params/src/Param/Moment.tsx
packages/react-params/src/Param/Static.tsx
packages/react-params/src/Param/Struct.tsx
packages/react-params/src/Param/Tuple.tsx
packages/react-params/src/Param/Unknown.tsx
packages/react-params/src/Param/Vector.tsx
packages/react-params/src/Param/Vote.tsx
packages/react-params/src/Param/VoteThreshold.tsx
packages/react-params/src/Param/index.tsx
packages/react-params/src/Params.css
packages/react-params/src/index.tsx
packages/react-params/src/types.ts

TODO: Allow for use where we query linked maps (storage)

Allow optional params in state/toolbox

---

package.json
packages/app-accounts/src/modals/Transfer.tsx
packages/app-contracts/package.json
packages/app-staking/src/Actions/Account/BondExtra.tsx
packages/react-api/package.json
packages/react-api/src/Api.tsx
packages/react-api/src/overrides/chain/index.ts
packages/react-api/src/overrides/spec/edgeware.ts
packages/react-api/src/overrides/spec/index.ts
packages/react-components/src/InputBalanceBonded.tsx
packages/react-components/src/TxComponent.tsx
packages/react-signer/src/Checks/index.tsx
yarn.lock

- Closes https://github.com/polkadot-js/apps/issues/1574
- Fixes staking (max < 0), also employ same checks elsewhere
- Inject Edgeware types by default when node is detected

Edgeware support

---

packages/apps/src/overlays/Connecting.tsx

Closes https://github.com/polkadot-js/apps/issues/1594

Fix Connecting

---

packages/app-generic-asset/LICENSE
packages/app-generic-asset/README.md
packages/app-generic-asset/package.json
packages/app-generic-asset/src/AssetCard.tsx
packages/app-generic-asset/src/AssetRow.tsx
packages/app-generic-asset/src/Assets.tsx
packages/app-generic-asset/src/Transfer.tsx
packages/app-generic-asset/src/assetsRegistry.tsx
packages/app-generic-asset/src/index.tsx
packages/app-generic-asset/src/modal.tsx
packages/app-generic-asset/src/modals/Create.tsx
packages/app-generic-asset/src/translate.ts
packages/apps-routing/src/generic-asset.ts
packages/apps-routing/src/index.ts
packages/react-params/src/Param/findComponent.ts
tsconfig.json

Part of #1451
Depends on https://github.com/polkadot-js/api/pull/1229
Needs some more thoughts about the UI/UX. Currently only able to make transfer call.
Can be tested with this branch: https://github.com/cennznet/substrate/tree/node-with-generic-asset

GenericAsset Transfer app

---

packages/app-settings/src/Developer.tsx
packages/app-settings/src/General.tsx
packages/app-settings/src/index.tsx
packages/app-treasury/src/index.tsx
packages/react-api/src/ledger.ts

Closes https://github.com/polkadot-js/apps/issues/1623

Limit Ledger capabilities per chain

---

packages/react-params/src/Param/findComponent.ts
packages/react-params/src/initValue.ts

Values & components for H{256, 512} & i{8, 16, 32, 64, 128}

---

packages/app-settings/src/General.tsx
packages/apps/src/SideBar/SideBar.css
packages/apps/src/SideBar/index.tsx
packages/apps/src/modals/Network.tsx

Added network modal to select chain

---

packages/react-components/src/Status/Queue.tsx
packages/react-components/src/Status/types.ts

WIP, this is still (a) not perfect & (b) a less-than-optimal monster

Convert status queue

---

packages/app-accounts/src/Account.tsx

Closes https://github.com/polkadot-js/apps/issues/1664

Remove backup, change pass & delete from dev accounts

---

packages/app-staking/src/Actions/Accounts.tsx
packages/react-components/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1669

Fix nomination selection (multi)

---

packages/react-components/src/Button/Button.tsx
packages/react-components/src/Button/types.ts
packages/react-components/src/Status/Queue.tsx
packages/react-components/src/Status/constants.ts
packages/react-components/src/Status/index.tsx

Added dismiss notifications feature

---

packages/app-toolbox/src/Rpc/Selection.tsx

Rework once we have https://github.com/polkadot-js/apps/issues/1661 & https://github.com/polkadot-js/apps/issues/1622

Display Option<Type> on RPC toolbox

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/1437

Bump API, JS console clone fix

---

packages/app-storage/src/Query.tsx
packages/app-storage/src/Selection/Consts.tsx
packages/app-storage/src/Selection/Modules.tsx
packages/app-storage/src/Selection/Raw.tsx
packages/app-storage/src/index.tsx

Also closes https://github.com/polkadot-js/apps/issues/1689

Rework query components (no refs)

---

packages/app-staking/src/Actions/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/react-components/src/AddressInfo.tsx
packages/react-components/src/AddressRow.tsx

- Closes #1701 
- Closes #1700

Fix nominate display, add commission display

---

packages/app-toolbox/src/Verify.tsx

Align Sig Validity Indicator (#1660)

---

packages/app-democracy/src/Overview/Propose.tsx
packages/app-democracy/src/Overview/index.tsx
packages/app-democracy/src/index.tsx

1. Convert Submit proposal tab into a modal component
2. Add a button to open up this modal

Turn Submit proposal tab into a modal

---

packages/app-staking/src/Actions/Account/Nominate.tsx

Closes https://github.com/polkadot-js/apps/issues/1712

Don't allow unknown nominate add

---

packages/app-democracy/src/Overview/Propose.tsx
packages/react-params/src/Param/BaseBytes.tsx

Democracy propose invalid Bytes disabled

---

packages/react-components/src/styles/semantic.ts

Closes https://github.com/polkadot-js/apps/issues/1696

Align input background transparency

---

packages/app-staking/src/Actions/Account/SetSessionKey.tsx
packages/app-staking/src/Actions/Account/index.tsx
packages/react-components/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1729

Set session key mismatch

---

packages/react-params/src/Param/BaseBytes.tsx
packages/react-params/src/Param/Hash256.tsx
packages/react-params/src/Param/Hash512.tsx
packages/react-params/src/Param/Tuple.tsx
packages/react-params/src/Param/findComponent.ts

Closes https://github.com/polkadot-js/apps/issues/1736

Fix Tuple rendering (in same vein as Struct)

---

packages/app-parachains/src/Overview/Parachains.tsx
packages/app-parachains/src/Overview/Summary.tsx
packages/react-components/src/InputFile.tsx
packages/react-params/src/Param/File.tsx

- allow detection for hex files
- update parachain queries for current polkadot master

Updates for parachains

---

packages/react-params/src/Param/Base.tsx
packages/react-params/src/Param/Vector.tsx

Remove some of the inconsistent magic, just render via Params

Rework Vector to use Params (like Struct, Tuple)

---

packages/app-js/src/ActionButtons.tsx
packages/app-js/src/Playground.tsx

- Closes #1746 
- Closes #1747

JS editor fixes

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/1753

Bump API (derive.staking.info fixes)

---

package.json
packages/app-accounts/src/modals/Create.tsx
packages/app-address-book/src/modals/Create.tsx
packages/app-contracts/package.json
packages/app-council/src/Motions/Propose.tsx
packages/app-council/src/Overview/Member.tsx
packages/app-council/src/Overview/Members.tsx
packages/app-council/src/Overview/SubmitCandidacy.tsx
packages/app-council/src/Overview/Summary.tsx
packages/app-council/src/Overview/Vote.tsx
packages/app-council/src/Overview/index.tsx
packages/apps-routing/src/council.ts
packages/react-api/package.json
packages/react-params/src/Param/Vector.tsx
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/1766

Support electionsPhragmen

---

packages/app-address-book/src/Address.tsx
packages/app-council/src/Overview/Summary.tsx
packages/app-council/src/Overview/index.tsx
packages/react-components/src/AddressInfo.tsx
packages/react-components/src/AddressRow.tsx

Nicknames & term progress

---

packages/app-council/src/Overview/Vote.tsx
packages/app-staking/src/Actions/Accounts.tsx
packages/react-components/src/AddressMini.tsx
packages/react-components/src/AddressRow.tsx
packages/react-components/src/InputAddress/index.tsx
packages/react-components/src/util/getAddressName.ts
packages/react-query/src/AccountName.tsx
packages/react-query/src/Balance.tsx
packages/react-query/src/Bonded.tsx
packages/react-query/src/LockedVote.tsx
packages/react-query/src/index.ts

Lookup nicknames

---

packages/react-components/src/AddressRow.tsx
packages/react-components/src/InputAddress/KeyPair.tsx
packages/react-components/src/InputAddress/createItem.tsx
packages/react-components/src/InputAddress/index.tsx
packages/react-components/src/util/getAddressName.ts
packages/react-query/src/AccountName.tsx

Closes https://github.com/polkadot-js/apps/issues/1776

Addresses in nominate

---

packages/react-query/src/AccountName.tsx

Cache names

---

packages/app-staking/src/Actions/Account/BondExtra.tsx
packages/app-staking/src/Actions/Account/index.tsx
packages/app-staking/src/types.ts
packages/react-components/src/InputBalanceBonded.tsx
packages/react-signer/src/Checks/constants.ts
packages/react-signer/src/Checks/index.tsx

- Closes #1823 
- Additionally (since it was hanging about), remove the explicit nonce RPCs (we have this on DerivedBalances)

Check freeBalance with bondExtra, not availableBalance

---

packages/react-signer/src/Modal.tsx

- Closes https://github.com/polkadot-js/apps/issues/1829 with a toggle alternative

Toggle for tip

---

packages/react-components/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1855

Enable pointer events for InputAddress

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
yarn.lock

Bump @polkadot/api

---

package.json
packages/app-contracts/package.json
packages/app-contracts/src/Deploy.tsx
packages/react-api/package.json
yarn.lock

Needs https://github.com/polkadot-js/api/pull/1559

Use most recent contract from result block

---

packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Query/Validator.tsx
packages/react-hooks/src/trackStream.tsx

Closes https://github.com/polkadot-js/apps/issues/1894

Add currency indicator to staking charts

---

packages/app-staking/src/Actions/Account/index.tsx
packages/app-staking/src/Actions/Accounts.tsx

Closes https://github.com/polkadot-js/apps/issues/1893

Disable stash operations (when not own)

---

packages/app-staking/src/Query/Validator.tsx
packages/app-staking/src/index.tsx
packages/app-staking/src/useSessionRewards.tsx
packages/react-hooks/src/index.ts

- Closes #1902 
- Closes #1903

Cleanup reward graphs

---

packages/app-staking/src/Actions/Account/Validate.tsx

Allow zero values for rewards

---

packages/app-settings/src/General.tsx
packages/react-components/package.json
yarn.lock

Declaring onChange handlers for each Settings property is quite repetitive. I added a high-order function that creates a handler for a given property name.
Required PR: https://github.com/polkadot-js/ui/pull/243

Refactor settings handlers with generic high-order function

---

packages/app-settings/src/General.tsx
packages/app-settings/src/types.ts
packages/app-settings/src/util.tsx
packages/apps/public/locales/en/app-settings.json
packages/apps/public/locales/ja/app-settings.json

Related Comment: https://github.com/polkadot-js/apps/pull/1919#issuecomment-556380093
Related PR: https://github.com/polkadot-js/ui/pull/244

Add language options inside app-settings

---

packages/app-toolbox/src/Sign.tsx
packages/app-toolbox/src/Unlock.tsx

Needs https://github.com/polkadot-js/extension/pull/196

Allow signRaw usable from extension

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
yarn.lock

Makes UI transactions work again after being broken with https://github.com/paritytech/substrate/pull/4165

Bump API deps (DispatchInfo changes)

---

package.json
packages/app-contracts/package.json
packages/app-staking/src/Targets/Summary.tsx
packages/app-staking/src/Targets/Validator.tsx
packages/app-staking/src/Targets/index.tsx
packages/app-staking/src/Targets/types.ts
packages/app-staking/src/index.tsx
packages/react-api/package.json
yarn.lock

Requires https://github.com/polkadot-js/api/pull/1612

Nomination target dashboard

---

packages/app-123code/src/SummaryBar.tsx

Fixes SummaryBar in app-123code

---

packages/app-staking/src/Overview/Address.tsx
packages/react-components/src/Badge.tsx

Closes https://github.com/polkadot-js/apps/issues/1980

Remove broken tooltip expand

---

packages/app-contracts/src/Contracts/Contract.tsx
packages/app-contracts/src/Contracts/index.tsx

This reverts commit 0aacf3a09d060ceb4ba76135e166e4c8f81f18f9.

Revert "Remove contracts call functionality (not working) (#1999)"

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
yarn.lock

- Pulls in API with DoubleMap hashing adjustments for variable-length params.
- Closes #2007
Slight UI adjustment since consts are now (correctly) without the length, but still working -

Api Bump (DoubleMap)

---

packages/app-claims/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/2016

Fixup claims pay message via consts

---

package.json
packages/app-contracts/package.json
packages/app-contracts/src/Contracts/index.tsx
packages/app-explorer/src/BlockInfo/Extrinsics.tsx
packages/react-api/package.json
packages/react-params/src/Param/Proposal.tsx
packages/react-signer/src/Transaction.tsx
yarn.lock

- Introduce identity types as per https://github.com/polkadot-js/api/pull/1658, follow ups fo
- https://github.com/paritytech/substrate/pull/4326
- https://github.com/paritytech/polkadot/pull/676
- Additionally closes https://github.com/polkadot-js/apps/issues/2021

Bump API (Polkadot frame-identity types)

---

packages/app-staking/src/Actions/Account/index.tsx

Closes https://github.com/polkadot-js/apps/issues/2057

Remove balance from commission display

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
yarn.lock

Bump to latest api

---

packages/app-accounts/src/Account.tsx
packages/app-accounts/src/Overview.tsx
packages/app-address-book/src/Address.tsx
packages/app-address-book/src/Overview.tsx
packages/react-components/src/Input.tsx
packages/react-components/src/Labelled.tsx

Closes https://github.com/polkadot-js/apps/issues/2100

Filter accounts/addresses by tag or name

---

packages/app-staking/src/Actions/Account/SetSessionKey.tsx
packages/app-staking/src/Actions/Account/index.tsx

Closes https://github.com/polkadot-js/apps/issues/2055

Own controller check on staking options

---

packages/react-components/src/AccountName.tsx

Add judgement waiting

---

packages/app-accounts/src/modals/Identity.tsx

Fix identity effect with twitter

---

packages/app-democracy/src/Overview/PreImage.tsx
packages/app-democracy/src/Overview/Propose.tsx
packages/app-staking/src/Actions/Account/BondExtra.tsx

Closes https://github.com/polkadot-js/apps/issues/1985

Adjust available labels

---

packages/app-council/src/Overview/Vote.tsx

Closes https://github.com/polkadot-js/apps/issues/2087

Remove old votes from council

---

packages/app-democracy/src/Overview/Referendum.tsx
packages/app-democracy/src/Overview/Voting.tsx
packages/react-params/src/Param/Vote.tsx

Closes https://github.com/polkadot-js/apps/issues/1625

Apply Vote conviction

---

packages/app-council/src/useCounter.ts
packages/app-democracy/src/useCounter.ts
packages/app-society/src/useMembers.ts
packages/app-tech-comm/src/useCounter.ts
packages/app-treasury/src/useCounter.ts
packages/apps/src/Apps.tsx

Should (hopefully) address https://github.com/polkadot-js/apps/issues/2209

Add derive availability failsafes (global)

---

packages/app-staking/src/Overview/Address.tsx

Close https://github.com/polkadot-js/apps/issues/2211

Empty heartbeats should not display

---

packages/app-democracy/src/Overview/Externals.tsx

Closes https://github.com/polkadot-js/apps/issues/2226

Add preimage button to externals

---

packages/app-settings/src/available/endpoints.ts

Pulls in https://github.com/polkadot-js/ui/pull/274/files
cc @drewstone

Edgeware updates

---

packages/react-hooks/src/index.ts
packages/react-hooks/src/types.ts
packages/react-hooks/src/useAccountId.tsx
packages/react-hooks/src/useCall.tsx
packages/react-hooks/src/useMembers.tsx
packages/react-hooks/src/useModal.tsx

- Pull in hooks from https://github.com/polkadot-js/apps/pull/2201
- Part of an effort to trim down and get the PR in piecemeal

Pull in collective hooks (from PR)

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
yarn.lock

Bump API (composite version)

---

packages/react-params/src/Param/Moment.tsx
packages/react-params/src/Param/Text.tsx
packages/react-params/src/Param/findComponent.ts

Fix proposal breakdown

---

packages/app-settings/src/SelectUrl.tsx
packages/app-settings/src/available/endpoints.ts

Closes https://github.com/polkadot-js/apps/issues/2269

Fix endpoints to use locally available

---

packages/react-api/src/overrides/spec/edgeware.ts

Closes https://github.com/polkadot-js/apps/issues/2288
cc @drewstone

Edgeware upgraded to new BalanceLock

---

packages/app-settings/src/Developer.tsx
packages/react-components/src/Tabs.tsx

Closes https://github.com/polkadot-js/apps/issues/2299

Allow empty type reg

---

packages/apps-config/README.md

Fix link paths in apps-config docs

---

package.json
packages/apps/src/WarmUp.tsx
packages/page-accounts/src/modals/Create.tsx
packages/page-accounts/src/modals/Derive.tsx
packages/page-contracts/package.json
packages/page-society/src/Overview/Member.tsx
packages/page-society/src/Overview/Members.tsx
packages/page-society/src/Overview/Summary.tsx
packages/page-society/src/Overview/index.tsx
packages/react-api/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/2333

Add password confirmation

---

packages/page-council/src/Motions/Motion.tsx
packages/page-democracy/src/Overview/DispatchEntry.tsx
packages/page-democracy/src/Overview/Referendum.tsx
packages/react-components/src/Table.tsx

Closes https://github.com/polkadot-js/apps/issues/2394

Indicate council motion vote end

---

packages/apps/src/WarmUp.tsx
packages/page-democracy/src/Overview/Referendum.tsx
packages/page-democracy/src/Overview/useIsPassing.ts

Closes https://github.com/polkadot-js/apps/issues/2418

Referendum passing status

---

packages/apps-config/src/api/index.ts
packages/apps-config/src/api/util.ts
packages/apps-config/src/ui/index.ts
packages/apps-routing/src/settings.ts
packages/page-settings/src/Extensions.tsx
packages/page-settings/src/index.tsx
packages/page-settings/src/useCounter.ts
packages/page-settings/src/useExtensions.ts
packages/react-api/package.json
packages/react-api/src/Api.tsx
packages/react-api/src/types.ts
packages/react-components/src/IdentityIcon.tsx
yarn.lock

Requires https://github.com/polkadot-js/extension/pull/288

Allow extension metadata update

---

packages/react-components/src/Extrinsic.tsx
packages/react-components/src/Params/Extrinsic.tsx
packages/react-components/src/Params/Proposal.tsx

useCallback in Extrinsic & Proposal components

---

packages/apps-routing/src/123code.ts
packages/apps-routing/src/accounts.ts
packages/apps-routing/src/claims.ts
packages/apps-routing/src/contracts.ts
packages/apps-routing/src/council.ts
packages/apps-routing/src/dashboard.ts
packages/apps-routing/src/democracy.ts
packages/apps-routing/src/explorer.ts
packages/apps-routing/src/extrinsics.ts
packages/apps-routing/src/generic-asset.ts
packages/apps-routing/src/index.ts
packages/apps-routing/src/js.ts
packages/apps-routing/src/parachains.ts
packages/apps-routing/src/settings.ts
packages/apps-routing/src/society.ts
packages/apps-routing/src/staking.ts
packages/apps-routing/src/storage.ts
packages/apps-routing/src/sudo.ts
packages/apps-routing/src/techcomm.ts
packages/apps-routing/src/toolbox.ts
packages/apps-routing/src/transfer.ts
packages/apps-routing/src/treasury.ts
packages/apps-routing/src/types.ts

Extra protections to avoid issues like https://github.com/polkadot-js/apps/issues/2503

Adjust Route exports

---

packages/page-council/src/Motions/Voting.tsx
packages/page-democracy/src/Overview/Voting.tsx
packages/page-tech-comm/src/Proposals/Voting.tsx
packages/page-treasury/src/Overview/Voting.tsx
packages/react-components/src/VoteActions.tsx
packages/react-components/src/VoteToggle.tsx

Hi,
This PR fixes #1624, that's what I've got so far:
I would pretty much appreciate your feedback
Thanks :)

Swap yes/no (voting) to Toggle

---

package.json
packages/page-contracts/package.json
packages/page-democracy/src/Overview/Referendum.tsx
packages/page-democracy/src/Overview/ReferendumVotes.tsx
packages/react-api/package.json
packages/react-query/src/FormatBalance.tsx
yarn.lock

Ref https://github.com/polkadot-js/apps/issues/2534

Update amount display (with hover info)

---

packages/page-treasury/src/Overview/Approve.tsx
packages/page-treasury/src/Overview/Proposal.tsx
packages/page-treasury/src/Overview/ProposalCreate.tsx
packages/page-treasury/src/Overview/Proposals.tsx
packages/page-treasury/src/Overview/Submission.tsx
packages/page-treasury/src/Overview/Summary.tsx
packages/page-treasury/src/Overview/Tip.tsx
packages/page-treasury/src/Overview/TipCreate.tsx
packages/page-treasury/src/Overview/TipEndorse.tsx
packages/page-treasury/src/Overview/TipReason.tsx
packages/page-treasury/src/Overview/Tips.tsx
packages/page-treasury/src/Overview/index.tsx
packages/page-treasury/src/index.tsx
packages/page-treasury/src/useCounter.ts
packages/react-hooks/src/index.ts
packages/react-hooks/src/useIncrement.ts

Closes https://github.com/polkadot-js/apps/issues/2167

Treasury tipping

---

packages/apps-config/src/api/spec/encointer-node.ts
packages/apps-config/src/api/spec/index.ts

adding spec to support Encointer Testnet Gesell and other future encointer chains

adding encointer spec

---

packages/page-staking/src/Actions/Account/SetControllerAccount.tsx
packages/page-staking/src/Actions/Account/index.tsx

Closing https://github.com/polkadot-js/apps/issues/2508

Drop warning

---

packages/react-params/src/Param/Static.tsx

Fixes new, mis-reported issue in https://github.com/polkadot-js/apps/issues/2200#issuecomment-613671616

Check for toHuman before using

---

package.json
packages/page-contracts/package.json
packages/page-democracy/src/Overview/ReferendumVote.tsx
packages/react-api/package.json
yarn.lock

- Needs https://github.com/polkadot-js/api/pull/2205
- Closes #2616

Voting delegations

---

packages/apps-config/src/links/subscan.ts

subscan.io has changed the format of addresses for the democratic proposals

Change URL for democratic proposals

---

packages/page-i18n/src/index.tsx

cc @dushaobindoudou - since you did an unbelievable effort on the zh translations, would love your feedback (positive and negative) on this - https://github.com/polkadot-js/apps/blob/master/I18N.md
No perfect there yet, but certainly should be easier to adjust. (It does not apply the translations directly into the app as they are done as of yet, that would be a good enhancement with the page-i18n as part of settings. Initial round just wanted to make it simpler to adjust)

Small cleanups for the i18n app

---

packages/page-js/src/snippets/index.ts
packages/page-js/src/snippets/storage-examples.ts

Also adjusts all the balance samples, just assuming Kusama-like chains here
Closes https://github.com/polkadot-js/apps/issues/2635

Sample for key hashes

---

packages/react-components/src/InputBalance.tsx
packages/react-components/src/InputNumber.tsx
packages/react-params/src/Param/Balance.tsx

cc @drewstone 
This "fix" has a side effect where if you change the units, it sets it back to 0 - however, first the fix, then look at that.

InputNumber fix

---

packages/apps-config/src/settings/languages.ts
packages/react-params/src/Param/Balance.tsx

Allows explicit selection of Russian after https://github.com/polkadot-js/apps/pull/2670

Add Russian to language dropdown

---

packages/page-accounts/src/Accounts/Account.tsx
packages/page-accounts/src/Accounts/index.tsx
packages/page-accounts/src/Accounts/modals/MultisigCreate.tsx
packages/page-accounts/src/Accounts/modals/RecoverAccount.tsx
packages/page-accounts/src/Accounts/modals/RecoverSetup.tsx
packages/page-accounts/src/Accounts/types.ts
packages/page-accounts/src/Accounts/useKnownAddresses.ts
packages/page-accounts/src/Sidebar/Flags.tsx
packages/react-hooks/src/types.ts
packages/react-hooks/src/useAccountInfo.ts

Multisig creation layout

---

package.json
packages/apps-config/src/api/spec/index.ts
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

As per https://github.com/polkadot-js/api/pull/2246

Bump API for Centrifuge (new node name)

---

package.json
packages/page-accounts/package.json
packages/page-contracts/package.json
packages/react-api/package.json
packages/react-components/package.json
packages/react-signer/src/Modal.tsx
yarn.lock

Unrelated bug while looking at #2716 , however with this applied this is what I do see -
(without controller)
(with stash & controller)
So managed to reproduce the issue the first time I tries and then not again. Not sure how the above would fix that issue, so not holding my breath, but continuing down the path of seeing how to make it break again (and then what is wrong)

Refresh signatory between items

---

packages/page-council/src/Overview/SubmitCandidacy.tsx
packages/page-council/src/Overview/index.tsx

Detection of candidate length requirement on submission call, as introduced by https://github.com/paritytech/substrate/pull/5949

Council submit candidacy

---

packages/page-sudo/src/Sudo.tsx
packages/page-sudo/src/types.ts

Introduced in https://github.com/paritytech/substrate/pull/5888

Allow sudo.sudoUncheckedWeight submission

---

packages/page-democracy/src/Overview/Seconding.tsx

Introduced in https://github.com/paritytech/substrate/pull/5828

Adjust seconding with weight hints

---

packages/page-democracy/src/Overview/DispatchEntry.tsx
packages/page-democracy/src/Overview/DispatchQueue.tsx
packages/page-democracy/src/Overview/Proposal.tsx
packages/page-democracy/src/Overview/Proposals.tsx
packages/page-democracy/src/Overview/Referendum.tsx
packages/page-democracy/src/Overview/Referendums.tsx
packages/react-components/src/Table/index.tsx

Closes https://github.com/polkadot-js/apps/issues/2719

Display turnout

---

packages/apps/src/overlays/Attest.tsx
packages/page-claims/src/index.tsx

this is meant to be merged into `tbaut-asset`

Add condition for the warning banner

---

packages/react-query/src/BlockAuthors.tsx
packages/react-query/src/Events.tsx

Adds the blockNumber & blockHash into the events context. (Doesn't do anything with it display-wise)
cc @danforbes

Add blockHash & blockNumber to keyed event context

---

packages/page-explorer/src/BlockInfo/Extrinsic.tsx
packages/page-explorer/src/Event.tsx
packages/page-explorer/src/Events.tsx
packages/page-explorer/src/types.ts

Add block number to events on explorer page

---

packages/apps-config/src/api/spec/encointer-node.ts
packages/apps-config/src/ui/logos/index.ts
packages/apps-config/src/ui/logos/nodes/encointer.svg

[encointer] add favicon and improved custom type definitions

---

packages/page-claims/src/Claim.tsx

- Introduced in https://github.com/polkadot-js/apps/pull/2734
- Closes https://github.com/polkadot-js/apps/issues/2827
@lsaether would like a check from you to make sure it seems sound, since you specifically found the cause

Kusama claims fix

---

packages/page-claims/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/2829

Only allow actual accounts to claim

---

packages/apps-config/src/links/polkascan.ts
packages/apps-config/src/links/subscan.ts
packages/apps-config/src/ui/general/index.ts

... and add Polkadot CC1 support

Remove "pre" in polkascan URLs

---

packages/page-staking/src/index.tsx

This reverts commit 824bf2f61c518a2461f43155c8ceb5cc6d432696.

Revert "Check ForceNone (#2835)"

---

packages/page-staking/src/Actions/Account/BondExtra.tsx
packages/page-staking/src/Actions/partials/Bond.tsx

Closes https://github.com/polkadot-js/apps/issues/2832

Display free balance for bonding

---

packages/apps-config/src/api/chain/arcadia.ts

This PR adds the new types required for the last Nodle Arcadia release building on Substrate rc2.

add new arcadia types

---

packages/apps-config/src/links/polkascan.ts

Closes https://github.com/polkadot-js/apps/issues/2870

Update to polkscan link to westend-m2

---

packages/react-signer/src/Modal.tsx

May help with https://github.com/polkadot-js/apps/issues/2907

Re-encode who addresses (align with settings)

---

packages/react-components/src/StakingRedeemable.tsx

Closes https://github.com/polkadot-js/apps/issues/2916

Withdraw with slashing spans

---

packages/page-claims/src/Claim.tsx
packages/page-claims/src/Statement.tsx
packages/page-claims/src/index.tsx

Seems we need this for #2939 and it is not a once-off, Kusama is broken.

Handle no statementKind

---

packages/apps-config/src/settings/endpoints.ts

... one day will get the IPFS publish to actually pass fully and even update CloudFlare

Failsafe for window.process_env

---

packages/page-js/src/snippets/rpc-examples.ts

Closes https://github.com/polkadot-js/apps/issues/2956

Fix metadata example

---

packages/page-staking/src/Targets/index.tsx
packages/page-staking/src/useSortedTargets.ts

Closes https://github.com/polkadot-js/apps/issues/2983

Fix targets with zero input

---

packages/page-treasury/src/Overview/Tip.tsx

Display council tip status

---

packages/page-accounts/src/Sidebar/Balances.tsx
packages/page-accounts/src/Sidebar/Sidebar.tsx

Closes https://github.com/polkadot-js/apps/issues/2982

Display balance in sidebar

---

package.json
packages/page-contracts/package.json
packages/page-staking/src/Targets/Validator.tsx
packages/page-staking/src/useSortedTargets.ts
packages/react-api/package.json
packages/react-components/package.json
yarn.lock

Needs https://github.com/polkadot-js/api/pull/2367

Display waiting in targets

---

packages/apps-config/src/api/spec/encointer-node-notee.ts
packages/apps-config/src/api/spec/encointer-node-teeproxy.ts
packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/ui/logos/index.ts
packages/apps-config/src/ui/logos/nodes/encointer-notee.svg
packages/apps-config/src/ui/logos/nodes/encointer-teeproxy.svg

[encointer] discriminate chain types noTEE and TEE proxy 

---

packages/page-treasury/src/Overview/Tip.tsx
packages/page-treasury/src/Overview/TipClose.tsx
packages/page-treasury/src/Overview/Tips.tsx
packages/react-hooks/src/useBlockTime.ts

Add treasury close tip button

---

packages/page-staking/src/Targets/Nominate.tsx
packages/page-staking/src/Targets/index.tsx
packages/page-staking/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3013

Disable target nominations in election

---

package.json
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/3015

Bump API (Optimize staking list queries)

---

packages/page-staking/src/Overview/Address/Status.tsx
packages/react-components/src/Badge.tsx

Closes https://github.com/polkadot-js/apps/issues/3026

Align staking status icons

---

packages/page-treasury/src/Overview/Tip.tsx

Closes https://github.com/polkadot-js/apps/issues/2673

Allow retracting of tips

---

CHANGELOG.md
packages/page-storage/src/Query.tsx
packages/page-storage/src/Selection/Modules.tsx
packages/page-storage/src/index.tsx
packages/react-components/src/InputAddress/index.tsx
packages/react-params/src/Param/Account.tsx
packages/react-params/src/Param/Option.tsx
packages/react-params/src/Param/index.tsx
packages/react-params/src/types.ts
packages/react-params/src/valueToText.tsx

Closes https://github.com/polkadot-js/apps/issues/2218

Allow entries() on map/doublemap

---

packages/react-params/src/Param/Bytes.tsx
packages/react-params/src/Param/Option.tsx

Closes https://github.com/polkadot-js/apps/issues/3055

Toggle for file upload

---

packages/page-storage/src/Selection/Modules.tsx

Closes https://github.com/polkadot-js/apps/issues/3056

No map iteration with last key as Option

---

packages/page-council/src/Motions/Motion.tsx
packages/page-council/src/Motions/Votes.tsx
packages/page-council/src/Motions/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3012

Rework council voting display

---

packages/page-accounts/src/Accounts/modals/Identity.tsx

Closes https://github.com/polkadot-js/apps/issues/3074
- does not allow empty submission (toggled field)
- displays a placeholder with format
- Basic inclusion, length & startsWith field checks

Basic identity helpers

---

package.json
packages/page-accounts/src/Accounts/Account.tsx
packages/page-contracts/package.json
packages/react-api/package.json
packages/react-components/src/AddressInfo.tsx
yarn.lock

Closes #3077
Needs https://github.com/polkadot-js/api/pull/2396

Add vesting claims

---

packages/page-accounts/src/Accounts/Account.tsx

Replaces https://github.com/polkadot-js/apps/pull/3085

Vesting appear logic (try #3)

---

packages/apps/public/locales/en/app-staking.json
packages/page-staking/src/index.tsx

As per https://github.com/polkadot-js/apps/pull/3091#discussion_r446964340

Add missing t(...) wrapper

---

packages/react-components/src/DemocracyLocks.tsx

Closes #3088
Not perfect, but better.

Group democracy locks

---

packages/page-accounts/src/Accounts/modals/IdentityMain.tsx

Closes #3104 
https://polkascan.io/polkadot-cc1/transaction/516737-2

Identity set fix

---

packages/page-staking/src/Overview/CurrentList.tsx
packages/page-staking/src/Overview/index.tsx
packages/page-staking/src/Targets/index.tsx
packages/page-staking/src/index.tsx
packages/page-staking/src/types.ts
packages/page-staking/src/useSortedTargets.ts

Closes https://github.com/polkadot-js/apps/issues/3090

Apply favorites consistently

---

packages/react-components/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3100

Fix InputAddress lastValue

---

packages/page-staking/src/Actions/Account/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3097

Add withdraw action to staking

---

packages/page-staking/src/Actions/Account/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3082

Hide unbond funds when active is 0

---

packages/react-components/src/ConvictionDropdown.tsx

This is simply bringing what was (and still is) [here](https://github.com/polkadot-js/apps/blob/master/packages/page-democracy/src/Overview/Voting.tsx#L104-L110)

Pull Dropdown into its own conviction component

---

packages/react-components/src/index.tsx

oops, I had pointed to it directly in my test, so didn't catch this.

export Conviction dropdown

---

package.json
packages/apps-electron/package.json
packages/apps/package.json
packages/page-accounts/package.json
packages/page-accounts/src/Accounts/Account.tsx
packages/page-accounts/src/Accounts/modals/IdentitySub.tsx
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/3066

Modal for setting sub identities

---

packages/react-components/src/Extrinsic.tsx
packages/react-components/src/Params/OpaqueCall.tsx
packages/react-components/src/Params/index.ts
packages/react-params/src/Param/OpaqueCall.tsx
packages/react-params/src/Param/findComponent.ts

Closes https://github.com/polkadot-js/apps/issues/3123

Handlers for OpaqueCall input/display types

---

CHANGELOG.md
packages/react-components/src/AccountName.tsx
packages/react-components/src/AddressMini.tsx
packages/react-components/src/EditButton.tsx

Closes https://github.com/polkadot-js/apps/issues/3131

Adjust AccountName icon alignments

---

packages/page-society/src/Overview/Member.tsx
packages/page-society/src/Overview/Members.tsx
packages/page-society/src/Overview/canary.ts
packages/page-society/src/draw/canary.ts
packages/react-components/src/Modal/types.tsx

Society generator

---

packages/react-components/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3142

Restore InputAddress minimal auto height

---

packages/page-staking/src/Filtering.tsx
packages/page-staking/src/Targets/index.tsx

Would allow for eg `https://lpolkadot.js.org/apps/#/staking/targets?filter=zug`

Name query filter on targets

---

packages/page-accounts/src/Accounts/Account.tsx
packages/page-accounts/src/Accounts/index.tsx
packages/react-components/src/Table/Head.tsx

Closes https://github.com/polkadot-js/apps/issues/3148 (Introduced in https://github.com/polkadot-js/apps/pull/3122)
Honestly dunno how I tested this and missed something this simple.

Fix accounts not showing with no democracy

---

packages/react-components/src/AccountName.tsx
packages/react-components/src/AddressSmall.tsx

Flattens the AddressSmall component, removing an extra wrapper
Closes https://github.com/polkadot-js/apps/issues/3165

Cleanup AddressName display

---

packages/page-accounts/src/Accounts/index.tsx
packages/page-poll/src/index.tsx

Not correct, should check against the actually list of accounts - but as of now since we add to the end, won't break and fixed the immediate bug we have on all new account creates
EDIT: since it was open slipped in some last minute test requests for polling

isDelegating fix (on new account create)

---

packages/page-accounts/src/Accounts/index.tsx
packages/page-explorer/src/Summary.tsx

Make Kulupu degrade based on functionality available

Adjust multisig check

---

packages/page-democracy/src/Overview/PreImage.tsx

Closes https://github.com/polkadot-js/apps/issues/3185

Display preimage costs on submission

---

packages/page-accounts/src/Accounts/Account.tsx
packages/page-accounts/src/Accounts/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3191

Align balance totals (responsive classes, number)

---

packages/apps-routing/src/society.ts
packages/page-accounts/src/Accounts/modals/Delegate.tsx
packages/page-accounts/src/Accounts/modals/Undelegate.tsx
packages/page-society/src/Overview/Bid.tsx
packages/page-society/src/Overview/BidNew.tsx
packages/page-society/src/Overview/Bids.tsx
packages/page-society/src/Overview/index.tsx
packages/page-society/src/index.tsx
packages/page-society/src/useCounter.ts
packages/page-staking/src/Actions/Account/BondExtra.tsx
packages/page-staking/src/Actions/Account/Unbond.tsx
packages/page-staking/src/Actions/Account/Validate.tsx

- Closes https://github.com/polkadot-js/apps/issues/3136

Society bid modal (& unbid, bidder overview counter)

---

packages/page-explorer/src/BlockInfo/ByHash.tsx
packages/page-explorer/src/BlockInfo/Extrinsic.tsx
packages/page-explorer/src/BlockInfo/Extrinsics.tsx
packages/page-explorer/src/Events.tsx
packages/page-explorer/src/Main.tsx
packages/page-explorer/src/index.tsx
packages/react-query/src/BlockAuthors.tsx
packages/react-query/src/Events.tsx
packages/react-query/src/types.ts

Closes https://github.com/polkadot-js/apps/issues/3193

Flatten recurring events (same block)

---

packages/apps-electron/src/electron/contentSecurityPolicy.ts

Make sure Electron loads CSS in packaged window app.

---

packages/react-signer/src/Address.tsx

- Fixes issue in https://github.com/polkadot-js/apps/pull/3215#issuecomment-660136134
- tested against normal batch (balance & staking), not working and staking batch (all staking included) and it does the trick

Inspect batch/limited calls

---

packages/apps/src/Content/index.tsx
packages/apps/src/SideBar/Item.tsx
packages/apps/src/endpoint.ts

Closes https://github.com/polkadot-js/apps/issues/3180

Redirect to explorer with no API support

---

packages/react-components/src/Tooltip.tsx
packages/react-query/src/FormatBalance.tsx

All children (e.g. toolips) on FormatBalance

---

packages/page-democracy/src/Overview/PreImage.tsx

Remove imminent toggle, pass through only

---

packages/apps-config/package.json
packages/apps-config/src/api/spec/acala.ts
packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/settings/endpoints.ts
packages/apps-config/src/ui/logos/index.ts
packages/apps-config/src/ui/logos/nodes/acala-circle.svg
packages/apps/public/locales/en/apps-config.json
packages/apps/public/locales/es/translation.json
packages/apps/public/locales/ja/translation.json
packages/apps/public/locales/pt/translation.json
packages/apps/public/locales/ru/translation.json
packages/react-components/src/ChainImg.tsx
yarn.lock

Hi, I added Acala Testnet support

support for acala mandala test network

---

packages/page-poll/src/index.tsx
packages/page-settings/src/I18n/index.tsx
packages/react-components/src/CardSummary.tsx
packages/react-components/src/Progress.tsx
packages/react-components/src/Spinner.tsx
packages/react-components/src/styles/index.ts
packages/react-components/src/styles/theme.ts

Moves towards https://github.com/polkadot-js/apps/issues/3134

Circular progress

---

packages/react-components/src/Modal/Column.tsx

Set max modal column widths

---

packages/page-accounts/src/Accounts/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3298

Optional proxy

---

packages/page-staking/src/Actions/Account/Nominate.tsx
packages/page-staking/src/Actions/Account/index.tsx
packages/page-staking/src/Actions/NewNominator.tsx
packages/page-staking/src/Actions/index.tsx
packages/page-staking/src/Actions/partials/Nominate.tsx
packages/page-staking/src/Targets/index.tsx
packages/page-staking/src/index.tsx
packages/page-staking/src/types.ts
packages/page-staking/src/useSortedTargets.ts

Ok, the latter is a huge issue as it stands. Skipping.

Remove auto validator defaults

---

packages/page-staking/src/Slashes/Row.tsx
packages/page-staking/src/Slashes/index.tsx
packages/page-staking/src/Slashes/types.ts
packages/page-staking/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3312

Slash breakdown

---

packages/apps-config/src/links/polkassembly.ts

This adds a link to Polkassembly for polkadot.

Added polkadot links for polkassembly

---

packages/apps-config/src/settings/endpoints.ts
packages/apps/src/SideBar/Endpoints.tsx
packages/page-explorer/src/SummarySession.tsx
packages/react-components/src/Icon.tsx
packages/react-components/src/Toggle.tsx
packages/react-components/src/styles/index.ts
packages/react-query/src/Bonded.tsx

Split from https://github.com/polkadot-js/apps/pull/3297

Endpoint toggle adjustments

---

packages/apps/src/overlays/Base.tsx

Closes https://github.com/polkadot-js/apps/issues/3335

Adjust overlay position

---

packages/page-treasury/src/Overview/TipEndorse.tsx
packages/react-components/src/Button/Button.tsx
packages/react-components/src/Button/types.ts
packages/react-components/src/TxButton.tsx
packages/react-components/src/styles/index.ts
packages/react-components/src/styles/theme.ts
packages/react-components/src/types.ts

Quick endorse with median

---

packages/apps-config/src/settings/languages.ts

Enable ko introduced in #2984 
@hskang9 feel free to add this to your branch, if you run locally it will help having the setting to click through.
()completely optional, happy to merge this straight after your is done to enable)

Enable ko in settings

---

packages/apps-config/src/links/polkassembly.ts
packages/apps-config/src/links/types.ts
packages/page-treasury/src/Overview/Tip.tsx
packages/page-treasury/src/Overview/Tips.tsx

Closes https://github.com/polkadot-js/apps/issues/3157
Looks like this:

Add tip link to Polkassembly

---

packages/react-components/src/VoteValue.tsx
packages/react-query/src/BalanceVoting.tsx

closes https://github.com/polkadot-js/apps/issues/3360
Tested both democracy and council voting with a treasury deposit (reserved).
Example:
Account has 1000
bond 500 in a treasury
--> can vote 500 for democracy
--> can vote 1000 for council

Fix council voting balance

---

packages/page-accounts/src/Vanity/Match.tsx
packages/page-accounts/src/Vanity/index.tsx

Closes https://github.com/polkadot-js/apps/issues/2119

Explicit save to vanity (button label)

---

packages/page-accounts/src/Accounts/modals/IdentityMain.tsx

Closes https://github.com/polkadot-js/apps/issues/3369

Sanitize the meta name before setting

---

packages/apps-config/src/settings/endpoints.ts

Set Amber icon to centrifuge

---

packages/page-accounts/src/Accounts/modals/IdentityMain.tsx
packages/page-parachains/src/Parachain/Deregister.tsx
packages/page-parachains/src/Parachain/Details.tsx
packages/page-parachains/src/Parachain/DispatchQueue.tsx
packages/page-staking/src/Actions/Account/Unbond.tsx
packages/react-components/src/Input.tsx
packages/react-components/src/InputAddressMulti/index.tsx
packages/react-components/src/InputBalance.tsx
packages/react-components/src/InputFile.tsx
packages/react-components/src/InputNumber.tsx
packages/react-components/src/Labelled.tsx
packages/react-components/src/Output.tsx
packages/react-components/src/Static.tsx
packages/react-components/src/Toggle.tsx
packages/react-params/src/Param/Bytes.tsx
packages/react-params/src/Param/Option.tsx

Closes https://github.com/polkadot-js/apps/issues/3366

Add ui--Toggle overlay positioning

---

packages/page-council/src/Overview/Vote.tsx

closes https://github.com/polkadot-js/apps/issues/3275

Add a "clear all" button to council vote

---

packages/page-accounts/src/Accounts/modals/IdentityMain.tsx

Allows to remove an identity when on was set.
Will probably minimally conflict with #3387

Add clear identity button

---

packages/page-parachains/src/Overview/Register.tsx
packages/react-components/src/InputFile.tsx
packages/react-params/src/Param/File.tsx

Closes https://github.com/polkadot-js/apps/issues/3396

Default to hex detection flag on uploads

---

packages/page-accounts/src/Accounts/modals/Create.tsx

closes https://github.com/polkadot-js/apps/issues/3411

Error out when using hex seed and a passowrd in derivation path

---

packages/apps-config/src/links/polkastats.ts
packages/page-staking/src/Overview/Address/index.tsx
packages/page-staking/src/Overview/CurrentList.tsx

Closes #3347
Added Polkastats validator and intention links for kusama, polkadot and westend.
Thanks!

Add Polkastats validator and intention links

---

packages/page-staking/src/Actions/useInactives.ts

Closes https://github.com/polkadot-js/apps/issues/3431

Adjust waiting noms extraction

---

packages/page-accounts/src/Accounts/BannerDOT.tsx
packages/react-query/src/BlockToTime.tsx

- Approx time using block
- provide countdown
- handle switch (language goes to past tense)

Add countdown for redenom

---

packages/page-parachains/src/Overview/Parachains.tsx
packages/page-parachains/src/Overview/Proposal.tsx
packages/page-parachains/src/Overview/Proposals.tsx
packages/page-parachains/src/Overview/Summary.tsx
packages/page-parachains/src/Overview/index.tsx
packages/page-parachains/src/Overview/types.ts

Part of https://github.com/paritytech/polkadot/pull/1607

Display parachains proposal list

---

packages/apps-config/src/links/polkascan.ts

The support is added again https://polkascan.io/kulupu

Uncomment Polkascan link for Kulupu

---

packages/apps-config/package.json
packages/apps-config/src/settings/endpoints.ts
packages/apps-config/src/ui/general/index.ts
packages/apps-config/src/ui/logos/index.ts
yarn.lock

Hi, We built a acala Parachain based on Rococo, and now we hope to put it into Polkadot Apps.

rococo acala

---

packages/react-components/src/HelpOverlay.tsx

Closes https://github.com/polkadot-js/apps/issues/3538

Adjust help slideout z-index

---

packages/page-accounts/src/modals/MultisigCreate.tsx

Closes https://github.com/polkadot-js/apps/issues/3541

Adjust min multisig threshold to 2

---

packages/react-components/src/InputNumber.tsx

Limit to max chainDecimals on InputNumber

---

packages/apps-electron/src/electron/contentSecurityPolicy.ts

To address https://github.com/polkadot-js/apps/issues/3552

Electron WASM execution allowance

---

packages/page-staking/src/Filtering.tsx
packages/page-staking/src/Ledgend.tsx
packages/page-staking/src/Targets/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3559

Staking ledgend v1

---

packages/page-accounts/src/modals/Import.tsx

Fix ecdsa JSON import

---

packages/apps/public/locales/en/react-components.json
packages/apps/public/locales/en/translation.json
packages/react-components/src/AddressInfo.tsx

https://github.com/polkadot-js/apps/issues/3561

add vestingPerBlock and vestingEndBlock in vested balance tooltip

---

packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/api/spec/robonomics.ts
packages/apps-config/src/settings/endpoints.ts
packages/apps-config/src/ui/logos/index.ts
packages/apps-config/src/ui/logos/nodes/robonomics.svg

Added Robonomics Network parachain endpoint in Rococo network.
* https://robonomics.network/
* https://parachain.robonomics.network/

Added Robonomics Network endpoints

---

packages/page-accounts/src/modals/Create.tsx

show warning when the password contains a /

---

packages/page-accounts/src/modals/Create.tsx

closes https://github.com/polkadot-js/apps/issues/3662
I did not type the index keys stronger because the validation can also spit out an unknown string [here](https://github.com/polkadot-js/apps/blob/b1e07bee2cdfe28bcd71d06c67bcc58e90d8c038/packages/page-accounts/src/modals/Create.tsx#L82)

Translate error and warning messages

---

packages/react-api/src/ledger.ts

Closes https://github.com/polkadot-js/apps/issues/3665

Update Ledger capability check (w/ WebUSB)

---

packages/apps-config/src/api/spec/crab.ts

https://github.com/darwinia-network/darwinia/blob/master/runtime/crab/polkadot_compatible_types.json
The darwinia-crab network has been upgraded, and the necessary types have been updated, so submit this pr to avoid apps reporting errors.
thankyou

Update darwinia crab 0.6.11 types

---

packages/page-staking/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3687

Adjust staking hidden (only accounts check)

---

packages/apps/src/initSettings.ts

Closes https://github.com/polkadot-js/apps/issues/3690

Check url for ws/wss

---

packages/page-accounts/src/modals/Transfer.tsx

Closes https://github.com/polkadot-js/apps/issues/2739 (Recently asked for in https://github.com/polkadot-js/apps/issues/3681)

Allow for transfer of full balance, reaping

---

package.json
packages/page-contracts/package.json
packages/page-democracy/src/Overview/ProposalCell.tsx
packages/page-explorer/src/BlockInfo/Extrinsic.tsx
packages/react-api/package.json
packages/react-components/src/CallExpander.tsx
packages/react-components/src/ProposedAction.tsx
packages/react-components/src/Status/Queue.tsx
packages/react-components/src/Status/index.tsx
packages/react-components/src/Table/Body.tsx
packages/react-components/src/util/isTreasuryProposalVote.ts
packages/react-params/src/Param/Call.tsx
packages/react-params/src/Param/DispatchError.tsx
packages/react-signer/src/Address.tsx
packages/react-signer/src/Transaction.tsx
yarn.lock

Also closes https://github.com/polkadot-js/apps/issues/3707 (position: relative on tbody)

Registry usage from type

---

packages/react-params/src/Param/Amount.tsx

Closes https://github.com/polkadot-js/apps/issues/2799 & Closes https://github.com/polkadot-js/apps/issues/3300

Use InputNumber for params Amount

---

packages/react-components/src/Button/Group.tsx
packages/react-components/src/Table/Body.tsx
packages/react-components/src/styles/semantic.ts

Closes https://github.com/polkadot-js/apps/issues/3716

Button Group margins

---

CHANGELOG.md
packages/page-accounts/src/modals/Create.tsx
packages/page-accounts/src/modals/ExternalWarning.tsx
packages/page-accounts/src/modals/Import.tsx

Show warning on JSON import to store accounts externally

---

packages/page-accounts/src/modals/Import.tsx

closes https://github.com/polkadot-js/apps/issues/3729
Suggestions welcome for the warning wording. I have to read it twice to understand it.

Show warning and genesis override when importing JSON with different genesis hash

---

packages/page-democracy/src/Overview/Propose.tsx

As per https://github.com/paritytech/substrate/pull/7111

Cater for new democracy propose args

---

packages/page-js/src/Playground.tsx

Additionally explicitly disables `Function`, `SerivceWorker` & `SharedWorker` in the environment.

Add warning to Js playground

---

packages/apps/src/Endpoints/index.tsx
packages/apps/src/initSettings.ts

Closes https://github.com/polkadot-js/apps/issues/3744

Encode rpc=<url> param

---

packages/apps-config/src/api/spec/stable-poc.ts

Update stable poc types

---

packages/apps-config/package.json
yarn.lock

Same as https://github.com/polkadot-js/apps/pull/3789, just with a `yarn` done to update the lockfile (since CI is immutable)

Subsocial bump

---

packages/apps-config/src/api/spec/equilibrium.ts
packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/settings/endpoints.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts
packages/apps-config/src/ui/logos/nodes/equilibrium.svg

Added endpoints, logos and spec of Equilibrium Test Network
https://equilibrium.io/en
https://testnet.equilibrium.io/

Added Equilibrium Test Network logos & endpoints

---

packages/page-contracts/src/Contracts/Call.tsx
packages/react-components/src/InputAddress/index.tsx
packages/react-components/src/util/toAddress.ts
packages/react-params/src/initValue.ts

Closes https://github.com/polkadot-js/apps/issues/3803

Remove handled address tranform logs

---

packages/react-components/src/AddressInfo.tsx

Closes https://github.com/polkadot-js/apps/issues/3806

Don't show countdown on fully vested

---

packages/apps-config/src/settings/endpoints.ts

Follow-up on https://github.com/polkadot-js/apps/pull/3820

Move Dock to alphabetical position

---

package.json
packages/page-contracts/package.json
packages/page-contracts/src/Summary.tsx
packages/page-contracts/src/index.tsx
packages/page-contracts/src/store.ts
packages/page-contracts/src/useAbi.ts
packages/react-api/package.json
packages/react-components/src/util/getContractAbi.ts
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/3845

Add overall contracts summary, bump API

---

packages/react-components/src/InputBalance.tsx

Closes https://github.com/polkadot-js/apps/issues/3870

Adjust formatting with large balance values

---

packages/page-settings/src/useChainInfo.ts
packages/react-api/src/Api.tsx
packages/react-api/src/index.ts

Pull metadata decimals/ss58 from Api

---

packages/apps/public/locales/ar/translation.json
packages/apps/public/locales/en/react-components.json
packages/apps/public/locales/es/translation.json
packages/apps/public/locales/fr/translation.json
packages/apps/public/locales/id/translation.json
packages/apps/public/locales/it/translation.json
packages/apps/public/locales/ko/translation.json
packages/apps/public/locales/pt/translation.json
packages/apps/public/locales/ru/translation.json
packages/apps/public/locales/zh/translation.json
packages/page-accounts/src/Accounts/Account.tsx
packages/react-components/src/StakingUnbonding.tsx

Closes https://github.com/polkadot-js/apps/issues/3873

Don't display unbonding blocks in Aura

---

package.json
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/2752

Add support for Solang u256/i256

---

packages/page-contracts/src/Codes/Code.tsx
packages/page-contracts/src/Codes/index.tsx
packages/page-contracts/src/store.ts
packages/page-contracts/src/types.ts

Closes https://github.com/polkadot-js/apps/issues/3913

Display codehash & allow copy

---

packages/react-params/src/Param/Amount.tsx

Closes https://github.com/polkadot-js/apps/issues/3916

Ensure bitLength is passed to number inputs

---

packages/apps-config/README.md

seems ui/general is depricated for ui/colors.ts

corrected internal link

---

packages/apps-config/src/api/spec/kulupu.ts

It has been upgraded to u32 RefCount already.

Remove RefCount type declaration for Kulupu

---

packages/apps-config/src/api/spec/crab.ts

https://github.com/darwinia-network/darwinia/blob/master/runtime/crab/polkadot-compatible-types.json

update crab types

---

packages/page-accounts/src/CreateAccount.spec.tsx

This should finally make the `test:all` pass :-)

Correct expected title of confirmation step in Create Account test

---

packages/apps-config/src/api/chain/beresheet.ts
packages/apps-config/src/api/spec/edgeware.ts

Most balances look wack! I almost had a heart-attack lol

Fix refcount for Edgeware to fix balance displays

---

packages/page-treasury/src/Tips/Tip.tsx
packages/page-treasury/src/Tips/Tips.tsx
packages/page-treasury/src/Tips/index.tsx

closes https://github.com/polkadot-js/apps/issues/3730
Certainly not as nice as a subscription, but it does the job. Your call whether it's acceptable or not :)

Trigger tip counter refresh on change

---

package.json
packages/page-contracts/package.json
packages/page-council/src/Motions/Motion.tsx
packages/page-council/src/Motions/index.tsx
packages/page-council/src/index.tsx
packages/page-council/src/useCounter.ts
packages/react-api/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/3947

Adjust council motions (unparsable proposals not shown)

---

electron-builder.yml
package.json
packages/apps-electron/package.json
packages/apps-electron/src/electron/contentSecurityPolicy.ts
packages/apps-electron/src/electron/window.ts
yarn.lock

Couple of small changes to the Electron app.
* Upgrade Electron deps versions
* Add additional hash for the index.html top script (I guess the whitespaces are different when packaged)
* Externalise packaging configuration

Electron app housekeeping

---

package.json
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/2816 (addresses https://github.com/polkadot-js/apps/pull/3961#discussion_r516839730)

Bump API (AccountId/Index length check)

---

packages/apps/src/themes.ts
packages/react-components/src/AccountName.tsx
packages/react-components/src/CardSummary.tsx
packages/react-components/src/styles/index.ts
packages/react-query/src/FormatBalance.tsx

Closes https://github.com/polkadot-js/apps/issues/3975

Revert font changes

---

packages/page-treasury/src/Tips/Tip.tsx
packages/page-treasury/src/Tips/Tips.tsx
packages/react-hooks/src/useCall.ts

Closes https://github.com/polkadot-js/apps/issues/3974

Filter tips with from-query hashes

---

packages/page-contracts/src/Contracts/Call.tsx
packages/page-contracts/src/shared/InputMegaGas.tsx
packages/page-contracts/src/types.ts
packages/page-contracts/src/useWeight.ts

Closes https://github.com/polkadot-js/apps/issues/3979

Default to max call weight

---

packages/react-components/src/VoteValue.tsx

Closes https://github.com/polkadot-js/apps/issues/3937

Cleanup maxVote calculations (no re-triggers)

---

packages/page-accounts/src/modals/Create.tsx

Reported in https://github.com/polkadot-js/apps/issues/4025

Move create check to first column

---

packages/page-staking/src/Actions/Account/ListNominees.tsx
packages/page-staking/src/Overview/Address/NominatedBy.tsx
packages/page-staking/src/Overview/Address/StakeOther.tsx
packages/page-staking/src/Targets/index.tsx
packages/react-components/src/Expander.tsx

On-demand Expander rendering

---

packages/page-contracts/src/useAbi.ts

Closes https://github.com/polkadot-js/apps/issues/4044

Reset error state on valid JSON ABI

---

packages/apps/src/overlays/Base.tsx
packages/apps/src/overlays/Connecting.tsx

Closes https://github.com/polkadot-js/apps/issues/4041

Actual in-progress-connect overlay

---

packages/apps/src/overlays/Connecting.tsx
packages/react-api/src/Api.tsx
packages/react-api/src/types.ts

Closes https://github.com/polkadot-js/apps/issues/1312

Display API errors with overlay

---

packages/react-components/src/Call.tsx
packages/react-components/src/CopyButton.tsx
packages/react-components/src/Labelled.tsx
packages/react-components/src/Output.tsx
packages/react-components/src/Static.tsx
packages/react-components/src/styles/components.ts
packages/react-params/src/Param/BaseBytes.tsx
packages/react-params/src/Param/Hash160.tsx
packages/react-params/src/Param/Hash256.tsx
packages/react-params/src/Param/Hash512.tsx

Allow CopyButton on all Hash* fields

---

packages/page-accounts/src/modals/ProxyOverview.tsx
packages/page-staking/src/Actions/NewNominator.tsx
packages/page-staking/src/Actions/NewValidator.tsx

Closes https://github.com/polkadot-js/apps/issues/3996

Use batchAll as appropriate

---

packages/apps-config/src/settings/endpoints.ts

Add polkadot and kusama endpoints hosted by onfinality.

Add polkadot and kusama endpoints hosted by onfinality

---

packages/page-calendar/src/DayItem.tsx
packages/page-calendar/src/util.ts

A small calendar icon is added to each event in order to allow user to download ics file and add it to calendar ![Screenshot 2020-11-25 at 12 12 02 AM](https://user-images.githubusercontent.com/5408605/100157228-dc4ca900-2eb2-11eb-85cc-6de43b34017b.png)

add "save event to calendar" functionality on calendar page

---

package.json
packages/page-accounts/package.json
packages/page-contracts/package.json
packages/page-staking/src/useSortedTargets.ts
packages/react-api/package.json
yarn.lock

WIP... will confirm in the last session of the current Kusama era

Staking targets includes to be dropped at end of session

---

packages/apps-config/src/api/rpc/moonbeam.ts
packages/react-components/src/InputRpc/SelectMethod.tsx
packages/react-components/src/InputRpc/index.tsx
packages/react-components/src/InputRpc/options/method.tsx
packages/react-components/src/InputRpc/options/section.ts
packages/react-components/src/InputRpc/rpcs.ts

Closes https://github.com/polkadot-js/apps/issues/4079

Treat user-RPCs consistently alongside known

---

packages/page-staking/src/Actions/index.tsx
packages/react-hooks/src/useOwnStashInfos.ts

Closes https://github.com/polkadot-js/apps/issues/3568

Validator chill refresh

---

packages/page-rpc/src/Rpc/Selection.tsx
packages/react-components/src/InputRpc/SelectMethod.tsx

Introduced in https://github.com/polkadot-js/apps/issues/4079

Fix RPC params change transform

---

packages/page-staking/src/index.tsx
packages/page-staking/src/useSortedTargets.ts
packages/react-hooks/src/index.ts
packages/react-hooks/src/useInflation.ts

Part of https://github.com/polkadot-js/apps/issues/1818

Introduce useInflation hook

---

packages/page-staking/src/Overview/Summary.tsx
packages/page-staking/src/Targets/Summary.tsx
packages/page-staking/src/Targets/Validator.tsx
packages/page-staking/src/Targets/index.tsx
packages/page-staking/src/index.tsx
packages/page-staking/src/types.ts
packages/page-staking/src/useSortedTargets.ts
packages/react-hooks/src/index.ts
packages/react-hooks/src/useInflation.ts

Closes https://github.com/polkadot-js/apps/issues/4089
Closes https://github.com/polkadot-js/apps/issues/3314

Show nominator return % per target

---

packages/page-staking/src/Legend.tsx
packages/page-staking/src/Overview/CurrentList.tsx
packages/page-staking/src/Targets/Validator.tsx
packages/page-staking/src/Targets/index.tsx
packages/react-components/src/Table/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4090

Cleanup targets pre-filtering on sort

---

packages/page-staking/src/Actions/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4093

Staking accounts filtering

---

packages/apps-config/src/api/index.ts
packages/apps-config/src/api/params/index.ts
packages/apps-config/src/api/params/inflation.ts
packages/apps-config/src/api/params/proposalThresholds.ts
packages/page-council/src/Motions/ProposeExternal.tsx
packages/page-council/src/Motions/ProposeMotion.tsx
packages/page-council/src/Motions/Slashing.tsx
packages/page-staking/src/Slashes/index.tsx
packages/page-staking/src/useSortedTargets.ts
packages/page-treasury/src/Overview/Council.tsx
packages/react-hooks/src/useInflation.ts

Closes https://github.com/polkadot-js/apps/issues/4097

Move chain params to apps-config

---

packages/page-explorer/src/SummarySession.tsx
packages/react-query/src/Elapsed.tsx

Makes is slightly more useful on eg. Edgeware where only Babe is used

Display activeEraStart with Babe

---

packages/page-staking/src/Targets/Validator.tsx
packages/page-staking/src/Targets/index.tsx
packages/page-staking/src/useSortedTargets.ts
packages/react-hooks/src/useBlockTime.ts

Closes https://github.com/polkadot-js/apps/issues/4104

Human-readable payout (target) descriptions

---

packages/apps/public/locales/en/app-explorer.json
packages/apps/public/locales/en/translation.json
packages/page-explorer/src/SummarySession.tsx

Suggestion from a member from Edgeware community. 
His/her TG: @mmmaaarrr01

Typo: elpased -> elapsed

---

packages/react-components/src/Output.tsx

Output className, remove extra }

---

packages/apps/src/Endpoints/Group.tsx
packages/apps/src/Endpoints/Network.tsx
packages/apps/src/Endpoints/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4144

Store network apiUrl affinity

---

package.json

Run eslint with --fix flag

---

packages/react-components/src/HelpOverlay.tsx

Closes https://github.com/polkadot-js/apps/issues/4153

Fix HelpOverlay background for dark

---

packages/page-accounts/src/Sidebar/Identity.tsx
packages/react-components/src/AccountName.tsx

Closes https://github.com/polkadot-js/apps/issues/4177

Ensure bad judgement has the highest priority

---

packages/page-bounties/src/Bounty.tsx

This should solve the problem with table columns changing their widths when expanding Bounty component.

Improve bounties display

---

packages/apps-routing/src/bounties.ts
packages/page-bounties/src/index.tsx
packages/page-bounties/src/useCounter.ts

This will add counter for active bounties in app menu.

Display bounties counter in menu

---

packages/apps-config/src/settings/endpoints.ts

<p>We've changed an endpoint for the sora-substrate project</p>

Change an endpoint for the sora-substrate project

---

packages/page-accounts/src/Accounts/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4190

Multisg/proxied add only with hasAccounts

---

packages/react-query/src/Elapsed.tsx

Closes https://github.com/polkadot-js/apps/issues/4214

Elapsed formatting

---

packages/apps-config/src/api/spec/dock.ts

Signed-off-by: lovesh <lovesh.bond@gmail.com>

Add type for Bonus for Dock 

---

packages/react-components/src/InputAddress/index.tsx
packages/react-params/src/Param/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4226

Allow InputAddress with no options

---

packages/page-accounts/src/modals/ProxyOverview.tsx
packages/page-staking/src/Actions/NewNominator.tsx
packages/page-staking/src/Actions/NewValidator.tsx
packages/react-components/src/BatchWarning.tsx
packages/react-components/src/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4237

Warn on non-atomic batches

---

packages/page-js/src/constants.tsx
packages/page-js/src/types.ts
packages/react-components/src/Dropdown.tsx
packages/react-components/src/Input.tsx
packages/react-components/src/InputError.tsx
packages/react-components/src/Menu.tsx
packages/react-components/src/Modal/Actions.tsx
packages/react-components/src/Modal/index.tsx
packages/react-components/src/Popup.tsx

Adjust sui imports (non-cjs)

---

packages/page-staking/src/Overview/CurrentList.tsx
packages/page-staking/src/Targets/index.tsx
packages/react-hooks/src/index.ts
packages/react-hooks/src/useSavedFlags.ts

Closes #4246 (also saves as in #4247)

Save target/overview toggles

---

packages/apps-config/src/api/bundle/spec/moonbeam.ts

- add ExitReason detailed types
- fixes range for first types to v4

Jlm update types 

---

packages/page-bounties/src/BountyCreate.tsx

Add second column to bounty add modal

---

packages/page-staking/src/Actions/Account/index.tsx

Fix bond more isDisabled check

---

package.json
packages/apps-electron/package.json
packages/apps/package.json
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/4283

Temp fix for incorrect contracts RPC de-serialization

---

packages/page-accounts/src/modals/ProxyOverview.tsx

UI helper for https://github.com/paritytech/substrate/issues/7799

Filter self-proxies in helper dialog

---

packages/react-components/src/AccountIndex.tsx
packages/react-components/src/AccountName.tsx
packages/react-components/src/InputAddress/KeyPair.tsx
packages/react-components/src/InputAddressMulti/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4289

Fix dark theme multi address background

---

packages/apps-config/src/api/spec/equilibrium.ts
packages/apps-config/src/api/specVersioned/equilibrium.ts

Updated Equilibrium types; 
Fixed broken extrinsic fee calc for Equilibrium;

Updated Equilibrium types

---

packages/page-democracy/src/Overview/Proposal.tsx

Missed in #4313 (was done, but not pushed alongside - local mess-up, of many different things at once)

Pass through deposit

---

package.json
packages/page-contracts/package.json
packages/page-parachains/src/Overview/Parachain.tsx
packages/page-parachains/src/Overview/ParachainList.tsx
packages/page-parachains/src/Overview/Upcoming.tsx
packages/page-parachains/src/Overview/UpcomingList.tsx
packages/page-parachains/src/Overview/index.tsx
packages/page-parachains/src/Overview/util.ts
packages/page-parachains/src/modals/Register.tsx
packages/react-api/package.json
yarn.lock

Needs https://github.com/polkadot-js/api/pull/3021

Expand upcoming parachain info

---

packages/page-accounts/src/modals/Derive.tsx

- Display actual path error messages
- Remove invalid help text (i.e. password is not supported atm)
Closes https://github.com/polkadot-js/apps/issues/4325

Display derive errors

---

package.json
packages/page-contracts/package.json
packages/page-staking/src/Actions/partials/Validate.tsx
packages/react-api/package.json
packages/react-components/src/InputNumber.tsx
packages/react-hooks/src/useOwnEraRewards.ts
yarn.lock

Staking fixes (comm, entries)

---

package.json
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/4335

Bump API (EthTransaction update)

---

packages/apps-config/src/api/constants.ts
packages/apps-config/src/settings/ledgerChains.ts

Signed-off-by: lovesh <lovesh.bond@gmail.com>

Allow Ledger support for Dock

---

packages/page-accounts/src/index.tsx
packages/page-js/src/Playground.tsx
packages/react-components/src/FilterOverlay.tsx
packages/react-components/src/HelpOverlay.tsx
packages/react-components/src/Tabs/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4338

Fix JS width (dropdown breaking out)

---

packages/apps-electron/src/electron/contentSecurityPolicy.ts

Closes https://github.com/polkadot-js/apps/issues/4349
cc @krzysztof-jelski - would like you eyes on this as well

Update CSP for ws

---

packages/apps-electron/src/main/account-store.ts

Fixes #4348 
Perhaps should be rather handled in [file keystore](https://github.com/polkadot-js/ui/blob/master/packages/ui-keyring/src/stores/File.ts ), but this workaround is good for now.

Remove colon from win path

---

packages/apps-config/src/endpoints/production.ts

Closes https://github.com/polkadot-js/apps/issues/4377

Remove Web3 Polkadot/Kusama endpoints

---

package.json
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Needed for https://github.com/polkadot-js/apps/pull/4388

Bump API (Missing parachain types)

---

packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/api/spec/plasm-parachain.ts

Fix `Address`-related types, added missed block types.

Fixed Plasm PC2 spec types

---

packages/page-settings/src/Metadata/NetworkSpecs.tsx
packages/react-components/src/styles/index.ts
packages/react-signer/src/Qr.tsx

Add small QR border

---

packages/page-parachains/src/Overview/Parachain.tsx
packages/page-parachains/src/Overview/ParachainList.tsx
packages/react-query/src/Events.tsx

Closes https://github.com/polkadot-js/apps/issues/4403
Closes https://github.com/polkadot-js/apps/issues/4401

Use CandidateIncluded events for last inclusion

---

packages/apps-config/src/api/constants.ts
packages/apps-config/src/settings/ledgerChains.ts

Adds details needed for Polymesh ledger integration.

Add Polymesh Ledger Integration

---

package.json
packages/apps-config/package.json
packages/apps-config/src/endpoints/testingRococo.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts
yarn.lock

acala rococo
I encountered an error while debugging. I'm not sure if it's because acala isn't connected to rococo yet.

mandala pc2

---

packages/react-hooks/src/useLedger.ts

TS seems happy with `LedgerTypes`

Nit, use as LedgerTypes casting

---

packages/apps-config/src/api/spec/robonomics.ts
packages/apps-config/src/endpoints/testingRococo.ts

* Fix chain types
* Added rococo parachain endpoint

Added robonomics rococo parachain endpoint

---

package.json
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/3067

Bump deps (w/ Rococo fix)

---

packages/apps-config/src/endpoints/testingRococo.ts
packages/apps-config/src/ui/logos/index.ts
packages/apps/public/locales/en/apps-config.json

As KILT is the next candidate to join the Rococo-v1 network as a parachain, we would be happy if our endpoint could be added as well.

chore: add kilt endpoint to rococo

---

packages/react-hooks/src/useTreasury.ts

Fix #4419 - using bounties without treasury

---

packages/page-accounts/src/modals/Transfer.tsx

Closes https://github.com/polkadot-js/apps/issues/4456
Closes https://github.com/polkadot-js/apps/issues/4180
Closes https://github.com/polkadot-js/apps/issues/2262

Add warning for unability to cover fees

---

packages/apps-config/src/api/chain/galois.ts

we add some types for chain transfer limit info.

[Galois]add Transfer limit require type

---

package.json
packages/page-accounts/package.json
packages/page-accounts/src/modals/Transfer.tsx
yarn.lock

Check sender/recipients against phishing address list

---

packages/apps-config/src/api/specVersioned/equilibrium.ts

Replaces & closes https://github.com/polkadot-js/apps/pull/4488
(Just want to get it in before cutting a release, will add credit where credit is due in the CHANGELOG - sadly cannot edit the above PR)

Equilibrium fix

---

packages/apps-config/package.json
packages/apps-config/src/api/specVersioned/polkabtc.ts
yarn.lock

Follow up to https://github.com/polkadot-js/apps/issues/4078

Move PolkaBTC currency type definitions to types repo

---

packages/apps-config/package.json
yarn.lock

To handle staking pallet for Moonbeam

Bump moonbeamtypes bundle dependency

---

packages/react-components/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4470

Ensure InputAddress doesn't return non-filtered

---

packages/apps-routing/src/storage.ts
packages/react-components/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4370

Allow storage without accounts

---

packages/page-accounts/src/modals/Transfer.tsx

Closes https://github.com/polkadot-js/apps/issues/4513

Ensure {recipient, sender}Id is used from transfer props

---

packages/test-support/scripts/createBounties.ts
packages/test-support/scripts/lib/changeBountyStateFunctions.ts
packages/test-support/scripts/lib/helpers.ts
packages/test-support/scripts/lib/multiFunctions.ts

Hey, this changes will speedup createBounties script :)

Use utility batch in scripts

---

packages/apps-config/src/api/spec/crab.ts
packages/apps-config/src/api/spec/darwinia.ts

https://github.com/darwinia-network/darwinia/pull/607
```
{
ss58Format: 18,
tokenDecimals: 9,
tokenSymbol: 'RING',
ktonTokenDecimals: 9,
ktonTokenSymbol: 'KTON',
}
```
=>
```
{
ss58Format: 18,
tokenDecimals: [
[9,9]
],
tokenSymbol: [
['RING','KTON']
]
}
```

fix Darwinia, Crab system.properties change

---

packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

This PR resolves some issues regarding the KILT (parachain) styles and updates the corresponding color.

Fix kilt parachain

---

packages/apps/public/locales/en/app-bounties.json
packages/apps/public/locales/en/translation.json
packages/page-bounties/src/Bounty.tsx

Hi, since in council motions bounties are identified by ID, we should display ID in app-bounties.

Display bounty ID

---

packages/page-accounts/src/Accounts/Account.tsx

Closes https://github.com/polkadot-js/apps/issues/4532

Cater for limited chains without utility.*

---

packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/api/spec/integritee.ts
packages/apps-config/src/endpoints/testingRococo.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts
packages/apps-config/src/ui/logos/nodes/integritee.svg

the linter currently complains, but not about my changes

include integritee parachain

---

packages/page-staking/src/useSortedTargets.ts

https://polkadot.js.org/apps/#/staking
```
Uncaught error. Something went wrong with the query and rendering of this component. Cannot read property 'unwrap' of undefined
```
thank you ~

Overrides types for Crab, Darwinia

---

packages/apps-config/src/endpoints/testingRococo.ts

Add Rococo endpoints hosted by Ares Protocol

---

packages/page-accounts/src/modals/Transfer.tsx

Closes https://github.com/polkadot-js/apps/issues/4524

Ensure Available from transfer props

---

packages/react-components/src/InputStorage/index.tsx

Closes https://github.com/polkadot-js/apps/issues/4567

Don't call query (useState via fn)

---

packages/page-accounts/src/Accounts/Account.tsx

Closes https://github.com/polkadot-js/apps/issues/4584

Remove accounts menu with no entries

---

jest.config.js
jest/jest-setup.ts
packages/page-bounties/src/Bounties.spec.ts
packages/page-bounties/src/Bounties.spec.tsx
packages/page-bounties/src/BountyStatusView.tsx
packages/page-bounties/test/hooks/defaults.ts
packages/page-bounties/test/pages/bountiesPage.tsx
packages/test-support/package.json
packages/test-support/src/creation/hashes.ts
packages/test-support/src/creation/treasury/defaults.ts
packages/test-support/src/creation/treasury/proposalFactory.ts
packages/test-support/src/hooks/mockHooks.ts
packages/test-support/src/keyring/addresses.ts
tsconfig.json
yarn.lock

This is quite a massive refactor of UI tests for bounties. Deals with:
- test structure and naming
- mocking hooks
- test readability via extracting a Page Object

Refactor Bounties tests

---

packages/apps-config/src/api/spec/equilibrium.ts

Replaces and closes https://github.com/polkadot-js/apps/pull/4562

Update Equilibrium Address type

---

packages/react-signer/src/PaymentInfo.tsx

Closes https://github.com/polkadot-js/apps/issues/4579

Add existential warning on signer

---

packages/page-accounts/src/modals/Create.tsx

Closes https://github.com/polkadot-js/apps/issues/4610

Fix Copy overlap on accounts

---

packages/page-explorer/src/BlockInfo/Extrinsic.tsx

Closes https://github.com/polkadot-js/apps/issues/4630

Adjust lifetime display (Unsigned !== immortal tx)

---

packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

We want the right theme for stagenet and standalone, to provide a better UX for developers

Add theme support for stagenet and local stadalone - Moonbeam

---

packages/apps-config/src/api/spec/plasm-parachain.ts

Added XCM transfers related types.

Updated plasm parachain types

---

packages/page-bounties/src/Bounty.tsx
packages/page-bounties/src/BountyNextActionInfo/BountyInfo.tsx
packages/page-bounties/src/index.tsx
packages/page-bounties/src/theme.ts

Piecemeal adjustment along the lines of https://github.com/polkadot-js/apps/pull/4510
Initially this just aligns the non-standard colors with the actual UI colors.

Initial bounty re-align (table borders, font colors)

---

packages/page-bounties/src/Summary.tsx

- UI-aligned countdown for funding period
- add total calculated bounty value

Adjust summary for bounty-specific info

---

packages/page-bounties/src/Bounties.tsx
packages/page-bounties/src/Bounty.tsx
packages/page-bounties/src/index.tsx
packages/page-bounties/src/theme.ts

Expanded rows have less padding, it closer to the parent, has the same background. No lines between combined rows.

Adjust bounty expanded rows

---

packages/apps-config/src/api/spec/dotmog.ts

changed substrate 2.0.0 to 3.0.0 changing IndiciesLookup to MultiAddress

updated address & lookupsource

---

packages/apps-config/src/api/spec/nodle.ts
packages/apps-config/src/endpoints/production.ts

- update nodle types
- switch to dedicated node

nodle updates

---

packages/page-js/src/snippets/extrinsics-examples.ts
packages/react-components/src/Status/Queue.tsx
packages/react-components/src/Status/types.ts
packages/react-signer/src/signers/ApiSigner.ts

Fix send via JS app

---

packages/react-signer/src/PaymentInfo.tsx

Closes https://github.com/polkadot-js/apps/issues/4677

Adjust min balance calc

---

packages/apps-config/package.json
yarn.lock

update moonbeam types for upcoming v6 release

---

packages/apps-routing/src/js.ts
packages/apps/public/locales/en/app-js.json
packages/apps/public/locales/en/apps-routing.json
packages/apps/public/locales/es/translation.json
packages/apps/public/locales/fr/translation.json
packages/apps/public/locales/id/translation.json
packages/apps/public/locales/it/translation.json
packages/apps/public/locales/ja/translation.json
packages/apps/public/locales/pt/translation.json
packages/page-js/src/Playground.tsx

Small fix but I guess it's important to JS developers. ;)

Fix spelling: Javascript -> JavaScript.

---

packages/react-components/src/styles/semantic.ts

Closes https://github.com/polkadot-js/apps/issues/4684

Fix disabled menu items in dark mode

---

packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

We'd like to change our collator name.

Update Litentry Collator name

---

packages/apps-config/src/api/spec/ternoa.ts

What it says in the title. I have updated the chaos net and it needs new types to work.

update ternoa types

---

packages/page-accounts/src/Accounts/BannerExtension.tsx

Closes https://github.com/polkadot-js/apps/issues/4735

Phishing protected message for extensions

---

packages/apps-config/src/api/spec/sgc.ts

update chain types

---

packages/apps-config/src/api/spec/index.ts

Adding the import for unique types in `apps-config/src/api/spec/index.ts`

Fix unique types import

---

packages/page-accounts/src/md/basic.md

https://wiki.polkadot.network/docs/en/learn-accounts#existential-deposit-and-reaping

Update ED and reaping info in app

---

packages/apps-config/package.json
yarn.lock

hi, version 0.6.2-20 didn't handle type updates well. 0.6.2-21 fixes this issue.

bump version

---

packages/apps-electron/src/electron/contentSecurityPolicy.ts

Should fix https://github.com/polkadot-js/apps/issues/4756

Adjust CSP for workers

---

packages/page-staking/src/Actions/partials/Nominate.tsx
packages/page-staking/src/Legend.tsx
packages/page-staking/src/Targets/Validator.tsx
packages/page-staking/src/Targets/index.tsx
packages/page-staking/src/types.ts
packages/page-staking/src/useSortedTargets.ts

Closes https://github.com/polkadot-js/apps/issues/4798

Filter targets by blocking status

---

packages/page-bounties/src/Bounty.tsx
packages/page-parachains/src/Auctions/Auction.tsx
packages/page-parachains/src/Auctions/Bid.tsx
packages/page-parachains/src/Auctions/Summary.tsx
packages/page-parachains/src/Auctions/WinBlock.tsx
packages/page-parachains/src/Auctions/WinRange.tsx
packages/page-parachains/src/Auctions/index.tsx
packages/page-parachains/src/Auctions/types.ts
packages/page-parachains/src/Auctions/useWinningData.ts
packages/page-parachains/src/Crowdloan/FundContribute.tsx
packages/react-components/src/Table/Body.tsx
packages/react-hooks/src/index.ts
packages/react-hooks/src/useExtrinsicTrigger.ts

It shows something... however from here we need a lot of cleanups and dedupes.

Initial display for auction bids

---

packages/react-signer/src/Address.tsx
packages/react-signer/src/TxSigned.tsx

Show errors on keypair retrieval

---

packages/apps-config/src/endpoints/testingRococo.ts

We updated our paraId of our Bit.Country Parachain proposal

update paraId for Bit.Country Parachain testnet

---

packages/apps-config/src/api/spec/index.ts

**Changes**
* dusty3 -> dusty4

Fix Dusty networkg spec name

---

packages/react-components/src/Output.tsx
packages/react-signer/src/TxSigned.tsx

Closes https://github.com/polkadot-js/apps/issues/4598

Display call hash on signer modal

---

packages/react-hooks/src/useInflation.ts

Should improve https://github.com/polkadot-js/apps/issues/4896

Avoid NaN for returns

---

packages/react-hooks/src/useInflation.ts

Additional calcInflation check

---

packages/page-explorer/src/BlockInfo/ByHash.tsx
packages/page-explorer/src/BlockInfo/Justifications.tsx
packages/page-explorer/src/BlockInfo/Logs.tsx

Requires https://github.com/polkadot-js/apps/pull/4875

Display justifications

---

packages/apps-config/src/api/constants.ts
packages/apps-config/src/endpoints/testingRococo.ts
packages/page-parachains/src/Auctions/Bid.tsx
packages/page-parachains/src/Overview/Parachain.tsx
packages/page-parachains/src/Proposals/Proposal.tsx
packages/page-parachains/src/Proposals/useProposal.ts
packages/page-parachains/src/useOwnedIds.ts
packages/page-parachains/src/useProposals.ts

Just awaiting reset for genesisHash update

New Rococo (& old paths removal)

---

package.json
packages/page-accounts/package.json
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Bump API (session/staking & treasury fixes)

---

packages/page-treasury/src/Tips/Tip.tsx
packages/page-treasury/src/Tips/TipCreate.tsx
packages/page-treasury/src/Tips/Tips.tsx
packages/page-treasury/src/Tips/index.tsx
packages/page-treasury/src/index.tsx
packages/page-treasury/src/useTipHashes.ts

Closes https://github.com/polkadot-js/apps/issues/4915 (Awaits API update before it is useful to solve the issue completely)

Tip hash hook

---

packages/apps-config/package.json
yarn.lock

Update dependency version for `@sora-substrate/type-definitions`

Update sora library version
