polkadot-js/apps

- packages/apps-config/package.json
- yarn.lock
> upgrade polkabtc/types to 0.6.2

- packages/page-parachains/src/Overview/LeaseBlocks.tsx
- packages/page-parachains/src/Overview/useActionsQueue.ts
> Fix actionQueue session counter

- packages/page-parachains/src/Auctions/Bid.tsx
- packages/page-parachains/src/Auctions/Summary.tsx
- packages/page-parachains/src/Auctions/index.tsx
- packages/page-parachains/src/Auctions/useWinningData.ts
- packages/page-parachains/src/Crowdloan/Fund.tsx
- update end-period display
- fix cap div-0 percentage issues
- don't allow smaller bids than current range
> Merge end-period data (new sections)

- packages/apps-config/src/endpoints/testingRococo.ts
- packages/apps-config/src/ui/logos/index.ts
> fix: add darwinia crab pc2 logo

- packages/page-parachains/src/Crowdloan/Fund.tsx
- packages/page-parachains/src/Crowdloan/types.ts
- packages/page-parachains/src/Crowdloan/useFunds.ts
> Sort cowdloan via status, no winner contribute

- packages/page-parachains/src/Auctions/Auction.tsx
- packages/page-parachains/src/Auctions/WinRange.tsx
- packages/page-parachains/src/Auctions/index.tsx
- packages/page-parachains/src/Crowdloan/Funds.tsx
- packages/page-parachains/src/constants.ts
- packages/page-parachains/src/index.tsx
- packages/page-parachains/src/types.ts
- packages/page-parachains/src/useFunds.ts
- packages/page-parachains/src/useWinningData.ts
> Interleave bids & crowdloan on results

- packages/page-parachains/src/Crowdloan/FundAdd.tsx
As per https://github.com/polkadot-js/apps/issues/4905#issuecomment-808889657
> Adjust check on first slot for loan

- packages/page-parachains/src/Crowdloan/Fund.tsx
- packages/page-parachains/src/Crowdloan/Funds.tsx
> Dissolve when all leases passed only

- packages/page-parachains/src/Crowdloan/Contribute.tsx
- packages/page-parachains/src/Crowdloan/Fund.tsx
- packages/page-parachains/src/Crowdloan/Withdraw.tsx
- packages/react-hooks/src/useAccounts.ts
> Crowdloan withdrawals

- packages/apps-config/src/api/spec/dotmog.ts
> added new types for DOTMog.NET

- packages/apps-config/src/api/spec/zero.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
hey there,
this pr contains new types and node name updates to make it fly again.
kudos and have a nice day.
> feat(zero.io): update name, types, colour

- packages/apps-config/src/api/spec/cumulus-test-parachain.ts
- packages/apps-config/src/api/spec/index.ts
This reverts commit f5872d5b9683aa35629f6e91a994e9f3d940d7fc.
> Revert "Update Cumulus test para types (#4981)"

- packages/apps-config/src/ui/colors.ts
> Fix PolkaFoundry color

- packages/page-parachains/src/Crowdloan/Fund.tsx
- packages/page-parachains/src/Overview/Parachain.tsx
- packages/page-parachains/src/Overview/Parachains.tsx
- packages/page-parachains/src/Overview/Periods.tsx
- packages/page-parachains/src/Overview/Upcoming.tsx
- packages/page-parachains/src/Overview/index.tsx
> Display formatted leases

- packages/page-calendar/src/DayItem.tsx
- packages/page-calendar/src/types.ts
- packages/page-calendar/src/useScheduled.ts
- packages/page-parachains/src/Auctions/Summary.tsx
- packages/page-parachains/src/index.tsx
- packages/page-parachains/src/useWinningData.ts
Closes https://github.com/polkadot-js/apps/issues/5008
> Adjust events for parachains

- packages/apps-config/src/api/spec/robonomics.ts
Updated robonomics parachain types declaration.
> Updated robonomics chain types

- packages/apps-config/src/endpoints/production.ts
mainnet4 is down temporarily. So switching to stable endpoint.
> Fix loading issues for Edgeware

- packages/apps-config/src/endpoints/testingRococo.ts
due to https://github.com/paritytech/polkadot/pull/2858
> update Acala Mandala PC2 parachain id

- packages/page-staking/src/Payouts/Stash.tsx
- packages/page-staking/src/Payouts/index.tsx
- packages/page-treasury/src/Tips/index.tsx
Closes https://github.com/polkadot-js/apps/issues/5050
> Tips & old-payouts via useBatchTx

- packages/apps-config/src/endpoints/testingRococo.ts
change paraid from 128 to 2048 for apron
> change paraid from 128 to 2048 for apron

- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
Changing the name here since it's changed in our code.
> Rename SORA-staging Node to Sora

- package.json
- packages/page-accounts/package.json
- packages/page-contracts/package.json
- packages/react-api/package.json
- yarn.lock
Pulls in https://github.com/polkadot-js/api/pull/3404
> Bump API (statemint known-types)

- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/endpoints/testingRococo.ts
Add elara westend testnet provider.
> Add westend provider

- packages/apps-config/src/api/spec/canvas.ts
As per https://github.com/polkadot-js/apps/issues/5121
The team updated their node to master
> Canvas aligned with master

- packages/apps-config/src/endpoints/testingRococo.ts
> fix typing error

- packages/page-explorer/src/BlockInfo/ByHash.tsx
- packages/page-explorer/src/BlockInfo/Extrinsic.tsx
- packages/page-explorer/src/BlockInfo/Extrinsics.tsx
Closes https://github.com/polkadot-js/apps/issues/2599
> Display extrinsic weights

- packages/apps-config/src/endpoints/testing.ts
Add onfinality endpoint for westend.
> Add onfinality endpoint for westend

- packages/apps-config/src/endpoints/testingRococo.ts
Remove apron config `isDisabled` flag
> Remove apron config `isDisabled` flag

- packages/apps-config/src/api/spec/dusty.ts
Fix Dusty chain types, added missed `SmartContract` type.
> Updated Dusty chain types

- packages/page-treasury/src/Tips/Tip.tsx
- packages/page-treasury/src/Tips/Tips.tsx
- packages/react-components/src/Table/Body.tsx
- packages/react-components/src/Table/index.tsx
Closes https://github.com/polkadot-js/apps/issues/5162
> All Table word breaks on 100% columns

- packages/apps-config/src/endpoints/production.ts
Add onfinality endpoint for edgeware
> Add onfinality endpoint for edgeware

- packages/page-council/src/Overview/Vote.tsx
Closes https://github.com/polkadot-js/apps/issues/4825
> Show council reserved voting amount

- packages/page-staking/src/Actions/Account/SetRewardDestination.tsx
- packages/page-staking/src/Actions/partials/Bond.tsx
Closes https://github.com/polkadot-js/apps/issues/4901
> Add check for reward destination existence

- packages/apps-config/src/api/spec/index.ts
- packages/apps-config/src/api/spec/neatcoin.ts
- packages/apps-config/src/endpoints/production.ts
Add configurations for the Neatcoin mainnet endpoint.
> Add Neatcoin mainnet endpoint

- packages/react-components/src/Call.tsx
- packages/react-components/src/Static.tsx
Closes https://github.com/polkadot-js/apps/issues/4762
> Fix explorer static copy

- packages/page-explorer/src/BlockInfo/ByHash.tsx
- packages/page-explorer/src/BlockInfo/Summary.tsx
Closes https://github.com/polkadot-js/apps/issues/5187
> Expand block summary

- package.json
- packages/page-contracts/package.json
- packages/page-contracts/src/Codes/Upload.tsx
- packages/react-api/package.json
- yarn.lock
Closes https://github.com/polkadot-js/apps/issues/5203
Adjust ConsensusEngineId as per https://github.com/polkadot-js/api/issues/3481
> Bump API (& adjust contracts upload)

- packages/apps-config/src/api/spec/bitcountry-rococo.ts
- packages/apps-config/src/api/spec/bitcountry.ts
- packages/apps-config/src/api/spec/index.ts
- packages/apps-config/src/endpoints/testingRococo.ts
Hi team,
We have updated the Bit.Country Parachain node to latest rococo-v1, so new custom types and updated paraId have been included in this PR. 
Thank you.
> update BitCountry latest customType and upgrade paraId to 1008

- packages/apps-config/src/api/spec/vln-rococo.ts
Updates the type definition to handle newly added pallets
> update swap types for VLN

- packages/page-parachains/src/Auctions/Summary.tsx
As per https://github.com/polkadot-js/apps/issues/4905#issuecomment-832978857
> Fix auction first-last display (use leasePeriodsPerSlot)

- packages/apps-config/package.json
- yarn.lock
Updated moonbeam-types-bundle to support change of AccountsInfoWithProviders
> updated to moonbeam-types-bundle v 1.1.13

- packages/apps-config/src/api/spec/ternoa.ts
> update ternoa types to support nft series

- packages/page-parachains/src/Parathreads/RegisterThread.tsx
Closes https://github.com/polkadot-js/apps/issues/5220
> Use registerNext for parachains

- packages/apps-config/src/endpoints/production.ts
Hello @jacogr . There is a subsocial provider needs to be added. Thanks~
> Add subsocial provider

- packages/page-democracy/src/Overview/TreasuryCell.tsx
Closes https://github.com/polkadot-js/apps/issues/3991
> Show treasury details in council proposals

- packages/apps-config/src/api/spec/gamepower.ts
```
AccountInfo: 'AccountInfoWithDualRefCount'
```
> Updating gamepower types

- packages/apps-config/package.json
- yarn.lock
Sorry @jacogr but it seems the last update broke the AccountInfo typing
> Fix moonbeam types

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Unfortunately I messed up the para name. I hope this can be merged to fix it. Really sorry about the inconvenience!
> fix: kilt para name

- packages/page-council/src/Overview/Vote.tsx
Closes https://github.com/polkadot-js/apps/issues/5300
> Cater for prev-gen council votes

- packages/page-council/src/Motions/Slashing.tsx
- packages/page-staking/src/Slashes/Era.tsx
- packages/react-components/src/types.ts
Closes https://github.com/polkadot-js/apps/issues/5306
> Adjust slash creation for staking pages

- packages/react-params/src/Param/DispatchError.tsx
- packages/react-params/src/Param/DispatchResult.tsx
- packages/react-params/src/Param/Static.tsx
- packages/react-params/src/Param/Unknown.tsx
- packages/react-params/src/Param/findComponent.ts
Closes https://github.com/polkadot-js/apps/issues/5312
> DispatchResult expansion

- package.json
- packages/page-contracts/package.json
- packages/react-api/package.json
- yarn.lock
Pulls in https://github.com/polkadot-js/api/pull/3548
Closes https://github.com/polkadot-js/apps/issues/5331
> Bump API (w/ metadata parsing fix)

- packages/page-staking/src/Legend.tsx
- packages/page-staking/src/Overview/Address/Status.tsx
- packages/page-staking/src/Overview/Address/index.tsx
- packages/page-staking/src/Overview/CurrentList.tsx
Closes https://github.com/polkadot-js/apps/issues/5342
> Hide para indicator on non relays

- packages/apps-config/src/api/spec/zero.ts
Hi there,
This is a pull request containing updated types for zero network.
Thanks in advance!
Marco
> feat(zero): update spec

- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps/public/locales/en/apps-config.json
> add kylin testnetwork

- jest-slow.config.cjs
- jest.config.cjs
- package.json
Closes https://github.com/polkadot-js/apps/issues/5373
`--runInBand` seems to be the culprit here
> Fix skipping of tests

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
- packages/apps-config/src/ui/logos/nodes/sakura.svg
- packages/apps/public/locales/en/apps-config.json
adds Clover's Sakura sister network entry.
> add sakura node

- packages/page-parachains/src/Crowdloan/Contribute.tsx
- packages/page-parachains/src/Crowdloan/Fund.tsx
Closes https://github.com/polkadot-js/apps/issues/5402
> Allow for verifier signature

- packages/apps-config/package.json
- yarn.lock
for new features author mapping
> Update moonbeam types

- .github/workflows/lock.yml
- packages/apps-config/src/endpoints/development.ts
- packages/apps-config/src/endpoints/index.ts
- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelays.ts
- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
- packages/apps-config/src/endpoints/testingRelays.ts
- packages/apps-config/src/endpoints/types.ts
- packages/apps-config/src/endpoints/util.ts
- packages/apps-config/src/settings/types.ts
- packages/apps-routing/src/index.ts
- packages/apps-routing/src/teleport.ts
- packages/apps-routing/src/types.ts
- packages/apps/src/Endpoints/index.tsx
- packages/apps/src/Menu/index.tsx
- packages/page-parachains/src/Teleport.tsx
- packages/react-api/src/Api.tsx
- packages/react-api/src/types.ts
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useParaApi.ts
- packages/react-hooks/src/useParaEndpoints.ts
- packages/react-hooks/src/useTeleport.ts
Closes https://github.com/polkadot-js/apps/issues/5254
> Allow xcm asset teleport

- packages/apps-config/src/endpoints/testingRelayRococo.ts
- Set new para-id in rococo
- Set new provider name and URL
> update VLN paraId and provider

- packages/page-parachains/src/Teleport.tsx
- packages/react-hooks/src/useTeleport.ts
Closes https://github.com/polkadot-js/apps/issues/5443
This is not possible to do on parachains, only relays. We just don't have enough info to extract the entries.
> Extract relay by genesis

- packages/react-components/src/InputBalance.tsx
- packages/react-components/src/InputNumber.tsx
Closes https://github.com/polkadot-js/apps/issues/5310
Closes https://github.com/polkadot-js/apps/issues/4928
> Balance display with SI units

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Add onfinality endpoint for statemine.
> Add onfinality endpoint for statemine

- packages/apps-config/package.json
- yarn.lock
> fix: pangolin types error

- packages/apps-config/src/endpoints/testingRelayWestend.ts
- packages/apps-config/src/ui/logos/index.ts
Add endpoint of Shiden Network dry-run on Westend relaychain.
> Shibuya, the Shiden doppelganger

- .github/workflows/chain-types.yml
- jest.config.cjs
- packages/apps-config/src/ciChainTypes.spec.ts
- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/endpoints/types.ts
- packages/apps-config/src/endpoints/util.ts
- packages/apps/src/Endpoints/Network.tsx
- packages/apps/src/Endpoints/index.tsx
- packages/apps/src/Endpoints/types.ts
Closes https://github.com/polkadot-js/apps/issues/5466
> Disable entries with no types

- .github/chain-types.md
- packages/apps-config/src/ciChainTypes.spec.ts
Closes https://github.com/polkadot-js/apps/issues/5472 (well, not really, but we log the output now...)
> Log chain check outputs

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
@jacogr , I need your approval to add these two providers
> Add statemine & westmint provider

- .github/workflows/chain-types.yml
- .github/workflows/lint-chain-urls.yml
- package.json
- packages/apps-config/src/ciChainUrls.spec.ts
After https://github.com/polkadot-js/apps/pull/5481
> Add url lint

- packages/apps-config/src/endpoints/testingRelayWestend.ts
Closes https://github.com/polkadot-js/apps/issues/5489
> Unreachable endpoints

- packages/apps-config/src/ui/identityIcons/index.ts
- packages/apps-config/src/ui/index.ts
- packages/page-democracy/src/util.spec.ts
- packages/page-settings/src/useChainInfo.ts
- packages/react-components/src/IdentityIcon/index.tsx
Closes https://github.com/polkadot-js/apps/issues/5486
> Adjust icon based on spec

- packages/apps-config/src/api/spec/polkadex.ts
This PR updates Polkadex Testnet Specs and Types
> Update Polkadex Testnet Specs and Types

- packages/page-calendar/src/DayItem.tsx
Closes https://github.com/polkadot-js/apps/issues/5474
> Display event blockNumber

- packages/apps-config/src/endpoints/util.ts
> Sort isUnreachable endpoints to bottom

- packages/page-parachains/src/Crowdloan/Fund.tsx
- packages/page-parachains/src/Crowdloan/Funds.tsx
Closes https://github.com/polkadot-js/apps/issues/5508
> Adjust crowdloan media queries

- packages/apps-electron/package.json
May have a positive impact on https://github.com/polkadot-js/apps/issues/5504
> Remove type="module" for apps-electron

- packages/page-parachains/src/Crowdloan/Fund.tsx
Closes https://github.com/polkadot-js/apps/issues/5519
> Use correct ss58Format to encode loan addresses

- packages/page-parachains/src/Crowdloan/Fund.tsx
- packages/react-hooks/src/useAccounts.ts
Optimization for https://github.com/polkadot-js/apps/issues/5519 (less resource-intensive, straight hex-encoding)
> Optimize finding loan account (hex-only encoding)

- packages/page-parachains/src/Crowdloan/Fund.tsx
> Display crowdloan contribution accounts

- packages/apps-config/package.json
- yarn.lock
> Bump Moonbeam Types

- packages/apps/src/Endpoints/Network.tsx
Closes https://github.com/polkadot-js/apps/issues/5536
> Select random provider from list

- packages/apps-config/src/endpoints/productionRelayKusama.ts
**Changes**
`www.plasmnet.io` -> `shiden.plasmnet.io`
> Fix Shiden Network homepage

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
Closes https://github.com/polkadot-js/apps/issues/5547
> Remove no-DNS entries

- packages/apps-config/src/api/spec/index.ts
- packages/apps-config/src/api/spec/opportunity.ts
- packages/apps-config/src/endpoints/testing.ts
> Update opportunity types

- packages/apps-config/src/endpoints/testingRelayWestend.ts
Closes https://github.com/polkadot-js/apps/issues/5580
> Remove unreachable endpoints

- packages/apps-config/src/endpoints/productionRelayKusama.ts
darwinia crab redirect is reachable now
> fix: darwinia crab redirect reachable

- packages/apps-config/src/endpoints/production.ts
Added new community node for SORA
> Added new community node for SORA

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testing.ts
Closes https://github.com/polkadot-js/apps/issues/5619
> Unreachable networks

- packages/page-rpc/src/Rpc/Results.tsx
- packages/page-storage/src/Query.tsx
- packages/react-params/src/valueToText.tsx
Closes https://github.com/polkadot-js/apps/issues/5613
> Handle non-codec queryStorage results

- packages/apps-config/src/api/spec/beresheet.ts
- packages/apps-config/src/api/spec/index.ts
We're starting to use a separate runtime for beresheet.
> Add types for beresheet runtime

- packages/react-params/src/Param/BaseBytes.tsx
Closes https://github.com/polkadot-js/apps/issues/5634
> Allow 0x input on Bytes

- packages/apps-config/src/endpoints/productionRelayKusama.ts
it will be helpful if there is automatic fallback
> more karura nodes

- packages/page-accounts/src/Vanity/index.tsx
Support for this on the generator libs was actually dropped quite some time ago, the UI was never updated.
So it would be cool to have it UI-wise, so any PRs would be welcomed to re-add the functionality.
Closes https://github.com/polkadot-js/apps/issues/5639
> Remove wildcard reference

- packages/apps-config/src/endpoints/testing.ts
Closes https://github.com/polkadot-js/apps/issues/5684
> unitventures.io is unreachable

- packages/page-explorer/src/BlockInfo/Extrinsics.tsx
Closes https://github.com/polkadot-js/apps/issues/5688
> Adjust empty extrinsic message

- package.json
- packages/page-accounts/package.json
- packages/page-contracts/package.json
- packages/page-parachains/src/Crowdloan/Fund.tsx
- packages/page-staking/src/Overview/Summary.tsx
- packages/react-api/package.json
- yarn.lock
Closes https://github.com/polkadot-js/apps/issues/5696
> Also display total nominator count

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps/public/locales/en/apps-config.json
Robonomics registered Kusama parathread with ID 2077.
> Robonomics ParaID 2077 added

- packages/apps-config/src/ui/logos/index.ts
related with https://github.com/polkadot-js/apps/pull/5706
> Update name logo for robonomics

- packages/react-hooks/src/useTreasury.ts
Closes https://github.com/polkadot-js/apps/issues/5712
> Treasury account from palletId (as available)

- packages/apps-config/package.json
- yarn.lock
> bump acala

- packages/react-params/src/Param/Option.tsx
- packages/react-params/src/Param/index.tsx
Closes https://github.com/polkadot-js/apps/issues/5705
> Fix Option isDisabled rendering

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Closes https://github.com/polkadot-js/apps/issues/5730
> Altair -> isUnreachable

- package.json
- yarn.lock
Work around for issues in https://github.com/polkadot-js/apps/pull/5644 - this is the only reliable way to get this done with the update process to get it to be stuck on an older version.
> Add @substrate/connect to resolutions (fixed)

- packages/apps-config/package.json
- yarn.lock
Closes https://github.com/PureStake/moonbeam/pull/559
(Actually help greatly in ensuring https://github.com/polkadot-js/apps/pull/5732 works)
> Bump moonbeam bundle

- packages/apps-config/src/endpoints/testing.ts
@raykyri double check this is our load balanced RPC.
> Update Edgeware testnet rpc

- packages/apps-config/src/endpoints/production.ts
@raykyri double check this is the right load-balanced RPC.
> Update Edgeware mainnet RPC

- packages/apps-config/src/endpoints/testingRelayRococo.ts
Closes https://github.com/polkadot-js/apps/issues/5767
> Disable unavailable Ares for Rococo

- packages/apps-config/package.json
- packages/apps-config/src/api/spec/crab.ts
- packages/apps-config/src/api/spec/darwinia-parachain.ts
- packages/apps-config/src/api/spec/darwinia.ts
- packages/apps-config/src/api/spec/index.ts
- packages/apps-config/src/api/spec/pangolin.ts
- packages/apps-config/src/endpoints/testing.ts
- yarn.lock
1. https://github.com/polkadot-js/apps/issues/5726
2. Merged the Darwinia, Crab, Pangolin network types.
> Fix crab, pangolin types

- packages/apps-config/src/endpoints/production.ts
Closes https://github.com/polkadot-js/apps/issues/5788
> Update unavailable endpoints

- packages/apps-config/src/api/params/proposalThresholds.ts
- packages/page-democracy/src/Overview/Fasttrack.tsx
Closes https://github.com/polkadot-js/apps/issues/5800
> Add config for fast-track thresholds

- packages/page-society/src/useVoters.ts
- packages/react-components/src/InputNumber.tsx
Closes https://github.com/polkadot-js/apps/issues/5808
> Ensure siDefault is always used on InputNumber

- packages/apps-config/src/ci/util.ts
Closes https://github.com/polkadot-js/apps/issues/5816
Introduced in https://github.com/polkadot-js/apps/pull/5644
> Update CI logging checks for Substrate connect

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> Khala is reachable

- packages/apps-config/src/endpoints/testingRelayWestend.ts
Closes https://github.com/polkadot-js/apps/issues/5830
> Update unreachable endpoints

- packages/apps-config/src/ci/util.ts
- packages/apps-config/src/endpoints/index.spec.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
- packages/apps-config/src/endpoints/types.ts
- packages/apps-config/src/endpoints/util.ts
- packages/apps/src/Endpoints/Network.tsx
- packages/apps/src/Endpoints/index.tsx
- packages/apps/src/Root.tsx
- packages/apps/src/initSettings.ts
- packages/page-accounts/src/CreateAccount.slow.spec.tsx
- packages/page-bounties/src/Bounties.slow.spec.tsx
- packages/react-api/src/Api.tsx
Closes https://github.com/polkadot-js/apps/issues/5814
> Rework API urls

- packages/apps-config/src/endpoints/testingRelayRococo.ts
Closes https://github.com/polkadot-js/apps/issues/5842
> Unreachable

- packages/apps-config/src/endpoints/testing.ts
> Unavailable endpoints

- packages/apps-config/package.json
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- yarn.lock
in addition, I change the endpoint
> Upgrade khala typedefs

- packages/react-hooks/src/useBlockTime.ts
- packages/react-hooks/src/useBlocksPerDays.ts
Closes https://github.com/polkadot-js/apps/issues/5910
> Discard invalid configuration minimumPeriod values

- packages/apps-config/package.json
- yarn.lock
relate: https://github.com/darwinia-network/darwinia.js/pull/15
> Bump darwinia.js version

- packages/apps/public/locales/en/react-components.json
- packages/page-accounts/src/Sidebar/Flags.tsx
- packages/page-accounts/src/Sidebar/Sidebar.tsx
- packages/react-components/src/EditButton.tsx
- packages/react-components/src/InputTags.tsx
- packages/react-components/src/Tag.tsx
- packages/react-components/src/Tags.tsx
- packages/react-components/src/styles/index.ts
hi, this will change look of tags in app according to the ui grant design.
> Style tags

- packages/page-extrinsics/src/Decoder.tsx
closes #5746
UX is a bit confusing but it does what I need
> allow submit from Decod page

- packages/apps-config/src/links/subscan.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
Fix names of Shiden Network after chain spec update.
> Fix Shiden network names

- packages/apps-config/src/endpoints/productionRelayKusama.ts
We registered a new KILT para ID
> Update KILT Spiritnet para id

- packages/apps-config/package.json
- yarn.lock
> Update moonbeam types deps

- packages/page-accounts/src/Sidebar/Sidebar.tsx
- packages/react-components/src/LinkExternal.tsx
> Replace sidebar text links with icons

- packages/apps-config/src/endpoints/productionRelayKusama.ts
update for our running crowdloan
> add homepage to integritee and change public node

- packages/page-accounts/src/Sidebar/Flags.tsx
- packages/react-components/src/Flag.tsx
- packages/react-components/src/Tag.tsx
- packages/react-components/src/index.tsx
- packages/react-components/src/styles/index.ts
- packages/react-components/src/types.ts
> Style flags

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
> changed basilisk parachain id

- packages/apps-config/package.json
- packages/apps-config/src/endpoints/testingRelayRococo.ts
- yarn.lock
> update interbtc-types to 0.12.0 and enable rococo listing

- packages/apps-config/src/endpoints/index.spec.ts
- packages/apps-config/src/endpoints/index.ts
- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelays.ts
- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/endpoints/testingRelays.ts
- packages/apps-config/src/endpoints/util.ts
> Ensure isUnreachable is sorted alongside

- packages/react-hooks/src/useBlockTime.ts
> Invalid target block time displayed on the summary bar

- packages/react-components/src/AddressInfo.tsx
- packages/react-components/src/Table/Head.tsx
Closes https://github.com/polkadot-js/apps/issues/6050
Also removes the duplicated "account balance", which is actually the root cause and not adding value.
> Adjust balance alignment

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Add Onfinality endpoint for Kilt spiritnet.
> Add Onfinality endpoint for Kilt spiritnet

- packages/react-components/src/AddressInfo.tsx
- packages/react-components/src/DemocracyLocks.tsx
Closes https://github.com/polkadot-js/apps/issues/6075
> Fix democracy icon location

- packages/apps-config/src/ui/colors.ts
* Fixes missing theme color for KILT Spiritnet
* Updates theme color
> fix + refactor: KILT theme color

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
As per https://github.com/polkadot-js/apps/pull/6024#issuecomment-913574404
> Dwellir RPCs

- packages/apps-config/src/endpoints/testing.ts
> Updated Shibuya testnet endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
not sure if manually removing the unreachable flag is how it should be done. Anyway, that node is reachable now. Let me know
> [integritee] add parachain rpc node which is online

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Just migrate Shiden Network endpoint
> Update Shiden endpoint

- packages/page-accounts/src/Sidebar/Sidebar.tsx
As in the title these changes will increase the width of the sidebar. This will cause some elements (like buttons) to fit better and sidebar width will match the design.
> Increase the width of the account sidebar

- packages/apps-config/package.json
- yarn.lock
Should be fixed in the types package itself, will have to re-check to remove this dep when that is done....
Closes https://github.com/polkadot-js/apps/issues/6107
> Fix Sora (explicit lodash dep)

- packages/apps-routing/src/gilt.ts
- packages/page-gilt/src/Overview/BidAdd.tsx
- packages/page-gilt/src/Overview/Summary.tsx
- packages/page-gilt/src/Overview/index.tsx
- packages/page-gilt/src/translate.ts
- packages/page-gilt/src/useProxies.ts
- packages/react-components/src/InputAddress/index.tsx
Closes https://github.com/polkadot-js/apps/issues/5785
> Only allow Gilt bids via proxy

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Waiting for Treasury proposal before merging.
> Added Kusama RPC endpoint, hosted by Dwellir

- packages/apps/public/locales/en/app-accounts.json
- packages/page-accounts/src/Sidebar/AddressSection.tsx
- packages/page-accounts/src/Sidebar/Sidebar.tsx
- packages/page-accounts/src/Sidebar/SidebarEditableSection.tsx
These changes will apply new styles to the upper section of sidebar.
> Style upper part of sidebar

- packages/page-democracy/src/Overview/Fasttrack.tsx
Only for Fasttrack atm ... let's first see if it works as expected before going all-out. (Since it is a `batch`, it will still be proposed if the original Aye fails)
Closes https://github.com/polkadot-js/apps/issues/6015
> Batch TC Aye with Fasttrack

- packages/apps-config/src/ui/colors.ts
> fix: darwinia chain color

- packages/apps-config/package.json
- yarn.lock
> chore: bump darwinia types

- packages/apps-electron/src/main/account-store.spec.ts
- packages/page-accounts/src/modals/Create.spec.tsx
- packages/react-components/src/Modal/Modal.spec.tsx
- packages/react-components/src/Popup/Popup.spec.tsx
- packages/react-components/src/i18n/index.ts
- packages/test-support/src/pagesElements/Table.ts
Also migrate i18next to suspense
> Reduce warnings in tests

- packages/apps-config/src/endpoints/productionRelayKusama.ts
added fritti.calamari.systems and smoothie.calamari.systems today to help ease the load on falafel.calamari.systems
> new calamari full nodes

- packages/apps-config/src/endpoints/testingRelayWestend.ts
> westend basilisk moved to the new parachain id

- packages/apps-config/package.json
- yarn.lock
> chore: bump darwinia types to 1.2.1

- packages/page-signing/src/Verify.tsx
Closes https://github.com/polkadot-js/apps/issues/6141
> Allow verification of new-style message wrapping

- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
- packages/apps/public/locales/en/apps-config.json
Lately we changed the name of our testnet and the custom colors and logo stoped working. We would like to fix that.
> Change Aleph Zero Testnet name

- packages/apps-config/src/endpoints/testing.ts
Hello team,
We would like to update Bit.Country Testnet rpc endpoint for Test Network.
Thanks,
Justin
> Update Bit.Country Metaverse Testnet Endpoint.

- packages/page-accounts/src/Accounts/index.tsx
- packages/page-addresses/src/Contacts/index.tsx
- packages/react-components/src/FilterInput.tsx
- packages/react-components/src/index.tsx
> Apply the same filter and buttons style to Contacts as in Accounts

- packages/apps-config/package.json
- yarn.lock
* Updates KILT Types to newest version
Our Spiritnet just applied a runtime upgrade in which we broke the API. We would be happy about a quick merge. Thanks a lot!
> chore: update kilt type version

- packages/page-storage/src/Query.tsx
- packages/page-storage/src/Selection/Modules.tsx
Oversight from the conversion from metadata v13 -> v14
> Fix map query iteration/non-iteration

- packages/apps-config/package.json
- yarn.lock
> chore: bump darwinia types version

- packages/apps-config/package.json
- yarn.lock
> bump darwinia types

- packages/page-claims/src/Attest.tsx
- packages/page-claims/src/Claim.tsx
- packages/page-claims/src/index.tsx
Closes https://github.com/polkadot-js/apps/issues/6158
> Show zero claimable & no statement errors

- packages/page-contracts/src/Contracts/Contract.tsx
- packages/page-contracts/src/Contracts/ContractsTable.tsx
- packages/page-contracts/src/Contracts/index.tsx
Closes https://github.com/polkadot-js/apps/issues/6082
> Remove rent projection

- packages/apps-config/src/api/params/teleport.ts
After https://github.com/paritytech/polkadot/pull/3911
> Adjust base xcm weights (all now like Kusama)

- packages/page-storage/src/Selection/Modules.tsx
Closes https://github.com/polkadot-js/apps/issues/6183
> dedupKeyPrefix has been remove (handle optionally)

- packages/apps-config/package.json
- yarn.lock
Update pontem-types-bundle from 1.0.14 to 1.0.15
> Update pontem-types-bundle from 1.0.14 to 1.0.15

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
Closes https://github.com/polkadot-js/apps/issues/6195
> Remove non-working endpoints

- packages/apps-config/src/api/spec/basilisk.ts
> Basilisk added legacy xcm types

- packages/apps-config/src/endpoints/production.ts
> HydraDX removed defunct snakenet node provider

- packages/apps-config/src/api/spec/basilisk.ts
> Basilisk asset details type fixed

- packages/apps-config/src/api/spec/subgame.ts
SubGame new pallets have new types that need to be update.
> SubGame add new types

- packages/react-api/package.json
- packages/react-api/src/Api.tsx
- yarn.lock
Upgrade substrate connect to 0.4.0 (altered API)
> Upgrade substrate connect to 0.4.0

- packages/apps-config/src/api/spec/basilisk.ts
> basilisk upgraded xcm to v1

- packages/apps-config/src/api/params/teleport.ts
- packages/page-parachains/src/Teleport.tsx
Pass unlimited to teleports and update teleport weight to 4 * base weight.
> Fix Teleports

- packages/page-assets/src/Balances/Account.tsx
- packages/page-assets/src/Balances/Transfer.tsx
- packages/page-assets/src/Balances/useBalances.ts
- packages/page-assets/src/Overview/Create/Create.tsx
- packages/page-assets/src/Overview/Create/Info.tsx
- packages/page-assets/src/Overview/Create/index.tsx
- packages/page-assets/src/Overview/Mint/Mint.tsx
- packages/page-assets/src/Overview/Mint/index.tsx
- packages/page-assets/src/Overview/index.tsx
- packages/page-assets/src/index.tsx
- packages/page-assets/src/types.ts
- packages/page-assets/src/useAssetInfos.ts
Closes https://github.com/polkadot-js/apps/issues/6443
> Use metadata v14 types in assets (statemine upgraded)

- packages/page-parachains/src/Crowdloan/Funds.tsx
- packages/page-parachains/src/Crowdloan/useContributions.ts
- packages/page-parachains/src/Proposals/useProposal.ts
- packages/page-parachains/src/useActionsQueue.ts
- packages/page-parachains/src/useAuctionInfo.tsx
- packages/page-parachains/src/useFunds.ts
- packages/page-parachains/src/useLeasePeriod.ts
- packages/page-parachains/src/useLeaseRanges.ts
- packages/page-parachains/src/useOwnedIds.ts
- packages/page-parachains/src/useProposals.ts
- packages/page-parachains/src/useUpcomingIds.ts
- packages/page-parachains/src/useWinningData.ts
- packages/react-components/src/ErrorBoundary.tsx
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useCall.ts
- packages/react-hooks/src/useCallMulti.ts
- packages/react-hooks/src/useNamedHook.ts
May help in the investigation of reproducible issues such as https://github.com/polkadot-js/apps/issues/6435
> Add error stakcs to useCall & ErrorBoundary

- packages/apps-config/src/endpoints/testingRelayWestend.ts
Closes https://github.com/polkadot-js/apps/issues/6456
> Mark Opal as isUnreachable

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps/public/locales/en/apps-config.json
Hi, we will participate the batch of polkadot's auction.
> add bifrost chain for dot auction

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Sorry for the inconvenience. Fix the crust para id to 2008
> Correct crust para id to 2008

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Signed-off-by: Cheng JIANG <alex_cj96@foxmail.com>
> update parallel's para id & make its rpc reachable

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Closes https://github.com/polkadot-js/apps/issues/6507
> Comment out unavailable

- packages/apps-config/src/endpoints/testing.ts
Closes https://github.com/polkadot-js/apps/issues/6519
> Remove isDisabled endpoints

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
- packages/apps/public/locales/en/apps-config.json
We are launching the mainnet on 2021-11-10, 11:00 CET/10:00 UTC.
> Add Aleph Zero mainnet

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
Closes https://github.com/polkadot-js/apps/issues/6530
> isUnreachable for non-active entries

- packages/apps-config/src/endpoints/production.ts
Closes https://github.com/polkadot-js/apps/issues/6547
> isDisabled for no DNS endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Closes https://github.com/polkadot-js/apps/issues/6550
> Additional isUnreachable

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Efinity RPC node is online so updating this to be reachable.
> Make Efinity reachable productionRelayPolkadot.ts

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Closes https://github.com/polkadot-js/apps/issues/6595
> isUnreachable

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/testing.ts
@jacogr Thanks for approving and adding support for our mainnet and ContextFree testnet. There are a minor modification that may need your help to approve, sorry for the inconvenience it may cause.
> Modify provider title for Automata and ContextFree

- packages/apps-config/src/links/index.ts
- packages/apps-config/src/links/subsquare.ts
- packages/apps-config/src/ui/logos/external/subsquare.svg
- packages/apps-config/src/ui/logos/index.ts
SubSquare is a governance platform for substrate based chains developed by [OpenSquare](https://www.opensquare.network/). Currently we have integrated [karura](https://karura.subsquare.io/) and [khala](https://khala.subsquare.io/).
> Add subsquare to external links

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
Remove endpoints support by elara
+ subsocial
+ moonriver
+ bifrost
> remove some endpoints support by elara

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
add OnFinality endpoint of Acala Polkadot Parachain
> add OnFinality endpoint of Acala Polkadot Parachain

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Adds the Zeitgeist parachain configuration to Kusama's parachains.
> Add Zeitgeist para config

- packages/react-api/src/Api.tsx
Workaround for deployment issues -
- https://github.com/polkadot-js/apps/issues/6632
- https://github.com/polkadot-js/apps/issues/6633
> Workaround for Statemint deployment issues

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
Closes https://github.com/polkadot-js/apps/issues/6635
> Unreachable RPCs

- packages/apps-config/package.json
- yarn.lock
good day!
please find updated type defs for our updated pallets
thanks for support and greetings!
2075
> feat(gamedao-types): bump types to 0.0.14

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> Adjust support of karura by Elara

- packages/react-hooks/src/useBlockTime.ts
Update `useBlockTime.ts`  add subspace `expectedBlockTime` 
- #6664
> Add Subspace expected block time

- packages/page-assets/src/Balances/index.tsx
> Style bug fix: Balances asset selector

- packages/apps-config/src/api/spec/subgame.ts
> Update SubGame types

- packages/apps-config/package.json
- yarn.lock
> bump darwinia types version

- packages/apps-config/src/ci/util.ts
Invalid results 
- Closes https://github.com/polkadot-js/apps/issues/6687
- Closes https://github.com/polkadot-js/apps/issues/6688
> Only throw on construction types

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
Closes https://github.com/polkadot-js/apps/issues/6721
> Disable unreachable endpoints

- packages/apps-config/package.json
- yarn.lock
Updates both Opportunity Testnet/Standard Parachain types to include EVM types.
> Update Opportunity/Standard types.

- packages/apps-config/package.json
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps/public/locales/en/apps-config.json
- yarn.lock
Add Phala parachain, just tag it unreachable
BTW, Yarn 3.0.1 has compaitible issue with NodeJS 17 (see https://github.com/yarnpkg/berry/issues/3597), could you help to upgrade to latest version? @jacogr
> Add Phala parachain

- packages/page-settings/src/Metadata/Extensions.tsx
Makes UI in https://github.com/polkadot-js/apps/issues/6739 slightly prettier
> Add empty logo for unknown extensions

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
It has never worked for me and I get exactly the same comments form others I speak to. It is either responding too slowly or something else is wrong, but from my EU location (and those that have the same complaint as me), it has just never been operational. Selecting any other endpoint basically appears within a second or two.
Either way, to stop the flood of complaints reaching my inbox, I'm disabling it since the UI auto-selects one - and it seems when this one is selected, it doesn't work at all (and not just for me).
> Remove Geometry

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> Added Polkadot RPC endpoint, hosted by Dwellir

- packages/apps-config/package.json
- yarn.lock
Adds the latest types that includes rpc encoding also for kintsugi nodes.
> feat: readd rpc types for kintsugi

- packages/apps-config/src/api/spec/interbtc.ts
Resolves https://github.com/polkadot-js/apps/issues/6744
See also: https://github.com/interlay/interbtc/pull/464
> add custom derive for interbtc native balances

- packages/apps-config/src/endpoints/testing.ts
Polkadex testnet is running again.
> Polkadex testnet have been resurrected

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Closes https://github.com/polkadot-js/apps/issues/6794
> Crab isUnreachable

- packages/apps-config/src/api/spec/robonomics.ts
Update Robonomics chain types.
> Fix Robonomics chain types

- packages/apps-config/src/endpoints/productionRelayKusama.ts
* We have scaled up the service to deal with the workload.
* We have improved and tuned our monitoring so that we will be alarmed if we need to scale up.
> Reactivated Dwellir Kusama RPC

- packages/apps-config/src/api/spec/interbtc.ts
> add available balance to interbtc derive

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps/public/locales/en/apps-config.json
This PR adds information for the ui to display Polkadex parathread data.
> Add Polkadex parathread/parachain information

- packages/apps-config/src/api/spec/clover.ts
add a new enum member to the bridge network
> update clover types

- packages/page-parachains/src/Crowdloan/Fund.tsx
- packages/page-parachains/src/Crowdloan/Funds.tsx
- packages/page-parachains/src/Parathreads/Parathread.tsx
- packages/page-parachains/src/Parathreads/index.tsx
adjust, planning for -
- line expansion
- address & sovereign address
> Initial para sizing adjustments (follow-up with multi-line)

- packages/page-parachains/src/Teleport.tsx
Closes https://github.com/polkadot-js/apps/issues/6861
> Don't crash Teleport when dest have no balances pallet

- packages/apps/webpack.serve.cjs
- packages/page-settings/src/index.tsx
- packages/react-components/src/Status/index.tsx
Additionally also tried to fix the webpack HMR issue by resetting the timeout... wtill no official WebPack solution here
> Always display Settings -> Developer on dev chains

- packages/apps-config/src/endpoints/testing.ts
* Updates address for KILT's Peregrine testnet
* Low priority
> refactor: update KILT peregrine DNS

- packages/page-treasury/src/Overview/Summary.tsx
- packages/react-hooks/src/useTreasury.ts
Also needs https://github.com/polkadot-js/api/pull/4503 (for non-bounty chains)
> Extend treasury display (w/ bounties/approved)

- packages/page-staking/src/Targets/index.tsx
> Targets page: fix validators sorting

- packages/react-signer/src/Address.tsx
Inspect nested calls on all proxy types.
Closes https://github.com/polkadot-js/apps/issues/6892
> Expand nested call proxy checks

- packages/page-democracy/src/Overview/Referendum.tsx
Closes https://github.com/polkadot-js/apps/issues/6950
> Format percentages consistently

- packages/react-components/src/Status/Queue.tsx
- packages/react-components/src/Status/checks.ts
- packages/react-components/src/Status/index.tsx
- packages/react-components/src/Status/types.ts
Closes https://github.com/polkadot-js/apps/issues/3072
> Add event status warnings

- packages/page-democracy/src/Execute/Scheduled.tsx
- packages/page-democracy/src/Execute/Scheduler.tsx
- packages/page-democracy/src/Execute/types.ts
- packages/react-components/src/CallExpander.tsx
Closes https://github.com/polkadot-js/apps/issues/6981
> Support PalletSchedulerScheduledV3

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
> crab config

- README.md
- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
- packages/apps/public/locales/en/apps-config.json
Updating `system.chain` and `system.name`.
> Update names for Ajuna Network

- packages/apps-config/src/endpoints/testing.ts
> Add OnFinality endpoint for Pontem Testnet

- packages/page-calendar/src/UpcomingEvents.tsx
- packages/page-calendar/src/useScheduled.ts
Closes https://github.com/polkadot-js/apps/issues/7045
> Use leaseOffset in start event calculation

- packages/react-params/src/Param/Vector.tsx
Closes https://github.com/polkadot-js/apps/issues/7069
> Fix Vector getValues

- packages/react-components/src/InputAddress/index.tsx
Closes https://github.com/polkadot-js/apps/issues/7097
> Cater for Address types in InputAddress

- packages/apps-config/src/endpoints/productionRelayKusama.ts
* added onfinality endpoint
* edit ours to fit for the naming convention
> [encointer] add onfinality endpoint

- CHANGELOG.md
- packages/page-democracy/src/Overview/Fasttrack.tsx
Closes https://github.com/polkadot-js/apps/issues/6751
> Only disable fast-track on super majority

- packages/apps-config/src/endpoints/testingRelayRococo.ts
> Encointer rococo para setup as teleporter

- packages/apps-config/src/api/spec/kusari.ts
- packages/apps-config/src/api/spec/swapdex.ts
> Update Kusari and Swapdex Types

- packages/react-params/src/Param/VoteThreshold.tsx
Closes https://github.com/polkadot-js/apps/issues/7218
> Remove instanceof, adjust VoteThreshold rendering

- packages/apps-config/package.json
- packages/apps-config/src/api/spec/index.ts
- packages/apps-config/src/api/spec/mangata.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- yarn.lock
use `@mangata-finance/types` for fetching types definitions
> fetch mangata types definitions from dedicated package

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testing.ts
- create dedicated entry for mangata testnet
- temporary disable mangata kusama parachain (until offical url is known)
> move mangata reference to testnet tab

- packages/apps-config/src/endpoints/testingRelayRococo.ts
Please accept our new rococo env.
> Add Integritee Rococo

- packages/page-staking/src/Bags/index.tsx
The  bags page can benefit from having introductory content on bags list
> Add info about Bags List

- packages/apps-config/src/endpoints/production.ts
Closes https://github.com/polkadot-js/apps/issues/7293
> Disable unavailable endpoints

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/testing.ts
> Add Creditcoin network info

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> Adding Centrifuge OnFinality Service

- packages/apps-config/src/api/spec/subspace.ts
- Fix: https://github.com/subspace/polkadot-js-apps/issues/14
> Subspace - Fix extractAuthor on genesis block.

- packages/page-parachains/src/useFunds.ts
Closes https://github.com/polkadot-js/apps/issues/7347
> Only check crowdloan prefix for detection

- packages/apps-routing/src/democracy.ts
- packages/apps-routing/src/types.ts
- packages/apps/src/Content/index.tsx
- packages/apps/src/Menu/index.tsx
- packages/apps/src/endpoint.ts
Enhances the capability detection check with construction via invalid parameters, instead of just "call availability".
Closes https://github.com/polkadot-js/apps/issues/7367
> Hide democracy via api construction capabilities

- packages/page-staking/src/Actions/partials/Bond.tsx
just removed the typo (duplicate "available" ).
> Remove repeated "available"

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- Change OriginTrail Parachain ID from 2042 to 2043
> Update OriginTrail Parachain ID

- packages/page-staking/src/Pools/Create.tsx
- packages/page-staking/src/Pools/types.ts
- packages/page-staking/src/Pools/useParams.ts
Split from https://github.com/polkadot-js/apps/pull/7384 for current master (pre-merge)
> Pool param query updates

- packages/apps-config/src/endpoints/productionRelayKusama.ts
This PR introduce empty endpoints for Shiden Network Crowdloan 2 (just add logo and title for parachain id).
> Added Shiden Crowdloan 2

- packages/page-bounties/src/Bounty.tsx
- packages/page-bounties/src/hooks/useBounties.tsx
Closes https://github.com/polkadot-js/apps/issues/7445
> Bounties w & w/o curator deposit

- packages/apps-config/src/ui/logos/index.ts
Fix not appearing logo at rococo.
> Fix integritee logo at rococo.

- packages/apps-routing/src/staking.ts
- packages/apps/src/endpoint.ts
- packages/page-democracy/src/Overview/Seconding.tsx
Closes https://github.com/polkadot-js/apps/issues/7460
> Adjust API check order, ensure deposit is defaultValue

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> Update homepage for Shiden Network in Crowdloan

- packages/apps-config/src/endpoints/testing.ts
> Re-enable Phala (PoC 5) Testnet

- packages/page-bounties/src/Bounty.tsx
- packages/page-staking/src/Pools/Pool.tsx
- packages/page-staking/src/Pools/Pools.tsx
- packages/react-components/src/Table/index.tsx
Part of https://github.com/polkadot-js/apps/issues/7458
> Expand pool details (w/ all accounts)

- packages/page-staking/src/Actions/Pool/Account.tsx
Part of https://github.com/polkadot-js/apps/issues/7458
> Badge for pool nominators

- jest/setupEnv.cjs
Failures in https://github.com/polkadot-js/apps/issues/7468 & https://github.com/polkadot-js/apps/issues/7467
> Adjust CI Jest setup

- packages/apps-config/src/links/subid.ts
Closes https://github.com/polkadot-js/apps/issues/7485
> Disable broken sub.id redirects

- packages/apps-config/package.json
- yarn.lock
@jacogr Hello! Here is just type-definitions latest update
> Sora: update type definitions to 1.8.30

- packages/react-components/src/Table/index.tsx
Closes https://github.com/polkadot-js/apps/issues/7497
> Fix table button alignment

- packages/page-staking/src/Pools/Pool.tsx
- packages/page-staking/src/Pools/Summary.tsx
Closes https://github.com/polkadot-js/apps/issues/7520
> Pool fixed (zero max values)

- packages/page-staking/src/usePoolAccounts.ts
- packages/react-components/src/AccountName.tsx
As per https://github.com/polkadot-js/apps/issues/7458#issuecomment-1117660725
> HACK for both npols & nopls

- packages/page-staking/src/Pools/Pool.tsx
- packages/page-staking/src/Pools/Pools.tsx
Part of https://github.com/polkadot-js/apps/issues/7458
> Display pool nominees in pool summary

- packages/page-staking/src/usePoolAccounts.ts
Part of https://github.com/polkadot-js/apps/issues/7458
For some reason I didn't see this in either the editor or the UI. Need my eyes tested...
> Use palletId correctly for nominationPools

- packages/react-components/src/InputNumber.tsx
- packages/react-params/src/Param/Amount.tsx
Closes https://github.com/polkadot-js/apps/issues/7536
Needs more manual testing - seems fine as-is, but worried that I missed something in my tests.
> Allow negative value inputs in InputNumber

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Adds OnFinality endpoint to Zeitgeist parachain on Kusama relaychain.
> Add OnFinality endpoint to Zeitgeist

- packages/react-query/src/BlockAuthors.tsx
Closes https://github.com/polkadot-js/apps/issues/7562
> Correctly handle option mappingWithDeposit

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- reenables node address hosted by mangata team (that has been down for some time)
- list OnFinality node
> fix mangata addresses

- packages/apps-config/src/endpoints/testing.ts
<p>Remove disabled prop for SORA stage cuz It works fine for now</p>
> Remove disabled prop for SORA stage

- packages/page-democracy/src/Overview/Fasttrack.tsx
Closes https://github.com/polkadot-js/apps/issues/7576
> Disable Fasttrack with no batching

- packages/react-params/src/Param/Option.tsx
Closes https://github.com/polkadot-js/apps/issues/7584
> Ensure Option params are correctly filled from decoded

- packages/page-accounts/src/modals/MultisigApprove.tsx
Closes https://github.com/polkadot-js/apps/issues/7588
> Fix multisig for >2 thresholds

- packages/react-api/src/Api.tsx
Closes https://github.com/polkadot-js/apps/issues/7605
> Remove Subwallet from disallow list

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
Closes https://github.com/polkadot-js/apps/issues/7621
Closes https://github.com/polkadot-js/apps/issues/7620
> Adjust endpoints

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/util.ts
Follow-up on https://github.com/polkadot-js/apps/issues/7620 - the OnFinality endpoint is also incorrect
> Move Polkadex endpoints

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- Removed Integritee Solo
- Added new Onfinality to Integritee Kusama
> Add new OnFinality endpoint for Integritee and remove Solo

- packages/apps-config/src/endpoints/testing.ts
Closes https://github.com/polkadot-js/apps/issues/7638
> Disbale unreachable endpoints

- packages/page-democracy/src/Overview/Fasttrack.tsx
Closes https://github.com/polkadot-js/apps/issues/7657
> No voting for Fasttrack when members <= 1

- packages/apps-config/src/endpoints/productionRelayKusama.ts
enable dorafactory kusama parachain access
> Dorafactory kusama onboard

- packages/apps-config/package.json
- yarn.lock
<p>Update SORA type definitions</p>
> Update SORA type definitions

- packages/apps-config/src/ci/chainTypes.spec.ts
Closes https://github.com/polkadot-js/apps/issues/7690
> Skip types checks

- packages/apps-config/src/api/spec/index.ts
> add interlay-parachain spec name

- packages/page-treasury/src/Overview/ProposalCreate.tsx
Closes https://github.com/polkadot-js/apps/issues/7336
Closes https://github.com/polkadot-js/apps/issues/7660
> Display max treasury bonded amount

- packages/apps-config/src/endpoints/index.spec.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
Closes https://github.com/polkadot-js/apps/issues/7718
Introduced in https://github.com/polkadot-js/apps/pull/7689
> Fix invalid Quartz URL (with additional test)

- packages/page-staking/src/Pools/Pool.tsx
Closes https://github.com/polkadot-js/apps/issues/7724
> isSome checks on pool roles

- packages/page-settings/src/Metadata/Extensions.tsx
- packages/page-settings/src/Metadata/index.tsx
> Fix overflow issue in extensions table

- packages/apps-config/src/endpoints/production.ts
Closes https://github.com/polkadot-js/apps/issues/7786
> Remove unreachable

- packages/react-params/src/Param/Enum.tsx
- packages/react-params/src/Param/Tuple.tsx
Closes https://github.com/polkadot-js/apps/issues/7814
> Fix nested enum default values

- packages/apps-config/src/ui/colors.ts
This PR simply adjusts the banner color for litentry-rococo parachain.
> Adjust litentry-rococo banner color

- packages/apps-config/src/endpoints/production.ts
> Removed HydraDX Snakenet from the list of live chains

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Added endpoint wss://polkadot.api.integritee.network
> Add integritee to polkadot

- packages/apps-config/package.json
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
- yarn.lock
<p>Add SORA Rococo Parachain & Kusama Parachain</p>
> Add SORA Rococo Parachain & Kusama Parachain

- packages/react-query/src/Events.tsx
Closes https://github.com/polkadot-js/apps/issues/7871
> Filter relayChainInfo.CurrentBlockNumbers

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/testing.ts
Update Creditcoin mainnet and testnet RPC endpoints.
> Update Creditcoin network endpoints

- packages/react-params/src/Param/findComponent.ts
- packages/react-params/src/Param/index.tsx
Closes https://github.com/polkadot-js/apps/issues/7898
> Perform inner inspect on Luukup types (Label & Component)

- packages/apps-config/src/ui/logos/index.ts
Fix turing chain image.
Please help to review.
> Fix turing chain image

- packages/page-alliance/src/Overview/index.tsx
- packages/page-alliance/src/index.tsx
- packages/react-hooks/src/types.ts
- packages/react-hooks/src/useCollectiveMembers.ts
Needs https://github.com/polkadot-js/api/pull/5113
> Introduce alliance motions

- packages/page-accounts/src/modals/ProxyOverview.tsx
Closes https://github.com/polkadot-js/apps/issues/7951
Handles `null` accountIds
> Handle error on invalid proxy account

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> Remove onfinality from Turing rpc selection

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Added Blast as an Astar wss endpoint option
> Added Astar/Shiden WS endpoint

- packages/apps-config/src/endpoints/testing.ts
> Add Web3Games network  Rpc address

- packages/apps-config/src/endpoints/index.spec.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
Replaces https://github.com/polkadot-js/apps/pull/7985
> Name cleanups

- packages/apps-config/src/api/derives.ts
- packages/apps-config/src/api/spec/index.ts
- packages/apps-config/src/api/typesBundle.ts
Note: `packages/apps-config/src/api/typesBundle.ts` autogenerated via yarn build.
> Add specs for interlay and kintsugi testnet

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Adding geo distributed, high performance, low latency endpoints from RadiumBlock to Statemine for public use.
> Add RadiumBlock endpoint to statemine

- packages/apps-config/src/api/spec/index.ts
- packages/apps-config/src/api/spec/rootnet.ts
- packages/apps-config/src/api/typesBundle.ts
- packages/apps-config/src/settings/ethereumChains.ts
This will enable our team to use the portal with a local node - we hope to spin up a testnet by next week so will make a PR then with the endpoint
> Add `Root Network` types

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Closes https://github.com/polkadot-js/apps/issues/8039
> Disable unreachable

- packages/apps-config/src/endpoints/production.ts
Closes https://github.com/polkadot-js/apps/issues/8046
Closes https://github.com/polkadot-js/apps/issues/8012
> Disable endpoints

- packages/apps-config/src/ui/logos/index.ts
Adds missing name mapping to enable info -> logo
Closes https://github.com/polkadot-js/apps/issues/8048
> Add named logo for "snow" info

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
> Galactic Council RPC servers upgraded

- packages/apps-config/src/endpoints/testing.ts
We no longer need them and want to shut them down
> Remove extra Subspace Gemini 1 endpoints

- packages/apps-config/src/links/subid.ts
> Add subid link to bit country chain

- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/ui/logos/index.ts
We're launching new network, endpoints are already live
> Add Subspace Gemini 2a endpoints

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Adding OnFinality API for Bajun Network.
> Add OnFinality API for Bajun Network

- packages/apps-config/src/endpoints/testingRelayRococo.ts
> Re-enable Bajun Rococo endpoint

- packages/apps-config/src/endpoints/testingRelayRococo.ts
Re: https://github.com/paritytech/subport/issues/466
Thanks.
> Update `paraId` for long-term slot on Rococo

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Remove Dwellir endpoints for Composable and Picasso
> Remove Dwellir endpoints for Composable and Picasso

- packages/apps-config/src/endpoints/testing.ts
Adding Beresheet v4 testnet endpoint by JelliedOwl
> New endpoint for Beresheet (Edgeware) testnet

- packages/page-accounts/src/Sidebar/RegistrarJudgement.tsx
As introduced in https://github.com/paritytech/substrate/pull/12170
cc @chevdor - please do give it a check as well
> Add hash to judgement call

- packages/apps-config/src/api/params/inflation.ts
- packages/react-hooks/src/useInflation.ts
... after I spent some time looking and digging, this should make future looks easier
> Link inflation calculations source

- packages/apps-config/src/endpoints/testingRelayWestend.ts
Closes https://github.com/polkadot-js/apps/issues/8118
To be merged when change actually does happen.
> Change collectives paraId (Westend)

- packages/page-contracts/src/useWeight.ts
- packages/page-explorer/src/BlockInfo/ByHash.tsx
- packages/page-explorer/src/BlockInfo/Extrinsic.tsx
- packages/page-explorer/src/BlockInfo/Extrinsics.tsx
- packages/page-explorer/src/BlockInfo/Summary.tsx
- packages/react-hooks/src/useTxBatch.ts
- packages/react-hooks/src/useWeight.ts
Needs https://github.com/polkadot-js/api/pull/5251
Addresses first part of https://github.com/polkadot-js/apps/issues/8188
... there are obviously major usability issues left, i.e. all the old/new close functionalities (e.g. democracy) are still outstanding. (These are more tricky since they do require the API upgrade to go lock-step with them)
> Adjust hooks for V2 weight usage

- packages/page-accounts/src/modals/MultisigApprove.tsx
- packages/page-contracts/src/useWeight.ts
- packages/page-council/src/Motions/Close.tsx
- packages/page-explorer/src/BlockInfo/ByHash.tsx
- packages/page-explorer/src/BlockInfo/Extrinsic.tsx
- packages/page-explorer/src/BlockInfo/Summary.tsx
- packages/page-tech-comm/src/Proposals/Close.tsx
- packages/react-hooks/src/useTxBatch.ts
- packages/react-hooks/src/useWeight.ts
Needs https://github.com/polkadot-js/api/pull/5251
Part of https://github.com/polkadot-js/apps/issues/8188
Next round would be to look at all the call failures, which also includes all multisig operations
> Adjust useWeights results (prepare for conv.)

- packages/apps-config/src/endpoints/productionRelayKusama.ts
We have set a proper RPC endpoint separated from our collators, time to update it in apps :)
> Change Amplitude's RPC endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Added Leemo RPC to Robonomics Parachain
> Updated Robonomics RPC endpoints

- packages/apps-config/src/endpoints/testingRelayRococo.ts
> Bridgehub Rococo RPC

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Closes https://github.com/polkadot-js/apps/issues/8301
> Remove unavailable endpoints

- packages/page-referenda/src/Referenda/Submit.tsx
Closes https://github.com/polkadot-js/apps/issues/8304
Not fully-featured, but gets over the existing hump.
> Referenda submit fix (Lookup only, split from cleanups)

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Move from `rpc.pendulumchain.tech` to `rpc-amplitude.pendulumchain.tech`
> Update RPC endpoint

- packages/page-referenda/src/Referenda/RefOngoing.tsx
- packages/page-referenda/src/Referenda/Vote.tsx
Closes https://github.com/polkadot-js/apps/issues/8323
> Show vote button even with no preimage

- packages/react-hooks/src/useAvailableSlashes.ts
Closes https://github.com/polkadot-js/apps/issues/8349
> Ensure staking slashes checks

- packages/apps-config/src/endpoints/productionRelayKusama.ts
@jacogr this node was repaired a few days ago and is working fine now, please take a look, thanks!
> Enable crust shadow endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
I added an alternativity provider for SubsocialX
> Add new Subsocial parachain provider

- packages/apps-routing/src/democracy.ts
- packages/page-democracy/src/Overview/PreImageButton.tsx
> Adjust democracy display detection

- packages/page-democracy/src/Overview/PreImageButton.tsx
- packages/page-democracy/src/Overview/ProposalCell.tsx
- packages/page-democracy/src/Overview/index.tsx
- packages/page-preimages/src/types.ts
- packages/page-preimages/src/usePreimage.ts
Closes https://github.com/polkadot-js/apps/issues/8388
> Support new preimages on v1 democracy

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
New endpoint deployment - Moving our infrastructure to a hybrid (cloud + on-prem) compute strategy for better decentralization, cost prediction and compute provider risk mitigation.
> Update RadiumBlock Polkadot endpoint

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> Uncommenting the Ajuna Network RPC

- packages/apps-config/src/settings/ethereumChains.ts
-Added Darwinia's Ethereum Compatibility validation
> Minor updates

- packages/page-council/src/Motions/ProposeExternal.tsx
- packages/page-democracy/src/Overview/Propose.tsx
Closes https://github.com/polkadot-js/apps/issues/8402
> Adjust council proposeExternal (basic, non-optimal detect)

- packages/page-ranked/src/useMembers.ts
Closes https://github.com/polkadot-js/apps/issues/8410
> Sort ranked collectives

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Please change link to our new endpoint
> Endpoint change picasso

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Deploying Astar endpoint using our hybrid (cloud + on-prem) compute infrastructure for better decentralization, cost prediction and compute provider risk mitigation.
> RadiumBlock Astar endpoint using hybrid compute

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/testing.ts
<p>I've updated SORA nodes for testing & production</p>
> Update SORA nodes for testing & production

- packages/page-democracy/src/Execute/Scheduler.tsx
Part of https://github.com/polkadot-js/apps/issues/8340
> Display inline scheduler entries

- packages/apps-routing/src/preimages.ts
Closes https://github.com/polkadot-js/apps/issues/8459
> Adjust preimage detection

- packages/page-referenda/src/Referenda/Referendum.tsx
Aim to fix wrong external links for fellowship referenda.
> Fix external links for fellowship referenda

- packages/page-democracy/src/Execute/Scheduled.tsx
- packages/page-democracy/src/Execute/Scheduler.tsx
- packages/page-democracy/src/Execute/types.ts
Closes https://github.com/polkadot-js/apps/issues/8340
> Decode scheduler Lookup entries

- packages/react-hooks/src/useAvailableSlashes.ts
Closes https://github.com/polkadot-js/apps/issues/8505
> Add missing 1 offset to slash retrieval

- packages/page-staking/src/Slashes/Era.tsx
- packages/page-staking/src/Slashes/index.tsx
Missed in https://github.com/polkadot-js/apps/pull/8507
> Add 1 era offset to slash era headers

- packages/page-referenda/src/Referenda/Vote.tsx
Really want the splits (also normal split votes) - this does require a complete modal re-work, so for now we just have basic balance + all-abstain functionality
Closes https://github.com/polkadot-js/apps/issues/8515
Additional full rework logged in https://github.com/polkadot-js/apps/issues/8517
> Add (basic) abstain functionality

- packages/page-referenda/src/Referenda/Vote.tsx
- packages/page-referenda/src/Referenda/VoteAbstain.tsx
- packages/page-referenda/src/Referenda/VoteBasic.tsx
- packages/page-referenda/src/Referenda/VoteSplit.tsx
- packages/page-referenda/src/Referenda/VoteStandard.tsx
- packages/page-referenda/src/Referenda/types.ts
- packages/react-components/src/VoteValue.tsx
Closes https://github.com/polkadot-js/apps/issues/8517
> Rework voting modal with all type values

- packages/page-accounts/src/modals/Qr.tsx
Adjust location for warning display as per https://github.com/polkadot-js/apps/pull/8522
> Adjust QR genesisHash warning

- packages/react-components/src/Call.tsx
- packages/react-params/src/Param/Call.tsx
Closes https://github.com/polkadot-js/apps/issues/8543
> Display Call hashes on disabled items

- packages/page-staking/src/Actions/useInactives.ts
- packages/page-staking/src/Validators/Address/NominatedBy.tsx
Closes https://github.com/polkadot-js/apps/issues/8548
See the notes - this is a horrible detection mechanism, but the only one available.
> Chilled filtering adjustments (no-auto, recent Substrate)

- packages/page-accounts/src/Accounts/index.tsx
As indicated by https://github.com/polkadot-js/apps/issues/8549 the "+ Multisig" functionality is detected, however the pallet functionality cannot really be found so you cannot send. (This is actually due to the older support where multisigs were available on `utility`, hence just checking for the platte is not enough) 
Enhance the check to actually check for required function calls. (This also apply this same approach to proxy, which _could_ have similar issues down the line)
> Adjust w/ function detection for proxy & multisig

- packages/page-referenda/src/Referenda/Referendum.tsx
- packages/react-hooks/src/useBlockTime.ts
Closes https://github.com/polkadot-js/apps/issues/8572
> Display time delays in referenda tooltip headers

- packages/react-components/src/Chart/Line.tsx
This _may_ help with https://github.com/polkadot-js/apps/issues/8588
TL;DR completely in the dark here, but looking ath the crosshair plugin code, this _may_ yield an improvement... (No impact whatsoever locally)
> Adjust chart plugin copy

- packages/page-referenda/src/Referenda/RefOngoing.tsx
- packages/page-referenda/src/Referenda/Vote.tsx
- packages/page-referenda/src/Referenda/VoteStandard.tsx
- packages/react-components/src/ConvictionDropdown.tsx
Closes https://github.com/polkadot-js/apps/issues/8597
See https://github.com/paritytech/substrate/blob/ee316317b85b2f65fc022b27bbfefcd42b6560ae/frame/conviction-voting/src/lib.rs#L460-L463
```rust
PollStatus::Completed(end, approved) => {
if let Some((lock_periods, balance)) = v.1.locked_if(approved) {
let unlock_at = end.saturating_add(
T::VoteLockingPeriod::get().saturating_mul(lock_periods.into()),
```
> Use convictionVoting votingPeriod in Vote display

- packages/page-accounts/src/modals/Delegate.tsx
- packages/page-democracy/src/Overview/Voting.tsx
- packages/page-referenda/src/Referenda/Vote.tsx
- packages/page-referenda/src/Referenda/VoteStandard.tsx
- packages/react-components/src/ConvictionDropdown.tsx
Follow-up to https://github.com/polkadot-js/apps/pull/8599 (ensure that we explicitly pass it so that we don't use the wrong values between pallets)
> Always pass through voting lock period

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
Simple PR to add [UnitedBloc](https://medium.com/@daniel_96988/unitedbloc-rpc-c84972f69457) endpoints for all Moonbeam-based networks.
> Adds UnitedBloc endpoints

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Signed-off-by: vol4tim <vol4tim@gmail.com>
> Updated paraId for Robonomics crowdloan 2

- packages/page-storage/src/Selection/Modules.tsx
- packages/react-params/src/Param/BaseBytes.tsx
- packages/react-params/src/Param/Option.tsx
- packages/react-params/src/types.ts
Additional cleanups for https://github.com/polkadot-js/apps/pull/8615
> Adjust Option<Bytes> encoding (per Option)

- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/ui/colors.ts
- packages/apps-config/src/ui/logos/index.ts
Changelog:
- Add bitgreen testnet to list of test networks
> add bitgreen testnet

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Changelog:
- Add bitgreen mainnet to Live networks
> add bitgreen mainnet

- packages/page-accounts/src/Accounts/Account.tsx
- packages/page-accounts/src/Accounts/index.tsx
- packages/page-addresses/src/Contacts/Address.tsx
- packages/page-addresses/src/Contacts/index.tsx
- packages/page-bounties/src/Bounties.tsx
- packages/page-democracy/src/Overview/External.tsx
- packages/page-democracy/src/Overview/Externals.tsx
- packages/page-democracy/src/Overview/Proposal.tsx
- packages/page-democracy/src/Overview/Proposals.tsx
- packages/page-democracy/src/Overview/Referendum.tsx
- packages/page-democracy/src/Overview/Referendums.tsx
- packages/page-referenda/src/Referenda/Group.tsx
- packages/page-staking/src/Pools/Pools.tsx
- packages/react-components/src/Columar.tsx
- packages/react-components/src/Table/index.tsx
Replacement for https://github.com/polkadot-js/apps/pull/8630
> Add isSplit on tables (unused)

- packages/page-referenda/src/Referenda/Group.tsx
- packages/page-referenda/src/Referenda/RefOngoing.tsx
- packages/page-referenda/src/Referenda/Referendum.tsx
- packages/page-referenda/src/Referenda/Votes.tsx
- packages/react-components/src/Table/index.tsx
Part of https://github.com/polkadot-js/apps/issues/8566
> Move external links to referendum expansion

- packages/apps-config/src/endpoints/testingRelayWestend.ts
New westend parachain: Bridge hub
> Bridge hub parachain on Westend

- packages/page-staking/src/Pools/Join.tsx
- packages/page-staking/src/Pools/useParams.ts
Closes https://github.com/polkadot-js/apps/issues/8688
> Adjust pool min join calc

- packages/page-extrinsics/src/Decoder.tsx
Closes https://github.com/polkadot-js/apps/issues/8700
> Length check in for extrinsic/call detect

- packages/react-api/src/light/index.ts
Needed once https://github.com/polkadot-js/api/pull/5405 hits, doesn't hurt otherwise
> Minor ScProvider adjustments

- packages/page-staking/src/Legend.tsx
- packages/page-staking/src/Validators/Address/Status.tsx
- packages/page-staking/src/Validators/Address/index.tsx
- packages/page-staking/src/Validators/CurrentList.tsx
- packages/page-staking/src/index.tsx
- packages/react-components/src/Badge.tsx
- packages/react-components/src/Tag.tsx
- packages/react-components/src/types.ts
Extracted from https://github.com/polkadot-js/apps/pull/8717
> Validator points adjustment

- packages/apps/public/index.html
- packages/apps/src/Endpoints/Network.tsx
- packages/page-staking/src/Payouts/PayButton.tsx
- packages/react-components/src/Table/Table.tsx
- Payout Modal now renders AddressMini in columns again 
- Network selection displays in non-UPPERCASE
- Cleanup to Table border selection (w/ revert of color change in index.html)
- Tables now have the correct bottom-margin (none) for for equal split rows
> Misc. small fixes

- packages/react-components/src/AddressInfo.tsx
- packages/react-components/src/DemocracyLocks.tsx
- packages/react-components/src/Popup/PopupWindow.tsx
- packages/react-components/src/StakingUnbonding.tsx
- packages/react-components/src/Tooltip.tsx
... we should really just drop the Tooltip component or rather create one where we can re-use other logic from Popup.
(We need both, but they both come up, have arrows, have placement - the only difference is click vs hover)
> Adjust popup  & tooltip spacing

- packages/apps-routing/src/staking.ts
- packages/page-preimages/src/Preimages/Call.tsx
- packages/react-hooks/src/useWeight.ts
Also _may_ work-around the issue that was attempted in https://github.com/polkadot-js/apps/pull/8547 (which still having decent support for feature-detection)
Closes https://github.com/polkadot-js/apps/pull/8547
> Adjust for shared default show/check address

- packages/react-components/src/InputBalance.tsx
Closes https://github.com/polkadot-js/apps/issues/8736
The reproduction supplied in https://github.com/polkadot-js/apps/issues/8743 did the trick.
> Balance unit detection with pre-defined values

- packages/page-explorer/src/Latency/index.tsx
Hail-Mary for https://github.com/polkadot-js/apps/issues/8745 (At best it still works as expected on _my_ machine)
> Render latency charts in order (nextTick delay)

- packages/page-democracy/src/Overview/ProposalCell.tsx
Picked up as part of https://github.com/polkadot-js/api/pull/5413
> Ensure correct preimage is used for democracy

- packages/apps/src/Apps.tsx
- packages/apps/src/Content/index.tsx
- packages/apps/src/Endpoints/Group.tsx
- packages/apps/src/Endpoints/Network.tsx
- packages/apps/src/Endpoints/Url.tsx
- packages/apps/src/Endpoints/index.tsx
- packages/apps/src/Menu/ChainInfo.tsx
- packages/apps/src/Menu/Grouping.tsx
- packages/apps/src/Menu/Item.tsx
- packages/apps/src/Menu/NodeInfo.tsx
- packages/apps/src/Menu/index.tsx
- packages/apps/src/TopBar.tsx
- packages/apps/src/overlays/Base.tsx
This is a log of dog work going through everything. However we do gain the actual prop types starting to work correctly. So it is a longer-term effort to convert all, but will be worth it at the end of it.
Here we just do `packages/apps`
> Start non-wrapping of components with styled.div

- packages/page-staking/src/Actions/Account/Nominate.tsx
- packages/page-staking/src/Actions/Account/Unbond.tsx
- packages/page-staking/src/Actions/Account/index.tsx
- packages/page-staking/src/Actions/partials/Nominate.tsx
- packages/page-staking/src/Bags/Stash.tsx
- packages/page-staking/src/Legend.tsx
- packages/page-staking/src/Payouts/PayButton.tsx
- packages/page-staking/src/Payouts/index.tsx
- packages/page-staking/src/Pools/Pool.tsx
- packages/page-staking/src/Query/Chart.tsx
- packages/page-staking/src/Query/Validator.tsx
- packages/page-staking/src/Targets/Nominate.tsx
- packages/page-staking/src/Targets/Summary.tsx
- packages/page-staking/src/Targets/index.tsx
- packages/page-staking/src/Validators/Summary.tsx
- packages/page-staking/src/index.tsx
Same application as in https://github.com/polkadot-js/apps/pull/8793
> Rework staking styled injection

- packages/apps/src/Menu/Item.tsx
- packages/page-claims/src/Claim.tsx
- packages/page-claims/src/Warning.tsx
Additionally it coverts (some more) hard-coded font-size to css variables
> Remove menu hover size adjustment

- packages/apps-routing/src/fellowship.ts
- packages/apps-routing/src/referenda.ts
- packages/apps/src/endpoint.ts
Closes https://github.com/polkadot-js/apps/issues/8820
> Disable referenda app where no tracks are defined

- packages/apps-routing/src/index.ts
- packages/apps-routing/src/staking2.ts
- packages/apps/src/Apps.tsx
- packages/page-staking/src/index.tsx
- packages/page-staking2/LICENSE
- packages/page-staking2/README.md
- packages/page-staking2/package.json
- packages/page-staking2/src/Validators/Validator.tsx
- packages/page-staking2/src/Validators/index.tsx
- packages/page-staking2/src/Validators/useExposure.ts
- packages/page-staking2/src/Validators/usePoints.ts
- packages/page-staking2/src/constants.ts
- packages/page-staking2/src/index.tsx
- packages/page-staking2/src/translate.ts
- packages/page-staking2/src/types.ts
- packages/page-staking2/src/useSessionInfo.ts
- packages/page-staking2/src/useValidatorsActive.ts
- packages/page-staking2/tsconfig.build.json
- packages/react-components/src/Table/Column/Balance.tsx
- tsconfig.base.json
- yarn.lock
Replaces https://github.com/polkadot-js/apps/pull/8717
(Still the same approach, test of a layout adjustment - just in a separate location to keep track of it in the repo)
1. Aligns the UI in terms of layout
2. Re-imagine the different staking parts (instead of all-at-once do retrievals as required only)
> Staking test app

- packages/apps-config/src/endpoints/productionRelayKusama.ts
New  Bridge hub kusama parachain will be released soon:  https://github.com/paritytech/cumulus/pull/1999
> New parachain for Kusama

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
delete onfinality ajuna endpoint
> deleted onfinality ajuna endpoint

- packages/page-referenda/src/Referenda/RefOngoing.tsx
- packages/react-hooks/src/types.ts
- packages/react-hooks/src/usePreimage.ts
This is a current gap that I knew about, but forgot about until making this comment - https://github.com/polkadot-js/apps/pull/8842#issuecomment-1396436143
> Make usePreimage deal with inline calls

- packages/page-alliance/src/Members/Member.tsx
- packages/page-alliance/src/Members/index.tsx
- packages/page-alliance/src/useMembers.ts
Closes https://github.com/polkadot-js/apps/issues/8841
> Remove founding alliance role

- packages/page-explorer/src/Api/index.tsx
- packages/page-explorer/src/Latency/Chart.tsx
- packages/react-hooks/src/ctx/ApiStats.tsx
Closes https://github.com/polkadot-js/apps/issues/8854
> Fix API stats graph

- packages/apps-config/src/endpoints/testingRelayWestend.ts
Dear @jacogr, dear team, 
For your consideration, this request aims to add an endpoint for the Westend network only, as agreed in the previous PR #8852.
Many thanks for your kind guidance on this!
Best regards
Miloš
> Add Westend endpoint - IBP Network

- packages/page-referenda/src/Referenda/RefOngoing.tsx
- packages/react-hooks/src/usePreimage.ts
Since we actually have some on-line data to test with, round out
> Add missing inline preimage conditions

- packages/apps-config/src/links/index.ts
- packages/apps-config/src/links/polkastats.ts
Closes https://github.com/polkadot-js/apps/issues/8903
> Remove unmaintained external links

- packages/react-components/src/InputAddress/index.tsx
Closes https://github.com/polkadot-js/apps/issues/8923
> Limit address inputs based on keyring type

- packages/page-referenda/src/util.ts
Closes https://github.com/polkadot-js/apps/issues/8938
> Adjust Reciprocal calculations

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Follow-up for https://github.com/polkadot-js/apps/pull/8929
> Small linting fixes

- packages/page-parachains/src/Teleport.tsx
Closes https://github.com/polkadot-js/apps/issues/8958
> Fix teleport chain dropdown

- packages/apps-config/src/links/statescan.ts
We released statescan-v2, and the urls are changed.
> Correct statescan external links

- packages/apps/src/Root.tsx
- packages/page-bounties/test/pages/bountiesPage.tsx
- packages/react-components/src/InputAddress/createItem.tsx
- packages/react-components/src/InputAddress/index.tsx
- packages/react-hooks/src/ctx/Keyring.tsx
- packages/test-support/src/pages/Page.tsx
Closes https://github.com/polkadot-js/apps/issues/8978
> Defer keyring init until chain type is available

- packages/apps/webpack.base.cjs
We are assuming that webpack itself can do a better job than us...
> Auto chunking

- packages/apps-config/src/links/subscan.ts
https://kusama.subscan.io/fellowship/23
https://kusama.subscan.io/referenda_v2/93
> feat: subscan support fellowship, referenda v2

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
New Polkadot Common Good Parachain: Bridgehub
> Add Polkadot Bridgehub

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- Update endpoint
- Make reachable
> make pendulum reachable

- packages/apps-config/src/endpoints/testingRelayRococo.ts
Changelog:
Update the new url for tangle-rococo
> [fix] update tangle rococo url

- packages/apps-config/src/links/statescan.ts
Add external links for litmus, collectives and westend collectives.
> Add statescan external links for more chains

- packages/apps-config/src/endpoints/testingRelayRococo.ts
- add polkadex testnet (kazien) parachain to rococo
> add kaizen endpoint to apps-ui

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
Pinknode has stopped providing public endpoint services.
> Removed pinknode enpoints.

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Bringing online RadiumBlock Bajun RPC endpoint
> RadiumBlock Bajun RPC endpoint

- packages/apps-config/src/settings/ethereumChains.ts
Added Pangoro2 on the ethereumChains
> ethereumChains updates

- .github/workflows/chain-endpoints.yml
- packages/apps-config/src/ci/chainEndpoints.spec.ts
Closes https://github.com/polkadot-js/apps/issues/9112
Doesn't address checks above, however the `ws` class behavior is different on close (plus makes the hook fail)
> Adjust endpoints tests

- packages/apps-routing/src/teleport.ts
- packages/react-components/src/styled.ts
As per https://github.com/polkadot-js/apps/issues/9127
> Disable teleports (no detection on versions)

- packages/apps-routing/src/preimages.ts
Closes https://github.com/polkadot-js/apps/issues/9130
> Check statusFor in addition to notePreimage for preimage app avail

- packages/apps-config/src/links/polkassembly.ts
> Added link to fellowship referendum for polkassembly

- packages/apps-config/src/endpoints/production.ts
> removed Darwinia Crab network

- packages/react-components/src/SortDropdown.tsx
Closes https://github.com/polkadot-js/apps/issues/8766
> Fix accounts sortby label alignment issues

- package.json
- packages/apps-electron/package.json
- packages/apps/package.json
- packages/page-accounts/src/modals/Import.tsx
- packages/page-accounts/src/modals/MultisigApprove.tsx
- packages/page-accounts/src/modals/MultisigCreate.tsx
- packages/react-components/package.json
- packages/react-components/src/InputFile.tsx
- packages/react-components/src/InputWasm.tsx
- packages/react-hooks/src/useWeight.ts
- tsconfig.base.json
- yarn.lock
Closes https://github.com/polkadot-js/apps/issues/9154
> Upgrade dropzone component

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> updated Darwinia crab RPC

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
- packages/react-components/src/ChainImg.tsx
Closes https://github.com/polkadot-js/apps/issues/8960
> Show ChainImg via endpoint map

- packages/apps-config/src/settings/ethereumChains.ts
https://github.com/paritytech/frontier/tree/master/template
> Add frontier template into ethereum chains

- packages/react-params/src/Param/Vector.tsx
- packages/react-params/src/Param/findComponent.ts
Add support for BTreeSet to the UI by re-using the `Vector` component.
> Support BTreeSet.

- packages/page-accounts/src/Accounts/index.tsx
Closes https://github.com/polkadot-js/apps/issues/6570
Also mention in https://github.com/polkadot-js/apps/issues/9209 (this issue is now also mentioned in the code, aka follow the trail upwards and see what needs to be done. It doesn't seem to be an apps UI "simple fix")
> Disable multisig addition on Ethereum chains

- packages/page-accounts/src/Accounts/index.tsx
- packages/page-accounts/src/modals/MultisigApprove.tsx
- packages/page-accounts/src/modals/MultisigCreate.tsx
Needs https://github.com/polkadot-js/ui/pull/740 
Needs https://github.com/polkadot-js/api/pull/5560 (Non-critial fix, here also worked-around)
(Hence marked WIP until there is a release and the dependencies are bumped)
Closes https://github.com/polkadot-js/apps/issues/9209
Closes https://github.com/polkadot-js/apps/issues/9032
> Re-add multisigs for Ethereum

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
(endpoints have been re-introduced and are stable)
> Remove all "false positive" unreachable comments

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
Modified the UnitedBloc endpoints for all Moonbeam networks
> Modified UnitedBloc endpoints

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Update Frequency Mainnet (ParaId 2091)
Re-Add Frequency RPC Endpoint 0 after resolving issues. (https://github.com/polkadot-js/apps/issues/9231)
> Update Frequency Mainnet RPC Node 0

- packages/apps-config/src/endpoints/productionRelayKusama.ts
We need to add this archive node URL for Mangata. Thank you
> Add archive node url for mangata

- packages/apps-config/src/api/spec/mangata.ts
- packages/apps-config/src/api/typesBundle.ts
fix ordering of header items due to alphabetic sort
add rest of types
add RPC defs
run typesBundle generation
> add rest of types and rpcs for mangata chain

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
<h1>Add SORA relaychain info</h1>
> Add SORA relaychain info

- packages/apps-config/src/endpoints/testingRelayWestend.ts
Dear Devs,
I am submitting this PR on behalf of LuckyFriday for inclusion on Westend's listing.  
This in keeping with [previous guidance](https://github.com/polkadot-js/apps/pull/9236)  that listing on a testnet is a quality control requirement before being listed on mainnets.
I hope the foregoing is complete and satisfactory.
Kind Regards,
Will | Paradox
> Adding LuckyFriday to Westend

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
We need to update the Mangat's public RPC endpoints addresses in Kusama and Rococo networks.
> Update Mangata's Kusama and Rococo endpoints

- packages/apps-config/src/endpoints/testingRelayRococo.ts
> Basilisk rococo RPC moved

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Hi @jacogr,
I've been stable on westend for three weeks (#9249) and now would like to add kusama if thats ok with you.
Regards
Max | Stakeworld
> Add stakeworld kusama rpc node

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Hi @jacogr,
I've been stable on westend and kusama and also would like to add polkadot, if thats ok. 
Regards
Max | Stakeworld
> Add stakeworld polkadot rpc node

- packages/apps-config/src/settings/ethereumChains.ts
This PR adds subspace evm domain to the ethereum chain list
> add subspace evm domain into ethereum chains

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> Chore: Update Mangata Kusama endpoints

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Added Dwellir endpoint for Kapex
> Added Dwellir endpoint for Kapex

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Bring online RadiumBlock Collectives endpoint
> Adding RadiumBlock Collectives endpoint

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Added Dwellir endpoint for Interlay
> Added Dwellir endpoint for Interlay

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
Hi @jacogr,
We have been stable on polkadot, kusama and westend for a while and would also like to include statemine/statemint and westmint.
I have an open issue #9532, if thats a blocking issue then of course its beter to delay merging untill it's resolved. 
Regards
Max | Stakeworld
> Add stakeworld statemine/statemint/westmint rpc nodes

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> Add the krest network's url

- tsconfig.base.json
Reverts base https://github.com/polkadot-js/dev/pull/1074
While we will have fixes from https://github.com/polkadot-js/common/pull/1843 & https://github.com/polkadot-js/ui/pull/765 we are not quite ready to "just apply it" inside apps
> Add tsconfig override

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
This PR will update the Polkadex Parachain endpoint.
> Updated Polkadex Parachain endpoint 

- packages/page-referenda/src/Referenda/Delegate/index.tsx
- packages/react-hooks/src/types.ts
- packages/react-hooks/src/useTxBatch.ts
Closes https://github.com/polkadot-js/apps/issues/9605
> Apply useBatchTx to gov2 delegation

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Hi @jacogr 
We would like to add our encointer endpoint.
Regards Max | Stakeworld.io
> Add stakeworld encointer endpoint

- packages/apps-config/src/endpoints/testing.ts
This will update thebifrost(testnet)'s providers url.
> Update testnet providers url. (thebifrost network)

- packages/apps-config/src/api/spec/imbue.ts
- packages/apps-config/src/api/typesBundle.ts
sorry @jacogr missed one commit! 😅
> add missing specs

- packages/apps-config/src/endpoints/testingRelayRococo.ts
> HydraDX Rococo RPC moved

- packages/apps-config/src/endpoints/production.ts
> Re-enable jelliedowl.edgeware.net

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Updated Polkadex mainnet and parachain endpoints
> Updated Polkadex mainnet and parachain endpoints

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Hello there,
We'd like to add our InvArch Tinkernet endpoint.
Thanks!
> Add Dwellir endpoint for InvArch Tinkernet

- packages/apps-config/src/endpoints/testing.ts
Adding endpoint of our recently launched network, endpoint is already live.
> Add Subspace Gemini 3f endpoint

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Onfinality got dns problem last week, please put this onfinality endpoints back, thanks
> get onfinality darwinia and kapex polkadot endpoints back

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/links/polkaholic.ts
- Bit.Country team updated the blockchain to correct name of Metaverse.Network Tewai and Metaverse.Network Pioneer
> Update Pioneer Blockchain to Metaverse.Network Pioneer 

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Please get onfinality hydradx endpoint back, we got a tech issue at that time, thanks
> please get onfinality hydradx back thanks

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> Restore Dwellir endpoint for Darwinia Crab

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Hey,
We'd like to add our endpoints for the Unique and Quartz chains.
Thanks!
> Add Dwellir endpoints for Unique, Quartz

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
...so everything displays nicely for our upcoming crowdloan (September 30th). :-)
> Add Logion parathread

- packages/apps-config/src/endpoints/production.ts
Please get onfinality Aleph Zero endpoint back. Thanks
> Add onfinaliy Aleph zero endpoint

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
We'd like to add our OriginTrail endpoint, thanks!
> Add Dwellir endpoint for OriginTrail

- packages/apps-config/src/endpoints/testingRelayRococo.ts
Update public rpc url for Energy Web testnet
> Energy Web Testnet RPC

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Hi @jacogr,
I want to add an extra RPC endpoint for Metaverse.Network Pioneer. 
Thank you.
> Add Extra Metaverse Network Pioneer RPC

- packages/page-contracts/src/Codes/Code.tsx
- packages/page-contracts/src/Codes/ValidateCode.tsx
- packages/page-contracts/src/Contracts/Summary.tsx
#9901 - Fix issue with Contracts tab for polkadot-v1.0.0 based chain
https://github.com/polkadot-js/apps/issues/9901
> #9901 - Fix issue with Contracts tab for polkadot-v1.0.0 based chain

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Add new provider
* bifrost-polkadot Europe provider
* bifrost-kusama USA provider
> add: liebi new providers

- packages/apps-config/package.json
- packages/apps-config/src/api/typesBundle.ts
- yarn.lock
We have new major update regarding mangata type definitions.
> feat: update mangata type definitons to new major version

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
See our public announcement for more details: https://forum.polkadot.network/t/scaling-down-of-parity-s-public-infrastructure/4697
> Remove Parity's Polkadot and Kusama RPC providers

- packages/apps-config/src/settings/ethereumChains.ts
Add innovatorchain as evm type chain for correct address formatting.
> Add innovatorchain in evm chains

- packages/apps-config/src/endpoints/productionRelayKusama.ts
added new providers for krest network in Kusama
> Update krest network providers

- packages/apps-config/src/endpoints/testing.ts
> Add Subspace Gemini-3g Nova testing rpc

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Dear team,
Please find attached our request for inclusion of our Acala RPC node to the repo.  The node has been running for several weeks without error.
Kind Regards,
Will | Paradox
> Added LuckyFriday's Acala node

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Dear team,
Please find attached our request for inclusion of our Karura RPC node to the repo.  The node has been running for several weeks without error.
Kind Regards,
Will | Paradox
> Adding LuckyFriday's Karura wss node

- packages/apps-config/src/endpoints/testingRelayRococo.ts
New Rococo parachain: Coretime
> Add rococo coretime parachain rpc

- packages/apps-config/src/settings/ethereumChains.ts
Add masverse as evm type chain for correct address formatting.
> Add masverse node

- packages/apps-config/src/endpoints/testingRelayRococo.ts
> Update Litentry rococo-parachain endpoint

- packages/apps-config/src/endpoints/production.ts
Ternoa websocket is reachable.
> Ternoa websocket

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Adds the public websocket RPC for Energy Web X provided by Energy Web
Please review and merge. Thank you
> Add public RPC endpoint for Energy Web X

- CHANGELOG.md
Few minor fix, doesn't require testing or changelog entry.
Have a nice week-end.
> Fix grammatical errors in changelog

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Fixed urls for genshiro & equilibrium nodes
> Fixed urls for genshiro & equilibrium

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Added RadiumBlock Watr endpoint to productionRelayPolkadot.ts
> Add RadiumBlock endpoint to Watr - Update productionRelayPolkadot.ts

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> return DAO IPCI endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
[Yerba Network](https://github.com/polkadot-js/apps/pull/9908) launches on Kusama!
(this PR adds name+logo, endpoints to be added in a follow-up PR)
> Add Yerba Network to Kusama

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
<p>I've just added SORA Polkadot Parachain node</p>
> Add SORA Polkadot Parachain node

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Reverts polkadot-js/apps#10190
Sorry for the trouble but we want to add it again :)
> Revert "Update productionRelayPolkadot.ts"

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Hello,
We'd like to update our Polkadex endpoints.
Cheers
> Dwellir: update Polkadex parachain, add Polkadex mainnet

- packages/apps-config/src/endpoints/testingRelayRococo.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
> Add people parachain RPC

- packages/apps-config/src/settings/ethereumChains.ts
This PR introduces the integration of the **Laos runtime**, an Ethereum-based blockchain, into the Polkadot.js ecosystem.
**Upcoming Migration Plans**: Prepared the groundwork for the upcoming chain name migration. This PR includes provisional adjustments that will ease the transition to the new chain name, ensuring a smooth update process for users once the rebranding is finalized.
**Chain Upgrades**: The following chains will be **upgraded to the Laos runtime**:
- KLAOS (on Kusama Network): [KLAOS Explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.klaos.laosfoundation.io#/explorer)
- Giedi (on Rococo Network): [Giedi Explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.giedi.laosfoundation.io#/explorer)
> Integrate Laos Chain as Ethereum-Based Chain

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
<p>I've just replaced current nodes with archive nodes for SORA Kusama and Polkadot parachains</p>
> Use archive nodes for SORA Kusama and Polkadot parachains

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
> Add IBP endpoints to Paseo

- packages/apps-config/src/endpoints/testingRelayWestend.ts
New Westend parachain: Coretime
> Add westend coretime parachain RPC

- packages/apps-config/src/endpoints/production.ts
Add separate entries for my RPCs in preparation for retiring the load balancer
> Reorganise Edgeware RPCs

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
This PR aims for add the metadata for Polkadex crowdloan. From this, it is easier for contributors to find our crowdloan as we opened it under new parachain id 3363.
> Add Metadata for Polkadex crowdloan

- packages/apps-config/src/endpoints/production.ts
See also comment on issue #10289
> Re-enable JelliedOwl Edgeware

- packages/apps-config/src/endpoints/production.ts
Since the WSS endpoint was updated, I am providing an update.
> Update 3dpass provider endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Add [Kippu](https://kippu.rocks)'s Websockets RPC endpoint for [Kreivo](https://github.com/virto-network/virto-node): `wss://kreivo.kippu.rocks`
> Add Kippu rpc endpoint for Kreivo

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Hello,
We've noticed that this entry was removed from Polkadot.JS; we've since retested the endpoint and it appears to be in working order.  Kindly confirm and re-add if there aren't any issues.
Regards,
Will
> Enable LuckyFriday Bridgehub

- packages/apps/src/Endpoints/index.tsx
- packages/apps/src/overlays/LocalFork.tsx
- packages/react-api/src/Api.tsx
- packages/react-api/src/types.ts
- packages/react-hooks/src/ctx/types.ts
issue: #10305
This pr removes the perisitent local fork mode
> fix: make local fork non persistent across sessions

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> Adding RockX endpoint

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Dear team, 
Please consider this PR to add the endpoint from the Infrastructure Builders Programme serving the Paseo network:
- wss://rpc.ibp.network/paseo
Many thanks!
**_Milos_**
> add Paseo's IBP endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Thank you so much for the kind support.
> Change Xode RPC address

- packages/page-collator/src/useCollators.ts
closes: https://github.com/polkadot-js/apps/issues/10322
> Fix Collator call for compatibility

- packages/apps-config/src/endpoints/testing.ts
1. Update Creditcoin 2.5 (PoS) Testnet
2. Add Creditcoin 3.0 (EVM) Testnet
> Update Creditcoin Testnet Details

- packages/apps-config/src/links/subscan.ts
- Paseo: 
https://paseo.subscan.io/
- Opal: 
https://opal.subscan.io/
> Add Subscan link to Paseo and Opal testnet

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Requesting an update to the endpoint we serve the Nodle parachain on.
Thanks
> Update Dwellir Nodle RPC endpoint

- packages/apps-config/src/endpoints/testing.ts
Due to an certificate failure the server was down. Its fixed now.
> Uncommented the provider for Phyken Network

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Adding RockX phala/khala endpoints
> Adding RockX phala/khala endpoints

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Found a copy paste bug that my eyes glazed over several times apparently.
> Fix provider name

- packages/apps-config/src/endpoints/production.ts
closes: https://github.com/polkadot-js/apps/issues/10411
> Disable unreachable endpoint

- packages/apps-config/src/api/typesBundle.ts
Changes from my previous PR (https://github.com/polkadot-js/apps/pull/10347) were removed by this commit https://github.com/polkadot-js/apps/commit/98e148b97265e8853a23fb0f9de4c3fa279001d9
> Peerplays types bundle

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Greetings,
We'd like this endpoint added for Paseo.
Cheers
> Add Dwellir paseo-rpc endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Hey,
We'd like this endpoint added for the Encointer Kusama parachain.
Cheers
> Add Dwellir encointer-kusama-rpc endpoint

- packages/react-hooks/src/useBlockInterval.ts
Follow up from https://github.com/polkadot-js/apps/pull/10456#discussion_r1559407903
> use runtime APIs to query block time

- packages/react-params/src/valueToText.tsx
Re adds a comment removed in https://github.com/polkadot-js/apps/pull/10475
> Add removed comment from valueToText

- packages/apps-config/src/endpoints/productionRelayKusama.ts
tested XCMv4 teleporting with success both ways after runtime 1002000 upgrade
> make encointer teleporter again

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Howdy,
We'd like to add this endpoint for AssetHub Paseo.
Cheers
> Add Dwellir asset-hub-paseo-rpc endpoint

- packages/apps-config/src/endpoints/testing.ts
Simple PR to update Dancebox endpoint
> Update Dancebox Endpoint

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Simply adds an additional endpoint.
> chore(pop): add rpc

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
Hello there,
We'd like to update the endpoints of our AssetHub nodes.
Thanks
> Dwellir: update AssetHub endpoints

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Soon, Kusama people will be launched:  https://kusama.polkassembly.io/referenda/384
People-kusama RPC is already available.
> Add people-kusama RPC

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
1. added ajuna polkadot rpc
2. removed ajuna rpc rococo
> added ajuna polkadot rpc

- packages/page-assets/src/Balances/index.tsx
- packages/page-assets/src/index.tsx
closes: https://github.com/polkadot-js/apps/issues/10573
@nuel77 Do you mind testing this out and confirming that it fixes your issue?
> Fix polkadex assets balances page

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
As winner of a slot LAOS is now active and ready to produce blocks
> added LAOS provider

- packages/page-assets/src/Balances/useBalances.ts
closes: https://github.com/polkadot-js/apps/issues/10476
Adds filtering to any `null` `id`.
> Filter assets before multi call

- packages/apps-config/src/endpoints/productionRelayKusama.ts
I would like to add a coretime rpc endpoint
> Stakeworld coretime rpc endpoint

- packages/react-api/src/Api.tsx
This ensures system chains on polkadot query the relay chain for identities.
> Fix identities for polkadot system chains

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> Add IBP2 to hydradx endpoints

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
**WHAT**
- Change Aventus RPC's urls
cc @nahuseyoum
> [CHORE] change Aventus public rpc endpoints

- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/endpoints/testingRelayPaseo.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
clean up and transitioned from rococo bajun to paseo bajun
> added paseo bajun rpc, removed bajun rococo & ajuna test

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Greetings,
We'd like to add our Coretime Kusama RPC endpoint.
Thanks!
Jakob
> Add Dwellir Coretime Kusama endpoint

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
Added some active Dwellir endpoints that had fallen out at various times.
> [endpoints] Adjusted some Dwellir endpoints.

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayRococo.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
Hello there,
We're doing some work to streamline naming of our endpoints, please let this change in.
Cheers,
Jakob
> Update Dwellir Bridge Hub and Collectives endpoints

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
Hi,
We'd like to add our People Westend and People Kusama RPC endpoints.
:wave:  Jakob
> Add Dwellir People Westend and People Kusama endpoints

- packages/page-parachains/src/Parathreads/RegisterThread.tsx
closes: https://github.com/polkadot-js/apps/issues/10668
cc: @DrW3RK
> Fix wasm.length to use parasConfig.maxCodeSize

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Related: https://github.com/polkadot-js/apps/issues/10663 https://github.com/polkadot-js/apps/issues/1066 https://github.com/polkadot-js/apps/issues/9861
> Add Darwinia and Crab Dcdao RPC

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Good day!
We'd like to update our Neuroweb endpoint on the site.
Thanks!
Jakob
> Dwellir: update Neuroweb endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Due to increase in demand we had to add more capacity to stabilize the endpoints.
> RadiumBlock would like to bring back our Khala and Ajuna endpoints in Curie

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Add additional RPC endpoints for Crust Mainnet, Crust-Parachain, Crust-Shadow to provide more choices and more stable services for users.
> Add additional RPC endpoints for Crust Mainnet, Crust-Parachain, Crust-Shadow

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
https://polkadot.polkassembly.io/referenda/972
RPC  endpoint is up
> add polkadot People parachain

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
This PR adds Muse testnet to Paseo.
> Add muse-paseo

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Added LuckyFriday provider to UI for Coretime KSM and People KSM
> Update productionRelayKusama.ts adding LuckyFriday provider to UI

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Please consider adding RadiumBlock Bifrost Polkadot endpoint.
> Add RadiumBlock Bifrost wss endpoint

- packages/react-components/src/AccountName.tsx
Closes https://github.com/polkadot-js/apps/issues/10784
> Change the rendering of chains' Sovereign Accounts

- packages/page-settings/src/useRawMetadata.ts
closes: https://github.com/polkadot-js/apps/issues/10802
> Ensure useRawMetadata checks for metadata call

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
https://polkadot.polkassembly.io/referenda/1107
RPC endpoint is up
> add polkadot coretime parachain

- packages/react-components/src/InputNumber.tsx
- packages/react-signer/src/SignFields.tsx
closes: https://github.com/polkadot-js/apps/issues/10864
revert https://github.com/polkadot-js/apps/pull/10862
> Revert #10862

- packages/apps-config/src/endpoints/production.ts
- packages/react-api/src/Api.tsx
closes: https://github.com/polkadot-js/apps/issues/10868
> Fix identity for live networks

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/testing.ts
Renaming Credictoin Classic to CC Enterprise
> feat: rename Creditcoin Classic to CC Enterprise

- packages/page-broker/src/Overview/Summary/RegionLength.tsx
- packages/page-broker/src/Overview/Summary/RenewalPrice.tsx
- packages/page-broker/src/Overview/index.tsx
- packages/react-hooks/src/useBrokerStatus.ts
- packages/react-hooks/src/useCurrentPrice.tsx
- packages/react-hooks/src/useRenewalBump.ts
- packages/react-query/src/BrokerStatus.tsx
Polkadot Coretime hasnt started being sold yet, hence no data is coming through. 
I added placeholders for the missing data.
> Fix: Error on Coretime on Polkadot due to no data coming from Coretime API 

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Includes an RPC for Paseo's coretime parachain.
> chore: add paseo coretime  RPC

- packages/apps-config/src/endpoints/testing.ts
<p>Hello! I've just updated the list of endpoints for the SORA testnet because the previous will have less resources.</p>
> Update endpoints for SORA testnet

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Frequency OnFinality node is back online now
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ffrequency-polkadot.api.onfinality.io%2Fpublic-ws#/explorer
> Enable OnFinality for 2091

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayPaseo.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
Hello,
We're migrating from using paths to subdomains. This PR is to update the IBP2 entries in PJS to the new subdomain format.
Thanks!
> Migrate IBP2 endpoints from path to subdomains

- packages/apps-config/src/endpoints/productionRelayKusama.ts
> Update Zero Canary Endpoints for productionRelayKusama.ts

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Parallel: wss://polkadot-parallel-rpc.parallel.fi
> Add the official RPC for parallel network

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
This PR is a request to add watr network (paseo) to polkadotjs
> Add watr to paseo

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
this PR is to add xode paseo network to polkadotjs
> Add xode to paseo polkadotjs

- packages/apps-config/src/api/spec/shibuya.ts
- packages/apps-config/src/endpoints/testing.ts
Attempt to make Shibuya have identity option in the UI.
> Allow identity on Shibuya

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testing.ts
- packages/apps-config/src/endpoints/testingRelayPaseo.ts
- packages/apps-config/src/endpoints/testingRelayWestend.ts
A lot of Radium Blocks are down and have been down for a while 🤷🏽‍♀️ 
Closes #11098 #11096 #11095 #11094 #11093 #11092 #11089 #11086 #11080 #11077 #11076 #11074 #11072 #11068 #11064
> disabled endpoints #11098

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Add IBP2 endpoint for invarch & acala
> Add IBP2 endpoint for invarch & acala

- packages/apps-config/src/endpoints/production.ts
Re-enable a node and update the location of another
> Update Edgeware nodes

- packages/apps-config/src/endpoints/testing.ts
Add Autonomys Taurus EVM testnet to test networks.
> Add Autonomys Taurus EVM testnet endpoints

- packages/apps-config/src/endpoints/productionRelayKusama.ts
- packages/apps-config/src/endpoints/testing.ts
There are some endpoints which are unreachable, so we are commenting it out.
> Disable unreachable RPC endpoints

- packages/page-runtime/src/Runtime/Selection.tsx
- packages/react-params/src/Param/Bytes.tsx
- packages/react-params/src/Param/index.tsx
- packages/react-params/src/ParamComp.tsx
- packages/react-params/src/index.tsx
- packages/react-params/src/types.ts
This PR aims to fix `transactionPaymentApi` Runtime API in any chain from the developer tab the following error is returned:
```
4003: Client error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed WASM backtrace: error while executing at wasm backtrace: 0: 0x9be8 - <unknown>!rust_begin_unwind 1: 0x319c - <unknown>!core::panicking::panic_fmt::hbb5a6b42001bdfec 2: 0x5730f1 - <unknown>!TransactionPaymentApi_query_fee_details
```
https://github.com/user-attachments/assets/5d8c7da1-8a0d-4435-b6fd-21dd347beabb
https://github.com/user-attachments/assets/77e448d2-a9a3-47ff-b18c-aefe7e3d552b
`0x550284002534454d30f8a028e42654d6b535e0651d1d026ddf115cef59ae1dd71bae074e0044d8b9975b8f64aa8af5e1710cc23f6e5daa177f62f1aa03ec5dff1785b35cd70960be9cf4d2fd2ba …
> fix: transactionPaymentApi issue

- package.json
- packages/apps-electron/package.json
- packages/apps/package.json
- yarn.lock
Increases test runner performance, and includes fixes for deno builds.
> Bump dev to 0.83.2

- packages/apps-config/src/endpoints/testing.ts
This PR handle the changes to update to the old Allfeat Testnet (Harmonie) to the new one (Melodie).
> update allfeat testnet

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/productionRelayKusama.ts
This PR aims to fix the unreachable endpoints.
> fix: disable unreachable endpoints

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayPaseo.ts
This PR aims to disable unreachable endpoints.
> chore: disable unreachable endpoints

- packages/react-hooks/src/useCoretimeInformation.ts
- Fixed not showing "renewed"
- Added what core the chain was renewed on.
> fix: showing what core the chain is renewed on

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Update paraid for xode testnet
> Update xode paraid in Paseo

- packages/apps-config/src/endpoints/production.ts
This PR adds an @latent-to endpoint to the Bittensor public endpoints.
> Add LH ws to bittensor

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Add IBP2 as mythos RPC provider
> Add IBP2 as mythos RPC provider

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Hi, this PR updates the para_id and rpc provider.
New para_id: 4683
New provider: wss://rpc2-paseo.xcavate.io
Thank You!
> update para id and providers

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
- packages/apps-config/src/endpoints/testingRelayPaseo.ts
> Update Heima parachain endpoints

- packages/apps-config/src/links/subscan.ts
add heima network link:
https://heima.subscan.io/
> Update subscan.ts - add heima network

- packages/apps-config/src/api/spec/peerplays.ts
Add Technical committee manager API to the types bundle
> Update Peerplays types bundle

- packages/react-signer/src/Address.tsx
> Fix multisig when the proxy pallet is not available

- packages/apps-config/src/endpoints/production.ts
3dpass network RPC address was migrated
> fix: update 3dpass rpc endpoint

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Adding Xcavate Chain into the Polkadot
> adding xcav into polkadot

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Add Helixstreet RPC Endpoint for the Kusama People Chain
> Kusama People Chain -> Helixstreet RPC Endpoint added

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Dear team, hello!
Please consider this pull request to add an endpoint to the `xcavate polkadot` parachain.
This endpoint is provided by the Infrastructure Builders Programme as part of its commitments to the ecosystem.
Many thanks!!
Best regards!
**_Milos_**
> Add IBP endpoint to Xcavate Polkadot

- packages/apps-config/src/endpoints/productionRelayPolkadot.ts
Endpoints are operational and I would like to include them in polkadot.js.
> Stakeworld endpoints for polkadot coretime and polkadot people

- packages/apps-config/src/endpoints/productionRelayKusama.ts
Kippu's node is back up again!
> Restore Kippu's node in Kreivo provider

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Pls help review @ap211unitech @valentinfernandez1
> chore: reenable peregrine RPC

- packages/apps-config/src/endpoints/testingRelayPaseo.ts
Dear team, hello,
Please consider this pull request to add endpoints served by the Infrastructure Builders Programme to the new PassetHub (Contracts) System Chain of the Paseo testnet.
(the second url is still being provisioned and will be activated in a separate PR)
Many thanks!
Best regards
**_Milos_**
> Add `passet-hub` Paseo endpoint by IBP

- packages/apps-config/src/endpoints/production.ts
We are moving on from onFinality to our own node deployed for our user. We have updated the changed endpoint in file production.ts
> Polkadex updated end point

- packages/apps-config/src/endpoints/production.ts
- packages/apps-config/src/endpoints/testing.ts
Small modification to Tanssi endpoints as they were moved to new production URLs
> Update Tanssi Endpoints

- packages/apps-config/src/endpoints/production.ts
Add Autonomys EVM mainnet endpoint
> Add Autonomys EVM mainnet endpoint

- packages/apps-config/src/endpoints/productionRelayKusama.ts
This PR is a request to add the RegionX Kusama parachain to Polkadot.js.
> Add RegionX Kusama

- packages/page-js/src/snippets/rpc-examples.ts
> chore: remove redundant word

- packages/react-components/src/AddressInfo.tsx
This PR aims to improve the tooltip UI for vesting component.
> Enhance tooltip styling and content in Vesting component
