README.md

Allows a user to run a Polkadot Node that's connected to PoC-1 Testnet with `polkadot --chain=poc-2 --ws-port=8081` and then connect to it via WebSockets from the polkadot-js apps portal front-end with `WS_URL=wss://poc-1.polkadot.io:9944 yarn run start`

docs: Fixes #77 by updating README with dev setup instructions

---

packages/app-accounts/src/Editor.js
packages/ui-app/src/Input.js

Adding an edit icon that is embedded in the account name input field makes it more obvious to the user that the input field isn't read-only, and that there is a way to "click before doing" (i.e. editing the input field that is identified as being editable before the ability to save changes is granted). Some users may click the edit icon itself thinking it toggles the ability to edit the input field, whilst others may just recognise that the edit icon means the input field is editable. In either case just having the edit icon should suffice as being the initial "call to action" for a user wishing to edit the input field, and since the Reset and Save buttons illuminate when the account name is modified, they'll recognise that a further step is required to save their changes.
Screenshot of …

feat: Fixes #75. Add edit icon from semantic-ui to account name input field

---

README.md

To avoid issues with installation it is necessary to install a compatible version of Yarn.
It was highlighted [here](https://github.com/polkadot-js/apps/pull/78) that Yarn 1.0 included workspaces, and we are successfully using Yarn 1.3.2 for Travis CI, so propose to request users to ensure they are using a version later than that to avoid and problems.
For instance, I was using Yarn 0.24.6 and it [wouldn't install the sub-package dependencies](https://github.com/polkadot-js/apps/pull/78) nor would it [run a necessary binary](https://github.com/polkadot-js/apps/issues/98), but after upgrading to Yarn 1.7.0 those issues were resolved.

Update Readme with Yarn version requirement

---

packages/app-extrinsics/src/Extrinsic.tsx

Closes https://github.com/polkadot-js/apps/issues/147
Clear the values when the extrinsic changes. As it bubbles down the Params will re-init the values.

Clear values on extrinsics change

---

packages/ui-react-rx/package.json
yarn.lock

To merge when https://github.com/paritytech/polkadot/pull/410 is available
(Brings in https://github.com/polkadot-js/api/pull/116, based on https://github.com/paritytech/jsonrpc/pull/293)

Bump api-rx (params: null revert)

---

package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-vanitygen/package.json
packages/app-vanitygen/src/generator/generate.ts
packages/app-vanitygen/src/generator/sodium.ts
packages/app-vanitygen/src/generator/sodiumKeygen.ts
packages/app-vanitygen/src/index.tsx
packages/ui-app/package.json
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react-rx/package.json
packages/ui-react/package.json
packages/ui-signer/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/108
Seems like a speedup in vanity generation of around 10x. (Still slower than command-line version, but a step in the right direction)

sodium-wasm support

---

packages/ui-app/src/Params/valueToText.ts

Applies to queries that are made to storage @polkadot/storage/ such as staking.ts and session.ts that have type ['AccountId'].

fix: Fixes #163 Concat index before value for queries with array response

---

packages/ui-react/src/IdentityIcon/index.tsx

- Closes https://github.com/polkadot-js/apps/issues/195 - Account switch not updating icon
- Closes https://github.com/polkadot-js/apps/issues/193 - IdentityIcon can take ss58, hex & u8a (last 2 publicKey formats) inputs

Convert u8a pk to address for IdentityIcon

---

packages/ui-app/src/styles/app.css
packages/ui-app/src/styles/components.css

Adjust header styling (font-weight)

---

packages/app-democracy/package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-explorer/src/BlockByHash/BlockByHash.tsx
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-explorer/src/index.css
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/ui-app/package.json
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/styles/components.css
packages/ui-react-rx/package.json
packages/ui-signer/package.json
yarn.lock

- Updates dependencies to pull in https://github.com/polkadot-js/api/pull/138
- Closes https://github.com/polkadot-js/apps/issues/231
- Closes https://github.com/polkadot-js/apps/issues/232
- Addresses monospace alignment issue raised by @tomusdrw

Fix encoding to allow both poc-1 & poc-2 blocks

---

packages/app-democracy/package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-explorer/src/Query.tsx
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/apps/src/NodeInfo.tsx
packages/apps/src/SideBar/SideBar.css
packages/apps/src/index.css
packages/ui-app/package.json
packages/ui-react-rx/package.json
packages/ui-react-rx/src/Api/index.tsx
packages/ui-signer/package.json
yarn.lock

- Enable block explorer view links (and search) based on existence of chain_getBlock method
- Cleanup info (version, chain, best) display on SideBar
- Closes https://github.com/polkadot-js/apps/issues/246

Bring back chain_getBlock checks (disabling on explorer)

---

packages/apps/src/index.css
packages/ui-app/src/i18n.ts

- Currently the SideBar does not take up all vertical height in explorer (which is bigger than a single screen). `align-items: stretch` with `100vh` min height solves the issue. Closes https://github.com/polkadot-js/apps/issues/251
- Fix to use relative paths in i18next language pack loads. Closes https://github.com/polkadot-js/apps/issues/252

Stretch SideBar to max height, relative i18next paths

---

package.json
packages/apps/webpack.config.js

- Better parallelize JS downloads
- Don't bundle moment locales (~200K savings)
- Split libsodium into an own bundle - in this case not much that can be done, it is a WASM bundle
- Split all UI-related 3rd party libraries into single bundle
- Adjust general 3rd party libraries in vendor bundle
- Main bundle size dropped from 1.8MB initial value
Current results -
```
$ ls -al packages/apps/build/*.js             
-rw-r--r--  1 jacogreeff  staff  586532 Aug 22 16:50 packages/apps/build/main.be814289.js
-rw-r--r--  1 jacogreeff  staff  515002 Aug 22 16:50 packages/apps/build/react.f8b82fe2.js
-rw-r--r--  1 jacogreeff  staff    1494 Aug 22 16:50 packages/apps/build/runtime.74ea5d42.js
-rw-r--r--  1 jacogreeff  staff  579105 Aug 22 16:50 packages/apps/build/sodium.a8bec706.js
-rw-r--r--  1 …
```

Additional webpack splitting config

---

packages/app-democracy/src/Referendum.tsx
packages/ui-app/src/Extrinsic.tsx
packages/ui-app/src/Params/Param/Bare.tsx
packages/ui-app/src/Params/Param/Base.tsx
packages/ui-app/src/Params/Param/BaseBytes.tsx
packages/ui-app/src/Params/Param/Hash.tsx
packages/ui-app/src/Params/Param/Proposal.tsx
packages/ui-app/src/Params/Param/StorageKeyValueArray.tsx
packages/ui-app/src/Params/Param/Unknown.tsx
packages/ui-app/src/Params/Param/findComponent.ts

- Decode Proposals, Closes https://github.com/polkadot-js/apps/issues/255
- Render decoded key/values as disabled fields (issue visible in screenshot from  https://github.com/polkadot-js/apps/issues/254)
- Swap functional components in Params to PureComponent
- Add extra logging for Referendum countdown
Fixed decoding from the linked block -

Decode Proposals in block explorer

---

packages/app-democracy/src/VotingButtons.tsx
packages/ui-react/package.json
yarn.lock

- Rename"yes" button, Closes https://github.com/polkadot-js/apps/issues/271
- Update polkadot-identicon to 1.1.0 (allows for copy-and-paste of address)

yay -> aye in democracy

---

package.json
packages/app-democracy/package.json
packages/app-example/package.json
packages/app-explorer/package.json
packages/app-staking/package.json
packages/ui-app/src/CopyButton.tsx
packages/ui-app/src/InputAddress/index.tsx
packages/ui-app/src/Params/valueToText.tsx
packages/ui-app/src/styles/components.css
packages/ui-identicon/package.json
packages/ui-keyring/package.json
packages/ui-react/package.json
yarn.lock

- Allow encoding to handle both ss58 & u8a (publicKey) inputs. Closes https://github.com/polkadot-js/apps/issues/272 . This is a hold-over from the encoding changes, expected everything to come back as ss58. (However the param value is u8a, while what comes back from storage is ss58)
- Time InputAddress query values, part of https://github.com/polkadot-js/apps/issues/264
- Add `cursor: copy` to `CopyButton` - aligns with copyable `IdentityIcon`, i.e. anything where it copies to clipboard has the same cursor

Fix AccountId display in labels

---

packages/app-extrinsics/src/Selection.tsx
packages/app-extrinsics/src/index.tsx

WIP for showing users that they can't execute an extrinsic until there are accounts present. New button links to Accounts page so that users can add an account. 
Not sure if this is the correct use of <Link> for this project. 
Open to all other input - I'm newish to React, blockchain, semanticui, 
and obviously Polkadot! The copy is too wordy, maybe a note explaining that they need accounts would be better.

WIP 257 extrinsics no accounts

---

packages/app-explorer/src/SummarySession.tsx
packages/app-staking/package.json
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/Overview/index.css
packages/app-staking/src/index.css
packages/ui-app/src/Balance.tsx
packages/ui-app/src/styles/components.css
packages/ui-react-rx/src/ApiObservable/index.ts
packages/ui-react-rx/src/ApiObservable/types.d.ts

- Add available + nominated balances for validators, Closes https://github.com/polkadot-js/apps/issues/305
- Display era & session progress, Closes https://github.com/polkadot-js/apps/issues/302
- Display number of validator slots, Closes https://github.com/polkadot-js/apps/issues/306
- Adjust padding for AddressMini in these displays
- Adjust column display with article (instead of around the account itself)

Adjust staking overview display

---

packages/app-democracy/src/Referendum.tsx
packages/app-democracy/src/VotingButtons.tsx
packages/ui-app/src/styles/theme/_colors-polkadot.css
packages/ui-app/src/styles/theme/polkadot.css

Sorry for the delay, this went totally off my radar.
- Fix https://github.com/polkadot-js/apps/issues/282
- Use uppercase for `Aye` and `Nay`
- Switch button order
- Thanks to Jaco for the theme handling :)
It looks like that now:

Modify voting button and graph colors

---

packages/app-rpc/src/Selection.tsx

- Ensure params are valid before RPC submission
- Revoke previous values (as in extrinsics/chain state) when method changes
- Closes https://github.com/polkadot-js/apps/issues/316
- Replaces & Closes https://github.com/polkadot-js/apps/pull/317

Check params consistency (validity + count) for RPC app

---

packages/ui-app/src/InputNumber.spec.js
packages/ui-app/src/InputNumber.tsx

* currently user cannot enter "0 ", but this prevents user from entering a space after any digit, i.e. "3 4" or "3  " or "3   3  3  ". This bug snuck through in PR #221
* Removes second argument in another existing unit test that, since isValidNumber only accepts 2x arguments (not 3x arguments)

fix: Fixes #340 prevent spaces in InputNumber

---

packages/app-storage/src/Selection.tsx

- Closes #324 
Merges previous and next params when changing key on chain state app, fixes button disabling when switching between keys with same param type.

Fix for disabled chain state button bug

---

README.md

The minimum Node version is 10.1.0 as specified in the package.json 'engines'. The installation fails if the node version is below that (eg. v10.0.0 ), that's why I changed it in the README

Updated required Node version in README

---

packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/StakeList/Account.tsx
packages/apps/src/NodeInfo.tsx
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-keyring/src/options/KeyPair.tsx
packages/ui-react-rx/src/Api/index.tsx
packages/ui-react/src/IdentityIcon/IdentityIcon.css
packages/ui-react/src/IdentityIcon/Polkadot.tsx
packages/ui-react/src/IdentityIcon/index.tsx

- Closes https://github.com/polkadot-js/apps/issues/382
- Add isHiglight to IdentityIcon
TODOs: 
- ~~Highlight does not display in dropdown lists~~
- ~~Highlight does not display in AddressMini~~
AddressSummary -
AddressRow -
AddressMini -
Input -

[next] Highlight validators

---

packages/app-explorer/src/BlockHeader/BlockHash.tsx
packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/app-explorer/src/BlockHeader/index.tsx

Cleans up block hash mismatch issues described in https://github.com/polkadot-js/apps/issues/414
Instead of calculating the hash, it now makes a call (move overhead, slower) to retrieve the hash based on the blockNumber. In future this should be reverted again, or maybe detected to see if there is a match - if not, then use this approach.

[next] Retrieve hash instead of calculating (slower)

---

packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-staking/package.json
packages/app-storage/src/Queries.tsx
packages/app-storage/src/Query.tsx
packages/app-storage/src/Selection/Modules.tsx
packages/app-storage/src/Selection/Raw.tsx
packages/app-storage/src/Selection/index.tsx
packages/app-storage/src/index.tsx
packages/app-storage/src/types.d.ts
packages/ui-app/package.json
packages/ui-app/src/Params/Param/StorageKeyValue.tsx
packages/ui-app/src/Params/valueToText.tsx
packages/ui-react-rx/package.json
yarn.lock

Needed for https://github.com/polkadot-js/apps/issues/381 (Contracts introduce their own storage keys, thse are not part of the runtime, so now known there or in metadata - it is specific on a per-contract basis)

[next] Allow raw-key queries via the storage app

---

packages/ui-app/src/Params/Param/BaseBytes.tsx
packages/ui-signer/src/Queue.tsx

- Handle hex inputs as not having the hex prefix 
- Cancelled queue items (signer) should not block subsequent queing
- Part of https://github.com/polkadot-js/apps/issues/460.

[next] Handle byte display consistently

---

packages/ui-identicon/package.json
packages/ui-identicon/src/Demo.tsx
packages/ui-identicon/src/Empty.tsx
packages/ui-identicon/src/IdentityIcon.css
packages/ui-identicon/src/Polkadot.tsx
packages/ui-identicon/src/Substrate.tsx
packages/ui-identicon/src/index.tsx
packages/ui-identicon/src/types.ts

[next] Proper license naming for identicon

---

packages/app-storage/src/Query.tsx
packages/app-storage/src/index.css
packages/ui-app/src/Params/valueToText.tsx

Hey there,
I implemented the spread and copy buttons for the substrate.code query..
The buttons have yet no functionality because I don't understand how the queries functionality is wired. I saw some code and modules which handle this functionality and ended there: https://github.com/polkadot-js/api/blob/master/packages/type-storage/src/substrate.ts
So yes, this would be my 'first revision' approach to this issue.
Greetings,
Robin
@tomusdrw

#459 Add spread and copy buttons for substrate.code query

---

packages/app-rpc/package.json
packages/app-settings/package.json
packages/app-staking/package.json
packages/app-toolbox/package.json
packages/app-transfer/package.json
packages/apps/package.json
packages/ui-app/package.json
packages/ui-react-rx/src/Api/index.tsx
packages/ui-signer/package.json
yarn.lock

Related to https://github.com/paritytech/polkadot/pull/68
Here we have a short-term override (from settings) to first use the networkId there - it will take some time for the updated chain specs to make the rounds.
Tested, 42 now shows for Alexander and Cherry -

Allow networkId from settings defaults (Alex & CC spec overrides)

---

packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/Status/Queue.tsx
packages/ui-reactive/package.json
packages/ui-signer/src/Fees/index.tsx
yarn.lock

Includes the following changes -
- https://github.com/polkadot-js/api/issues/597 - Allows the UI to support the latest metadata
- https://github.com/polkadot-js/api/issues/588 - Allows the UI to derive accountIndexes from indices

Bump API, use derive.accounts.*, support latest substrate master

---

packages/app-accounts/src/Creator.tsx
packages/app-transfer/src/Transfer.tsx
packages/ui-params/src/Param/findComponent.ts
packages/ui-params/src/initValue.ts
packages/ui-signer/src/Modal.tsx

- Trap invalid signAndSend results due to https://github.com/polkadot-js/api/issues/598
- Allow "look like hex" raw seeds < 32 in length (reported by @jiangfuyao)
- ui-params inputs AccountIndex as a number (should actually also allow ss58 - however the previous dropdown approach didn't work at all here)
- Remove unneeded debug log in transfer app

Small fixes & tweaks

---

packages/app-democracy/src/Summary.tsx
packages/app-explorer/src/BlockHeader/index.tsx
packages/app-explorer/src/Main.tsx
packages/app-explorer/src/Summary.tsx
packages/app-explorer/src/index.css
packages/app-nodeinfo/src/Summary.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/Overview/index.css
packages/app-transfer/src/Transfer.tsx
packages/ui-app/src/styles.ts
packages/ui-app/src/styles/components.css
packages/ui-app/src/styles/form.css
packages/ui-app/src/styles/media.css

(From the still WIP `jg-ui-break` branch)
- `ui--grid` and `ui--row` now defaults to `nowrap` (this solves breaks in eg. Accounts, Closes #671)
- Hide some stuff in apps based on media-query size (ui-app/styles/media.css)
- explorer - summary items + author for a block (this solves my specific phone-view use-case)
- transfer - hide recipient on medium, sender on small - the inputs are ok-ish
- 2-column apps - on small screens lose 2-column layout (media flex)
- Half-ports, i.e. not close to 100%, but better than current master -
- linked dropdowns (e.g. chain state section  + method), has smaller sizing allowance for first item, allowing for better with overlaps on small screens, but nowhere close to perfect
Nowhere near comprehensive, these are just the forward-ported items (really quick …

Forward-port low-hanging breaks

---

packages/app-explorer/src/Events.tsx

This is just to make the UI not break.
Need to debug in API and see what happens with events, something is up.

CC breaks on events, fix for UI (need proper solution in api)

---

packages/app-explorer/src/BlockByHash/Events.tsx
packages/app-explorer/src/BlockByHash/Extrinsics.tsx
packages/app-explorer/src/BlockByHash/Logs.tsx
packages/app-explorer/src/index.css

Just adding flex on medium+ displays (as per other areas where we have 2 column layouts) - wrapping is horrible on small screens.

Explorer flex for events, extrinsics (medium+)

---

package.json

Current requirement in package.json doesn't allow to run Polkadot Apps on Node.js 11.x

Allow to run on Node.js 11.x and higher

---

packages/app-accounts/src/Backup.tsx
packages/app-accounts/src/ChangePass.tsx

- Closes https://github.com/polkadot-js/apps/issues/696
- Caused by new label placement
Modals seriously need a rework all-around...

Remove password rows on modals

---

packages/ui-app/src/InputAddress/index.tsx

Closes https://github.com/polkadot-js/apps/issues/742 - basically don't add the recent header (it is done in the background and available on the list when opened again for categorisation purposes) and since there is a single value only, it gets selected when onBlur

InputAddress selects current value (via search)

---

packages/app-js/src/Playground.tsx
packages/app-js/src/index.css
packages/app-js/src/index.tsx

Smaller quick-fixes for app-js 

---

packages/app-accounts/src/Restore.tsx

Fixes file validity check, solving #760
The encoding.content value is not just the string 'pkcs8' but an array `['pkcs8', 'ed25519']`
https://github.com/polkadot-js/common/blob/503dc99815700c79d01c09dc337c5bc8bebd38cc/packages/keyring/src/pair/toJson.ts#L20

Fix app-accounts Restore feature

---

package.json
packages/ui-api/package.json
yarn.lock

Add addition resolution overrides, for instance in the case of edgeware (https://github.com/hicommonwealth/apps/commit/28c6b911505e53afeabeb58409f0c429ecc1191b) types are being registered, however the base has an older version of the API (although compatible) and it creates havoc with the resolutions.
Force these for apps to always use the specified version as defined by apps.
cc @drewstone

Add resolution overrides

---

packages/apps/package.json

Related to https://github.com/polkadot-js/dev/pull/191 which needs to be merged before this one.
Additionally a new version of the `dev` packages needs to be published before this PR can me merged..

delete react-hot-loader devDependency

---

jest.config.js
packages/app-123code/README.md
packages/apps/webpack.config.js
scripts/findPackages.js

- Instead of having a fixed list of packages to map aliasses, read the packages/* structure and auto-add these
- Do this for both webpack.config.js and jest.config.js, i.e. no manual config needed here
- This removes some manual config from the build process, one less thing to take care of when adding own packages.
Future efforts -
- https://github.com/polkadot-js/apps/blob/master/tsconfig.json not quite, this is a json file (other options?)
Effectively anything that trims the "this is how you add stuff" README is great and just eases extensions

Auto-add all packages to webpack alias

---

packages/app-123code/src/Transfer.tsx
packages/ui-app/src/Status/Queue.tsx
packages/ui-app/src/Status/types.ts
packages/ui-app/src/TxButton.tsx
packages/ui-app/src/index.tsx
packages/ui-signer/src/ApiSigner.ts
packages/ui-signer/src/Modal.tsx

- Planning use thereof as part of https://github.com/polkadot-js/apps/issues/715
- Medium term need to start moving all submission buttons to use this (e.g. Transfer, Staking, etc.)

Move TxButton to ui-app

---

packages/ui-app/src/InputNumber.tsx

Closes https://github.com/polkadot-js/apps/issues/806 (tested on Chrome, things like Shift-2 (`@`) is still not entered.

Remove InputNumber shift check

---

packages/app-js/src/Playground.tsx
packages/app-js/src/snippets/wrapping.ts

Closes https://github.com/polkadot-js/apps/issues/831
e.g.
```js
const { Balance } = types;
const { u8aToHex } = util;
console.log(u8aToHex(new Balance(12345).toU8a()))
```
(Sadly the `toU8a()` returns a pure `Unint8Array` hence the `u8aToHex` helper above - maybe at some point we can convert all `toU8a()` on the types in `@polkadot/types` to return a `U8a`, which would allow something like
```js
const { Balance } = types;
console.log(new Balance(12345).toU8a().toHex())
```

Expose types on JS console

---

packages/app-democracy/src/Referendums.tsx

Addresses one visible issue in https://github.com/polkadot-js/apps/issues/836 - the referendum array has no values, but doesn't render "no available" (As a bonus, less RPC, cleaner overall and less logic since we only check the array of values)

Simplify referendum rendering

---

packages/app-explorer/src/BlockQuery/Query.tsx
packages/app-storage/src/index.css

Fix for #823.
Only query I'd have here is with `max-width`. Perhaps adhere to a value that other elements will stretch to also. 620px being a visually appealing amount and suitable for displaying an entire hash.

Full width storage--actionrow

---

packages/ui-reactive/src/TimePeriod.tsx

Replaces https://github.com/polkadot-js/apps/pull/867 & Closes #866 
This PR builds on @shawntabrizi 's work but caters for both the new version and the current testnet version

Support new blockPeriod

---

packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/index.css
packages/app-staking/src/types.ts

Closes #875 
Adds a lower-right badge for staking validators showing number of offline instances, which expands to message with instances and first block number. It was originally to open on hover but this seems more mobile friendly. I have combined the nominators summary and badge into a new combined child node.
Please double check that I have the mapping from recentlyOffline() through bonded() correct! At the moment there are two validators with the badge visible. Also any corrections for css/js project standards I'm not aware of :)

Add recently offline badge to validators

---

packages/app-explorer/src/NodeInfo/Summary.tsx
packages/app-explorer/src/Summary.tsx
packages/apps/src/Content/index.tsx
packages/ui-app/src/CardSummary.tsx
packages/ui-app/src/SummaryBox.tsx
packages/ui-app/src/styles/app.css
packages/ui-app/src/styles/media.css
packages/ui-app/src/styles/semantic.css
packages/ui-app/src/styles/theme/polkadot.css

Tabs:
- minimises Tabs UI 
- adds scrolling functionality to Tabs bar
Summary:
- removes scrolling functionality from summary bar
- Smaller stats on small screens
- 3 stats on small screens: room for 2 pertinent and 1 ticker
Padding:
- minimises `<Content />` padding on small screens 
- removes padding from `<main>`, with the thought of having more flexibility further down the hierarchy
- would be nice to have a full width summary bar
- would be nice to have more granular control of content padding
Before and after (so far):

Tabs Simplify and Summary Tidy-up

---

packages/app-settings/src/Developer.tsx
packages/app-staking/src/Account/Bonding.tsx
packages/app-staking/src/Account/SessionKey.tsx
packages/app-staking/src/Account/Validating.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/ui-app/src/CardSummary.tsx
packages/ui-app/src/Dropdown.tsx
packages/ui-app/src/Input.tsx
packages/ui-app/src/InputAddress/index.tsx
packages/ui-app/src/InputBalance.tsx
packages/ui-app/src/InputExtrinsic/index.tsx
packages/ui-app/src/InputFile.tsx
packages/ui-app/src/InputNumber.tsx
packages/ui-app/src/InputRpc/index.tsx
packages/ui-app/src/InputStorage/index.tsx
packages/ui-app/src/Labelled.tsx
packages/ui-app/src/Output.tsx
packages/ui-app/src/Static.tsx
packages/ui-app/src/styles/components.css

- Closes https://github.com/polkadot-js/apps/issues/892
- Used `styled-components` for `Labelled` and add help on hover
- Adds `help` (optional) prop to all inputs
- Add help strings to all dialogs in the staking app
- Display next up count, Closes https://github.com/polkadot-js/apps/issues/891
- Remove validator/intentions low/high (not applicable, not working)

Add hover help info for status dialogs

---

packages/app-staking/src/Account/SessionKey.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/index.css
packages/app-staking/src/index.tsx
packages/app-staking/src/types.ts

- Change the recentOffline map to have an array of values per account (see attached screenshot)
- Generate recentOffline with `getDerivedStateFromProps`
- Split nominators & offline rendering into own functions

recentlyOffline returns multiple entries per account

---

packages/app-staking/src/Account/Nominating.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/StakeList.tsx
packages/app-staking/src/index.tsx
packages/app-staking/src/types.ts
packages/ui-app/src/Dropdown.tsx
packages/ui-app/src/InputAddress/index.tsx

- Closes #860
- Added multiple select to dropdown & InputAddress (`isMultiple` property)
- Allow actual options to be passed to InputAddress (`options` property)
- Swap nomination dialog to use new components (Array-of-one now just becomes the multi value)
- Swap displays (overviews) to stash accounts (removing confusion - see comment in #898)

Nominate multiples

---

packages/ui-app/src/Input.tsx
packages/ui-app/src/InputNumber.tsx

Closes #886 
- Change InputNumber to default to whole unit (DOT)
- Update input value to reflect new unit when selected from dropdown
- Regex-based key/paste interception and sanitizing
- Prevent edge cases (too small or too big for max bit length)
- Distinguishes between , and . for decimal character (needs EU tester)
Originally was going to use a number input but there was some trouble with allowing region-specific decimal separators

Refined InputNumber

---

packages/app-staking/src/Account/SessionKey.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/index.css
packages/apps/src/Content/index.tsx
packages/apps/src/SideBar/NodeInfo.tsx

- Display session keys on overview, Closes https://github.com/polkadot-js/apps/issues/910
- Don't force session key for nominating, Closes https://github.com/polkadot-js/apps/issues/908
- As a bonus, remove the display of node name & version when not connected

Display session key with stashes

---

packages/app-staking/src/Overview/Address.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/styles/components.css

Sorry @kwingram25 - I KNOW this is on your list, but needed a view while trying to help. However, this is only one part, only on overview. (We still need it on accounts, which is probably more problematic since we need to display it on the stash - and query from the controller.)
- Added extraInfo to AddressSummary & AddressRow
- query bonded value from staking.ledgerr
- pass this amount through
- Part of https://github.com/polkadot-js/apps/issues/896

Display bonded amount on overview

---

packages/apps/src/Apps.tsx
packages/apps/src/SideBar/SideBar.css
packages/apps/src/SideBar/index.tsx
packages/ui-app/package.json
packages/ui-app/src/constants.ts
packages/ui-app/src/media.ts
packages/ui-app/src/styles/app.css
packages/ui-app/src/styles/media.css
packages/ui-app/src/styles/theme.ts
packages/ui-app/src/styles/theme/polkadot.css
yarn.lock

* Introduces `styled-theming`, installed in `ui-app`. `substrate` and `polkadot` themes as per `settings.uiTheme`
* `<ThemeProvider />` wraps everything in `Apps.tsx`
* media templates for `MOBILE`, `TABLET` and `DESKTOP` imported from `ui-app/src/media.ts` Media templates are "mobile first" adopting a `min-width` approach to screen sizing, following the conventions used in `media.css`.
* Converted the menu toggle media queries to styled theming
Following @jacogr guidelines to introduce `styled`  as and when files are touched.
Demonstration of embedded theme config:
```
const Toggle = styled.img`
background: ${theme('theme', {
substrate: '#333',
polkadot: 'none'
})};
padding: ${theme('theme', {
substrate: '4px',
polkadot: 'none'
})};
...
```
Demonstation of media template usage:
```
const …
```

Styled Theming + media template introduction

---

packages/ui-app/src/Input.tsx

Closes #921 
Use toLocaleString() instead of Intl to find local decimal separator

Fix Safari Intl issue

---

packages/app-123code/src/SummaryBar.tsx
packages/app-staking/src/index.tsx
packages/ui-app/src/AddressSummary.tsx

Also mentioned in watercooler. Basically since we display a placeholder for the stash (while retrieving the id), we ended up calling staking.bonded on an invalid address (inside the IdentityIcon).
Swap to the base component for invalid addresses (spacing and all others remain in-tact)

Fix errant bonded call (with invalid address)

---

packages/app-staking/src/StakeList.tsx
packages/app-staking/src/index.css

- Closes https://github.com/polkadot-js/apps/issues/862
- Not sure about the spacer hack to get the last one right, but life is too short...

2-column staking layout

---

packages/apps/src/SideBar/index.tsx
packages/apps/src/constants.ts
packages/ui-app/src/styles/media.css

Just a maintenance PR:
* `SIDEBAR_MENU_THRESHOLD` now takes `ScreenSizes.DESKTOP` value, conforming to media templates
* SideBar show/hide threshold has increased from 767px to 991px - expanding with this additional space feels more natural

sidebar <=> SrcreenSizes

---

package.json
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/index.css
packages/app-staking/src/index.css
packages/ui-api/package.json
yarn.lock

- Pulls in updated API with Consensus DigestItem support (decoding author)
- Closes #932 
Best I could come up with -
and

Re-add blocknumber for validators

---

packages/ui-reactive/src/AccountIndex.tsx
packages/ui-reactive/src/Balance.tsx
packages/ui-reactive/src/BestFinalized.tsx
packages/ui-reactive/src/BestNumber.tsx
packages/ui-reactive/src/Bonded.tsx
packages/ui-reactive/src/Chain.tsx
packages/ui-reactive/src/NodeName.tsx
packages/ui-reactive/src/NodeVersion.tsx
packages/ui-reactive/src/Nonce.tsx
packages/ui-reactive/src/TimeNow.tsx
packages/ui-reactive/src/TimePeriod.tsx
packages/ui-signer/src/Checks/Proposal.tsx
packages/ui-signer/src/Checks/Transfer.tsx
packages/ui-signer/src/Checks/index.tsx

Other projects might (hopefully) want to re-use components from apps. Right now, it's kind of hard because they need to provide a React.Context with an api object, which is not what every project wants to do.
This PR allows exporting the dumb components. Dumb components are easy to share/test/re-use, pass in props and they render correctly.
```javascript
import Chain from 'ui-reactive/Chain'; // Smart HOC'd component 
import { Chain } from 'ui-reactive/Chain'; // Dumb component
```

Allow exports of dumb components

---

packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/Overview/index.tsx
packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/CardSummary.tsx
packages/ui-app/src/RecentlyOffline.tsx
packages/ui-app/src/styles/components.css

Closes #948, rel #936 
Adds last block and portrait to staking overview summary
Also experimenting with placement of offline warning badge because I noticed it was overlapping the block label that pops up for each entry

Add last block to staking overview, reposition warning

---

packages/ui-app/src/Labelled.tsx

It was just slightly off-center, very small adjustment to make it fit. (Also tested with multi-line labels)

Label icon -> middle

---

packages/ui-app/src/Call.tsx

Adjust extrinsic hash formatting

---

packages/app-js/src/Output.tsx

so that output of
```
const { metadata } = await api.rpc.state.getMetadata();
console.log( JSON.stringify(metadata.asV3.modules.toJSON(), null, 2) );
```
in JS editor is readable

use pre tag for new line display

---

packages/apps/src/SideBar/index.tsx

Closes #1014
Restores link to new wiki ([https://wiki.polkadot.network]()) and makes external links open in new tab

Restore wiki link

---

packages/apps/src/SideBar/SideBar.css

- closes #1025 
Couldn't find any better hack than what's said in [this thread](https://stackoverflow.com/questions/20997183/how-to-hide-scrollbar-in-firefox) to make the behaviour on Firefox the same as chrome.

Hide Sidebar scrollbar on Firefox (like chrome)

---

packages/ui-app/src/Labelled.tsx
packages/ui-app/src/styles/app.css

- closes #1024
It turned out to be more complex than I expected. TL;DR It was due to the fact that a parent element had an `opacitiy`<1 in our case the `label` and also had a z-index. (a [good article](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/) about it).
I modified the color of `label` to make it match what it looked like before (with the opacity). Here is how things look like now (basically the same, the background of the help-hover is a little darker, which makes the help text easier to read).

Make sure labels aren't above help-hover

---

packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/types.ts

Hello!
I'm in love with this project and I'd like to help as much as I can, this is my first attempt resolving the issue  #971.
Implementation of a basic "non-tag" filtering in the staking overview page inspired in #965:

Added a simple filter to the staking overview (#971) .

---

packages/ui-api/src/with/call.tsx

This is more of issue report instead of proper fix. Please feel free to reject this and do it properly.
with
```
export default withCalls<Props>(
['query.kitties.ownedKitties', { paramName: 'accountKey', propName: 'item' }]
)
```
and 
```
export class OwnedKittiesKey extends Tuple.with([AccountId, Option.with(KittyIndex)]) {
get account (): AccountId {
return this[0] as AccountId;
}
get kittyId (): Option<KittyIndex> {
return this[1] as Option<KittyIndex>;
}
}
```
it just won't work because tuple is also array so it got unpacked and resulting unexpected behavior.
(Yes I am writing another Substrate Kitties)

withCall can't handle Tuple parameter

---

packages/app-accounts/src/Creator.tsx

- closes 1019
The bug reported in the issue happened when `seed===''`.

Mark raw seed as invalid if smaller than 32 char

---

packages/apps/public/index.html
packages/ui-app/src/Labelled.tsx
packages/ui-app/src/RecentlyOffline.tsx
packages/ui-app/src/Tooltip.tsx
packages/ui-app/src/styles/components.css

Hello! 
I've been trying to solve #938 and came up with a possible solution:
This component will allow to render a react-tooltip component easily at the body level (as recommended in the react-tooltip documentation) with literally no effort.
I'd like to know what are your thoughts about it 
Thanks!

Tooltip component, a react-tooltip wrapper (#938)

---

packages/app-accounts/src/Restore.tsx

Summary: old checksum formats doesn't pass the validation. Relax checksum check (via decodeAddress) and re-encode address to be able to retrieve info.
@chevdor I would appreciate if you can verify with one of your problematic accounts that it actually _does_ import. (It certainly gets past the first step now)

Old json checksum & imports

---

packages/app-democracy/src/Overview/Item.tsx
packages/app-democracy/src/Overview/Proposal.tsx
packages/app-democracy/src/Overview/Proposals.tsx
packages/app-democracy/src/Overview/Referendum.tsx
packages/app-democracy/src/Overview/Referendums.tsx
packages/app-democracy/src/Overview/Summary.tsx
packages/app-democracy/src/Overview/Voting.tsx
packages/app-democracy/src/Overview/VotingButtons.tsx
packages/app-democracy/src/Overview/index.tsx
packages/app-democracy/src/Proposals.tsx
packages/app-democracy/src/Propose.tsx
packages/app-democracy/src/index.css
packages/app-democracy/src/index.tsx

Closes #975
Adds button and modal to submit new proposals from app-democracy instead of going through app-extrinsics.
This also includes the relocated ui-app/Extrinsic I added for #1036

Add create proposal option to app-democracy

---

packages/app-accounts/src/index.tsx
packages/app-address-book/src/index.tsx
packages/app-democracy/src/index.tsx
packages/app-staking/src/Accounts.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-transfer/src/index.tsx
packages/ui-app/src/FilterOverlay.tsx
packages/ui-app/src/index.tsx
packages/ui-app/src/media.ts

Closes https://github.com/polkadot-js/apps/issues/1053
- Add FilterOverlay component
- Use component in staking
Responsiveness is ok, but not great - it does overlap on very small screens. (Not great, but not worse than we have elsewhere). Should be ok for the 99.9% of actual users.

Consistent staking filter placement

---

packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/Overview/index.css

- It is slightly off after the AdrressMini changes (no spacing/padding)
- swap to IdentityIcon
Old vs new:

Tweak block staking icon display

---

packages/app-accounts/src/Creator.tsx
packages/app-accounts/src/Vanity/Match.tsx
packages/app-accounts/src/Vanity/index.tsx
packages/app-accounts/src/index.tsx
packages/app-accounts/src/vanitygen/cli.ts
packages/app-accounts/src/vanitygen/generate.ts
packages/app-accounts/src/vanitygen/types.d.ts

Closes https://github.com/polkadot-js/apps/issues/949
- Pass through vanity generation type (missing previously)
- Also opens the door for sr25519 vanity support - added as an option

Fix vanitygen (type passing) & support sr25519

---

packages/ui-app/src/TxButton.tsx

Makes TxButton more robust, and stops this on the sudo app.

TxButton should not calc. on disabled

---

packages/apps/src/Apps.tsx
packages/ui-app/src/CardSummary.tsx
packages/ui-app/src/SummaryBox.tsx

Removes min-height and padding-top from CardSummary for consistent vertical spacing between the tab menu items and the contents below across different apps, and some responsive tweaks so not too much padding on mobile devices.

refactor: Relates to #1060. Consistent top padding across apps

---

packages/app-staking/src/Account/index.tsx
packages/app-staking/src/index.css

Closes #1089 
Collapse account actions items to columns on lower browser widths (< 1280px)

Fix staking account actions layout -md -sm

---

packages/ui-app/src/Status/index.tsx
packages/ui-app/src/Tooltip.tsx
packages/ui-app/src/styles/components.css
packages/ui-app/src/styles/semantic.css

- Move Status to use styled-components
- Fix the following (pre and post)
(Actual fix here is only removing the 3 lines starting at https://github.com/polkadot-js/apps/pull/1097/files#diff-ac54e2de59aa4a9d39d402ceaa550154L351 - not quite visible since it has been copied to styled, but the copy does not have those 3, otherwise identical)

Cleanup status display with address

---

packages/app-toolbox/src/Hash.tsx
packages/app-toolbox/src/Sign.tsx
packages/app-toolbox/src/Verify.tsx

Closes https://github.com/polkadot-js/apps/issues/1004
- Remove .small, replace by .medium & split into rows
- Initially tried to adjust the min-width of the content holder, but then it breaks the text on resize - the label just takes up too much space

Adjust toolbox layout (.small is problematic)

---

packages/app-explorer/src/index.tsx
packages/apps-routing/src/index.ts

Closes https://github.com/polkadot-js/apps/issues/941. Light vs Full -

Show explorer in light (but hide node info)

---

packages/app-accounts/src/Creator.tsx
packages/app-accounts/src/Editor.tsx
packages/app-accounts/src/Forgetting.tsx
packages/app-accounts/src/modals/Backup.tsx
packages/app-accounts/src/modals/ChangePass.tsx
packages/app-accounts/src/modals/Forgetting.tsx
packages/app-address-book/src/Forgetting.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/Accounts.tsx
packages/app-staking/src/Overview/Address.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/Labelled.tsx
packages/ui-app/src/styles/components.css
packages/ui-app/src/styles/semantic.css
packages/ui-app/src/styles/theme/polkadot.css
packages/ui-app/src/util/getAddrName.ts

- Closes https://github.com/polkadot-js/apps/issues/985
- Adjust all Account & Address modals
- AddressRow
- Description for each operation
- Help label information as applicable
- Rework AddressRow/AddressSummary to populate the name (from keyring)
- Adjust global modal styling somewhat (fits in slightly better with overall L&F)
Accounts:
Address book:

Rework account & address modals

---

packages/apps/src/Content/index.tsx

- Recently have been struggling with the RPC load on the hosted nodes (where they finally run out of resources and bumps everybody)
- This alleviates the problem at the expense of making "next up" queries for staking take longer.
- multi queries for disparate types would help here, however we don't have API support for it as of yet (This specific query however does not benefit from multi, so it, for the time being, will remain ineffective)

Disable hot-start global controller query (RPC load)

---

packages/app-staking/src/Account/Bond.tsx
packages/app-staking/src/Account/BondExtra.tsx
packages/app-staking/src/Account/Unbond.tsx
packages/app-staking/src/Account/index.tsx
packages/app-staking/src/types.ts
packages/app-transfer/src/Transfer.tsx
packages/ui-app/src/Dropdown.tsx
packages/ui-app/src/InputBalance.tsx
packages/ui-app/src/InputNumber.tsx
packages/ui-app/src/styles/components.css
packages/ui-signer/src/Checks/constants.ts
packages/ui-signer/src/Checks/index.tsx

Closes #1043 
- Adds MAX button to auto-fill maximum available balance when using Transfer and Staking app
- Adds checks for too-high values to InputNumber if maximum is specified

Add maximum balance button to app-transfer and app-staking

---

packages/app-toolbox/src/Sign.tsx

fix https://github.com/polkadot-js/apps/issues/1139
added a help label for account.
Question before I implement it:
Rather than letting users click on the "Unlock" button, I'd fire up directly the unlock modal if a locked account is selected. If it's cancelled, then the unlock button will still be there. I would add a message also to say that the data can't be signed unless the account is unlocked (again it would only be visible if the modal is cancelled). What do you think?

Fix signing tool

---

packages/ui-app/src/InputNumber.tsx

Lately this is happening - disabled field pops up, but it is marked as invalid. (In this case sending again makes everything all-ok. The `isValid` filed does not get reset for `isDisabled` - so start it off as valid. `isError` can still show errors)

Don't set isValid on isDisabled (InputNumber)

---

packages/app-staking/src/Overview/Address.tsx
packages/ui-api/src/with/call.tsx
packages/ui-api/src/with/types.ts

Closes https://github.com/polkadot-js/apps/issues/800
Usage:
```js
withCalls(
// single param passed in the form of an array
['query.balances.freeBalance', { params: [Alice, Bob, Dave], isMulti: true }]
)
```

Add isMulti param for withCall

---

packages/app-toolbox/src/Unlock.tsx

- Closes https://github.com/polkadot-js/apps/issues/1161
Does not do enter-on-submit from #1162 (Didn't want to modify password - or even look if it has the `onEnter`). However, at least password has `autoFocus` now, which helps.

Unlock modal update

---

package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-api/src/Api.tsx
packages/ui-app/package.json
packages/ui-signer/src/Modal.tsx
packages/ui-signer/src/Unlock.tsx
yarn.lock

- Allow the injection of external accounts, i.e. from extensions (not stored in storage, but injected and available)
- Allow signing for external accounts (tested for extension https://github.com/polkadot-js/extension, hopefully extensible for others- there will be tweaks)
- Some groundwork from https://github.com/polkadot-js/apps/issues/355 (Not compared against https://github.com/polkadot-js/apps/pull/592 which is _very_ outdated)
https://youtu.be/VzxGQeCHM8Y
NOTE: This PR needs an updated `ui-keyring`, so `yarn install` when pulling the branch.

External account injection & external signing

---

packages/ui-app/src/Status/Queue.tsx

Closes https://github.com/polkadot-js/apps/issues/1183 - doesn't try to solve the world's problems, specifically focusses on `ExtrinsicFailed`

Mark ExtrinsicFailed as error

---

packages/apps/src/index.tsx
packages/apps/src/overlays/Connecting.tsx
packages/ui-api/src/Api.tsx
packages/ui-api/src/Injected.tsx
packages/ui-api/src/index.ts
packages/ui-api/src/types.ts
packages/ui-signer/src/Modal.tsx

- Allows the use of `enable()` for extensions - this allows the extension to approve/reject
- Needs https://github.com/polkadot-js/extension/pull/20
- Demo https://youtu.be/Tio_Tl31M44

Make enable() call to extensions

---

packages/ui-api/src/Injected.tsx

- Pulled master
- `yarn install`
- Got an error of trying to attach ref on functional component
Changes lately -
- API with ref for buttons
- This functional component
Result -
- Change the functional component to a PureComponent

withInjected -> PureComponent (fix new refs)

---

packages/ui-app/src/Input.tsx
packages/ui-app/src/InputNumber.tsx

This is quite heavy-handed, but we actually don't use the combination anywhere. Additional, it allows us to not have this (check the current master balance here - in red) -

Don't display errors on Input with isDisabled

---

packages/ui-app/src/styles/components.css
packages/ui-reactive/src/Unlocking.tsx

- closes https://github.com/polkadot-js/apps/issues/1214
- adds a margin left for (i) icon on locked

Cater for empty unlockings and margin on icon

---

packages/app-accounts/src/Creator.tsx
packages/app-accounts/src/Restore.tsx
packages/app-address-book/src/Creator.tsx
packages/app-address-book/src/Editor.tsx
packages/app-transfer/src/Transfer.tsx
packages/ui-app/src/AddressInfo.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/AddressSummary.tsx
packages/ui-app/src/styles/components.css

- As mentioned in https://github.com/polkadot-js/apps/pull/1210/#issuecomment-496079805
- Next step would be to remove Summary altogether and pull the styles into AddressRow (finally making it clean)

Swap AddressSummary for AddressRow

---

packages/app-explorer/src/BlockInfo/Extrinsics.tsx
packages/ui-app/src/Call.tsx

It removes confusion, i.e. on the signer where it is the _unsigned_ hash. This doesn't match up once submitted. On the explorer block info it is useful and matches up with what is calculated elsewhere in the ecosystem.

Only display extrinsic hash on block info

---

packages/app-explorer/src/BlockHeader/BlockHeader.css
packages/app-explorer/src/BlockHeader/index.tsx

closes https://github.com/polkadot-js/apps/issues/1245
div -> span does the trick.
edit: new screenshot with align-middle
regarding closing an issue == opening a new one, the research by block field is in the way :)

Fix ellipsis bug with FF

---

packages/ui-app/src/FilterOverlay.tsx

closes https://github.com/polkadot-js/apps/issues/1249
The no-wrap fixes this problem on FF

Hide search and filter on small screens

---

packages/app-storage/src/Selection/Modules.tsx
packages/ui-app/src/Extrinsic.tsx

Display extrinsic meta documentation on hover

---

packages/apps/src/Apps.tsx

A trial. Atm, at least with chrome, we are being our own worst nightmare in development.
1. Each save re-compiles with the webpack-plugin-serve
2. VSCode jumps in trying to validate the TypeScript (which was problematic <3.5)
3. Hot reloader reloads the page, however do bear in mind that we have a WASM leak in Chrome
The end result, at least for me, it that -
1. Hot reload doesn't always seem to work (css is mostly fine, anything bigger and it doesn't)
2. So refresh is anyway in the order of the day (especially after a lot of changes)
At least for my workflow, all that happens at it that i need to continue looking at Chrome Helper at >100% CPU for most of the time
... so, this is a trial to see if things get better without a major impact elsewhere on productivity

Disable react-hot-loader

---

packages/ui-api/package.json
yarn.lock

- Pulls in FF compat, finally. In FF `about:debugging` load `manifest.json` from `packages/extension/build` - https://github.com/polkadot-js/extension/pull/44
- Extension also has basic breakdown for metadata from known chains (currently only Alexander), https://github.com/polkadot-js/extension/pull/40
Strictly neither of these actually require this bump (it works fine as-is since only the extension needs to be updated), however the first one changes the load procedure slighty with some init error logging, and it is good pulling this in just in case things do go wrong with any extension. The logs would be good in these cases.

Bump extension-dapp

---

packages/ui-app/src/AddressRow.tsx

There's no such thing as a too small PR.
Fixes that (visible in modals):

Fix AddressRow cut

---

packages/ui-params/src/Param/Enum.tsx
packages/ui-params/src/Param/Null.tsx
packages/ui-params/src/Param/Static.tsx
packages/ui-params/src/Param/Struct.tsx
packages/ui-params/src/Param/Unknown.tsx
packages/ui-params/src/Param/findComponent.ts
packages/ui-params/src/Params.css
packages/ui-params/src/initValue.ts

- Closes https://github.com/polkadot-js/apps/issues/546
- This uses deep object inspection via `toRawType` to build up the inputs for Enum, Struct & Option
Currently with Enums:
With this in place:
As a bonus, it also allows Option<Type> with proper inputs - however here there is no "None", it is always "Some":
For structs, the old bytes input is gone:

Create Enum, Option & Struct from toRawType

---

packages/ui-app/src/AddressRow.tsx

First item fixed, second one the old version. Just make stuff consistent.

Adjust AddressRow-buttons right margin

---

packages/app-staking/src/index.css

- Caused by https://github.com/polkadot-js/apps/pull/1284
Screenshot show current vs adjusted:

Fix AddressMini padding on staking

---

packages/app-js/src/snippets/index.ts
packages/app-js/src/snippets/storage-examples.ts

This PR adds a new snippet to the list:
It shows up as:

Add new snippet for api.query.balances.freeBalance.multi

---

packages/ui-app/src/AddressMini.tsx
packages/ui-app/src/AddressRow.tsx
packages/ui-app/src/Messages.tsx
packages/ui-app/src/Row.tsx
packages/ui-app/src/util/getAddressName.ts
packages/ui-app/src/util/getAddressTags.ts

- AddressMini address renders as AddressCase (whatever that means), name as UPPERCASE
- AddressMini name retrieval is back
- Re-apply buttonrow spacing adjustments (got lost)
- Make messages buttons look like messages (contracts)
- Some minor styled adjustments (copy only, without Wrapper)
- Limit AddressMini width and add text overflow

Various small UI fixes (incl. AddressMini names)

---

package.json
packages/app-accounts/src/Account.tsx
packages/app-accounts/src/modals/ChangePass.tsx
packages/app-accounts/src/modals/Create.tsx
packages/app-accounts/src/modals/Import.tsx
packages/app-address-book/src/Address.tsx
packages/app-address-book/src/modals/Create.tsx
packages/app-contracts/src/Params.tsx
packages/app-staking/src/Actions/Accounts.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-toolbox/src/Sign.tsx
packages/app-toolbox/src/Unlock.tsx
packages/app-toolbox/src/Verify.tsx
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-app/src/CryptoType.tsx
packages/ui-app/src/InputAddress.tsx
packages/ui-app/src/util/getAddressName.ts
packages/ui-app/src/util/getAddressTags.ts
packages/ui-app/src/util/getContractAbi.ts
packages/ui-signer/src/Modal.tsx
packages/ui-signer/src/Unlock.tsx
yarn.lock

Includes -
- polkadot-js/common#419 (keyring interface)
- https://github.com/polkadot-js/api/pull/997 (additional ABI types)
- https://github.com/polkadot-js/api/pull/991 (substrate 2.x metadata v5)
And additions due to the above -
- https://github.com/polkadot-js/ui/pull/146  (ui-keyring with new keyring interface)
- https://github.com/polkadot-js/extension/pull/57 (extension-dapp with compliant injection)

Bump deps (change use as required)

---

packages/app-democracy/src/Propose.tsx
packages/app-extrinsics/src/Selection.tsx
packages/app-sudo/src/Sudo.tsx
packages/ui-api/src/Api.tsx
packages/ui-api/src/types.ts
packages/ui-app/src/Params/Proposal.tsx

- Consensus module removed in 2.x, setCode moved to system
- support with consensus, 2.x without and fallback if neither
NOTE: Current substrate master needs additional API types (as a fall-out from the above change). Types merged in https://github.com/polkadot-js/apps/pull/1297, updates for session in https://github.com/polkadot-js/apps/pull/1298

Default proposal/sudo for new 2.x substrate

---

packages/ui-app/src/InputExtrinsic/options/method.tsx
packages/ui-app/src/InputExtrinsic/options/section.ts
packages/ui-app/src/InputStorage/options/key.tsx
packages/ui-app/src/InputStorage/options/section.ts

There is currently a crash in indices - the section calls are `[]` in the metadata, so it has an index, however there are no items for the dropdown. 
TL;DR There are valid reasons why the metadata returns `[]` instead of `null` of calls, however we assume for non-`null` that we always have methods inside the section. This is not the case.

Filter modules (query & storage) without methods

---

package.json
packages/app-contracts/package.json
packages/app-contracts/src/Codes/Upload.tsx
packages/app-contracts/src/Codes/ValidateCode.tsx
packages/app-contracts/src/Contracts/Call.tsx
packages/app-contracts/src/Contracts/ValidateAddr.tsx
packages/app-contracts/src/Deploy.tsx
packages/apps-routing/src/contracts.ts
packages/ui-api/package.json
packages/ui-signer/src/Checks/index.tsx
yarn.lock

- Closes https://github.com/polkadot-js/apps/issues/1316
- includes the derive the s/contract/contracts/interfaces, e.g. https://github.com/polkadot-js/api/pull/1036

Support 1.x contract & 2.x contracts

---

packages/app-contracts/src/Codes/Upload.tsx
packages/app-contracts/src/Deploy.tsx

In substrate, the `contract` module was renamed to `contracts`. This looks up the record on success by the correct name, should be backwards compatible.

Fix upload and deploy contract(s) after rename

---

packages/app-accounts/src/modals/Create.tsx
packages/app-address-book/src/modals/Create.tsx
packages/app-contracts/src/Codes/Add.tsx
packages/app-contracts/src/Codes/Upload.tsx
packages/app-contracts/src/Contracts/Add.tsx
packages/app-contracts/src/Deploy.tsx
packages/app-contracts/src/Modal.tsx
packages/ui-app/src/Row.tsx

In 99% of the cases people just want to get their work done - de-clutter. (Always available on edit)
Mentioned in https://github.com/polkadot-js/apps/issues/1332

Remove all tags on create dialogs

---

package.json
packages/app-contracts/package.json
packages/app-storage/src/Query.tsx
packages/app-storage/src/Selection/Modules.tsx
packages/app-storage/src/types.ts
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-app/src/InputStorage/SelectKey.tsx
packages/ui-app/src/InputStorage/SelectSection.tsx
packages/ui-app/src/InputStorage/index.tsx
packages/ui-app/src/InputStorage/options/key.tsx
yarn.lock

Pulls in https://github.com/polkadot-js/api/pull/1059
Works with latest master right after Basti's PR got merged in.

Upgrade api to use MetadataV6

---

packages/app-staking/src/index.tsx

- closes https://github.com/polkadot-js/apps/issues/1359
The `allAccounts` was `undefined` the first time the component was called.

Fix "query.staking.bonded Bonded expect one argument"

---

packages/ui-signer/src/Modal.tsx
packages/ui-signer/src/PasswordCheck.tsx

- closes #1363
I didn't want to use the bells and whistles from a class, however I couldn't manage the have the styled component work with `withMulti`.
```js
export default withMulti(
styled(PasswordCheck)`
margin-left: 15em;
color: #9f3a38;
`,
translate
);
```
The style wasn't taken into account.. any hint welcome
This is how it looks:

Add wrong password indication

---

README.md

https://github.com/polkadot-js/apps/issues/1391
Looks like [app-nodeinfo](https://github.com/polkadot-js/apps/blob/master/README.md#L27) package has been merged to [app-explorer directory](https://github.com/polkadot-js/apps/tree/master/packages/app-explorer/src/NodeInfo)? 
If so I will make PR to remove it from README to prevent further confusion.

Removed broken link to app-nodeinfo from README

---

packages/app-staking/src/Actions/Account/index.tsx
packages/app-staking/src/Actions/Accounts.tsx
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/Summary.tsx
packages/app-staking/src/Overview/index.tsx
packages/app-staking/src/index.tsx
packages/app-staking/src/types.ts
packages/ui-api/src/Api.tsx
packages/ui-api/src/types.ts

- one part of https://github.com/polkadot-js/apps/issues/1378 the rest should be sorted with `derive.staking.info` (https://github.com/polkadot-js/api/issues/1113)
- cleaning the balance props that was carried around and never used
- a lot of renaming to make things clearer (IMHO), e.g `stashes` --> `allStashes` (includes the ones currently **not** selected in the validator set) or the monster `currentValidatorsControllersV1OrStashesV2` that represents either the stash (v2) or the controllers (v1) from the validators currently in the validator set. lmk if you think about something better.
- working well on Alex, and almost nothing is shown on v2 (because of the derive)

Staking compatibility with v2

---

packages/app-contracts/src/Codes/ValidateCode.tsx
packages/app-contracts/src/Contracts/ValidateAddr.tsx
packages/app-democracy/src/Overview/Referendum.tsx
packages/app-democracy/src/Overview/Summary.tsx
packages/app-js/src/snippets/storage-examples.ts
packages/app-treasury/src/Overview/Approve.tsx
packages/app-treasury/src/Settings.tsx
packages/ui-api/src/with/call.tsx
packages/ui-api/src/with/types.ts
packages/ui-signer/src/Checks/Proposal.tsx

Solves https://github.com/polkadot-js/apps/issues/1415
I added an option to pass fallback endpoints to the `ui-api` to provide an easy way to make the components backwards compatible.
I changed the ui-api so that it loops through the endpoint and fallback endpoints, if provided.
This way, we can just pass deprecated endpoints to `withCalls`.
If no fallbacks are provided `withCalls` will behave like before.
For 1 fallback call:
`['consts.democracy.launchPeriod', { fallback: ['query.democracy.launchPeriod'] }]`
For multiple fallback calls:  
`['consts.contracts.contractFee', { fallback: ['query.contracts.contractFee', 'query.contract.contractFee'] }]`

Add endpoint fallbacks option and handling of consts to ui-api

---

packages/ui-reactive/src/TimePeriod.tsx

closes https://github.com/polkadot-js/apps/issues/1410
Opened instead of https://github.com/polkadot-js/apps/pull/1422 and https://github.com/polkadot-js/apps/pull/1417

Update minimumPeriod for 2.0 and drop  pre 1.0 support

---

packages/ui-app/src/CardSummary.tsx

My turn for a "small PR while waiting for a build". It does this -
Just formats the numbers consistently like we have elsewhere (has never been an . issue)

CardSummary number format adjustment

---

packages/ui-params/src/Param/findComponent.ts

Instead of the picture in #1438 (without the icon and name), we now have this -

Display AuthorityId param as Address

---

package.json
packages/app-123code/package.json
packages/app-accounts/package.json
packages/app-address-book/package.json
packages/app-contracts/package.json
packages/app-council/package.json
packages/app-dashboard/package.json
packages/app-democracy/package.json
packages/app-explorer/package.json
packages/app-extrinsics/package.json
packages/app-js/package.json
packages/app-parachains/package.json
packages/app-settings/package.json
packages/app-staking/package.json
packages/app-storage/package.json
packages/app-sudo/package.json
packages/app-toolbox/package.json
packages/app-transfer/package.json
packages/app-treasury/package.json
packages/apps/package.json
packages/ui-api/package.json
packages/ui-app/package.json
packages/ui-params/package.json
packages/ui-signer/package.json
yarn.lock

cc @kwingram25 
- pulls in the last derive fixes 
- support metadata v7 (which fixes collective queries)
- needed for any substrate master version from now on

Bump api, Metadata v7 support

---

packages/app-staking/src/Actions/Account/index.tsx
packages/app-staking/src/Actions/Accounts.tsx
packages/app-staking/src/index.tsx

- closes https://github.com/polkadot-js/apps/issues/1445
- remove useless `isActiveStash` (I remember telling this to myself earlier.. but hadn't had the chance yet)
- nits alphabetical ordering
Because of https://github.com/polkadot-js/apps/issues/1408 (I'll get to it soon) it's not easy to play with, you need to send `staking.validate` manually.

Fix account wrongly seen as current validator

---

packages/ui-app/src/CardGrid.tsx
packages/ui-app/src/Collection.tsx

Found this issue while working on #1452
The prop `isEmpty` was ignored. You can observe this bug in Address book with no addresses.
Also `Collection.isEmpty` gives false if children is `[false]`. I am not sure what is the desired behavior as do we want to ignore any non-renderable children or just strictly check children is empty array?

Fix isEmpty for CardGrid

---

README.md

When compiling via `yarn`, the default port used is 3000 (see #L50).  However, the given Docker command runs the UI on port 80 (default HTTP port).  
I added an extra sentence enumerating this difference, because I used the same port with Docker as I did with the local build at first, and it was a bit confusing why I was getting a 404.

Add explanation that Docker port is 80

---

packages/app-settings/src/md/basics.md

Makes the types example a valid json object.
Noticed the typo when copy-pasting the code.

Correct typo in JSON example.

---

packages/app-staking/src/Actions/Account/index.tsx
packages/react-components/src/CopyButton.tsx

Avoid overflow on staking pages while keeping consistent with the address ellipsis that we have on accounts app.
That's what I've got so far:
Wasn't able to detect any side effects by the css changes, I'd appreciate a close look on those.
Thanks

Avoid overflow on staking pages #1502

---

packages/app-settings/src/General.tsx
packages/react-api/src/Api.tsx

- Will require `@polkadot/util` 1.5.1 when https://github.com/polkadot-js/common/pull/472 is in
- Closes https://github.com/polkadot-js/apps/issues/1621
- Prefix change is a reload (this is not great)

ss58Format overrides

---

packages/app-contracts/src/Deploy.tsx

srml-contract deploy API renaming broke the contract deployment function.
- keep backward compatible with the deprecated function call
- substrate PR <https://github.com/paritytech/substrate/pull/3649>

Fix broken contract deployment function

---

packages/apps/src/SideBar/SideBar.css
packages/react-components/src/styles/theme.ts

Change link color back to white in sidebar navigation to get better contrast.
Before:
After:

Switch back to white menu items in sidebar

---

package.json
packages/app-contracts/package.json
packages/app-storage/src/Query.tsx
packages/app-storage/src/Selection/Modules.tsx
packages/app-storage/src/types.ts
packages/react-api/package.json
packages/react-components/src/Button/Button.tsx
packages/react-components/src/InputConsts/SelectSection.tsx
packages/react-components/src/InputStorage/SelectKey.tsx
packages/react-components/src/InputStorage/SelectSection.tsx
packages/react-components/src/InputStorage/index.tsx
packages/react-components/src/InputStorage/types.ts
yarn.lock

A bit more involved than it should have been since we are missing `StorageEntryPromise` which was removed in https://github.com/polkadot-js/api/pull/1406

Bump API (latest substrate master)

---

packages/react-params/src/Param/BaseBytes.tsx

This allows ss58 inputs anywhere we have Bytes types. 
(This is the reverse of existing functionality where we already allow 0x... publicKey inputs in any address field - in both the existing and new case, we just convert transparently)
cc @shawntabrizi cc @JoshOrndorff - this may help somewhat

Allow ss58 input on Bytes fields

---

packages/apps/src/index.tsx

- Closes https://github.com/polkadot-js/apps/issues/1707
(Or rather... _should_ close, cannot reproduce the error, but this approach doesn't break anything else... so _hopefully_ does the trick)

Extra RPC endpoint split on hash

---

packages/app-address-book/src/Address.tsx
packages/react-components/src/AddressInfo.tsx

- Adds the available locks (for some reason we didn't include this previously)
- Closes https://github.com/polkadot-js/apps/issues/1781
Will log to actually display the breakdowns and the to-block info (like with unlocking)

Display locked amounts

---

packages/react-components/src/AddressMini.tsx
packages/react-components/src/InputAddress/index.tsx
packages/react-components/src/Status/index.tsx

Closes https://github.com/polkadot-js/apps/issues/1797
This is actually problematic - since the names are now a wrapped component, we don't actually allow lookups on name, only address. This fixes the issue reported, however we need to have some magic somehow to do name lookups as well.

Fix input addr crash

---

packages/app-js/src/Playground.tsx

Hi @jacogr 
I think the issue #1795 is caused by the `fn _stop()`, set the running `true` then switch to `false`.
I have modified a bit to enable the display of stop/play button.
While I think the best solution is to switch the  isRunning-state according to exec result.

Js console

---

packages/app-staking/src/Actions/Account/BondExtra.tsx
packages/app-staking/src/Actions/Account/InputValidateAmount.tsx
packages/app-staking/src/Actions/NewStake.tsx

- Warns the user that tx is allowed, but max will be bonded https://github.com/polkadot-js/apps/issues/1830

Add bond fund warning

---

packages/app-accounts/src/Vanity/index.tsx
packages/app-council/src/Overview/Vote.tsx
packages/react-api/src/with/call.tsx

Change selection for council votes

---

package.json
packages/app-contracts/package.json
packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/index.tsx
packages/app-staking/src/Query/Validator.tsx
packages/app-staking/src/Query/index.tsx
packages/app-staking/src/index.tsx
packages/app-staking/src/types.ts
packages/app-storage/src/Query.tsx
packages/app-storage/src/Selection/Consts.tsx
packages/react-api/package.json
packages/react-components/src/AddressRow.tsx
packages/react-components/src/Chart/Line.tsx
packages/react-components/src/InputAddressSimple.tsx
packages/react-components/src/InputConsts/index.tsx
packages/react-components/src/InputConsts/options/key.tsx
yarn.lock

Almost gets to https://github.com/polkadot-js/apps/issues/1848, closing anyway... this displays the blocks generated

Enable validator overview

---

packages/app-staking/src/Actions/Account/Validate.tsx

Closes https://github.com/polkadot-js/apps/issues/1884
As per a similar thing in council, e.g https://github.com/polkadot-js/apps/blob/master/packages/app-council/src/Overview/VoteValue.tsx#L31, we need a general solution.

Fix validatorPrefs (don't pull defaults)

---

packages/app-staking/src/Overview/Address.tsx
packages/app-staking/src/Overview/CurrentList.tsx
packages/app-staking/src/Overview/index.tsx
packages/app-staking/src/Query/Validator.tsx
packages/app-staking/src/Query/index.tsx
packages/app-staking/src/index.tsx
packages/app-staking/src/types.ts
packages/react-api/src/util/historic.ts
packages/react-hooks/src/index.ts
packages/react-hooks/src/trackStream.tsx

First attempt (with holes) for https://github.com/polkadot-js/apps/issues/1889

Add trackStream, impl. in staking overview

---

packages/app-staking/src/Actions/Accounts.tsx
packages/app-staking/src/Query/Validator.tsx
packages/react-hooks/src/useSessionRewards.tsx

- Unknown, non-account stash now shows.
- there are gaps -
- when you don't have the controller, the controller options will also show in the menu
- when you don't have the stash, the stash options will also show in the menu
... but it gets it going.

Map non-account stashes

---

packages/app-staking/src/useSessionRewards.tsx

Fix old v1 queryStorage results

---

README.md
package.json
packages/app-contracts/package.json
packages/app-staking/src/Actions/Account/index.tsx
packages/app-staking/src/Actions/index.tsx
packages/app-staking/src/index.tsx
packages/react-api/package.json
yarn.lock

Adjust staking

---

packages/app-staking/src/useSessionRewards.tsx

Closes https://github.com/polkadot-js/apps/issues/1931

Remove empty rewards from cache

---

packages/app-toolbox/src/Sign.tsx

Fixes issue uncovered in https://github.com/polkadot-js/extension/pull/196#issuecomment-558317719 (hex data is not always passed)

Always pass hex to signRaw

---

packages/react-components/src/Status/index.tsx
packages/react-query/src/AccountName.tsx

Rework status name display

---

package.json
packages/app-contracts/package.json
packages/app-staking/src/Actions/Account/Validate.tsx
packages/app-staking/src/Targets/Validator.tsx
packages/app-staking/src/Targets/index.tsx
packages/app-staking/src/Targets/types.ts
packages/react-api/package.json
packages/react-components/src/AddressInfo.tsx
yarn.lock

Needs https://github.com/polkadot-js/api/pull/1618

Update ValidatorPrefs with commission

---

package.json
packages/app-contracts/package.json
packages/app-democracy/src/Overview/PreImage.tsx
packages/app-democracy/src/Overview/Proposal.tsx
packages/app-democracy/src/Overview/Proposals.tsx
packages/app-democracy/src/Overview/Propose.tsx
packages/app-democracy/src/Overview/Referendum.tsx
packages/app-democracy/src/Overview/Referendums.tsx
packages/app-democracy/src/Overview/Summary.tsx
packages/app-democracy/src/Overview/index.tsx
packages/apps-routing/src/democracy.ts
packages/react-api/package.json
packages/react-components/src/ActionItem.tsx
packages/react-components/src/Chart/HorizBar.tsx
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/1970

Support democracy with preimages

---

packages/react-api/src/overrides/spec/edgeware.ts

We can discontinue the current mainnet as it is an old testnet basically. For now, these are the most up to date settings.

Update extra key for new Edgeware testnet

---

packages/apps/src/overlays/Connecting.tsx

Remove FF warning (can now connect to local ws)

---

package.json
packages/app-accounts/src/modals/Identity.tsx
packages/app-contracts/package.json
packages/react-api/package.json
packages/react-components/src/AccountName.tsx

Closes https://github.com/polkadot-js/apps/issues/2098

Display sub identities

---

packages/app-staking/src/Actions/Account/Nominate.tsx

Also (finally) closes https://github.com/polkadot-js/apps/issues/2037 (the issue here was using currentList, which could include waiting)

Always include staking favourites in the list

---

packages/app-js/package.json
packages/app-js/src/ActionButtons.tsx
packages/app-js/src/Playground.tsx
packages/app-js/src/index.tsx
packages/app-js/src/snappyjs.d.ts
packages/react-components/src/Dropdown.tsx

Additionally, close the loophole where `this` still refers to the window.

Remove snippet sharing

---

packages/app-democracy/src/Overview/PreImage.tsx

Closes https://github.com/polkadot-js/apps/issues/2146

Align noteImminent with Substrate

---

packages/react-components/src/Status/Queue.tsx
packages/react-params/src/Param/DispatchError.tsx

Closes https://github.com/polkadot-js/apps/issues/2179

Handle DispatchError failures gracefully

---

packages/app-accounts/src/Account.tsx
packages/app-accounts/src/modals/RecoverAccount.tsx
packages/app-accounts/src/modals/RecoverSetup.tsx
packages/react-components/src/Status/index.tsx

Closes https://github.com/polkadot-js/apps/issues/2124

Social account recovery

---

packages/app-democracy/src/Overview/DispatchEntry.tsx
packages/app-democracy/src/Overview/PreImage.tsx
packages/app-democracy/src/Overview/PreImageButton.tsx
packages/app-democracy/src/Overview/Proposal.tsx
packages/app-democracy/src/Overview/Referendum.tsx
packages/react-components/src/Input.tsx
packages/react-components/src/InputAddress/index.tsx
packages/react-components/src/styles/semantic.ts

Closes https://github.com/polkadot-js/apps/issues/2147

Add preimage buttons to proposals

---

packages/react-components/src/AddressInfo.tsx
packages/react-components/src/Tooltip.tsx
packages/react-query/src/FormatBalance.tsx

Closes https://github.com/polkadot-js/apps/issues/1785

Expand locks (& display all)

---

packages/apps-routing/src/types.ts
packages/apps/src/Content/index.tsx
packages/apps/src/SideBar/Item.tsx
packages/react-components/src/ErrorBoundary.tsx

Just removed the crash bit from https://github.com/polkadot-js/apps/issues/2249 - now it will just display that it can't, well, display. (There could be a re-direct to something known, but rather not go this route since it may be a valid failure)

Don't make unavailable apps crash the full app

---

package.json
packages/app-contracts/package.json
packages/react-api/package.json
packages/react-components/src/AccountIndex.tsx
yarn.lock

- Bump API
- skip AccountIndex rendering
Will cater for https://github.com/paritytech/polkadot/pull/816 (when indices have been disabled for networks from a display perspective, API already treats it as optional)

Skip indices rendering when not available

---

packages/app-staking/src/index.tsx

We're converting our chain from PoA to PoS in this PR https://github.com/DataHighway-DHX/node/pull/52/commits/7c8c96939ab6a2b77dd3a2f4bef427e831dafbda
But when I run the chain with those latest changes I got error `TypeError: Cannot read property 'receivedHeartbeats' of undefined` when I tried to go to the Staking app using polkadot.js.org/apps, as explained here https://matrix.to/#/!XOxcnpiHXHhAjJfRFP:matrix.parity.io/$0oidO-aZvsjMRdskB2nig6P_Y4CjH4Gc6TMrl4V7ZB8?via=matrix.parity.io&via=matrix.org&via=matrix.dapp.org.uk
After cloning https://github.com/polkadot-js/apps and debugging the error, I found that this change resolved the error and the Staking App runs

fix: Fixes TypeError: Cannot read property 'receivedHeartbeats' of undefined

---

packages/apps-config/src/settings/endpoints.ts
packages/apps/src/initSettings.ts

- Replaces https://github.com/polkadot-js/apps/pull/2348
- Closes #2347 
(Introduction of headers - the find allows non-headers as well)

find the first available URL

---

packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/api/spec/node-template.ts

Adds the necessary types to make apps work with the [node template](https://github.com/substrate-developer-hub/substrate-node-template) with zero-config from the end user, who is likely a learner.
These types became necessary with https://github.com/paritytech/substrate/pull/5025 and this PR was discussed in https://github.com/substrate-developer-hub/substrate-node-template/pull/25

Add types for Substrate node template

---

packages/apps-config/src/api/chain/berlin.ts
packages/apps-config/src/api/chain/westend.ts
packages/apps-config/src/api/spec/centrifuge-chain.ts
packages/apps-config/src/api/spec/edgeware.ts
packages/apps-config/src/api/spec/kulupu.ts

- Substrate ReferendumInfo type changes, overrides for non-upgraded chains
- API support in https://github.com/polkadot-js/api/pull/2078
- UI support in https://github.com/polkadot-js/apps/pull/2432
cc @drewstone @jnaviask @philipstanislaus

Add ReferendumInfo type overrides

---

packages/apps-config/src/settings/endpoints.ts
packages/apps/src/initSettings.ts

This PR brings a slightly better support for WS_URL and especially allows using WS_URL even in cases where the user already saved another network. This is especially useful on docker/k8s infrastructures where the containers may need to link dynamically.
In that case, passing `WS_URL` accordingly will make the endpoint show up in the list and even make it the default if the user did not define anything yet for this (UI) url.
If `WS_URL` is not provided, things work just like today and nothing special shows up:
However, if `WS_URL` is provided, it will show up in the endpoints list:
I put the new ENV section at the top of the list for 2 reasons:
- if WS_URL is not specified (which is likely the majority...) the list looks as it does today
- it however WS_URL is provided, it will be selected …

Improve support for WS_URL

---

packages/page-settings/src/Extensions.tsx
packages/page-settings/src/useChainInfo.ts

Data can be pulled from chainInfo (not everything needed) in #2360

Expose useChainInfo (re-use of some info for signer)

---

packages/page-explorer/src/BlockInfo/Extrinsics.tsx

Hello - this line was causing us some pain on our network which does not include tips in extrinsics. Thanks!

Don't crash if there is no tip field in extrinsics

---

package.json
packages/page-contracts/package.json
packages/page-democracy/src/Overview/Referendum.tsx
packages/page-democracy/src/Overview/ReferendumVotes.tsx
packages/page-democracy/src/useChangeCalc.ts
packages/page-democracy/src/util.spec.ts
packages/page-democracy/src/util.ts
packages/react-api/package.json
yarn.lock

- Pulls in the approx changes logic from the API derives (since there is no one-size its all here, UI-driven params)
- Swap back to conviction-only changes as a default (with appropriate tooltips)

Referendum change adjustments

---

packages/page-council/src/Overview/Voters.tsx
packages/page-staking/src/Overview/Address/StakeOther.tsx
packages/page-staking/src/Overview/Address/index.tsx
packages/page-staking/src/Targets/Validator.tsx
packages/react-api/src/Api.tsx
packages/react-components/src/AddressInfo.tsx
packages/react-components/src/Expander.tsx
packages/react-components/src/Tooltip.tsx
packages/react-query/src/FormatBalance.tsx

Closes https://github.com/polkadot-js/apps/issues/2248
The `system_chainType` was specifically added to enable this behavior, with this PR the UI now checks the RPC as a first step. (On older versions it will fallback to "string" detection, as was the case up till now)

Use system_chainType

---

packages/page-staking/src/Overview/Address/index.tsx

Currently polkadot.js filters validators with sub-accounts incorrectly:
I.e. only one Ryabina validator is shown despite there being two of them, no sub-account of the other:
We propose a fix to filter sub-accounts as intended:

sub accounts search fix

---

packages/apps-config/src/settings/endpoints.ts

The ava.do cloud allows regular users to share their Kusama node with others through a load balanced mechanism.

Added RYO endpoint

---

packages/page-123code/src/SummaryBar.tsx
packages/page-explorer/src/Summary.tsx
packages/page-staking/src/Targets/Summary.tsx
packages/react-query/src/TotalIssuance.tsx

The Polkadot UI currently expects the balance module to be enabled and has breaking Javascript errors if it's not included in the runtime. Since our chain uses pallet_generic_asset instead of pallet_balance, these changes are needed for the UI to tolerate the balance module being optionally available.

Support for optional usage of pallet_balance

---

packages/apps-config/src/api/spec/node-template.ts

Chains building with https://github.com/substrate-developer-hub/substrate-node-template/ will currently be using `alpha-v6` which has u32 weights. For the time being, I believe it makes sense for us to keep the default setting as Weight = u32 until the node template moves to a Substrate version that uses u64 weights.

Update node-template types to include Weight `u32`

---

packages/apps-config/src/links/index.ts
packages/apps-config/src/links/polkassembly.ts

This adds a link to Polkassembly for kusama.
Tested all proposal, council, treasury and referendum live, because we have them all as of writing.

Add link to Polkassembly

---

packages/apps-config/src/api/chain/arcadia.ts

As per the [polkadot JS FAQ](https://polkadot.js.org/api/start/FAQ.html#using-a-non-current-master-node-i-have-issues-parsing-events) non substrate master nodes need to define a custom type to correctly parse events. This PR cover this for Nodle's Arcadia test network.

add alpha.6 types for arcadia

---

packages/page-contracts/src/Codes/Upload.tsx
packages/page-contracts/src/Contracts/Call.tsx
packages/page-contracts/src/Deploy.tsx

Alternative to #2664 that allows for both deployed chains and the new Substrate master (gas limit usage detected). Due to this comment, https://github.com/polkadot-js/apps/pull/2664#pullrequestreview-403873922, we actually need support for both.
As a bonus, also removes anything `contract`, only use the `contracts` module (old support, good time to clean up)
- Closes #2606
- Closes #2664

putCode with optional gas (UI detection)

---

packages/apps-config/src/api/spec/kulupu.ts

An update ("era change") is [planned](https://github.com/kulupu/kulupu/tree/era/1) on block number 320,000, approximately 8 days from now, on 6th May. This completely updates to Substrate master by exporting the current Kulupu state and regenerate a new genesis block. As a result, we don't need any of those custom type definitions from that point on.
It uses `Lookup = Indices` so I believe I don't need the custom type definitions as in `substrate-node-template`.
This indeed means that in the next ~8 days (or whenever this PR is merged to 6th May), the Kulupu interface on polkadot.js.org is broken, but I'd rather it breaks before the hard fork rather than after the hard fork.

Update Kulupu type definitions

---

packages/apps-config/src/api/chain/index.ts
packages/apps-config/src/api/index.ts

Seems like we did add the correct types in #2663 but forgot to link them to our chain name. This is now fixed and confirmed working from my machine.

expose arcadia types correctly

---

packages/apps-config/src/api/chain/berlin.ts
packages/apps-config/src/api/spec/edgeware.ts

Cleanup up https://github.com/polkadot-js/apps/pull/2690 (specifically the ordering, just adds the eslint override, these are always somewhat problematic with types...)

Fix edgeware linting

---

packages/apps-config/src/api/spec/kulupu.ts

This adds the type definition of `Era` to Kulupu. This is a simple structure that stores pre-squash-fork genesis block hash, final block hash and state root, just in case they need to be used later.

kulupu: add type definition of Era

---

packages/apps-config/src/api/spec/node-template.ts

This PR removes the custom weight type for the node template.
Now that alpha.7 is released, we want builders to use that and it includes the u64 weight type, same as Substrate master
Followup on my previous plan to move these types to the api and spec-version them. I made a foolish mistake and missed the opportunity. All along I was thinking "we'll bump the spec version when alpha.7 comes out". But that is wrong. I needed to do it before alpha.7 was tagged. Because of this oversight on my part, the node template runtime is still not spec-versioned, and we still need to maintain types this way.

Node Template: Restore default weight type (u64)

---

packages/page-claims/src/Attest.tsx
packages/page-claims/src/Claim.tsx
packages/page-claims/src/index.tsx

to be merged in tbaut's branch
The `Step.Claim` step can be either of 2 components:
- Attest (will send tx claims.attest)
- Claim (will send tx claims.claim or claims.claimAttest)
also adds logic to choose between these 2 components in index.tsx

Attest vs Claim

---

packages/page-claims/src/Attest.tsx
packages/page-claims/src/Claim.tsx
packages/page-claims/src/index.tsx

to be merged into tbaut's branch

fix flow between claim and attest

---

packages/page-claims/src/Claim.tsx
packages/page-claims/src/index.tsx

intended to be merged in tbaut-attest

Add ETH address field for non preclaimed addresses

---

packages/apps/src/overlays/Attest.tsx
packages/page-claims/src/Attest.tsx
packages/page-claims/src/index.tsx

To be merged in `tbaut-attest`

Show the amount of token that will be claimed

---

packages/page-contracts/src/Contracts/Call.tsx
packages/page-contracts/src/Modal.tsx
packages/page-contracts/src/constants.ts

I read in one of the smart contract channels, that @kwingram25 is in the process of bigger contracts refactor. So this is just a a really basic quick fix for https://github.com/polkadot-js/apps/issues/2604 to enable people to instantiate their contracts through the UI until there's time for a more involved approach.
I just set higher default gas limit, and switched the bitlength for the gasLimit input field from u32 to u128.

Set higher default for contracts maximum gas allowed

---

packages/page-claims/src/Warning.tsx
packages/page-claims/src/index.tsx

meant to be merged in `am-attest`
Looks like:

Add warning to claim

---

packages/page-accounts/src/Accounts/index.tsx
packages/page-staking/src/Actions/NewNominator.tsx
packages/page-staking/src/Actions/NewValidator.tsx
packages/page-staking/src/Payouts/PayButton.tsx
packages/page-staking/src/Payouts/Stash.tsx
packages/page-staking/src/Payouts/index.tsx

All operations utilizing the utility module is disabled when not available. (Multisig, nominator/validator create & payouts)
Closes https://github.com/polkadot-js/apps/issues/2758

Disable batching usage without utility pallet

---

packages/page-claims/src/index.tsx

Meant to be merged in tbaut-attest

Remove EthreumAddress type to avoid unexpected behaviors

---

packages/page-claims/src/Statement.tsx
packages/page-claims/src/index.tsx
packages/page-claims/src/md/regular.md
packages/page-claims/src/md/saft.md

- remove the `Statement` component for old process (that was a bug)
- show a friendly message when the ethereum address did corresponds to neither a Default or Alternative statement kind.
- add the (non final) md

Enhance UX for claim process

---

packages/react-signer/src/Checks/index.tsx

Protect against (very weird) paymentInfo failures on-the-wire, closes https://github.com/polkadot-js/apps/issues/2810

Protect paymentInfo

---

packages/page-claims/src/Attest.tsx
packages/page-claims/src/Claim.tsx
packages/page-claims/src/index.tsx

fixes #2838 
Tested on Polkadot:
todo:
cc @joepetrowski @lsaether @Tbaut @0x7CFE @ascjones

Restrict attest to accounts, allow claimAttest for all

---

packages/apps-electron/src/electron.ts

App sometimes crashes on start without this flag

Enable remote module

---

packages/react-signer/src/Modal.tsx

... not quite sure why round #1 didn't quite work, however this one has less moving parts

Filter signatories based on outstanding approvals

---

packages/page-settings/src/I18n/index.tsx

As per https://github.com/polkadot-js/apps/pull/2969#issuecomment-645302610
This protects against losing connecting to the node - when we have already loaded, it won't clobber what have have (or edits that have been made)

Don't reload i18n when cached

---

electron-builder.yml
package.json

Extract Electron Builder config to a separate file.
Restore zip target for mac (needed for automatic updates - compare [note 2. in auto update guide](https://www.electron.build/auto-update#quick-setup-guide)).

Electron build - restore zip target

---

packages/page-staking/src/Actions/Account/index.tsx
packages/react-components/src/AddressInfo.tsx

Closes https://github.com/polkadot-js/apps/issues/1565
We already to the checks when bonding (or bonding more), this covers the case where the last remaining is being unbonded

Don't allow re-{validate, nominate} with active 0

---

CHANGELOG.md
packages/apps-config/src/settings/endpoints.ts

My fault for letting this in - since it does not work "out of the box" it doesn't make sense to list it as an endpoint at this point in time. Users will go to it and will be greeted with a loading screen. I should have tested properly instead of assuming it just works.
cc @ltfschoen
PS: Really happy to re-enable when it works without tweaks, which means we would probably need https://github.com/polkadot-js/apps/pull/3084

Remove DataHighway endpoint until fully working

---

packages/page-staking/src/Actions/Account/index.tsx
packages/react-components/src/AddressInfo.tsx
packages/react-components/src/StakingUnbonding.tsx

closes https://github.com/polkadot-js/apps/issues/3081
This was actually a little bug more than a missing feature. [this component](https://github.com/polkadot-js/apps/blob/master/packages/page-staking/src/Actions/Account/index.tsx#L129) was passing the account info in `stakingInfo` prop, although the prop name was `value`. I went for the renaming of the `prop` to keep things consistent with the other similar component.

Show unbonding value in staking account actions

---

packages/page-democracy/src/Overview/PreImage.tsx

closes https://github.com/polkadot-js/apps/issues/2140
The field looks disabled. One can't edit it either, but selection is now possible on FF. 
I checked on Chrome and the behaviour is the same as on FF.

Be able to select preimage hash in Firefox

---

packages/page-democracy/src/Overview/Voting.tsx

closes https://github.com/polkadot-js/apps/issues/2536

Default to 1x conviction for referenda votes

---

packages/apps-electron/src/electron/index.ts

We have at least 2 links (GitHub, Wiki) that lead to external resources. Electron by default opens them in a new Electron window, which doesn't make much sense. This PR changes this behaviour to open those links in a system browser.

Open external links in default system browser

---

packages/apps-electron/src/electron/contentSecurityPolicy.ts
packages/apps-electron/src/electron/index.ts

As per [Electron Security Tutorial](https://www.electronjs.org/docs/tutorial/security#6-define-a-content-security-policy), this PR adds a (hopefully minimal) CSP header configuration.

Add Content Security Policy headers.

---

packages/apps-electron/src/renderer/remote-electron-store.ts

I found out that when there are no accounts yet the accounts list (`result` variable) can be undefined. That's a bit strange, because on the main process side we return an empty array. Probably has to do with how Electron handles IPC (inter-process communication).
Anyway, added a `?` to prevent the error from happening.
I also added the base error messages to ease debugging.

Improve error handling in remote electron account store

---

packages/react-components/src/InputAddressMulti/Selected.tsx
packages/react-components/src/InputAddressMulti/index.tsx

Naive fix that closes #3078
I know this component is used at many other places, I've considered this, however I think that the selected/right side should never be filtered, in any of the implementations we have. Also for consistency, we shouldn't have a multiselect that sometime filters all the fields, sometimes just the left part. Open to discussion if you disagree.

Do not use filter on selected accounts

---

packages/page-claims/src/index.tsx

Some claimants have been confused about the final input field as it has no explanation and seemingly contains value (the placeholder). This will hopefully help.

Clarify signed message input

---

packages/page-accounts/src/Accounts/modals/ProxyOverview.tsx

Fixes the following:
Now looks like:

Fix overflow in proxy overview for long names

---

packages/page-staking/src/Actions/Account/BondExtra.tsx

closes #3232 
We now take any unbonding amount as well as any amount that hasn't been redeemed yet.
I've tested it with both unbonding (also several) and redeemable amounts.

Take unlocking and redeemable into account to bond more funds

---

packages/apps-electron/src/electron/window.ts
packages/apps-electron/webpack.main.config.js

Currently when running the AppImage version on Ubuntu, no icon is displayed in the system dock. This PR fixes it.

Show icon in dock on linux

---

packages/apps-config/src/links/index.ts
packages/apps-config/src/links/polkastats.ts

Added links for account, block & extrinsic paths on currently supported networks Polkadot, Kusama and Westend.

Add PolkaStats links

---

packages/page-staking/src/md/basic.md

It took me forever to understand this myself.
I'd actually find it more useful (and easier to find) as a helper text right next to the >>
Would you find that suitable?

Add info about the nominators state

---

packages/page-explorer/src/NodeInfo/Summary.tsx
packages/page-explorer/src/NodeInfo/index.tsx

Closes https://github.com/polkadot-js/apps/issues/3250 (well, that issue operates fully as expected, but the hardening inspired by it, empty values have no real benefit here)
Since these values are not retrieved since the RPC is displayed, just hide the summary columns completely. Additionally make sure we do fully treat the RPCs are optional (failures have no effect)

Hide non-retrieved node values

---

packages/apps-config/src/settings/endpoints.ts

The old domain is usually troubled by adblocker for some reasons. Moving this to `rpc.kulupu.corepaper.org` to improve situations on that.

Update Kulupu RPC endpoint

---

packages/apps/src/Menu/ChainInfo.tsx
packages/apps/src/Menu/Grouping.tsx
packages/apps/src/Menu/index.tsx
packages/react-components/src/styles/media.ts

Part of https://github.com/polkadot-js/apps/issues/3457
Makes the above slightly better. At below 950px it should swap to hamburger-style, however that is far off in the future.

Media breakpoints for nav

---

packages/apps-config/src/settings/endpoints.ts
packages/apps-config/src/ui/general/index.ts
packages/apps-config/src/ui/logos/index.ts

Hi, we've wired the Laminar Chain into Rococo and now want it to display on the Polkadot Apps.
Because a type is missing, only after this PR merge can it work well.
https://github.com/polkadot-js/api/pull/2519

add rococo laminar

---

packages/react-components/src/InputAddress/index.tsx
packages/react-components/src/util/toAddress.ts

Some apparent misunderstanding on indices are spreading and since the apps UI has support for chains with `Address: 'LookupSource'` people are misinterpreting the config of chain such as Kusma and Polkadot.
For these it seems there is an effort ongoing (as per txs on-chain) to registering indices and expecting it to work in the situation where `Address: 'AccountId'`. It doesn't and there is no space-savings, featuring only (a) vanity & (b) lookups to address book.
To protect users against themselves using functionality not built into the UI (indices registration), take a blanket approach and just always skip indices as destinations.

No indices lookups anywhere, only on address book

---

packages/page-settings/src/I18n/index.tsx

This is bug fix.
On the settings page, when I select a language, the old value remains.
I think this is because the browser language is not initialized.
In my case, if I select Korean and then Japanese, the old value remains.
(My browser language is 'ja')

fill in all empty values in all languageCaches.

---

packages/page-staking/src/Actions/Account/SetRewardDestination.tsx
packages/page-staking/src/Actions/Account/index.tsx
packages/page-staking/src/Actions/constants.tsx
packages/page-staking/src/Actions/index.tsx
packages/page-staking/src/Actions/partials/Bond.tsx
packages/page-staking/src/Actions/types.ts
packages/page-treasury/src/Tips/Tips.tsx
packages/react-hooks/src/types.ts
packages/react-hooks/src/useOwnStashInfos.ts

Part of https://github.com/polkadot-js/apps/issues/3354
Allows -
- display in staking actions
- allows changing once set
(Initial set assumed via extrinsics)

Display reward destination for isAccount

---

package.json
packages/page-contracts/package.json
packages/react-api/package.json
packages/react-components/src/styles/index.ts
packages/react-signer/src/TxSigned.tsx
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/3698
Caveat: chains needs to have the system.accountNextIndex` RPC available (Most new generations chains do have it, however it is generally an optional RPC. It is available on chains such as Polkadot, Kusama, Kulupu and others

Determine nonce via accountNextIndex

---

packages/page-council/src/thresholds.ts

In the current runtime it's changed to 0.5. It's planned to be changed back (of course, given the community agrees) to 0.8 when we get `MoreThanMajorityThenPrimeDefaultVote`.

Update Kulupu treasury threshold

---

packages/apps-config/src/api/spec/crab.ts
packages/page-staking/src/Query/ChartStake.tsx
packages/page-staking/src/Query/util.ts
packages/page-staking/src/useSortedTargets.ts

This applies a fix to the Darwinia Crab types on Indv. Exposure types. Additionally it makes sure the apps UI doesn't crash where eg total is not found. (Fields are different)
cc @WoeOm

Update Darwinia Crab IndividualExposure types

---

packages/react-components/src/Expander.tsx

I had a look at the account creation, Council motions, payout.. and couldn't notice any break.
Was like this
Is now:

Fix overflow in democracy proposal (polkadot)

---

packages/react-components/src/Expander.tsx

As per https://github.com/polkadot-js/apps/pull/3739#issuecomment-696671595
Funnily enough, it actually has (mostly) been scrubbed from the code anyway.

Filter #<weight>...</weight> from metadata

---

package.json
packages/apps-config/src/api/chain/beresheet.ts
packages/apps-config/src/api/spec/edgeware.ts
packages/apps-config/src/api/spec/index.ts
packages/page-contracts/package.json
packages/react-api/package.json
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/3752
Replaces & closes https://github.com/polkadot-js/apps/pull/3753
This is similar to #3753 with a couple of changes -
- it pulls in the latest API with a filter for null keys (there are really worrying, I'm hoping it is not a long-term issue, but rather just part of the initial migration - only seen here)
- The Mainnet types (since they are still previous-gen) now pulls in Beresheet which is current. As soon as the library gets update, this needs adjustment
As it stands it does make the UI appear, but since some of the keys are non-decodable, there is bound to be inaccuracies, not exactly sure what they are atm.
cc @drewstone

Bump API & Edgeware types

---

packages/page-accounts/src/Sidebar/Sidebar.tsx

Now looks like this (it was originally unreadable in white on white):

Style identity bar for dark theme

---

packages/page-contracts/src/shared/Messages.tsx

Fix contract metadata backround in dark mode

---

packages/apps/public/locales/zh/translation.json

here `sudo` has been translated to `undo`, `撤销` means `cancel` or `undo` in Chinese and nothing to do with `sudo`...

Fix an important translation error in Chinese

---

packages/apps-electron/src/main/ipc-main-handler.ts
packages/apps-electron/src/main/register-ipc-handler.ts

Frankly, I don't know how this could've ever worked... 😮 
Currently, no information is passed from main to renderer. So account is saved on disk, but nothing can be loaded. This change fixes it.

Fix IPC communication in Electron account store

---

packages/page-staking/src/Actions/partials/Bond.tsx

Closes https://github.com/polkadot-js/apps/issues/3954
For some reason only the change/set rewards destination had the capability to set the account.

Allow selection of payment destination

---

packages/page-rpc/src/Rpc/Selection.tsx
packages/react-signer/src/index.tsx

https://github.com/polkadot-js/apps/issues/4079 - actually added the useMemo before even attempting to debug and then couldn't reproduce. Not sure how it worked in the past.
Additionally fixes the RPC state updates in the signer.

useMemo in RPC params

---

packages/apps-config/src/api/spec/dusty.ts
packages/apps-config/src/api/spec/index.ts

This PR updates the Dusty Plasm Network type definitions and separates the types from the main network to the test network (Dusty). Notably, the Dusty network implements the following types:
- dapps staking
- ovm
- plasm rewards
- plasma
and it also removes the `RefCount` type which is specific to the main network of Plasm.

added plasm dusty type definitions

---

packages/react-components/src/Status/index.tsx
packages/react-signer/src/TxSigned.tsx

Enzyme signing doesn't return an error object, ensure that when an error string is received, it is still displayed.

Display error.message || error (when string is thrown)

---

packages/page-accounts/src/modals/Create.tsx
packages/page-settings/package.json
packages/page-settings/src/Developer.tsx
packages/react-api/package.json
packages/react-api/src/Api.tsx
packages/react-api/src/urlTypes.ts
packages/react-components/src/Button/Group.tsx
packages/react-components/src/CopyButton.tsx
yarn.lock

Closes https://github.com/polkadot-js/apps/issues/4187

Sharing of user types

---

packages/react-components/src/Tooltip.tsx

Hi,
I found that all modal tooltip is now not displayed.
I debugged it and found that the z-index defined by ui-Tooltip was overwritten.  Now the z-index is 999, which is less than the modal's z-index 1000, so tooltip is not displayed. So I manually set the z-index to 1002 again to solve the problem.

fix tooltip z-index

---

packages/page-staking/src/Targets/index.tsx

Because the media query width set in the table body is 1400 and the media query width set in the table head is 1500, there will be problems with the display when the width is between 1400 and 1500
https://github.com/polkadot-js/apps/blob/master/packages/page-staking/src/Targets/Validator.tsx#L116

fix media query width

---

packages/apps/public/locales/en/app-bounties.json
packages/page-bounties/src/Bounties.tsx
packages/page-bounties/src/Bounty.tsx
packages/page-bounties/src/BountyClaim.tsx
packages/page-bounties/src/BountyCreate.tsx
packages/page-bounties/src/helpers/index.tsx
packages/page-bounties/src/helpers/isClaimable.spec.ts
packages/page-bounties/src/helpers/isClaimable.ts

This PR adds Claim button to the bounty list, which allows beneficiary to claim the payout. The button is visible only if among accounts exists beneficiary, otherwise it's not rendered. Clicking the button performs the claim transaction from the beneficiary account.

Claim payout from bounty list

---

packages/apps-config/src/api/spec/kulupu.ts

The runtime just today was updated to include the new MultiAddress support https://github.com/paritytech/substrate/pull/7380 and hence we need to update the type definitions.

Update Kulupu Address and LookupSource definitions

---

packages/page-contracts/src/useWeight.ts
packages/page-staking/src/Payouts/PayButton.tsx

The per calls extrinsic value exhausts block limits, stick to 65%
Closes #4280

Use maxBlock value for weight limits

---

packages/page-bounties/src/useCounter.ts

To correctly display the number of active bounties we should switch to `DeriveBounties` because `bountyCount` returns a number of all bounties ever created.

Use derive call in Bounty's useCounter

---

packages/apps/src/Menu/Item.tsx
packages/page-calendar/src/Day.tsx
packages/page-calendar/src/Month.tsx
packages/page-calendar/src/UpcomingEvents.tsx
packages/react-components/src/styles/index.ts

Still not 100% on the very light items such as Moonbeam and Centrifuge (it could use an increase in opacity there), but now good on the very dark ones such as Kusama.

Menu hover adjustments (only background)

---

package.json
packages/page-accounts/package.json
packages/page-contracts/package.json
packages/page-parachains/src/Overview/Actions.tsx
packages/page-parachains/src/Overview/Parachain.tsx
packages/page-parachains/src/Overview/ParachainList.tsx
packages/page-parachains/src/Overview/Proposal.tsx
packages/page-parachains/src/Overview/Proposals.tsx
packages/page-parachains/src/Overview/Upcoming.tsx
packages/page-parachains/src/Overview/index.tsx
packages/page-parachains/src/Overview/types.tsx
packages/page-parachains/src/Overview/useProposals.ts
packages/page-parachains/src/Overview/util.ts
packages/page-parachains/src/modals/Propose.tsx
packages/react-api/package.json
yarn.lock

As per https://github.com/paritytech/polkadot/pull/2243

Parachain proposals

---

packages/apps/public/locales/zh/translation.json

string 'comm.' is used in https://github.com/polkadot-js/apps/blob/0360df1ccf47886c1247d0fa6d67578b230bbcb6/packages/page-staking/src/Targets/index.tsx#L274
here it is abbr of 'commission' which in Chinese should be '佣金'

fix Chinese translation of 'comm.'

---

packages/apps-config/src/api/spec/plasm-parachain.ts

In parachain `Address` should be `AccountId` for correct XCM work.

Fix account type in plasm parachian

---

packages/react-components/src/styles/semantic.ts

Hi, a little change, as in the picture:

Adjust the popup's arrow according to the theme

---

packages/page-bounties/src/BountyActions/AwardBounty.tsx
packages/page-bounties/src/BountyActions/ProposeCuratorAction.tsx
packages/page-bounties/src/BountyActions/SlashCurator.tsx

It will fix the problem with selecting accounts in propose curator and award bounty actions.

Remove type prop from address inputs in app-bounties

---

packages/page-staking/src/Targets/Summary.tsx
packages/page-staking/src/Targets/index.tsx

Display information for https://github.com/polkadot-js/apps/issues/4575 on targets (rolling, so updated each era)
The dover-tails with the information messages on the account actions when the stake is lower (not included) for any validator, so it tracks the changes there.

Add min staked to targets

---

packages/page-staking/src/Actions/Account/InputValidateAmount.tsx
packages/page-staking/src/Actions/NewNominator.tsx
packages/page-staking/src/Actions/partials/Bond.tsx

Closes https://github.com/polkadot-js/apps/issues/4575
There are now 3 points of info -
- account actions will display a warning where it has not ben applied 
- min active is displayed in targets
- when bonding it checks against the min
Since the targets are always adjusting, the account actions is actually the most-useful (together with targets)

Check nomination amount on intial set

---

packages/apps-config/src/settings/ethereumChains.ts

Moonbeam now has a new network name (spec name) that needs to be added to the list of ethereum network

add moonbeam spec name

---

packages/apps-config/package.json
packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/api/spec/snowbridge.ts
yarn.lock

[Snowbridge](https://github.com/Snowfork/polkadot-ethereum) is a trust-minimized bridge between Polkadot and Ethereum.
The type definitions are sourced from our [@snowfork/snowbridge-types](https://www.npmjs.com/package/@snowfork/snowbridge-types) package, located in our repository [here](https://github.com/Snowfork/polkadot-ethereum/tree/main/types).

Add type definitions for Snowbridge

---

packages/apps-config/src/api/spec/kulupu.ts

This is due to the introduction of pallet-lockdrop.

kulupu: add CampaignIdentifier type for runtime 17

---

packages/apps-config/src/endpoints/testing.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

Closes https://github.com/polkadot-js/apps/issues/4801
- Alphabetical in all cases
- match network name to actual name retrieved
- fix info for endpoints (as per logo name)

Fix ReAlis

---

packages/apps-config/src/api/spec/kilt.ts
packages/apps-config/src/endpoints/testing.ts
packages/apps/public/locales/en/apps-config.json

This PR updates the KILT types to be compliant with our upcoming (~1h from now) release 0.24.0 running on Substrate 3.0.0. It also adds the _KILT_ prefix to the `Mashnet` chain name.
According to my tests I suppose the `Address` and `LookupSource` keys are not required to be set manually anymore? If this is not the case, we would like to re-add them before this PR is merged. The same applies to the RefCount, for which we just follow Substrate.

Update KILT types for upcoming release

---

packages/apps-config/src/api/spec/dusty.ts

**Changes**
From now `SessionKeys` contains 3 elemets.

Fix Dusty chain types

---

packages/apps-config/src/api/spec/index.ts

Test the chainx and zenlink, The correct specnames:
chainx is  "chainx-parachain": https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsherpax.chainx.org#/rpc
zenlink is  "dev-parachain":  https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-parachain.zenlink.pro#/rpc

Match the correct specName by getRuntimeVersion

---

packages/apps-config/src/api/spec/kilt.ts

This PR adds necessary types for XCMP which are required for the WS Connection, otherwise errors are thrown.

feat: add KILT XCMP types

---

packages/react-params/src/Param/Hash160.tsx
packages/react-params/src/Param/Hash256.tsx
packages/react-params/src/Param/Hash512.tsx

The u8a, when wrapped as an Option, gets handled incorrectly in these cases.
Closes https://github.com/polkadot-js/apps/issues/5070

Hex-only for H160/256/512 values

---

packages/react-signer/src/PaymentInfo.tsx
packages/react-signer/src/Transaction.tsx
packages/react-signer/src/TxSigned.tsx

Closes https://github.com/polkadot-js/apps/issues/5100
2 issues -
- the proxy address above was never checked for the fees (only account being proxied, same would apply to eg. multisig)
- fees should come from available, but free balance should be checked for existential

Adjust fee calc for signer

---

packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/api/spec/vodka.ts
packages/apps-config/src/endpoints/testing.ts

This adds the Vodka testnet endpoint and type definitions, Neatcoin's testnet.

Add Vodka testnet endpoint

---

packages/page-staking/src/index.tsx
packages/react-hooks/src/useAccounts.ts

Trying to solve a frustration: opening a "tab-level" url directly redirects to root of the section (eg. `#/staking/actions`).
It happens because accounts are not loaded at first, and the lack of accounts marks the "actions" tab as hidden. This in turn triggers a `window.location.hash` change to `/staking` root.
Provided solution checks whether accounts are loaded and only then hides (or not) the tab.

Check if accounts are loaded before hiding a tab in staking

---

packages/apps-config/src/api/spec/zeitgeist.ts

Adding an alias for the Tokens pallet so that the clash of `AccoundData` types between that pallet and Balances' AccountData doesn't cause Apps to complain. Something of a stop-gap for now until we start generating the full bundle in our own package.

Add tokens alias for Zeitgeist

---

packages/apps-config/src/api/spec/dusty.ts

Added `AccountInfo` type definition for balance display issues.

Update Dusty chain type

---

packages/page-settings/src/I18n/index.tsx

Currently when going to #/settings/i18n we have the spinner loading forever.
It is caused by 404 on locales/pl/translation.json missing.
bug introduced by this PR:
https://github.com/polkadot-js/apps/pull/4724
To avoid this in future and instead of creating a locales/pl/translation.json (that can be done in another PR) ii catch any error on retrieveJson and return an empty {}

Fix translations loading for ever

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

Adds KILT Parachain ID to the live parachains tab. Please note that the linked websocket address is not live yet.

feat: add KILT paraId

---

packages/apps-config/src/api/spec/index.ts

Previously, the redirection of the type definitions didn't set properly. This PR fixes that.

fix ma (from Manta Network) display

---

packages/apps-config/src/api/spec/plasm.ts

Adds type `AccountInfo: 'AccountInfoWithRefCount'` for Plasm Main Network.

[Plasm] Add AccountInfo type

---

packages/page-staking/src/Query/Validator.tsx

The validator stats page was not displayed correctly while in Dark theme, making it unreadable. (See attached before and after screenshots). This Pull request attempts to fix that, and I'd like some feedback. 
Thanks.

use selected theme in the validator stats page

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

This PR changes the Westmint RPC URL to use the one on the polkadot.io domain. 
You can validate using this link that this new RPC endpoint is active (although the chain is currently stuck due to an issue) : https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestmint-rpc.polkadot.io#/explorer

Change Westmint RPC URL

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

We had to deregister 2000 due to the wrong wasm blob, but I couldn't register it again
So updating to 2013
Shame I lost the special number!

update paraid for kylin

---

packages/page-calendar/src/useScheduled.ts
packages/page-parachains/src/Auctions/Auction.tsx
packages/page-parachains/src/Auctions/Bid.tsx
packages/page-parachains/src/Crowdloan/FundAdd.tsx
packages/page-parachains/src/useLeaseRanges.ts
packages/page-parachains/src/useWinningData.ts

We still had left-over hardcoded start + 3 for the ranges, correct these.
Also closes https://github.com/polkadot-js/apps/issues/5501

Calculate auction range correctly (no BN_THREE)

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

We want to test the KILT Spiritnet release candidate on Westend and will most likely be onboarded tomorrow. This PR
* Adds WILT to Westend 
* Renames KILT Mainnet to KILT Spiritnet
* Fixes unavailable WS address of Spiritnet to an available one

feat: add KILT to Westend

---

packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

We recently updated all working titles of our different chain types and realized some of them were never supported in the Polkadot Apps in terms of styling.

fix: logo and theme for KILT chains

---

electron-builder.yml

Apple requires explicit ask for permissions be configured in Info.plist.
See: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos?language=objc
Notes for the reviewer:
1. Testing: to easily remove camera binding for Polka Desktop: 
`sudo tccutil reset Camera com.polkadotjs.polkadotjs-apps`
2. `yarn packElectron:mac` did not work for me unless I pinned electron-builder to some specific version, see: https://github.com/electron-userland/electron-builder/issues/5668

Fix electron qr scan issue on mac

---

packages/apps-electron/appleEntitlements/entitlements.mac.plist

Another attempt. This time extending the set of entitlements in use.

Fix electron QR camera permission on mac

---

packages/react-query/src/BlockAuthors.tsx

Change of function name for author mapping
- Moonshadow currently uses authorIds
- New version will use authorMapping

Fix author mapping call

---

docker/Dockerfile

The current Dockerfile script doesn't seem to be able to build successfully from the ground up. This PR fixes it:
* Install `ca-certificates`. Without it, it seems that every SSL requests would fail -- nodesource can't be fetched, npm can't install.
* Remove duplicate `nodejs` and `npm` package installation. `nodejs` comes from `nodesource` which includes the `npm` executable, and `npm` comes from Ubuntu. They conflict.

Fix docker build script

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

Small fix on the provider name, from "Purestake" to "PureStake".

Fix provider name

---

packages/react-api/package.json
yarn.lock

Just pulled the dependency from https://github.com/polkadot-js/apps/pull/5644 - this way we can merge this (no breakages) and avoid the constant conflicts.

Add @substrate/connect dependency

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

The endpoint is now up (See https://polkadot.js.org/apps/?rpc=wss://fullnode.altair.centrifuge.io#/explorer), so this can be marked as online now.

Re-enable Altair endpoint

---

packages/page-settings/src/types.ts
packages/page-settings/src/useChainInfo.ts

In order to be recognized by the extension as an ethereum chain

Add chainType to chainInfo

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

Had to de-register a parathread and as a consequence, the reserved parachain id was lost (it is not attached to my account anymore).
This PR reflects the new allocated ID.

Change parachain id of Zeitgeist

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

My apologies for the confusion. The last deployed WASM blob was non-deterministic due to the fact that the chain specification wasn't using a generated file and this situation could lead to bad future network updates.

Update Parachain ID of Zeitgeist

---

package.json
packages/react-api/package.json
yarn.lock

Fix conflicts in https://github.com/polkadot-js/apps/pull/5644
(Also means `@substrate/connect` is now `^` as per the linked PR, unneeded resolution removed)

Bump @substrate/connect

---

packages/react-api/package.json
yarn.lock

We deployed 7 more bootnodes which listen on TLS over the weekend for both kusama and polkadot. This should make connecting to polkadot and kusama much more reliable with substrate connect.  This PR bumps the version of @susbtrate/connect to pick up the new chainspecs that include those new bootnodes.

Upgrade @substrate/connect@0.3.16

---

packages/apps/public/locales/id/translation.json

"Nominator" is still "Nominator" in Bahasa Indonesia.

Fix typo in ID translation

---

packages/page-settings/src/Metadata/NetworkSpecs.tsx
packages/page-settings/src/types.ts

Both in the QR content and in the metadata UI.
Chaintype is either ethereum or substrate.
Necessary for the mobile app to create correct address type (as per paritytech/parity-signer#788)

Add chain type to metadata

---

packages/apps-config/src/links/subscan.ts

Just enable the link to Subscan for Shiden.

Set Subscan link for Shiden Network

---

packages/apps-config/package.json
packages/apps-config/src/endpoints/testing.ts
yarn.lock

Changes:
* Update dependency `@snowfork/snowbridge-types` in `packages/apps-config`
* Add endpoint for our testnet: `wss://parachain-rpc.snowbridge.network`
The changes have been tested using a local build of PolkadotJS-Apps. No type decoding errors were seen in the console after running our E2E tests against the parachain.

Update types and endpoint for Snowbridge testnet

---

packages/page-accounts/src/Sidebar/Sidebar.tsx

These changes will add `width: 100%;` to flags in sidebar.

Set width to flags

---

packages/page-accounts/src/modals/Transfer.tsx

Our users are complaining about accidentally making transfers that together with a fee are bigger than the account balance. Also currently it is inconvenient to check if a transfer together with a fee is lower than the balance. Because of that we thought about preventing users from making invalid transfers.
This PR passes `maxValue` prop for `InputBalance` set to `maxTransfer`. Now, when user tries to make a transfer that is too big the transfer button will be locked and the input field will be red. This will stop users from making this type of mistake and loosing fee in a process. Also now it is easier to check if a transfer is valid.

Add max transfer bound to transfer modal

---

packages/apps/public/locales/ar/translation.json
packages/apps/public/locales/en/app-democracy.json
packages/apps/public/locales/es/translation.json
packages/apps/public/locales/fr/translation.json
packages/apps/public/locales/id/translation.json
packages/apps/public/locales/it/translation.json
packages/apps/public/locales/ko/translation.json
packages/apps/public/locales/pt/translation.json
packages/apps/public/locales/ru/translation.json
packages/apps/public/locales/zh/translation.json
packages/page-democracy/src/Overview/Voting.tsx

This PR fixes a self-contradictory description to clarify how conviction locking works.
The original description,`Conviction locks do overlap and are not additive, meaning that funds locked during a previous vote can be locked again.` makes three claims regarding conviction locks:
* They do  overlap
* They is (are) additive
* funds locked during a previous vote can be locked again
The first and third claim are correct and consistent with one another, but the second is opposite. If locks were additive then previously locked tokens could not vote again.

Clarify conviction locking

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

[Dwellir](https://dwellir.com/) runs RPC nodes for both Polkadot and Kusama relay chains. We want to contribute by making them public available!

Added Dwellir RPC endpoints for Kusama and Polkadot relay chains

---

packages/apps-config/package.json
yarn.lock

Sorry for my send PR for bumping our typedef frequently,
but our users report
```
Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding session.setKeys:: Struct: failed on args: {"keys":"Keys","proof":"Bytes"}:: decodeU8a: failed at 0x9806e123fe7d92fa… on keys: (AccountId,AccountId,AccountId,AccountId):: decodeU8a: failed at 0x00… on : AccountId:: Expected at least 32 bytes (256 bits), found 1 bytes
```
This bumping overrides `Keys` to fix it

bump @phala/typedefs

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

Closes https://github.com/polkadot-js/apps/issues/6101
It has been unreachable for days now with no DNS

isUnreachable

---

packages/apps-config/src/links/index.ts
packages/apps-config/src/links/polkassembly.ts

Fixes https://github.com/polkadot-js/apps/issues/6124
* Replaces default export of Polkassembly with PolkassemblyIo
* Adds PolkassemblyNetwork endpoint for Bifrost, Karura, KILT, Khala, Moonriver parachains (tested at https://*.polkassembly.network)
cc @niklabh

feat: add Polkassembly.network endpoint

---

jest-slow.config.cjs
jest/globalSetup.cjs
jest/globalTeardown.cjs
jest/substrateTestsGlobal.ts
packages/page-accounts/src/CreateAccount.slow.spec.tsx

Currently the slow (nightly) tests fail on first Typescript import statement (`import './Backend'` in `i18n`). Jest resolvers tries to fetch this module as `Backend.cjs` and obviously fails.
I confirmed it has nothing to do with what we do in the `globalSetup` file. Exporting an empty function gives the same result.
I didn't get to the bottom of the `jest` bug, but found a solution nonetheless. Changing module type from TypeScript to CommonJS for the `globalSetup` file apparently helps.

Restore slow tests

---

packages/apps-config/src/endpoints/testing.ts
packages/apps-config/src/endpoints/testingRelayRococo.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

Disable the networks that are currently not reachable, as reported by the nightly test run.
Closes https://github.com/polkadot-js/apps/issues/6181

Disable unreachable networks.

---

packages/page-signing/src/Sign.tsx

Align with https://github.com/polkadot-js/extension/pull/743
(Verification is already done, checking both paths in the underlying `signatureVerify` function)

Align signing with extension (w/ <Bytes> wrapper)

---

packages/react-params/src/Param/findComponent.ts

Also closes https://github.com/polkadot-js/apps/issues/6199 (additional lookups for non-primitive `Vec` types)

Support lookupName in UI component lookups

---

packages/react-query/src/FormatBalance.tsx

Closes https://github.com/polkadot-js/apps/issues/6237
`labelPost` is now displayed the same in all paths

Fix everything + indicator formatting

---

packages/apps-config/src/endpoints/testing.ts

node address was changed in previous PR, just realised its still set to disabled

re-enable dock testnet endpoint

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This PR is to add a Polkadot and Kusama endpoints built through a W3F grant [Load Balanced Endpoints Operations](https://github.com/w3f/General-Grants-Program/blob/master/grants/speculative/load_balanced_endpoints_operations.md).  Status page for the endpoints can be found at http://status.substrate.geometry.io/ with links to additional dashboards.  The endpoints are run in two clusters on autoscaling groups with optimized nvme backed instances so they should be very robust.  Medium article is being submitted for review that will advertise the endpoints use.

Add geometry labs endpoints for polkadot and kusama

---

packages/apps-config/src/endpoints/testing.ts

We are migrating this address: https://alephzero.org/blog/migrating-to-new-infrastructure/. The new address is already operational.

Update the Aleph Zero testnet address

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

- manta node names corrected
- removed `isUnreachable` flag as nodes are now deployed and accepting wss requests

correction to manta node names

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

We got caught out by 
https://github.com/substrate-developer-hub/substrate-docs/issues/513
So had to create a new genesis/wasm with a new para id
Producing blocks now so hopefully no more changes!

change para id to 2112

---

packages/apps-config/src/endpoints/production.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

Integritee has launched their mainnet as solochain today.
This PR lists Integritee under Live Networks

Add Integritee Live Mainnet

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

We have identified the problem with the RPC service and have developed a scaling solution for it, until the bottleneck is fixed in the service code.
For more information see:
https://github.com/paritytech/polkadot/issues/4064

Re-activating Dwellir Kusama RPC

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

New Robonomics Network ParaID used because of new Polkadot 0.9.12 based runtime.

Update Robonomics ParaID

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

Tick parachain was redeployed with new DNS name.
resolves https://github.com/polkadot-js/apps/issues/6656

Update Tick rococo rpc endpoint

---

packages/apps-config/src/api/constants.ts
packages/apps-config/src/endpoints/testingRelayRococo.ts

This should also let users teleport ROC to Statemint/Canvas. See for example, ROC to Canvas teleports as described in the [Canvas README](https://github.com/paritytech/canvas#rococo-deployment).
However in my tests, my changes fail to bring up the Teleport tab for the Rococo network.

Update Rococo parachain URLs and enable teleport

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

On 22.12.2022 rococo network was reset.  Only rococoStatemint and rococoCanvas will be present after reset.

Remove tick trick track parachains

---

packages/page-parachains/src/Teleport.tsx
packages/page-parachains/src/index.tsx

As per https://github.com/polkadot-js/apps/issues/6742#issuecomment-1002043647
Since `limitedTeleport` it is not only the hard-coded values anymore, so it is overshooting the fees applied on the destination side - this is not the sending side, but rather the old 3b weight * the destination chain fee. Until we have xcm estimations on the receiving side (issue logged), we'd rather not confuse. 
(For older chains the value is still applicable, but as of now since all the relay chains have been updated, it makes more sense to remove it)

Remove teleport destination fees

---

packages/apps-config/src/endpoints/index.spec.ts
packages/apps-config/src/endpoints/production.ts
packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testing.ts

Endpoints can only be one of a type, i.e. it is a parachain on Kusama or a production network, not both.
A number of duplicates have been added, this PR adds a test for them and then also removes the duplicated entries, e.g. if a parachain, keep it in parachains when duplicated elsewhere.

Check for duplicate urls (eg parachain & production)

---

packages/page-parachains/src/Teleport.tsx

As the destination transfer fee estimate is removed in https://github.com/polkadot-js/apps/pull/6745/ , it is resourceful to update the message mentioning that the teleported amount is subject to destination transfer fees along with the transfer fees at the source (and the balance should be above Existential Deposit, if the recipient's account is new

Clarify Teleport transaction fee message

---

packages/page-accounts/src/Sidebar/AccountMenuButtons.tsx
packages/page-accounts/src/modals/Transfer.tsx

See #6780:
- handle if `tx.balances` or `consts.balances` are undefined on Accounts page and Transfer model
- don't show Send button on sidebar if `tx.balances` is undefined

don't crash transfer model if balances is not available

---

packages/page-accounts/src/modals/MultisigCreate.tsx

This PR adds a new file upload field, so it could be possible to upload a list of multisig signatories
When the file gets uploaded it hides the current accounts selection row and displays found addresses in the provided JSON file.

Allow to upload a JSON file with the list of multisig signatories

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

This PR activates the ZeitgeistPM endpoint within the list of Kusama parachains.
The endpoint is reachable now: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-0.zeitgeist.pm#/explorer

Enable Zeitgeist and Subsocial

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

since runtime 9016, Encointer is a trusted teleporter. This PR adds UI functionality for this
https://github.com/paritytech/polkadot/blob/41ab002d7451766324a9f314fee11c9c53314350/runtime/westend/src/xcm_config.rs#L75-L85

make encointer teleporter on westend

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

this change removes individual manta/calamari network nodes in favour of a latency based dns load-balancer url that automatically selects a healthy node with the lowest latency for the request client

calamari endpoints: switch to load balancer

---

packages/page-contracts/src/Codes/Upload.tsx
packages/page-contracts/src/Contracts/Deploy.tsx

Constructors are not payable by default so the instantiation was failing with `ContractTrapped` when passing any value (endowment)
Fixes https://substrate.stackexchange.com/questions/120/polkadot-canvas-testnet-contract-deploy-error-contracts-contracttrapped
The instantiation still fails with `NewContractNotFunded` because Canvas needs an update (coming soon)
Not sure this PR is needed though, the error might be fixed with the Canvas update.

Fix contract trapped

---

packages/react-components/src/CallExpander.tsx

This just plasters over the effects of https://github.com/polkadot-js/apps/issues/6981
Basically in this case it seems like the Call is invalid and incorrectly extracted - it needs investigation as to "why" and a fix for the root cause, but for the time being just don't display that information when invalid, i.e. "don't crash"

Ensure CallExpander doesn't crash

---

packages/apps-config/src/endpoints/testing.ts

Node responsible for the RPC had additional heavy traffic, thus failing health-checks. This is load-balanced now, so should be good to reenable.

fix: Opportunity chain re-enabled

---

packages/page-parachains/src/Teleport.tsx

Cleans up all the previous-runtime-detection magic that would make things like https://github.com/polkadot-js/apps/issues/6922 easier

Only use current-gen limitedTeleportAssets

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

The Moonbeam Foundation has recently changed their URL structure for public APIs. This change reflects that.

Updated Moonbeam Foundation's Moonriver endpoint

---

CHANGELOG.md
packages/apps-config/src/api/spec/interbtc.ts

Closes https://github.com/polkadot-js/apps/issues/7065
Actually this whole derive as added needs a rip-out and re-do. This issue is because the code bypasses the type-checker with `any` it creates issues such as this. Where the type-checker can be of help is is helpless and invalid data structures are returned.

Align interlay derives with actual API (outdated)

---

packages/page-staking/src/Actions/Account/BondExtra.tsx

The label 
**additional bonded funds** 
is shown when users are about to bond additional funds. It suggests that the funds are already bonded which is not the case. Therefore, I propose to change the content of the label to 
**additional funds to bond**.

changing 'tense' of label, because funds are not yet 'bonded'

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

We have stopped our westend ( api.westend.encointer.org ), therefore deleted from config.

[encointer] remove westend

---

packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

When connecting to Canvas on Rococo the logo was missing and the default styling was displayed.

Fix Canvas styling

---

packages/page-parachains/src/Crowdloan/Fund.tsx

The logic in the crowdloan pallet is:
```rust
// Only allow dissolution when the raised funds goes to zero,
// and the caller is the fund creator or we are past the end date.
let permitted = who == fund.depositor || now >= fund.end;
let can_dissolve = permitted && fund.raised.is_zero();
ensure!(can_dissolve, Error::<T>::NotReadyToDissolve);
```
https://github.com/paritytech/polkadot/blob/master/runtime/common/src/crowdloan/mod.rs#L559
As long as the fund `hasEnded`, anyone should be allowed to call "Close" to dissolve a crowdloan.

Allow Crowdloan Dissolve by Anyone When Ended

---

packages/page-accounts/src/Vanity/index.tsx

Closes https://github.com/polkadot-js/apps/issues/7104

Fix vanity readability

---

packages/apps-config/src/api/spec/index.ts

Not included as part of https://github.com/polkadot-js/apps/pull/7226
Closes https://github.com/polkadot-js/apps/issues/7227 (team-reported)

Add missing mangata-parachain types mapping

---

packages/apps/public/locales/ar/translation.json
packages/apps/public/locales/en/app-settings.json
packages/apps/public/locales/es/translation.json
packages/apps/public/locales/fr/translation.json
packages/apps/public/locales/hi/translation.json
packages/apps/public/locales/id/translation.json
packages/apps/public/locales/it/translation.json
packages/apps/public/locales/ko/translation.json
packages/apps/public/locales/pt/translation.json
packages/apps/public/locales/ru/translation.json
packages/apps/public/locales/ur/translation.json
packages/apps/public/locales/zh/translation.json
packages/page-settings/src/Metadata/NetworkSpecs.tsx

Related to issue https://github.com/polkadot-js/apps/issues/7251
The current long text is not aligned with the SS58 Prefix type used in substrate, cumulus and parachains. 
The text update only affects the English version and translated versions will have to be updated by the community.

Updates the ss58 prefix long description to align with substrate (u16)

---

packages/page-accounts/src/Sidebar/AddressSection.tsx
packages/page-accounts/src/Sidebar/Sidebar.tsx

Closes #7209 
Added the copy icon in the sidebar, on the right side of the address.
When the user copies the icon changes to a "check" icon until the user leaves the button area.

Add "Copy" icon to the User Sidebar

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Polkadex is changing our para id from 2036 to 2040 for the upcoming crowdloan.

Update Polkadex para id

---

packages/react-api/src/Api.tsx
yarn.lock

Susbtrate light client is not working due to wrong parameter provided in `ScProvider`.
Since latest API changes, ScProvider should either receive a `WellKnownChain` or a stringified chainspec

Fix broken substrate connect light client

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

This will work only after [Substrate connect fix](https://github.com/polkadot-js/apps/pull/7362) is merged

Add support of light client to Rococo

---

packages/page-democracy/src/Overview/Proposal.tsx
packages/page-democracy/src/Overview/Proposals.tsx
packages/page-democracy/src/Overview/ReferendumVotes.tsx
packages/react-components/src/ExpanderScroll.tsx
packages/react-components/src/Table/index.tsx
packages/react-components/src/index.tsx

Dedupe new scrollable expander introduced in https://github.com/polkadot-js/apps/pull/7360 into `ExpanderScroll` - this allows actual application of it inside all areas where the address list is displayed (e.g. council voting, staking, etc.)

Dedupe into ExpanderScroll

---

packages/page-staking/src/Actions/Account/ListNominees.tsx

Part of https://github.com/polkadot-js/apps/issues/7449
However, we need to find a way of detecting these and just disabling.

Cater for non-standard nominee maps

---

packages/page-extrinsics/src/Decoder.tsx
packages/page-extrinsics/src/index.tsx
packages/page-extrinsics/src/types.ts
packages/react-components/src/Input.tsx

Why: there are many locations where you want to tee up a transaction for submission. There are many testing situations where this would make a lot of integrations slicker. Arguably POST could be accepted as well as GET because some call datas could be long but the vast majority are not and ease of use is important (so even if POST was allowed I would still like GET to work).

calldata hyperlink

---

packages/apps-config/src/api/spec/joystream.ts

Update types for Joystream testnet node due to the recent Rhodes [runtime upgrade executed at block `697500`]( https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.joystream.org%3A9944#/explorer/query/697500).
Types based on: https://github.com/Joystream/joystream/blob/master/types/augment/all/defs.json

Update Joystream testnet types (Rhodes release)

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

We had to resolve some certificate issues and `wss://rpc-parachain.bajun.network` is reachable now.
Thanks

Fix websocket and remove `isUnreachable` for bajun-kusama

---

packages/apps-config/src/endpoints/index.spec.ts

Adjust duplicate url check w/0 trailing / - this prevents issues such as https://github.com/polkadot-js/apps/issues/7620 which should have been caught as part of the test

Duplicate url check w/o trailing /

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testing.ts

This PR ads [Blast](https://blastapi.io/) as a provider for Moonbeam, Moonriver and Moonbase. Also, it modifies some info and sort providers alphabetically (Moonbeam Foundation's first)

Adds Blast API as Provider

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This PR enables litentry endpoint -- now `wss://rpc.litentry-parachain.litentry.io` should be reachable.

Enable litentry endpoint

---

packages/apps-config/src/links/subsquare.ts
packages/page-democracy/src/Overview/External.tsx
packages/page-democracy/src/Overview/Externals.tsx

Happy to tell that we have implemented subsquare for kusama. https://kusama.subsquare.io/
Do you think we should also add external links for external proposals? We have links to the list and each item.

Add subsquare external links for Kusama

---

packages/apps-config/src/endpoints/production.ts
packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testing.ts

Pinknode endpoints for the following networks have been added or modified:
1) Astar
2) Shiden
3) Shibuya
4) Moonbeam
5) Moonriver
6) Moonbase Alpha
7) Polkadex
8) Khala
9) Nodle

Added / Modified Pinknode Endpoints

---

packages/apps-config/src/settings/ethereumChains.ts

we need those two armonia-eva` and `armonia-wall-e` as running Ethereum-liked chain in apps.

add `armonia-eva` and `armonia-wall-e` for ethereumChains

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Dwellir is removing support for Parallel and Parallel Heiko RPC endpoints. Before doing so it's important we remove them publicly from Polkadot.js.org

Dwellir is removing support for Parallel and Parallel Heiko RPC

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

Hi,
the ParaID 3025 is now registered for helixstreet (historically Arctic). The rpc-endpoint is live; the parachain didn't connect yet in the current slot due to issues with the genesis block - will recreate WASM and Genesis Files. 
The Arctic entry is here removed and the helixstreet entry entered alphabetically based on the text field.
Thx in advance.
Tom

Update testingRelayRococo.ts / helixstreet ParaID 3025 ( formerly Arctic)

---

packages/page-staking/src/useSortedTargets.ts

Closes https://github.com/polkadot-js/apps/issues/7794
(the line seem to have moved recently alongside other adjustments - we don't calculate these historically since we don't have access to full stake until validating, same as all in the waiting list)

Adjust logic location for skipRewards

---

packages/react-params/src/Param/Enum.tsx

Close https://github.com/polkadot-js/apps/issues/7801 
The issue sadly misses all the critical info and is therefore non reproducible, so it is scratching in the dark. However, it _seems_ related to this. Can be re-opened if there is ever reproducible steps and this doesn't address the hunt in the dark (which includes the actual chain)

Allow for pre-set Enum changes

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

RadiumBlock would like to bring up our public Polkadot and Kusama enpoints in Curie, our high performance, highly distributed Endpoint Delivery Network

Add RadiumBlock Polkadot/Kusama Enpoints

---

packages/apps-config/src/settings/ethereumChains.ts

we (altlayer) support two runtime spec-name for ethereum chain:
1. alt-producer
2. flash-layer

add altlayer's ethereum chain to `ethereumChains`

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

In preparation for the Collectives common good parachain in Polkadot, collectives parachain will be tested in Westend.
There's no official logo as this moment.

Westend Collectives Parachain RPC

---

packages/apps-config/src/links/singular.ts

Issue: Singular app domain name was changed after the release of RMRK 2.0 and singular.rmrk.app being sunsetted and uniques will soon be available only on singular.app
Change: update Singular app URL to latest version for both Kusama (rmrk nfts) and Statemine (uniques)

update singular url to singular v2

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

We are removing our own rpc node and will use onFinality's rpc node for the time being.

Remove Bit Country RPC node

---

packages/apps-config/src/endpoints/testingRelayRococo.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

This PR makes https://github.com/polkadot-js/apps/pull/7936 obsolete.

Add Amplitude to Rococo

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

The GM parachain was already in the apps ui, but it was set to unreachable because the endpoint wasn't up yet, now it's been deployed, and it should be reachable.

Enable GM Parachain's endpoint

---

packages/apps-config/package.json
yarn.lock

Update KILT types to v0.2 which includes support for RPC and runtime calls extensions.

chore: update KILT types to v0.2

---

packages/apps-config/src/endpoints/testingRelayRococo.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/index.ts

This PR adds Tinkernet Rococo Testnet, required by this Rococo slot request issue: https://github.com/paritytech/subport/issues/461

Add Tinkernet Rococo

---

packages/apps-config/package.json
packages/apps-config/src/api/spec/logion.ts
packages/apps-config/src/api/typesBundle.ts
yarn.lock

This PR defines new types for an upcoming logion runtime upgrade and fixes the encoding/decoding of `OpaquePeerId` with logion chains (see #8113).

Update logion types

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

Changes the `paraId` to that used by Zeitgeist on Kusama and updates the testnet name.
Additionally, it enables the rpc endpoint for the Parachain: `wss://roc.zeitgeist.pm`. ~The endpoint is currently being set up, I'll ping once it's ready.~

Update Zeitgeist entry for Rococo

---

packages/apps-config/src/endpoints/production.ts

Messed up DNS settings during a change. Oops!
It should be back up now.

Re-enable Neatcoin endpoint

---

packages/apps-config/package.json
packages/apps-config/src/api/spec/khala.ts
packages/apps-config/src/api/typesBundle.ts
yarn.lock

Some (ancient) blocks can't be decoded for example https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpublic-rpc.pinknode.io%2Fkhala#/explorer/query/100786
This PR fix typedef of Khala that fix the problem

Update and fix Khala typedef

---

packages/react-api/src/light/kusama/shiden.json
packages/react-api/src/light/polkadot/astar.json

These updates should help when `smoldot` also gets updated.

Updates to Astar and Shiden bootNodes

---

packages/apps-config/package.json
yarn.lock

Unfortunately, the KILT Protocol type definitions need to rolled back from version `0.*.*` as any `1.*.*` version (introduced in #8277) currently includes a minor bug and is therefore marked as deprecated.

fix: rollback KILT custom type decorations

---

packages/apps-config/src/ui/identityIcons/index.ts

Hi, we'd like to add an identicon override for `litentry-node` as we prefer `polkadot` style.

Add identicon override for litentry-node

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

Removed Dwellir RPC endpoint from Robonomics parachain due to it being shut down soon.

Updated Robonomics RPCs

---

packages/apps-config/src/endpoints/production.ts

Changing the CW Labs' endpoint temporarily to an upgraded solo node. Given that it's not a load-balanced RPC, changing the display priority for now.

Updating one of the RPC endpoint for Edgeware

---

packages/react-params/src/Param/BaseBytes.tsx
packages/react-params/src/Param/Bytes.tsx

Correctly encoded `Option<Bytes>` by pre-pending 1 for valid options.

Fix `Option<Bytes>` encoding

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

The endpoint for Quartz became available again.

Add back OnFinality endpoint for Quartz

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

In the commit I labeled it as stake.plus endpoints by accident when it's actually a geodns endpoint split between multiple sites as part of the proof of concept milestone for the infrastructure builders program. This program will be open for RFC/RFQ soon. You can view the future program proposal below. This endpoint is currently split between one site located in US-East serving North and South America and one site located in Istanbul serving EU, and MEA. The US-East site is hosted by https://stake.plus/ and the Istanbul location is being hosted by https://helikon.io/
https://docs.google.com/document/d/16USQYVhlyAlrU829EUB2TRoqUC0nnfoS_uCdZ84HT8k/edit?usp=sharing

Add dotters network rpc endpoints for westend, kusama, polkadot

---

packages/apps-config/src/endpoints/testing.ts

We'll be shutting down extra endpoints for this testnet in the future.

Remove extra Subspace Gemini 2a RPC endpoints

---

packages/page-preimages/src/usePreimage.ts

The solution here is exceptionally messy to say the least.
Closes https://github.com/polkadot-js/apps/issues/8440

Skip (& don't break) on previous-gen preimage pallet

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/ui/colors.ts
packages/apps-config/src/ui/logos/chains/pendulum.svg
packages/apps-config/src/ui/logos/index.ts

The main purpose is to be able to see our chain's name and logo for the Polkadot crowdloan, parathread, and parachain pages.
Please that the endpoint is set to Unreachable until we launch.
As reference, similar PR for Kusama: https://github.com/polkadot-js/apps/pull/7807

Add Pendulum chain (unreachable) & logo

---

packages/page-referenda/src/Referenda/RefOngoing.tsx

Basically we doubled-up here - the value is the end, not the start.

Confirming end block

---

packages/page-accounts/src/modals/Qr.tsx

Extra warning for mismatched genesis (QR import vs chain) as found in https://github.com/polkadot-js/apps/issues/8465

Display warning on mismatched genesisHash (QR vs chain)

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Deploying statemint endpoint using our hybrid (cloud + on-prem) compute infrastructure for better decentralization, cost prediction and compute provider risk mitigation.

RadiumBlock Statemint endpoint via hybrid compute

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

Deploying Kusama endpoint using our hybrid (cloud + on-prem) compute infrastructure for better decentralization, cost prediction and compute provider risk mitigation.

RadiumBlock Kusama endpoint via hybrid compute

---

packages/page-referenda/src/Referenda/Referendum.tsx
packages/page-referenda/src/types.ts

Also adds a confirmation overlay as suggested in https://github.com/polkadot-js/apps/issues/8573

Only fully calculate ref graphs on expand

---

packages/page-explorer/src/Latency/Chart.tsx
packages/page-referenda/src/Referenda/Referendum.tsx
packages/page-staking/src/Query/Chart.tsx
packages/page-staking/src/Query/ChartPoints.tsx
packages/page-staking/src/Query/ChartPrefs.tsx
packages/page-staking/src/Query/ChartRewards.tsx
packages/page-staking/src/Query/ChartStake.tsx
packages/page-staking/src/Query/types.ts
packages/page-staking/src/Query/util.ts
packages/react-components/src/Chart/Line.tsx
packages/react-components/src/Chart/chart-js-crosshair.d.ts

This _may_ help with https://github.com/polkadot-js/apps/issues/8588
- ensure all charts have the same options (enable per-plugin overrides on options)
- display all staking charts at once (with loader overlay - this is driven by the comments above that there could be a timing issue - staking is different since not all charts are available at the same time)
Some small option fixes for crosshair as well, correctly enabling snapping

Adjust all chart options

---

packages/react-components/src/ChainImg.tsx

This PR fixes the ChainImg component when the `logo` prop is not specified. Previously this would always be an empty logo, using the chain color only, but this change uses the defined chain logo, if it matches, as intended.

Fix ChainImg logo to match chain

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

The endpoint was disabled previously in #8553 but has since been fixed and back online, this PR enables it again.

Enable Tinkernet's OnFinality endpoint

---

packages/page-staking/src/Query/Chart.tsx
packages/page-staking/src/Query/ChartPoints.tsx
packages/page-staking/src/Query/ChartPrefs.tsx
packages/page-staking/src/Query/ChartRewards.tsx
packages/page-staking/src/Query/ChartStake.tsx
packages/page-staking/src/Query/Validator.tsx
packages/page-staking/src/Query/index.tsx
packages/page-staking/src/Query/types.ts
packages/react-components/src/Chart/Line.tsx

Inspired by https://github.com/polkadot-js/apps/issues/8588
It also tweaks the staking charts to pass in a known set of labels (which may or may not have some impact on resolving the above)

Add ErrorBoundary to charts

---

packages/apps-config/src/ui/logos/index.ts

The logo of our cess testnet chain is not displayed. We found the reason because the name is wrong, so we can modify it to display it.

fix the cess testnet logo wrong bug

---

packages/react-components/src/Table/index.tsx

On Safari `visibility: collapsed` has a bug, i.e. it is treated as `visibility: hidden` by the browser.
Since we don't have alternating rows (anymore), using `display: none` does exactly the same job. As a bonus, we are removing some lines of css.

Replace (some-browser-broken) visibility: collapsed

---

packages/page-explorer/src/Latency/index.tsx
packages/page-explorer/src/Latency/useLatency.ts
packages/react-hooks/src/index.ts
packages/react-hooks/src/useEventChanges.ts
packages/react-hooks/src/useEventTrigger.ts
packages/react-hooks/src/useExtrinsicTrigger.ts
packages/react-hooks/src/useMemoValue.spec.ts
packages/react-hooks/src/useMemoValue.ts

Split from https://github.com/polkadot-js/apps/pull/8749
- add the `useMemoValue` hook
- use the hook in triggers (previously without any protection)
- unlike the original PR, add some tests for compares
(The latency changes are unrelated - but was locally looking for a home to push to. It just aligns with the addition of `--tmp`)

Pull in useMemoValue (& basic use)

---

packages/react-components/src/IdentityIcon/index.tsx
packages/react-components/src/InputAddressSimple.tsx
packages/react-hooks/src/useAccounts.ts
packages/react-hooks/src/useAddresses.ts
packages/react-params/src/Holder.tsx
packages/react-params/src/Param/BasicAccountId20.tsx
packages/react-params/src/Param/BasicAccountId32.tsx
packages/react-params/src/Param/BasicAccountIdBase.tsx
packages/react-params/src/Param/findComponent.ts

Closes https://github.com/polkadot-js/apps/issues/8702
It allows for non-native inputs via a SimpleAddress bridge. There may be dragons lurking since this is not something we actually set out for. (Same with the Ethereum support which is bare-bones)
On the testnet linked in the issue above -

Params support for non-native AccountId{20, 32}

---

packages/apps/public/index.html
packages/apps/src/Menu/Grouping.tsx
packages/apps/src/Menu/Item.tsx
packages/react-components/src/Tabs/Tab.tsx
packages/react-components/src/styles/components.ts
packages/react-components/src/styles/index.ts

We probably just need to re-adjust everything with a ration, e.g. https://type-scale.com/
So it could be with 1.067 -
- 1em
- 0.937207122774
- 0.878357190979
- 0.823202615725
- 0.771511354944
...

Adjust article.{error, warning} sizing

---

packages/react-components/src/Badge.tsx
packages/react-components/src/Tooltip.tsx

Closes https://github.com/polkadot-js/apps/issues/8759
This fucking styled-components and Props - it gets completely lost and causes issues like this where the Props are not type-checked. This is 2023.

Fix tooltips

---

packages/page-democracy/src/Overview/Summary.tsx

Our chain no longer has `api.consts.democracy.launchPeriod`, causing the democracy page to generate an error when loading. This PR just hides the launch period card summary if this constant is undefined. This is a quick fix to get the page to load again.
The reason why we no longer have the `launchPeriod` is because we made some changes to the referendum scheduling, s.t. they are always created on mondays. Longer term I'd love to be able to get the launch period card summary to work for our chain as well, but I'm not sure how to approach that. Right now we use a timestamp-based approach, but we could refactor this back to be block-based. Then the only change required for us would be that the value would be calculated as `(bestNumber + api.consts.democracy.ourNonStandardOffset) …

fix: democracy page for chains without launchPeriod

---

packages/page-council/src/Overview/Voters.tsx
packages/page-democracy/src/Overview/ProposalCell.tsx

Currently, the Governance -> Council page relies on Democracy. Using Council without Democracy causes the Council page to not render properly. 
See [Issue 8788](https://github.com/polkadot-js/apps/issues/8788) for more details. 
This PR provides two small changes to provide compatibility for a chain with Council, but without Democracy.
The following screenshots show the Overview and Motion page with the new changes. 
**Polkadot**
**Without Democracy**

Small fixes to provide council page compatibility

---

packages/apps-config/src/api/spec/interbtc.ts

Without this, we run into [this issue](https://github.com/polkadot-js/apps/issues/8458) when we submit transactions on a chopsticks-ed chain. To be honest I don't understand why this change is required on chopsticks and not on mainnet

fix: add account derive

---

packages/page-council/src/Motions/ProposeExternal.tsx
packages/page-democracy/src/Overview/ProposalCell.tsx
packages/page-democracy/src/Overview/Propose.tsx
packages/page-preimages/src/Preimages/Call.tsx
packages/page-preimages/src/Preimages/Free.tsx
packages/page-preimages/src/Preimages/Preimage.tsx
packages/page-preimages/src/types.ts
packages/page-referenda/src/Referenda/RefOngoing.tsx
packages/page-referenda/src/Referenda/Submit.tsx
packages/page-referenda/src/Referenda/Vote.tsx
packages/page-scheduler/src/Scheduled.tsx
packages/page-whitelist/src/Hashes/Details.tsx
packages/react-hooks/src/index.ts
packages/react-hooks/src/types.ts
packages/react-hooks/src/usePreimage.ts

Has an effect on https://github.com/polkadot-js/apps/pull/8774

Move usePreimage to react-hooks

---

packages/page-extrinsics/src/Decoded.tsx
packages/page-extrinsics/src/Decoder.tsx

As per https://github.com/polkadot-js/apps/issues/8837
Seems to do the trick, have tested with -
1. Call
2. Extrinsic
3. Un-prefixed payload
Have not done prefixed payloads, but if unprefixed work, it _should_ be sane

Attempt to decode ExtrinsicPayload in decoder

---

packages/apps-config/src/links/polkassembly.ts
packages/apps-config/src/links/subscan.ts

There were some naming issues with the External URLs for Subscan and Polkassembly that were not auto-populating the `external links` sections

Fixes External URLs for Moonbase Alpha

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

Subsocial team decided to leave `para.f3joule.space` as a private node for stability purpose

Change Provider for SubsocialX

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

@jacogr we have implemented rate limits as requested by network owners that restrict access to these public endpoints to `polkadot.js.org`. We believe that your monitoring that is indicating these endpoints are down due to your monitoring solution being blocked by this rate limit. Can you please let us know what origin or IP you are making these monitoring requests from so we can allow list it

Add Missing OnFinality Networks

---

packages/react-components/src/Modal/index.tsx

As commented on in https://github.com/polkadot-js/apps/issues/8926#issuecomment-1415766986
This ensures that the signing modal doesn't bring down the whole app

Add explicit ErrorBoundary to Modal displays

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/testingRelayRococo.ts

It seems like the Bajun Logo got wrongly changed to the Ajuna Logo. Hopefully, this will fix the change.
Kusama and Rococo are running under the Baju Network (nodesBajunPNG)

fix: bad logo after PR 8941

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Dear @jacogr, dear team,
For your consideration, this request aims to add the remaining endpoints from the Infrastructure Builders Programme for the Polkadot and Kusama networks, as agreed a the previous PR #8852.
The trial period for the Westend endpoint (#8872) has now reached  two weeks, and we trust the service has been provided to a high standard (please inform if otherwise).
Would you kindly consider adding these addftional endpoints?
Many thanks, best regards
**_Miloš_**

Add endpoints for Polkadot and Kusama - IBP Network 

---

packages/apps-config/src/endpoints/production.ts
packages/apps-config/src/endpoints/testing.ts

'thebifrost' and 'bifrost' are different networks.
The logo of 'bifrost' was used for 'thebifrost', so we fixed it.

Correct thebifrost network logo

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Closes https://github.com/polkadot-js/apps/issues/8973
These were originally re-enabled in https://github.com/polkadot-js/apps/pull/8908
As per the comments on the items, these _could_ be false positives as it stands, however since these are reported twice daily, we really cannot manually check them again. Until we have a solution, there is no other option but to remove these to not continue the unreachable spam from the CI checks.
cc @jamesbayly

Disable unreachable endpoints

---

.github/workflows/chain-endpoints.yml

Hi @jacogr,
We're not finding an easy way to whitelist just your automated CI for our rate limited endpoints.
We suspect that one of the big issues is that every fork (heres mine doing it https://github.com/jamesbayly/apps/actions/runs/4159421728) will run this automated check task at the same time, so we might have tens if not hundreds of calls from GItHub at the same time (that get rate limited) as each fork executes the check.
I've added a line that only runs the endpoints check in your repo (not on forks) and changes the time it does this to slight later in the 12 hour window since i can't change code in already forked codebases
Let me know if you have any other ideas that we should pursue
James

Update ChainEndpoints Check task

---

packages/apps-config/src/api/params/tracks/index.ts
packages/apps-config/src/api/params/tracks/polkadot.ts
packages/apps-config/src/api/params/tracks/util.ts

Just pulls in the human summaries like we have on Kusama.
Values as per https://github.com/paritytech/polkadot/pull/6701

Add Polkadot trackinfo

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This PR adds Watr Polkadot info to the already existing and producing blocks Watr Parachain.

Add Watr Polkadot

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

The [onfinality--wss://bifrost-polkadot.api.onfinality.io/public-ws](https://polkadot.js.org/apps/?rpc=wss://bifrost-polkadot.api.onfinality.io/public-ws#/explorer) is reachable now

restore onfinality provider

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

We faced a DNS issue with one of our onprem servers that confused the front end load balancer causing a failure with the statemint endpoint. We have been working to fix it. The fix is in place and endpoint has been operating stable and would like to re-enable it. 
We take this disruption very seriously and would like to apologize and assure that we will continue to monitor the endpoint with high priority.

Fix statemint endpoint

---

tsconfig.webpack.json

Closes #9117 
Seems to be the actual tsc compiler using `__spreadArray` on iterators which in turn uses a non-existent length and thus never spreads the iterator. This seems to fix the tsc output by forcing it to latest (as a side-effect this also aligns with the settings used in the libs, so at worst is consistent).

Adjust TS compilation target

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testing.ts

Replaced OnFinality endpoints with Geo Load Balancer.
Renamed test Opal enpoints in the same manner like in Unique and Quartz.

Unique Network - remove OnFinality endpoints

---

packages/page-accounts/src/Sidebar/Identity.tsx
packages/page-accounts/src/modals/IdentityMain.tsx
packages/react-hooks/src/types.ts

Enables discord identity in the sidebar. Follow up to #8381

display discord identity in profile sidebar

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

Dear team, 
This request is to add endpoint support to the system parachains listed below, these endpoints are provided by the Infrastructure Builders' Program:
**Polkadot**:
- Statemint
- Collectives
**Kusama**: 
- Statemine
- Encointer
- BridgeHub
**Westend**:
- Westmint
- Collectives
Additionally, current endpoints which are already active for the relay chains are now renamed (and re-sorted in the list) to show that they are being managed by the Infrastructure Builders' Program.
Please note that this PR replaces #9149 and that one will be now closed.
Many thanks!!.. best regards..
**_Miloš_**

Add IBP endpoints to system parachains, update naming convention

---

packages/apps-config/src/endpoints/production.ts

Bittensor recently hard-forked to a new network, so I'm updating the Opentensor Foundation's node url.

Bittensor - switch node to finney public node

---

packages/react-api/src/Api.tsx

Currently any `isEthereum==true` chain will force the development mode off, making it impossible to add any extra types as needed.

Allow to run with isDevelopment on ethereum-like chains

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

We have spent a significant amount of time trying to reproduce the issue in https://github.com/polkadot-js/apps/issues/9240
However we are not able to reproduce this issue. The endpoint loads on our end.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstatemint.public.curie.radiumblock.co%2Fws#/explorer
We have not detected any failures in our monitoring systems.
We run monitoring from various locations around the world and have not seen any failures.
Our monitoring includes standalone wss requests as well as automated polkadot-js page loads. 
We are attaching the monitoring report from we have for the endpoint.
We don't believe it's an issue with the setup or load given that statemint has a fraction of the load seen on kusama and polkadot and those endpoints of ours have been working …

Debug and fix cron issue of RadiumBlock statemint endpoint

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

Hi Jaco,
I would like to add our westend rpc node to polkadot.js. I have an [earlier PR](https://github.com/polkadot-js/apps/pull/8227) for a kusama rpc node but I understand you prefer to start with a test net first so i'll close that for now and resubmit later if this one goes well.
Regards
Max | Stakeworld

Add stakeworld westend rpc node

---

packages/react-components/src/Input.tsx

Closes #8212
This is particularly useful for any fields containing output values, for example when decoding an extrinsic. Currently it is impossible to select and copy and values in Firefox because all pointer events are disabled.

Make disabled input fields selectable

---

packages/apps-config/package.json
packages/apps-config/src/api/spec/frequency.ts
packages/apps-config/src/api/spec/index.ts
yarn.lock

Just finished updating the `@frequency-chain/api-augment` JS package to support esm in v1.5.2.
The build now passes and pulls in the correct augmented information for Frequency. (See example ss below)
Question: @jacogr, I don't think I need to update `packages/apps-config/src/api/typesBundle.ts`, but let me know if I do.
References:
- #9243 
- https://github.com/LibertyDSNP/frequency/issues/1116
Screenshot (showing that it loads in the custom RPCs):

Update Frequency to 1.5.2 with esm support

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

Hi Devs,
I would like to add our Westend rpc node to polkadot.js. This aligns with the earlier [guidance](https://github.com/polkadot-js/apps/pull/9239) that getting listed on a testnet is a necessary quality control measure prior to being listed on mainnets.
Regards,
Calvin | BlockOps

Add BlockOps RPC node to Westend

---

packages/apps-config/src/endpoints/testing.ts

Change the aleph zero testnet name, to make it distinguishable from aleph zero mainnet. Needed for Sirato smart contract verifier.

change aleph testnet name to make it unique

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

following issues with Manta's lb, a new lb url for the calamari network has been provisioned.

new (Manta Network) load balanced provider url

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

Dear PJS team,
Subsequent to our [treasury application](https://kusama.subsquare.io/council/motion/572) and successful rounds of testing the LuckyFriday team is seeking approval to have their RPC nodes listed within the Polkadot.JS application.  The RPC nodes are hosted on self-owned, newly acquired bare-metal servers hosted at a private Datacenter with bandwidth rated at 20 GBit (in/out/redundant).  We believe that LuckyFriday would be a good addition to the listing providing service outside of mainstream cloud and infrastructure providers.
We have spent the past few weeks load testing the servers using various sized payloads from from the staking and conviction voting pallets.  Tests were done at multiple geographic locations all to our satisfaction.  We also invited members of ChaosDAO …

Added LuckyFriday's Kusama and Statemine RPC nodes

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Now that our westend endpoints has been up and running for a week, This PR will be adding our Kusama and Polkadot endpoints

Add blockops endpoint

---

packages/apps-config/src/endpoints/production.ts
packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This PR re-enables the self-hosted fullnodes for Centrifuge and Altair parachains.

re-activate centrifuge fullnodes

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Dear Devs,
Following our successful implementation of endpoints on Westend, Statemine and Kusama, we are following up with an endpoint for Polkadot.  This endpoint has been in operation for a little over a week and has passed our internal load and up-time checks.
We hope this is satisfactory.
Kind Regards,
Will | Paradox

Adding LuckyFriday to Polkadot WSS endpoints

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

A few weeks ago nodle testnet experienced an outage related to an expired parachain lease on Rococo. 
The lease has been restored and the endpoint is operational again now. 
Link was removed in PR #9416 and automatic ticket #9415

Restore nodle testnet link

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Addressing https://github.com/polkadot-js/apps/issues/9480
We had switched to using the relay chain as external RPC rather than running a relay chain RPC along with asset chains - to take advantage of a feature in cumulus binary. We are having mixed success with this. Its particularly worse since the relay chain block constantly lags beyond what is usually considered acceptable (>10 blocks) ever since v0.39. We struggle with > v0.39 for validators too. We are seriously considering downgrading back to v0.39 rather than following the convention of using the latest binary.  What makes this hard is that the timeouts due block delays are infrequent and only a service restart seems to fix it. We will revert the external RPC to make sure that choice is not amplifying the issue. We request our …

Addressing issue 9480

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

The ['wss://bifrost-rpc.rococo.liebi.com/ws'](https://polkadot.js.org/apps/?rpc=wss://bifrost-rpc.rococo.liebi.com/ws#/explorer) is reachable now

restore Liebi rococo provider

---

packages/apps-config/src/links/subid.ts

@jacogr We have notice that Sub.ID is missing on several chains.
P.S. If you find Sub.ID valuable for the ecosystem, please support us with an AYE vote on our [proposal](https://polkadot.polkassembly.io/motion/412) (which ends in less than 24h) for continued development of Sub.ID.

Add new chains for Sub.ID links

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

Fully rebuild the westend deployment to address stability issues. Observed to be stable for 1 week plus of testing.  Enabling RadiumBlock Westend endpoint.

Enabling RadiumBlock Westend endpoint

---

packages/react-components/src/InputRpc/rpcs.ts

Fixing `jsonrpc` attribute while building full RPC record object.

Fix `jsonrpc` attribute

---

packages/apps-config/src/api/spec/shiden.ts
packages/apps-config/src/api/typesBundle.ts

Currently, having issue like https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fshiden.api.onfinality.io%2Fpublic-ws#/explorer/query/339618 because of type error.
so, adding `EthTransaction: 'LegacyTransaction' property to typeDefinition in shiden

Add ethTransaction type for shiden

---

packages/page-referenda/src/Referenda/Delegate/Activity.tsx
packages/page-referenda/src/Referenda/Delegate/index.tsx

Fixes the following
- Delegation with x0.1 conviction (conviction === 0) sets the extrinsic to `null` and the `TxButton` to disabled.
- Typo on delegation
Remarks:
- Also the type of `activityTo` is `VoteResultItem[] | null | undefined` but is set by default to `[]` which is truthy. This result in step 2 being valid even if the selected account has no activity. Is this expected or do you intend to check for `.length`?

Fix delegation with x0.1 conviction and typo

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

Using the new assethub naming. Old endpoints (/statemine etc) will still work for a while.

Renaming stakeworld's /statemint/statemine/westmint endpoints to /assethub

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Dear Devs,
We'll like to add RPC nodes for any outstanding System Chains on both Polkadot and Kusama as well as RPC nodes for Interlay, Kintsugi, Picasso and Centrifuge.
The nodes have been online and tested for the past few days.
Regards,

Adding LuckyFriday nodes

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

Dear @jacogr, dear team, 
Please consider this Pull Request to add endpoint support from the Infrastructure Builders' Programme ([IBP](https://ibp.network/)) to the following chains:
- Polkadot BridgeHub
- Westend BridgeHub
The endpoints are currently provided by a network of 07 independent RPC providers in geo-diverse locations (working towards having 12 worldwide locations soon) each location is comprised of at least 2x archive nodes serving requests in failure-resistant and load-balancing mode.
Many thanks!
Best regards
Milos

Add IBP BridgeHub support in Polkadot & Westend

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

Westmint endpoint is back online now.

Add OnFinality Westmint endpoint

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

we increased replicas behind endpoints and also improved the monitoring. The nodes should be more stable now.

Enable parity endpoints

---

packages/page-nfts/src/AccountItems/useItemsInfos.ts
packages/page-nfts/src/useCollectionInfos.ts

On the nfts page the metadata disappeared because of the way we extract it. `metadata.data.toString()` was previously converting from u8a to string under the hood, while now it converts u8a to hex and produces the wrong result

Fix the way we read the nft's metadata

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

A few weeks ago Blockops Polkadot and Westend endpoints experienced an outage, we have root caused this Westend (#9614) and Polkadot (#9748) issue.
Please re-enable the endpoints, the endpoints are operational again now. Thanks, @jacogr

Update Blockops  Endpoints

---

packages/react-components/src/Status/index.tsx

The previous style is fine in styled-components 5.x, but not anymore in 6.x (As a bonus, also check for other occurrences or bare `:hover` - none found)
Closes https://github.com/polkadot-js/apps/issues/9804

Add missing & specifier to status

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/testing.ts

It was a long time since Stake Technologies was rebranded to Astar. Finally, the time has came to change this on Polkadot.js

Rename StakeTechnologies to Astar

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

Added forks of asset hub and bridge hub required to test Snowbridge. We have added forks as we want to test the bridge without merging our changes upstream to bridge hub and asset hub.
TODO:

Add new Snowbridge forks

---

packages/apps-config/src/links/subsquare.ts

- Add account external link to subsquare user votes page.
- Support vara network.

Add subsquare user external link and support vara network

---

packages/apps-config/src/endpoints/production.ts

This PR replaces `wss://rpc.mainnet.creditcoin.network/ws`, one of the RPC endpoints provided by the Creditcoin Foundation, with `wss://mainnet.creditcoin.network/ws`, which routes connections through the foundation's load balancer in order to better serve users.

Update Creditcoin WS endpoint

---

packages/apps-config/src/endpoints/production.ts
packages/apps-config/src/endpoints/testing.ts

The bifrost.finance team and our bifrost network are unrelated projects, so we added 'the' to avoid confusion before.
However, the two chains are located in different sections, removing 'the' to unify the name convention with other apps on the bifrost network.

Update chain text. (thebifrost network)

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testing.ts

Removes OnFinality public endpoints from Moonbeam networks, as they are gradually being phased out.  OnFinality API Key private endpoints (free and paid) are not impacted and remain unchanged. For more information, please see: https://forum.moonbeam.network/t/proposal-mb19-mr14-onfinality-high-performance-public-infrastructure-transition-project/1303

remove OnFinality public endpoints from Moonbeam networks

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

We had to register a new ParaId for Logion following an error (wrong lease period) in our current crowdloan.

Change Logion ParaId

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

After Watr's successful mainnet launch this PR re-enables the corresponding RPC endpoint.

Enable Watr mainnet RPC

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

As Nodle will stop the support for "wss://nodle-paradis.api.onfinality.io/public-ws", is planned to use this one on public clients
- wss://node-6957502816543653888.lh.onfinality.io/ws?apikey=09b04494-3139-4b57-a5d1-e1c4c18748ce

Update testnet wss url for Nodle - testingRelayRococo.ts

---

packages/apps-config/src/endpoints/testing.ts

Adding the endpoint of our recently launched network, the endpoint is already live.

Add Subspace Gemini 3g endpoints

---

packages/page-referenda/src/useAccountLocks.ts
packages/react-components/src/ConvictionDropdown.tsx

Closes #9260
This PR fixes the issue reported in #9260. The problem was related to the incorrect calculation of the remaining locking period for tokens that are locked in referendums. The account menu on the apps was displaying inaccurate data. For example, when a user cast their vote on a Kusama referendum with a conviction of 6x, the displayed locking period was only 42 days instead of the expected 224 days (6 multiplied by 7). This PR addresses the issue and ensures that the correct locking period is displayed.
- Previously, the lock period was incorrectly multiplied by the conviction index. We have updated it to be multiplied by the conviction duration.
- Before
- After(Corrected)

Fixes #9260: Corrects calculation of remaining locking period for referendums

---

packages/apps-config/src/settings/ethereumChains.ts

we (altlayer) support one runtime spec-name for ethereum chain:
1. altbeacon-dev

Add altlayer's ethereum dev chain to `ethereumChains`

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testing.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

* The full node is provided by "BOTLabs GmbH" and not "KILT Protocol".
* Remove the WILT network. This will most likely never be used again.

Rename KILT Protocol to "BOTLabs"

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

We're decommissioning Kapex RPC.

Removing Kapex RPC for Dwellir

---

packages/apps-config/package.json
yarn.lock

This PR updates the version of @frequency/api-augment to 1.9.0, with no other changes.

update @frequency/api-augment to v1.9.0

---

packages/react-api/src/Api.tsx

Change ethereum icons based on URL

---

packages/page-accounts/src/Accounts/Account.tsx
packages/page-addresses/src/Contacts/Address.tsx
packages/react-components/src/AccountSidebar/AccountMenuButtons.tsx

Removed `transfer` call in polkadot v1.2 causing the transfer button disappearance.
See: https://github.com/paritytech/polkadot-sdk/pull/1226/files#diff-5dfe6adcc3c44280fc10cd49830df408a491c768a54f47835d822a0d1334d385L737
This bug causes the transfer button to be missing on chains upgraded to Polkadot ^1.2.0, like [Phala](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fphala.api.onfinality.io%2Fpublic-ws#/accounts).

Fix transfer button disappearance

---

packages/page-js/src/snippets/extrinsics-examples.ts

Make transfer example extrinsic currently doesn't work due to variable name difference. `transferAllowDeath` variable doesn't exist since the variable is named `transfer`.

 Fix make transfer example

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

we will be using rpc.parallel.fi for other purpose

Update parallel rpc

---

packages/apps-config/src/endpoints/testingRelayRococo.ts

Reenabling the endpoint for Mangata's RPC on rococo.
It's available and can be checked here:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcollator-01-ws-rococo.mangata.online#/explorer

Feat: Reenable Mangata's project rococo endpoint

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This PR adds Helikon public RPC endpoints for Khala, Phala and HydraDX networks.
All endpoints are load balanced with two archive nodes on NVMe drives on a 500Mbps symmetrical network. All services run on owned hardware in a data center in central Istanbul, and are monitored 24/7 at software (node), hardware (disk, CPU, memory) and network level.
Nodes can be viewed on the W3F Telemetry instance, viewable for [Khala](https://telemetry.w3f.community/#list/0xd43540ba6d3eb4897c28a77d48cb5b729fea37603cbbfc7a86a73b72adb3be8d), [Phala](https://telemetry.w3f.community/#list/0x1bb969d85965e4bb5a651abbedf21a54b6b31a21f66b5401cc3f1e286268d736) and [HydraDX](https://telemetry.w3f.community/#list/0xafdc188f45c71dacbaa0b62e16a91f726c7b8699a9748cdf715459de6b7f366d).
Helikon is a member of the IBP …

Add Helikon RPC public endpoints for Phala, Khala and HydraDX

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This PR adds Helikon public RPC endpoint for Polimec.
Polimec RPC endpoint is load balanced with two archive nodes on NVMe drives on a 500Mbps symmetrical network. All services run on owned hardware in a data center in central Istanbul, and are monitored 24/7 at software (node), hardware (disk, CPU, memory) and network level.
Nodes can be viewed [here](https://telemetry.w3f.community/#list/0x7eb9354488318e7549c722669dcbdcdc526f1fef1420e7944667212f3601fdbd) on the W3F Telemetry instance.
Helikon is a member of the IBP GeoDNS and provides public RPC endpoints for Kusama, Westend, Polkadot, all system parachains, Phala, Khala and HydraDX. We also run boot nodes for all the chains mentioned in this PR.
Thanks!

Add Helikon public RPC endpoint for Polimec

---

packages/apps-config/src/endpoints/production.ts

`wss://rpc.joyutils.org` is a load-balanced Joystream RPC endpoint with 2 high-availability backing nodes. `joyutils` is operated by senior Joystream DAO member with staked roles in the DAO.

Add joyutils RPC endpoint for Joystream

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

The Dwellir Bifrost Kusama wss endpoint is working again.

Dwellir Bifrost Kusama endpoint working again

---

packages/apps-config/src/endpoints/production.ts

* `rpc01.logion.network` was unavailable because the max number of connections was reached (was set to 100) and additional connections were refused
* Max number of connections was increased to 300 (there are currently 200 connections on average)
* Additional RPCs are added to spread the load and improve availability
* The number of connections on our RPCs will be monitored more closely on our side

Update Logion RPCs

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

the outage has been fixed. producing blocks, rpcs are responsive

Integritee Polkadot rpc's are up again, reactivating

---

packages/page-settings/src/Metadata/Extensions.tsx

This bug has been annoying me for a while now lol, increased the z-index to 2.
Thank you for all the awesome work guys.
Before:
After:

fix: :lipstick: dropdown options not visible for metadata upgradable extensions

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

We had an issue with out RPC node that is now fixed. Opening a PR to enable our provider url.

Enable Aventus provider

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

NeuroWeb opened new crowdloan for extending its slot, more info available [here](https://docs.neuroweb.ai/polkadot/crowdloan). We are adding this metadata so it is easier for contributors to find our crowdloan as we opened it under new parachain id 3360 (you can confirm in the docs that this is NeuroWeb para id for this auction). This metadata will be removed once auction slot is won and we perform swap of leases.

Add metadata for NeuroWeb crowdloan

---

packages/page-democracy/src/Overview/Propose.tsx

Fix: The democracy page doesn't include a field to add the proposal length.
I have based the fix on the `propose` in the referendum and altered some variables.
The issue is that the proposal length is set to 0 with no option to change this and no warning. This will result in an invalid proposal.

fix: updating the democracy proposal modal

---

packages/apps/src/Endpoints/index.tsx
packages/apps/src/overlays/LocalFork.tsx
packages/react-api/src/Api.tsx
packages/react-components/src/Sidebar.tsx

As mentioned in #10305, this PR includes
- Fix when user change rpc endpoint to another chain in url and load the page, it should not automatically enter local fork mode (although refreshing the page will still be in local fork mode)
- Refactor `Sidebar` buttons slightly and change the order of `Switch` and `Fork` buttons, so `Switch` remains in the old position that users are used to.

fix: switch rpc in url should not auto use local fork

---

packages/apps-routing/src/preimages.ts
packages/page-preimages/src/Preimages/Preimage.tsx
packages/page-preimages/src/usePreimages.ts
packages/react-hooks/src/usePreimage.ts

closes: https://github.com/polkadot-js/apps/issues/10288, https://github.com/polkadot-js/apps/issues/10141
Due to the deprecation of `StatusFor` given https://github.com/paritytech/polkadot-sdk/pull/1363 the `usePreimage` hook needs to support both `StatusFor` and `RequestStatusFor` calls when gathering data for preimage hashes.

Support requestStatusFor for usePreimage

---

packages/apps-routing/src/preimages.ts

https://github.com/polkadot-js/apps/pull/10310 broke backwards compatibility for chains that don't have `requestStatusFor`. This PR fixes that issue.

Fix break in backwards compatibility with preimages

---

packages/apps/package.json
yarn.lock

This pr upgrade chopsticks version to latest, this includes fixes for some parachains

Upgrade chopsticks version

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Our Polkadot Shell parachain has been upgraded to production runtime. This adjusts meta info

wake up Integritee shell on Polkadot and adapt naming

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This endpoint does not work; it keeps disconnecting and re-connecting. 
This has been ongoing for a while and a cause of complaints in the ecosystem, so I recommend we remove it until this problem is fixed.
I notice that it has already been commented out from prodParasPolkadot but this would also remove it from the prodRelayPolkadot list.

Remove Automata 1RPC from Polkadot Relay Chain RPC list

---

packages/apps-config/src/settings/ethereumChains.ts

similar to #10219, `klaos` and `laos` runtimes are separated, so we need both of them to be recognized as an EVM chain

Add `klaos` to ethereum chains list

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

We have decided to discontinue the use of this node.

Remove the Turing Network endpoint provided by the provider Dwellir

---

packages/apps-routing/src/staking.ts

rel: https://github.com/polkadot-js/apps/issues/10004
Since `api.query.staking.ledger` returns `legacyClaimedRewards` now instead of `claimedRewards` it was stopping westend from showing up. 
Therefore we added some compatibility logic inside of apps-routing for staking.
There will also need to be follow up work done to get the rest of the calls compatible.
closes: https://github.com/polkadot-js/apps/issues/10388

Fix apps-routing for staking (Westend)

---

packages/page-accounts/src/modals/MultisigCreate.tsx

Polkadot allows for multisig account with up to 100 signatories (see [`api.consts.multisig.maxSignatories`](https://polkadot.js.org/docs/polkadot/constants#maxsignatories-u32))

Fix MAX_SIGNATORIES

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

In prevision of the imminent Polkadot<>Kusama bridge launch, see https://forum.polkadot.network/t/polkadot-kusama-bridge/2971/20. We want to offer the option to teleport DOT/KSM to the Polkadot and Kusama BridgeHub system parachains (para ID: 1002) using the UI.

Add bridge hub teleport destination for Polkadot and Kusama

---

packages/apps/public/locales/en/translation.json
packages/apps/public/locales/zh/translation.json
packages/page-assets/src/Balances/index.tsx
packages/page-assets/src/Overview/Query.tsx
packages/page-assets/src/Overview/index.tsx

Currently there are more and more assets on polkadot, and we need to spend a lot of time on the page to find the assets, so I submitted this pr to try to improve that, both asset ID and name filtering are supported.

feat: add asset filter

---

packages/apps-config/package.json
packages/apps-config/src/api/spec/index.ts
packages/apps-config/src/api/typesBundle.ts
yarn.lock

- Simple Update of the types package
- Testnet runtime was renamed generic due to Paseo

Update Frequency Types package and testnet chain name

---

packages/apps-config/src/endpoints/production.ts

Tangle is launching on 10th April and we have our RPC endpoints and node set up.
This PR adds Tangle to live networks
https://polkadot.js.org/apps/?rpc=wss://rpc.tangle.tools#
Refers Issue https://github.com/webb-tools/tangle/issues/600

Add tangle to live networks

---

packages/page-accounts/src/modals/LocalAdd.tsx

to fix this [problem](https://github.com/polkadot-js/apps/pull/10342/files/01f677603bcd7c27ef03224897a2db0aa155d98f#r1560596487), so I removed account storage override when add a local account in `local fork` mode

fix: remove local account storage override

---

packages/page-parachains/src/Auctions/index.tsx
packages/page-parachains/src/Crowdloan/index.tsx

Adds a warning to the deprecation of the Crowdloan and Auctions page.

Add warning banners for Auctions and Crowdloans

---

packages/apps-config/src/api/constants.ts
packages/apps-config/src/ui/identityIcons/index.ts

This change fixes parachain names not showing in Paseo testnet.
After the fix:
The validator set is still not properly displayed in any relay :thinking:

Show parachain names in Paseo

---

packages/page-storage/src/Query.tsx
packages/react-params/src/valueToText.tsx

This adds a button to the output of the queries to copy the results.
Closes #10391

fix: added copy button to query output

---

packages/react-components/src/AccountSidebar/RegistrarJudgement.tsx

identity.identityOf call now returning a tuple with username. Based on this [commit](https://github.com/paritytech/polkadot-sdk/commit/d1f678c0ec44e9734cf242247dab90c2678774a9#diff-4a95a3948151a729b1fa4e91da9c72cdc6cd2d1611842fca6f177efeed34fd1aR221)

Identity fix. Username has been introduced in identity pallet. 

---

packages/apps-config/src/endpoints/production.ts
packages/apps-config/src/endpoints/testing.ts

* Logion solochain is now archived, a single RPC node remains.
* Logion solochain testnet has been retired.
logion-network/logion-internal#1209

Archive Logion solochain and switch testnet

---

packages/page-staking/src/useSortedTargets.ts

This ensures claimedRewards is queried for both elected and waiting calls.

Fix useSortedTargets flags for claimedRewards

---

packages/react-components/src/AccountSidebar/RegistrarJudgement.tsx

rel: https://github.com/polkadot-js/apps/issues/10493
https://github.com/polkadot-js/apps/pull/10491 broke backwards compatibility for chains that did not update their identity pallets. This ensures that there is both forward and backwards compatibility

Backwards compatibility for identityOf

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

I would like to add a people chain rpc endpoint, its using the most current [chain-spec](https://raw.githubusercontent.com/paritytech/polkadot-sdk/930b0462d347d56d9d8751b1ca42b210ed6d9c51/cumulus/parachains/chain-specs/people-kusama.json).

Stakeworld people chain rpc endpoint

---

packages/apps-config/src/endpoints/testing.ts
packages/apps-config/src/endpoints/testingRelayPaseo.ts
packages/apps-config/src/endpoints/testingRelayRococo.ts

We migrated our testnet to Paseo: https://github.com/paseo-network/support/issues/62, and we are onboarding our RILT chain again. 
Fixes https://github.com/KILTprotocol/ticket/issues/3097.

chore: update Peregrine location and fix RILT endpoint

---

packages/page-accounts/src/modals/IdentityMain.tsx

closes: https://github.com/polkadot-js/apps/issues/10580

Fix set identity on accounts

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts
packages/apps-config/src/endpoints/testingRelayRococo.ts

We have migerated the bifrost-rococo to bifrost-paseo network, and the [node](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbifrost-rpc.paseo.liebi.com%2Fws#/explorer) is available now
So need to change the display in polkadot.js/apps

update: migrate bifrost-rococo to bifrost-paseo  providers

---

packages/apps-config/src/endpoints/testing.ts

Add the Subspace Gemini 3h Nova endpoint to the list of available test networks.

Add Subspace Gemini 3h Nova endpoint

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

Good day,
We'd like to add our Coretime Westend RPC endpoint to the list.
Thanks,
Jakob

Add Dwellir Coretime Westend endpoint

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts
packages/react-api/src/Api.tsx

I have noticed several changes regarding the identity pallet, its types and how it is displayed in the app.
@validorange has reported that setting an identity was not available in the accounts tab of pjs/apps.
I believe this change should re-enable that and and use legacy identities instead of People chain ids. Please, point me in the right direction if that is not the case @TarikGul

fix(paseo): relay for identity

---

packages/react-api/src/Api.tsx

1000 KSM is not enough for testing parachain registration on Kusama. Bumping the balance of Alice to 100K KSM. This applies to other networks as well.

Increase Alice Balance - Chopsticks

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

Blockops has temporarily stopped providing public endpoint services for Kusama and Westend. This PR removes both endpoints

remove public endpoint support for Kusama and Westend

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts

Hello there! 
Emmanuel from Zondax, currently part of the teams that maintain paseo network.
We would like to contribute here to Polkadot-JS adding our archival paseo node to the available ones to use.

add zondax paseo rpc endpoint

---

packages/page-referenda/src/Referenda/Referendum.tsx
packages/page-referenda/src/util.ts

Closes https://github.com/polkadot-js/apps/issues/9963
Currently, the UI is not prepared to display graphs of referenda with short timeframes (which exist on development chains).
For example [here](https://github.com/polkadot-js/apps/blob/6b8e76edbd2024ee10671ed1a80300e9e8e8da8d/packages/page-referenda/src/util.ts#L230), if the decision period is short enough, the division will bring the `step` to `0` and no graph will work.
It causes the graphs to be botched, and even freezes the UI in an infinite loop in some cases (when the confirmation period overruns the usual decision period).
In the PR, I'm bringing the precision up by multiplying by `100` first, and dividing back by `100` after relevant calculations.
It fixes the graphs on local development chains.
I also compared side-by-side the …

Higher precision of referenda graphs

---

packages/react-signer/src/TxSigned.tsx
packages/test-support/src/transaction/execute.ts

This PR enables `withSignedTransaction` for signers. Please refer to the following PR's for more information: 
https://github.com/polkadot-js/api/pull/5920
https://github.com/polkadot-js/api/pull/5922

Enable `withSignedTransaction` for signing and sending payloads

---

packages/page-staking/src/Payouts/PayButton.tsx

- Closes https://github.com/polkadot-js/apps/issues/10712
I tested it locally with `fast-runtime` to be sure. Seems to do what it's supposed to do.
---
---

Use `forceBatch` in Staking Payout

---

packages/react-api/src/Api.tsx

Failed transactions, https://polkadot.subscan.io/extrinsic?module=identity&call=set_identity
UI after the fix:

Not show identify in account page for failed set identity txs.

---

packages/react-hooks/src/types.ts
packages/react-hooks/src/usePreimage.ts

- Closes https://github.com/polkadot-js/apps/issues/10313
First, this includes some refactoring.
A `registry` doesn't really make sense in the preimage type - replaced with `api` as a parameter to `createResult`, which gives access to `registry` needed in this function.
Next, replaced the way of returning the final result with pre-defined values with direct return of a result.
- It allows us to return earlier - reducing nesting.
- Works better with multiple attempts at decoding.
- we know exactly what's being returned at a given line.
Finally, added a new attempt at decoding - with `api.tx(callData.toString())`
It doesn't seem to help _very much_, but fixes at least two preimages that I've seen.
Besides the preimage [described in the …

Try decoding a preimage as a transaction

---

packages/page-staking/src/MarkPoolsWarning.tsx
packages/page-staking/src/index.tsx

Add warning banner for staking page. This is specific to pools, more info here: https://hackmd.io/@ak0n/delegate-stake-faq

Add pools warning for staking to staking page

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

RadiumBlock would like to bring up our Polkadot People endpoints in Curie. Our high performance, highly distributed Endpoint Delivery Network.

Adding RadiumBlock as Polkadot People Endpoint provider 

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

- We had a payment issue that resulted in CF downgrading our account hence a lot of our fw configurations were not working which resulted in polkadot-js requests being blocked, We have fixed it and put in measures to ensure this doesnt happen anymore 🙏🏾

enable blockops endpoint -fixed issue

---

packages/page-preimages/src/Preimages/Call.tsx
packages/react-query/src/FormatBalance.tsx

closes: https://github.com/polkadot-js/apps/issues/10793
`info.deposit.amount` is returning a Null type for Tangle which breaks `FormatBalance`. The original fix I made was in `FormatBalance` but I figured we would get to the source of the exception which was in `PreimageCall`.

Fix Preimage failure of Null amount for Tangle

---

packages/apps-config/src/endpoints/production.ts

A new Creditcoin mainnet is being launched, preserving existing account balances. To prevent any confusion about network continuity, the following names were chosen:
Old network: `Creditcoin` -> `Creditcoin Classic`
New netowork: `Creditcoin`
I'll post another PR in about a week and a half to establish an endpoint for the new Creditcoin network in Polkadot.js.

Change Creditcoin Mainnet Name Ahead of New Mainnet Release

---

packages/react-signer/src/SignFields.tsx

Closes #10861 
Changes `current account nonce` to be equal to the value of the accounts nonce, not the value input by the user.

fix(bug): set current account nonce to be independent from user input

---

packages/react-components/src/InputNumber.tsx
packages/react-signer/src/SignFields.tsx

Closes #10737
I'm currently split between limitting the lifetime to c`onst.system.blockHashCount`, so that if they input a larger value, it gets converted to that max value automatically and displaying a warning or something like that. I'm leaning towards the first case since screen realestate is limited.

fix(bug): user can input invalid lifetime for tx

---

packages/page-referenda/src/Referenda/Vote/VoteStandard.tsx
packages/react-components/src/VoteValue.tsx
packages/react-query/src/BalanceVoting.tsx

closes: https://github.com/polkadot-js/apps/issues/10837
TODO:

Allow reserved in voting balance

---

packages/page-explorer/src/BlockInfo/ByHash.tsx
packages/page-explorer/src/BlockInfo/Summary.tsx
packages/react-hooks/src/useWeight.ts

This PR includes the proof size as a summary along with the consumed weight. 
When checking the weights, there could be occasions when one would expect a block to be fully utilized, while weight consumption is low. This is due to the fact that the PoV is quite large, since weights in V2 are two-dimensional. The main idea is to display both dimensions of the weight, and not just one.

Add proof size summary

---

packages/react-query/src/FormatBalance.tsx

closes: https://github.com/polkadot-js/apps/issues/10907
This was introduced here as a small change: https://github.com/polkadot-js/apps/pull/10898/files#diff-bd3b5461ecbd00f7fb43c4db09b724ad24ce8a3588574bcbf3f42a559ac90e9cR67
Next will tackle fixing this in the coretime price renewal section.

Fix format balance issue

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

RadiumBlock would like to request removal of our Watr Endpoint provider.

Removal of RadiumBlock as Watr Endpoint Provider

---

packages/apps-config/src/endpoints/testing.ts
packages/apps-config/src/endpoints/testingRelayPaseo.ts
packages/apps-config/src/endpoints/testingRelayRococo.ts

`wss://cocos-node.regionx.tech`
error: connect ETIMEDOUT 104.155.73.224:443
`wss://rhala-node.phala.network/ws`
error: Unexpected server response: 502
`wss://api2.zondax.ch/pas/node/rpc`
Connected (press CTRL+C to quit)
Disconnected (code: 1000, reason: "Closing connection")
`wss://nova.gemini-3g.subspace.network/ws`
error: connect ETIMEDOUT 34.207.192.183:443

Disabled unreachable endpoints

---

packages/react-components/src/AccountName.tsx

Helps with https://github.com/polkadot-js/apps/issues/10954 but does not solve not parsing the `AccountId`

Patch for crashing explorer

---

packages/react-components/src/AccountSidebar/Identity.tsx

Identity object used to hold `discord` information under `others`, now it is part of the object on a higher level.
Reference for the changes after mirgration
https://github.com/paritytech/polkadot-sdk/pull/2931/files
`cumulus/scripts/migrate_storage_to_genesis/identityMigration.js`
```
// Migrate `IdentityInfo` data to the new format:
// - remove `additional` field
// - add `discord` field
// - add `github` field`
```

Reflecting changes to Identity pallet 

---

packages/page-addresses/src/modals/Create.tsx
packages/react-components/src/AccountName.tsx

Choosing to use `AccountId20` type if the address is of 20 bytes 😊 
This should solve issues with parsing H160 addresses for Laos Network https://github.com/polkadot-js/apps/issues/10954

H160 address parsing issues on Address book and AccountName component

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts

There is a condition for filtering out people chain endpoints names, which requires the name of the relay chain to be part of the info property for the endpoint configuration. 
```
{
info: 'PaseoPeopleChain',
isPeople: true,
...
}
```
`endpoints.find(({ info, isPeople }) => isPeople && isString(info) && isString(curApiInfo) && info.toLowerCase().includes(curApiInfo.toLowerCase())) || null;`

Naming issue for Paseo People chain

---

packages/apps-routing/src/treasury.ts
packages/page-treasury/src/Overview/index.tsx

rel: https://github.com/polkadot-js/apps/issues/11031

Fix treasury page, and disable propose button

---

packages/apps-routing/src/ambassador.ts
packages/apps-routing/src/fellowship.ts

I am not sure how `needsAccounts` work. Based on my undersatnding it should allow for the page to appear if the collective has accounts. But while the collective has accounts it still dissappears.
By removing this boolean - the pages reappear but it would be nice to understand what that flag is doing
cc @TarikGul

Alter code to make fellowship and ambassador pages to reappear

---

packages/page-broker/src/utils.ts
packages/page-coretime/src/ParachainTableRow.tsx
packages/page-coretime/src/ParachainsTable.tsx
packages/page-coretime/src/Row.tsx
packages/page-coretime/src/utils.ts
packages/react-hooks/src/types.ts
packages/react-hooks/src/useCoretimeInformation.ts

Addressing some of the issues in #11028
- Fixed end dates for the chains that did not renew during the renewal period (interlude).
- Showing "renewed" only if there is workplan for the same chain on the same core.
- Taking taskIds from `api.query.coretimeAssignmentProvider.coreDescriptors` instead of `api.query.paras.parachains`
- Showing renewable eligibility and price of renewal only if the current phase is within the interlude period of the current cycle/sale.
- Added expandable rows to the table in order to show if chain owns multiple cores.

Relay Chain Coretime UI bugs

---

packages/apps-routing/src/treasury.ts

Fixes: https://github.com/polkadot-js/apps/issues/11046
Ref: https://github.com/polkadot-js/apps/issues/11031#issuecomment-2444860196

API check for treasury page

---

.github/workflows/push-master.yml

rel: https://github.com/polkadot-js/apps/issues/10486
Currently the macos certs are expired for the builds and need to be changed over to the new maintainers. This is out of bandwidth at the moment - therefore I am removing is as part of the CI build process, and will keep it tracked in the issue above.

Remove macos from electron CI build

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

RadiumBlock would like to bring back our Khala endpoints. We have some observations that are causing issues. For various para chains, using external url for the relay chain seems to cause chains stalls. This issue has become much more prominent since the recent round of kusama/polkadot upgrades. We have a mitigation in place using extra capacity and eventually switching to using internal relay chain because the external relay seems to under perform.

Re-adding Radiumblock as Khala Endpoint provider 

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

RadiumBlock would like to bring back our  Bridgehub Kusama and Polkadot AssetHub endpoints. We have some observations that are causing issues. For various para chains, using external url for the relay chain seems to cause chains stalls. This issue has become much more prominent since the recent round of kusama/polkadot upgrades. We have a mitigation in place using extra capacity and eventually switching to using internal relay chain because the external relay seems to under perform.

Re-adding RadiumBlock as Bridgehub Kusama and Polkadot AssetHub Endpoint provider

---

packages/apps-config/src/endpoints/testingRelayWestend.ts

RadiumBlock would like to bring back our Westend Endpoint.  It's a best effort service and it running up against compute limit but have decided to increase capacity for community benefit.

Re-adding RadiumBlock as Westend Endpoint Provider 

---

packages/page-files/src/CrustFiles.tsx

1. The old download link is no longer available, so we should use cf-ipfs.com
2. Fix the status link to link to specific file information

Fix Files(IPFS) module status link and download link

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

RadiumBlock would like to bring back our Shiden and Bifrost Polkadot endpoints. We have some observations that are causing issues. For various para chains, using external url for the relay chain seems to cause chains stalls. This issue has become much more prominent since the recent round of kusama/polkadot upgrades. We have a mitigation in place using extra capacity and eventually switching to using internal relay chain because the external relay seems to under perform.

Re-adding RadiumBlock as Shiden and Bifrost Polkadot Endpoint provider

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testingRelayPaseo.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

Dear team,
Please consider the following changes to the endpoints provide by the Infrastructure Builders Programme (IBP):
- correction of spelling for `bridge-hub-paseo` (solving [issue 10966](https://github.com/polkadot-js/apps/issues/10966)).
- update of names for `asset-hub-kusama`, `asset-hub-westend` and `hydration`.
- addition of IBP endpoints for `coretime-polkadot`, `coretime-paseo`, `people-paseo`, `acala`, and `invarch`.
- addition of an independent endpoint for `parallel` by Gatotech (a member of the IBP).
Many thanks!!
Best regards
**_Milos_**

Additional IBP endpoints and miscellaneous maintenance

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts

This PR adds NeuroWeb Testnet endpoint to Paseo relay chain section.

Add NeuroWeb Testnet endpoint for Paseo

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This PR adds Helikon public RPC endpoint for Mythos.
Mythos RPC endpoint is load balanced with two archive nodes on NVMe drives on a 5Gbps symmetrical network. Our services run on owned hardware in multiple data centers in central Istanbul, and are monitored 24/7 at software (node), hardware (disk, CPU, memory) and network level.
Nodes can be viewed [here](https://telemetry.w3f.community/#list/0xf6ee56e9c5277df5b4ce6ae9983ee88f3cbed27d31beeb98f9f84f997a1ab0b9) on the W3F Telemetry instance.
Helikon is a member of the IBP GeoDNS and provides public RPC endpoints for Kusama, Westend, Polkadot, all system parachains, and multiple Polkadot parachains. We also run boot nodes for all the chains we provide RPC services for.
Regards.

Add Helikon public RPC endpoint for Mythos.

---

packages/react-api/src/Api.tsx

rel: https://github.com/polkadot-js/apps/pull/10609
This will allow parachains to set `isPeopleForIdentity` which will allow them to access the identity pallet from the peoples parachain.

Allow for parachains with isPeopleForIdentity to access identity from people chain

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

Following #10598, we're registering People as the identity provider for Kreivo in polkadot.js apps

Set Kusama People as identity provider for Kreivo

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

Onfinality no longer supports this network.
- bajun: `wss://bajun.api.onfinality.io/public-ws`

Deleted the OnFinality Bajun endpoint

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts

Updated the Onfinality Nodle endpoint:
From:
`wss://node-6957502816543653888.lh.onfinality.io/ws?apikey=09b04494-3139-4b57-a5d1-e1c4c18748ce`
To:
`wss://node-7273232234617282560.nv.onfinality.io/ws?apikey=b937a7d7-7395-49b9-b745-60a0342fa365`.
The old endpoint is no longer valid.

Updated the Onfinality Nodle endpoint

---

packages/apps-config/src/endpoints/types.ts

This PR aims to add some description for types used for `endpoints/types.ts` in `apps-config`.

docs: added missing types description

---

packages/page-bounties/src/Bounties.spec.ts
packages/page-bounties/src/Bounties.tsx
packages/page-bounties/src/Bounty.tsx
packages/page-bounties/src/BountyActions/index.tsx
packages/page-bounties/src/BountyExtraActions/index.tsx
packages/page-bounties/src/BountyInfos/VotingDescriptionInfo.tsx
packages/page-bounties/src/BountyInfos/VotingSummary.tsx
packages/page-bounties/src/BountyInfos/index.tsx
packages/page-bounties/src/BountyNextActionInfo/BountyActionMessage.tsx
packages/page-bounties/src/VotersColumn.tsx
packages/page-bounties/src/helpers/determineUnassignCuratorAction.ts
packages/page-bounties/src/helpers/extendedStatuses.ts
packages/page-bounties/src/helpers/getBountyStatus.spec.ts
packages/page-bounties/src/helpers/getBountyStatus.ts
packages/page-bounties/src/hooks/useBountyStatus.ts
packages/page-bounties/test/pages/bountiesPage.tsx
packages/test-support/src/creation/bounties.ts

This PR aims to fix the `BountyType` with new `PalletBountiesBounty`.
The polkadot-js api update with the substrate types in the most recent release `v15.2.1` has introduced a break in the TS compiler.
The old type: [`Bounty`](https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/treasury/types.ts#L9-L16)
The new type: [`PalletBountiesBounty`](https://github.com/polkadot-js/api/blob/master/packages/types-augment/src/lookup/types-substrate.ts#L8203-L8210)

Fix `BountyType` with new `PalletBountiesBounty`

---

packages/page-assets/src/Balances/index.tsx

On visiting the balances page for assets, a continuous loading screen is displayed. However, searching for assets manually from the dropdown works fine. But this can be confusing and difficult for some users to notice.
https://github.com/user-attachments/assets/acbe85e8-e8f5-4cc0-add2-3592f082df49

fix: default asset selection

---

packages/page-treasury/src/Overview/ProposalCreate.tsx
packages/page-treasury/src/Overview/index.tsx

In this issue, `Submit Proposal` button has been disabled if `tx.treasury.proposeSend` is not available. Our focus is here to undo this change and fix the breaking changes. The Idea here is show same UX for all chains in Treasury Page.
Now, In this PR, All breaking changes have been fixed and `Submit Proposal` have been enabled.

fix: restore submit proposal button

---

packages/apps-config/src/api/constants.ts
packages/page-assets/src/Overview/Create/Info.tsx
packages/page-assets/src/index.tsx

When creating a new asset, the Asset ID field should default to the next possible asset_id which is basically `last_created_asset_id + 1`
The current UI makes it seem that any asset id would work, but after a runtime upgrade it is required that newly created asset id's follow a specific rule: the newly created asset's id should be the next possible id of the last created asset. 
In other terms, next_asset_id = previous_asset_id + 1
* **What is the motivation for changing the behavior?**
Without this change, users will face this error:

fix: get next asset id issue

---

packages/page-treasury/src/Overview/index.tsx

rel: https://github.com/polkadot-js/apps/pull/11218
This just ensures the create button wont appear if the support isn't there for it.

Add check for proposeSend

---

packages/page-assets/src/Balances/index.tsx

This PR aims to fix a breaking edge case on `/assets/balances` page on top of https://github.com/polkadot-js/apps/pull/11222. 
This issue arises when the automatic selection of Asset ID (which happens on first visit) exceeds `2^53 - 1`, causing it to break. To address this, we will handle the selected Asset ID as a string instead of a number.

fix: broken balances page

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

This pull request publishes the new Kusama and Polkadot endpoints from Helixstreet's successful application for [Public RPC Bounty - Tender 2](https://docs.google.com/document/d/18ZvQPdaNMlohHeGwqSQYqTd037R8NJngWVEX13kGClk/edit?usp=sharing) for Kusama and Polkadot.

addHelixstreetEndpoints

---

packages/page-treasury/src/Overview/ProposalCreate.tsx
packages/page-treasury/src/Overview/index.tsx

This PR aims to make use of `spendLocal` instead of `proposeSpend` as this has been deprecated.

fix: make use of `spendLocal` in treasury

---

packages/apps-routing/src/broker.ts
packages/apps-routing/src/coretime.ts
packages/apps/public/locales/en/app-broker.json
packages/apps/public/locales/en/apps-routing.json

Removes the experimental tag from coretime.
closes: https://github.com/polkadot-js/apps/issues/11202

Remove Experimental from Coretime

---

packages/page-treasury/src/Overview/index.tsx

This ensures that for certain chains that don't have `proposeSend` and or `spendLocal` we can safeguard from the active send button

Ensure safeguard against treasury spendLocal functions

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Dear team, hello, 
Please consider this endpoint to the Polkadot's Mythos parachain.
This endpoint is provided by the Infrastructure Builders' Programme.
Many thanks and best wishes!
**_Milos_**

Add IBP endpoint to Mythos

---

packages/apps-config/src/endpoints/productionRelayKusama.ts

This provider was temporarily out of service due to a misconfiguration in the DNS service, bus has since then be active for the last month ininterruptedly.

Restore `wss://kreivo.io` provider to the list of providers

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts

This PR adds Permanence DAO ([X](https://x.com/PermanenceDAO), [web](https://permanence.io)) public RPC endpoints for Polkadot and Westend Asset Hub.
RPC endpoints are load balanced with two archive nodes, running on servers in Germany and Poland. Services are monitored 24/7 at software (node), hardware (disk, CPU, memory) and network level.
Polkadot nodes can be viewed [here](https://telemetry.polkadot.io/#/0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3), and Westend Asset Hub node [here](https://telemetry.polkadot.io/#list/0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9), on the Polkadot Telemetry instance. Please search by name `Permanence DAO`.
Best regards.

Add Permanence DAO Europe public RPC endpoints for Polkadot and Westend Asset Hub

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

I'd like to kindly request that the Helixstreet endpoints be re-enabled.
For your information, Helixstreet has a total of 3 DNS entries - 2 IPv4 and one IPv6. Currently, most access is via IPv6. The endpoints are accessible via 2 ISPs.
We experienced issues with one endpoint at a provider, which has been temporarily removed. The endpoints are currently reachable via IPv4 & IPv6.
I apologize for any inconvenience caused.

enable Helixstreet Endpoints

---

packages/page-parachains/src/Teleport.tsx
packages/react-components/src/InputBalance.tsx

Currently, users can input any value when teleporting assets, which can lead to unexpected errors if the amount exceeds the allowable limit or if it doesn't leave existential deposit behind. This PR addresses the issue by fetching the maximum transferable value for Teleport and enforcing this limit to ensure users cannot exceed it.
This update improves reliability and provides a smoother user experience by preventing invalid transfers and unexpected errors.

Maximum transfer value while teleport

---

packages/page-assets/src/Balances/index.tsx
packages/page-assets/src/Overview/Asset.tsx
packages/page-assets/src/index.tsx
packages/react-hooks/src/ctx/PayWithAsset.tsx

This PR aims to fix the issue with parsing asset IDs. Asset IDs can be non-digits, such as objects like multilocations. For chains with these types of asset IDs, the UI explorer is breaking and displaying a white blank page. This issue will be addressed in this PR.
Additionally, the Assets page is also being fixed as this was also breaking.
There will be no effect for other chains.

Fix Asset Id Parsing

---

packages/apps/public/locales/en/react-signer.json
packages/react-components/src/Status/types.ts
packages/react-components/src/TxButton.tsx
packages/react-components/src/index.ts
packages/react-components/src/modals/Transfer.tsx
packages/react-hooks/src/ctx/PayWithAsset.tsx
packages/react-signer/src/PayWithAsset.tsx
packages/react-signer/src/PaymentInfo.tsx
packages/react-signer/src/Transaction.tsx
packages/react-signer/src/TxSigned.tsx
packages/react-signer/src/types.ts

In [PR#11229](https://github.com/polkadot-js/apps/pull/11229), support for paying fees with Sufficient Assets was introduced. However, this functionality currently only applies to transferring system assets.
Now, it's a good time to extend this feature to all possible areas where users can submit transactions. To achieve this, we will move the Fee Asset dropdown from the `Transfer Modal` to the `Authorize Transaction Modal`. This change will ensure that users can select a fee asset for almost all the transactions they sign.
https://github.com/user-attachments/assets/cbdcb2be-87bb-4578-ad54-40a915d3d0ab

Enhancement: Fee Payment with Sufficient Assets

---

packages/react-hooks/src/ctx/PayWithAsset.tsx
packages/react-signer/src/PayWithAsset.tsx

This PR aims to fix - 
- **Initial `selectedAssetValue` Update:** Now initializing with `-1` instead of `0`, as non-native assets can have an asset ID of `0`, which may cause issues like [this](https://github.com/polkadot-js/apps/issues/11339).
- **Enhanced Fee Token Verification:** Improved checks to ensure a chain implements sufficient fee token mechanism.
https://github.com/user-attachments/assets/d26dfefc-1ca4-4846-a165-ca3138a30cc2

Enhancement: Improve Fee Token Verification & Asset ID Handling

---

packages/page-referenda/src/Referenda/useVotes.ts

After v1.4.0 runtime upgrade, Relay chains i.e. Kusama and Polkadot, or other parachains chains, replaced `voting` method with `votingFor`. So, We will be adding a safety check here so that app doesn't break.

Fix: Voting on referenda breaks Apps

---

packages/react-hooks/src/useAccountInfo.ts
packages/react-hooks/src/useOwnStashInfos.ts
packages/react-hooks/src/utils/isEmpty.ts

This PR aims to create a custom utility function for checking `isEmpty` state.  The reason is, For any address that is not a validator, the `staking.validators` method returns - 
```ts
{
"commission": 0,
"blocked": false
}
```
We have to check absolute emptyness for this Struct.

Replace `isEmpty` checks with utility function

---

packages/page-coretime/src/Row.tsx
packages/react-hooks/src/types.ts
packages/react-hooks/src/useCoretimeInformation.ts

Fixing this comment: https://github.com/polkadot-js/apps/issues/11253#issuecomment-2692017978
Expires soon banner should only be shown for chains that expire within a week and have not renewed their core.

Fix for not showing expires if the chain renewed 

---

packages/page-preimages/src/Preimages/Preimage.tsx
packages/page-preimages/src/Preimages/index.tsx
packages/page-preimages/src/Preimages/userPreimages/Preimage.tsx
packages/page-preimages/src/Preimages/userPreimages/index.tsx
packages/react-hooks/src/useAssetIds.ts

This PR enhances the **Preimages** page by improving its user-experience and adding new features to streamline interactions.  
- **Batch Unnote**:  
- Users can now **select multiple preimages** and unnote them in a single action.  
- **Account-Based Filtering**:  
- Display preimages associated only with the user’s accounts.  
These improvements will significantly enhance the user experience by:  
✅ Making it easier to manage multiple preimages at once.  
✅ Providing better visibility of preimages relevant to the user.  
https://github.com/user-attachments/assets/85637ee2-7ac4-4690-9860-cfd93c7f3af8

Enhance Preimages Page with Improved Usability

---

packages/page-explorer/src/Forks.tsx

Users can read the fork hash display in Explorer/fork when the result is not finalized in darkmode. Fix from this 
This was the original dark mode followed by light mode 
The images below are taken after I fixed the dark mode, which is also compatible with the light mode.

Fix dark mode display hash display result in Fork 

---

packages/page-staking/src/MarkPoolsWarning.tsx

Since runtime [version 1.4.0](https://github.com/polkadot-fellows/runtimes/releases/tag/v1.4.0), funds delegated to nomination pools can now participate in Polkadot OpenGov. The current warning message is outdated and could be Modified.

Changed pools warning message

---

packages/apps/src/overlays/Base.tsx
packages/apps/src/overlays/DotApps.tsx

With this implementation, once the X is click on the "dev" notification - then a localstorage is added in order to keep it hidden
An extra check is added - if the notification is hidden more than 1 month - then it will reappear and user needs to re-deactivate it.
Fixes #11398

Remove the dev notification for 1 month

---

packages/react-hooks/src/ctx/PayWithAsset.tsx
packages/react-signer/src/PayWithAsset.tsx

Sometimes, a discrepancy occurs when selecting fee assets. Specifically, switching between native and non-native assets for fee payment can display an incorrect fee and prevent paying the fee in native tokens until the page is reloaded.
This PR resolves the issue by ensuring seamless switching between fee assets without requiring a page reload.
https://github.com/user-attachments/assets/05dc2d05-a85a-4f83-9c93-370d0eaa7b67
https://github.com/user-attachments/assets/fcd7183a-83ad-4a5b-abc4-2d98e27dc8d3

FIX: Fee Asset Selection

---

packages/page-accounts/src/modals/MultisigApprove.tsx

This PR addresses layout inconsistencies in the **Multisig Pending Approvals Modal**, specifically when switching between multiple pending transaction hashes in the dropdown.  
- When toggling between multiple pending hashes, the **call data input field** occasionally disappears.  
- If a user enters call data and then switches to another transaction, the previously entered call data becomes invisible.  
- Although this issue is **not consistently reproducible**, performing these actions **three to four times** typically triggers the bug.  
- Ensures that the call data input field remains visible when switching between transactions.
- Adjust the width of the **"Multisig message with call (for final approval)"** toggle to match its content. Currently, clicking on the empty space to the …

Improvement: Multisig Call Data Field

---

packages/page-accounts/src/Accounts/Account.tsx
packages/page-accounts/src/Accounts/index.tsx

Currently, the UI lacks the ability to export Multisig accounts, making it challenging for users to transfer them when switching devices or browsers.  
This update introduces a feature that allows users to export all signatories as a JSON file, ensuring seamless portability. The exported JSON can be easily imported via the UI, enhancing user convenience and accessibility.  
This feature simplifies account management for users, allowing them to easily carry their Multisig accounts between different environments without manual reconfiguration.  
https://github.com/user-attachments/assets/b2855d6e-4f4e-4cfa-a385-610964383bca

Export Multisig as JSON

---

packages/react-signer/src/Address.tsx

The current polkadot-js explorer has a bug where MultiSig calls fail to execute properly under specific conditions.
1. Use a multisig account that also has an associated proxy account.
2. Attempt to perform a transaction **without** using the proxy (i.e., select "Don't use a proxy call for this call").
3. The UI gets stuck on the loading icon over the "Sign and Submit" button, making it unresponsive.
4. The only workaround previously was to remove the proxy account from the explorer.
- Identified and resolved the root cause of the issue, ensuring proper handling of multisig transactions regardless of proxy usage.
- Updated transaction submission logic to prevent UI from freezing.
- Ensured that the "Sign and Submit" button remains functional in all cases.
- Conducted thorough testing …

Fix: Multisig calls linked to a proxy account

---

packages/page-sudo/src/Sudo.tsx

The Sudo page sometimes returns unexpected errors when submitting a call. However, the same action works correctly when performed from the Extrinsics page.  
To resolve this issue, we are aligning the Sudo page's submission behavior with the Extrinsics page, which functions correctly. This involves analyzing the working implementation on the Extrinsics page and applying the necessary adjustments to the Sudo page.  
This fix ensures a more consistent and error-free experience when submitting calls via the Sudo page.
https://github.com/user-attachments/assets/e6335184-f137-4fae-83a8-b5c5288a102b
https://github.com/user-attachments/assets/02a75839-0dfc-4b57-bfda-e50e4fdedac1

FIX: Unwanted Errors on Sudo Page When Submitting Calls

---

packages/react-signer/src/Address.tsx

A multisig account cannot sign transactions as an "any" proxy for its associated proxied account, resulting in an endless loop in the UI. The issue does not occur when the proxy account is a standard account instead of a multisig account.
- Conducted thorough testing covering all possible cases to prevent recurrence of this issue.
- Verified successful execution of MultiSig transactions with and without an associated proxy account.
- Ensured the UI remains responsive and functional under all conditions.
- This fix enhances the reliability of MultiSig transactions within polkadot-js explorer.
https://github.com/user-attachments/assets/79c51784-aa5a-407e-89aa-b25b4fe55358

Improve signing with multisig proxy

---

packages/page-accounts/src/modals/ProxyOverview.tsx
packages/react-components/src/InputAddress/index.tsx

This PR aims to improve the behaviour for adding proxy for an account. Currently, an anonymous proxy is not allowed to be added for an account, however it should be possible technically. Additionally, It fixes account dropdown behaviour.
https://github.com/user-attachments/assets/51bb0f97-0d9a-485e-b2f5-f4982cd2d0a7

Allow anonymous proxy

---

packages/apps-routing/src/extrinsics.ts

This PR ensures that the extrinsic page is always accessible, even when no accounts are connected. This allows developers to explore deployed pallets, construct encoded calls, and interact with the UI for testing purposes without requiring an active account. While transaction submission remains restricted in this scenario, this enhancement provides valuable visibility into the available extrinsics and facilitates development workflows.
If the user/developer has an account, they will always be able to submit transactions, maintaining the existing flow.

Enable Extrinsic Page Access Without Accounts

---

packages/page-society/src/Suspended/index.tsx

This PR aims to prevent breaking `Suspended` Tab in Society Page for Kusama.

Suspended candidates query

---

packages/apps-config/src/endpoints/testing.ts

This PR modifies the endpoint and the display name for the zkVerify testnet, which have been updated recently.

Update zkVerify testnet endpoint and name

---

packages/page-parachains/src/Crowdloan/Fund.tsx
packages/react-params/src/Named/CallExpander.tsx

This PR aims to improve behavior for dissolving crowdloan. As `crowdloan.dissolve` is [permissionless extrinsic](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/runtime/common/src/crowdloan/mod.rs#L565)  (when certain conditions met) so it should be executed by any account, not necessarily from the depositor account.
https://github.com/user-attachments/assets/429e16ff-537c-459e-aff4-402401c0a4e4

Improved behavior for dissolving crowdloan

---

packages/page-accounts/src/Accounts/index.tsx
packages/page-accounts/src/modals/ExportAll.tsx
packages/page-accounts/src/modals/ImportAll.tsx

This PR introduces import and export functionality to the **My Accounts** page, mirroring the existing features found on the Address Book page. This enhancement promotes consistency across the app and empowers users to manage their account data more efficiently.
- Added **Import** and **Export** buttons to the My Accounts page.
- Enabled support for uploading and downloading account data
- Implemented error handling and success notifications.
Extending the import/export capabilities to the My Accounts page ensures a consistent user experience and provides valuable data portability for users who manage multiple accounts.
https://github.com/user-attachments/assets/44fbbb19-3053-41c0-8507-1e4afc2e2a39

Import and export of addresses to the My Accounts Tab

---

packages/react-params/src/Param/Vote.tsx

This PR addresses a bug where transactions with a `Nay` vote are incorrectly displayed as `Aye` in the **Submission** tab of the UI. The bug occurs during the decoding process after switching tabs, even though the underlying transaction data remains correct. 
The issue is with the `Vote` type itself, not just the `aye`. Even if we change `Conviction` value and switch back to submission tab, it resets to `None`.
Encoded call - 0x1400c8000400e87648170000000000000000000000
Here is one successful transaction with current flow (on Paseo) - https://paseo.subscan.io/extrinsic/0x543a94bbf3d5d9637b1baa7adfa6909df65466709ca2a6aee80347536ab55530

Refactor: Vote component

---

packages/page-files/src/CrustFiles.tsx

fix: update upload menu background color to use theme variable

---

packages/page-accounts/src/modals/Delegate.tsx

This PR fixes the behavior of the **Delegated Account Input** component. Previously, the input only allowed selection from available (in-browser) accounts. However, this is incorrect — a delegated account does **not** need to be present in the browser extension or local keyring; it simply needs to be a valid address.
The fix aligns with the approach used for the **Proxy Input** component, as implemented in [this PR](https://github.com/polkadot-js/apps/pull/11450/files#diff-d35ac8929895659270ed7fb55bab94ba2f603624d8ea28a2a82f7dca8348f85a).
With this change, the Delegated Account Input now correctly accepts any valid address, regardless of its presence in the browser.

Update delegated account input type

---

packages/page-accounts/src/Accounts/useMultisigApprovals.ts

fixes #11546
The MultisigApprove modal was experiencing a UI glitch where the "call data for final approval" input field was constantly being reset during user interaction. This occurred because:
1. Any blockchain event (even those unrelated to multisig) would trigger the useMultisigApprovals hook
2. This caused unnecessary re-renders of the MultisigApprove component 
3. Each re-render would reset the input field value (`callHex`), making it impossible for users to input or edit call data
The fix optimizes the useMultisigApprovals hook to prevent unnecessary triggers and re-renders:
1. Added a `useRef` to track previously processed multisig events
2. Implemented a filtering mechanism that only processes events that are:
- From the multisig section
- Related to the current address
- …

fix: multisig data disappears while signing multiple multisig tx's from same account

---

packages/react-params/src/Param/BaseBytes.tsx

This PR addresses a regression where input for Bytes component starting with `0x` are incorrectly parsed as hex-encoded byte strings. This caused issues where display names like `0xTaylor` were misparsed as hex bytes (e.g., `0x0a0000`), leading to incorrect rendering.
This update improves the logic by only interpreting a string as hex if it is a *valid* hex sequence. Non-hex strings starting with `0x` are now correctly treated as plain text.
https://github.com/user-attachments/assets/7765c0bb-ad70-4434-ae17-1dc723fe80a7

Improve input conversion logic in BaseBytes component

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Related to this issue: https://github.com/polkadot-js/apps/issues/11513
However, I can reach the endpoint using this link:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fzeitgeist.api.onfinality.io%2Fpublic-ws#/explorer

Add ZeitgeistPM OnFinality provider to production relay polkadot endpoints

---

packages/page-coretime/src/Sale/boxes/Cores.tsx
packages/page-coretime/src/Sale/boxes/Timeline.tsx
packages/page-coretime/src/utils/sale.ts

chore: display prices as full number on sales page

---

packages/page-broker/src/Overview/WorkInfoRow.tsx

Small fix for non-showing tag for Reservation type on Coretime Broker - Coretime Chain

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts

This PR enables `R0GUE-RPC3` as it is reachable again.
It seems it was disabled after https://github.com/polkadot-js/apps/issues/11513

chore: re-enable rpc3 for Pop Network

---

packages/page-preimages/src/Preimages/Call.tsx
packages/page-preimages/src/Preimages/userPreimages/Preimage.tsx

This PR updates the preimage page to include a link that contains the encoded call. When clicked, the link gets decoded and displays the decoded call for the preimage, making it easier for users to view and access the raw data directly. This improves visibility into the preimage content without requiring manual decoding or use of external tools.
The hex value can also be easily copied for use in scripts or debugging workflows. This enhancement is particularly useful for developers who need quick access to the preimage hex for validation or integration purposes. By simplifying the process through a clickable, self-decoding link, this update streamlines developer experience and workflow efficiency.

Enhance Preimage Page with Decodable Call Link

---

packages/apps-config/src/index.ts
packages/apps-config/src/ui/index.ts
packages/apps/src/Menu/NodeInfo.tsx
packages/page-settings/src/Metadata/NetworkSpecs.tsx
packages/page-settings/src/Metadata/SystemVersion.tsx
packages/page-settings/src/Metadata/index.tsx

Fixes #11580 
On mobile devices, key information from the menu bar—such as runtime version, block number, node version, API version, and apps version—was previously hidden due to limited screen space.
To resolve this, these details have now been added to the **Settings** page, under the existing **Metadata** tab.
*info hidden in menu bar due to limited size*
*info now visible under Settings > Metadata*

Display Basic Chain Info, Apps, API, and Metadata in Settings

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts

- Network name: `Niskala` → `Mandala`
- ParaID: Updated to `4818`
- RPC endpoints updated to new Mandala infrastructure:
- Autobot: `wss://rpc1.paseo.mandalachain.io`
- Bumblebee: `wss://rpc2.paseo.mandalachain.io`
The Mandala testnet is now live on Paseo and ready for testing. This replaces the previous Niskala configuration with the new network infrastructure.

Update Mandala testnet config

---

packages/apps-electron/src/electron/window.ts

This PR manages how URLs are handled in Electron apps. For example, not all URLs need to open in the Electron window; some can be opened in an external browser window.

Handle External URL Navigation in Electron App

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts

1. [bifrost.public.curie.radiumblock.co](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbifrost.public.curie.radiumblock.co%2Fws#/explorer)  is actually bifrost-polkadot, but it was placed under bifrost-kusama. Now it has been returned to its original position.
2. bifrost homepage now is : https://bifrost.io/

Fix radiumblock bifrost endpoint

---

packages/page-referenda/src/useReferenda.ts

This PR fixes a bug where referenda would temporarily disappear from the UI after voting or during loading. The issue stemmed from the `OPT_MULTI` transformer in `useReferenda`, which previously filtered out any referenda whose `info.isSome === false`.
- Updated the `OPT_MULTI` transformer to **retain all referenda IDs**, even if their `info` is not available (`Option::None`).
- Ensures `referenda.length === ids.length`, preventing mismatch issues in grouping logic.
- The `group()` function and UI can now handle entries with `info: undefined`, avoiding silent omissions after voting.
- Voted on an ongoing referendum and verified that it no longer disappears briefly from the UI.
- Confirmed that all referenda are rendered regardless of `info` availability.
- Verified that grouping and …

Preserve referenda with missing info during grouping

---

packages/apps-config/README.md

https://polkadot.js.org/api/start/types.extend.html#extending-types  - dead link
https://polkadot.js.org/docs/api/start/types.extend  - new link

docs: fix dead link in apps-config/README.md

---

packages/apps-config/src/index.ts
packages/apps-config/src/ui/index.ts
packages/apps/src/Menu/NodeInfo.tsx
packages/page-settings/src/Metadata/SystemVersion.tsx

In the current implementation, the build is created before the package version is bumped. As a result, `getPackageVersion` returns a cached version, causing the UI apps to display an outdated version even with a new build release.
To resolve this issue, the version should be read directly from the source file in `@polkadot/apps-config`, ensuring the displayed version is always accurate and up to date.

fix(ui): resolve apps version caching issue

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/productionRelayPolkadot.ts
packages/apps-config/src/endpoints/testingRelayPaseo.ts
packages/apps-config/src/endpoints/testingRelayWestend.ts
packages/page-parachains/src/Teleport.tsx

While Asset Hub (AH) is expected to play a central role in most activities post–AH migration, its current teleport functionality remains limited in scope—supporting only the Relay Chain as a destination for asset transfers. This feature is designed to significantly broaden that capability by extending teleportation support to additional system parachains, such as People, BridgeHub, and others. Importantly, this expansion will work in both directions, enabling seamless and efficient asset movement between AH and other system parachains. The goal is to deliver a more streamlined and intuitive teleport user experience across the Polkadot ecosystem.
https://github.com/user-attachments/assets/c699edff-1320-4818-8594-71c86653de55

Teleport Feature Enhancement

---

packages/page-coretime/src/Sale/SaleDetailsView.tsx
packages/page-coretime/src/utils/index.ts

This pull request corrects some typographical errors:
- `unsual` -> `unusual`
- `traget` -> `target`

Fix typos in comment

---

packages/page-explorer/src/BlockInfo/ByHash.tsx
packages/page-explorer/src/BlockInfo/Summary.tsx

This PR fixes the calculation of `proofSize` on the block details page.
Previously, the implementation only captured the `proofSize` from the final `system` event in the block, which often led to inaccurate or underestimated values. This update changes the logic to fetch the actual block weight from storage, ensuring accurate reporting of `proofSize` and `refTime`.

Accumulate proof size for block details page

---

packages/apps-config/src/endpoints/productionRelayKusama.ts
packages/apps-config/src/endpoints/testingRelayPaseo.ts

Decomissioning the previous server.
1. Changing RPC of XODE on kusama from rpcnodea01.xode.net/n7yoxCmcIrCF6VziCcDmYTwL8R03a/rpc to  kusama-rpcnode.xode.net
2. Changing RPC of XODE on paseo from testrpcnodea01.xode.net/aRoyklGrhl9m2LlhX8NP/rpc to paseo-rpcnode.xode.net

Update: Change XODE rpc on Kusama and Paseo

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

Blockops has temporarily stopped providing public endpoint service for polkadot-assethub. This PR removes the endpoint

remove public endpoint support update polkadot-assethub

---

packages/apps-config/src/endpoints/productionRelayPolkadot.ts

It seems that the slot swap paraId got mixed up with the correct ParaId which holds our lease now

fix Integritee Polkadot paraid

---

packages/apps-config/src/endpoints/testingRelayPaseo.ts

A brief downtime of our rpc node seems to have triggered deactivation: https://github.com/polkadot-js/apps/issues/11817
This shall reactivate it

reactivate Integritee Paseo endpoint

---

packages/react-api/src/Api.tsx

Closes #11875 . I already provided an explanation of the cause in the issue.

fix: filter-out non eth accounts from eth chains
